import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {accountActionState,GW_HEADING_FONTS,validHeadingFont} from '../src/account-actions-model.js';
test('preview retains signed-in unfinished identity for explicit signout',()=>{assert.equal(accountActionState({mode:'preview',session:{signedIn:true,status:'new'},configured:true}).signOutRemote,true);assert.equal(accountActionState({mode:'preview',configured:true}).signOutRemote,false);assert.equal(accountActionState({mode:'live',reviewOnly:true}).signOutRemote,false)});
test('actual branded font identities remain the persisted two choices',()=>{assert.deepEqual(GW_HEADING_FONTS.map(x=>x.value),['serif','sans']);assert.deepEqual(GW_HEADING_FONTS.map(x=>x.label),['DM Serif Text','Momo Trust Display']);assert.equal(validHeadingFont('invalid'),'serif');assert.equal(validHeadingFont('sans'),'sans')});
test('You and Profile use one shared signout component and preview escape',()=>{const root=readFileSync(new URL('../src/react-app.jsx',import.meta.url),'utf8');assert.ok(root.includes('<PreviewAccountControls compact/>'));assert.ok(root.includes('<PreviewAccountControls/>'));assert.ok(!root.includes('you-sign-out'));assert.ok(!root.includes('className="creator-credit"'));assert.ok(root.includes("onClick={()=>setPage('appearance')}"));assert.ok(root.includes('GW_HEADING_FONTS.map'));});
test('signout preserves preview storage and supports anonymous preview',()=>{const source=readFileSync(new URL('../src/live-adapter.js',import.meta.url),'utf8'),body=source.slice(source.indexOf(' async function signOut(){'),source.indexOf(' async function upload(file)'));assert.match(body,/session\?\.signedIn===true\|\|ref\.current\.mode==='live'/);assert.match(body,/setState\(signedOut\)/);assert.doesNotMatch(body,/save\(initialState\(\)\)/);assert.match(body,/signOutLock\.current/);});

test('all onboarding direct action groups retain space and disclosures remain secondary',()=>{const css=readFileSync(new URL('../dist/react-ui.css',import.meta.url),'utf8'),disclosure=readFileSync(new URL('../src/inline-disclosure.jsx',import.meta.url),'utf8');assert.match(css,/\.onboard\.card\{display:flex;flex-direction:column;align-items:stretch;gap:18px;/);assert.doesNotMatch(css,/\.onboard\.card\{[^}]*gap:0;/);assert.match(disclosure,/button secondary inline-disclosure-trigger/);});

test('Make it feel like home belongs to profile color editor, not onboarding action',()=>{const app=readFileSync(new URL('../src/react-app.jsx',import.meta.url),'utf8'),profiles=readFileSync(new URL('../src/profiles.jsx',import.meta.url),'utf8');assert.doesNotMatch(app,/InlineDisclosure label="Make it feel like home"/);assert.match(profiles,/<legend>Make it feel like home<\/legend>/);assert.match(profiles,/aria-label="Profile color"/)});
