import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import test from 'node:test';

const read = path => readFile(new URL('../' + path, import.meta.url));
const hash = bytes => createHash('sha256').update(bytes).digest('hex');

test('browser favicon uses a dedicated transparent asset, separate from installed icons', async () => {
  const html = (await read('dist/index.html')).toString();
  assert.match(html, /<link rel="icon" href="favicon\.svg" type="image\/svg\+xml">/);
  assert.doesNotMatch(html, /<link rel="icon"[^>]*app-icon\.svg/);
  assert.match(html, /<link rel="apple-touch-icon" sizes="180x180" href="\/apple-touch-icon\.png">/);
  assert.match(html, /<link rel="manifest" href="manifest\.webmanifest">/);
});

test('transparent favicon preserves the approved original mark and geometry exactly', async () => {
  const favicon = (await read('dist/favicon.svg')).toString();
  const appIcon = (await read('dist/app-icon.svg')).toString();
  const background = '<rect width="512" height="512" rx="112" fill="#123d29"/>';
  assert.equal(appIcon.split(background).length, 2);
  assert.equal(favicon.trim(), appIcon.replace(background, '').trim());
  assert.doesNotMatch(favicon, /<rect|<filter|<pattern|<style|<foreignObject|<script/);
  const embedded = favicon.match(/href="data:image\/png;base64,([A-Za-z0-9+/=]+)"/);
  assert.ok(embedded);
  const artwork = await read('dist/tree-artwork.png');
  assert.deepEqual(Buffer.from(embedded[1], 'base64'), artwork);
  assert.equal(hash(artwork), '449056bf214b445d6922667102d93749cf62196f1b83ad43f2ab510319cd88ba');
  assert.equal(artwork[25], 6, 'approved PNG must retain its RGBA color type');
});

test('favicon is generated by every build before existing asset versioning', async () => {
  const pkg = JSON.parse(await read('package.json'));
  assert.match(pkg.scripts.build, /node scripts\/build-favicon\.mjs && node scripts\/version-assets\.mjs$/);
});

test('installed-app, maskable, and Apple touch assets are unchanged', async () => {
  const expected = {
    'app-icon.svg': '0bdbe7bb38701ecb1e0c3222116a1b13e653eb7f828dafabbe6cefccf073b8d5',
    'manifest.webmanifest': '82dc3ba146cc407851ca04e49094956aaa67f438a15ab19194871b5a22b3625b',
    'apple-touch-icon.png': '511a6897e99fbaa950f741fbdf25c025f6135ec5cf93272b89fcfb6d382d9f70',
    'icon-192.png': 'ad43fd244203798b81b2739df7a9fbcd7e2fd32ee0864a2cc7f994e2e382ecf8',
    'icon-512.png': 'fa9b18fbd42228696eb1bfa39b829691a3ab72dc4466a0d371eb70adb1a83a5d'
  };
  for (const [name, sha256] of Object.entries(expected)) {
    assert.equal(hash(await read('dist/' + name)), sha256, name + ' changed');
  }
});
