// Offline static-markup and source-contract coverage. UI boundaries are intentionally stubbed; browser/device layout and interaction remain release gates.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {build} from 'esbuild';
const root=new URL('../',import.meta.url).pathname;
const sources=Object.fromEntries(['profiles.jsx','family.jsx','memories.jsx','form-layout.css','image-upload-control.jsx','inline-disclosure.jsx','inline-disclosure.css'].map(file=>[file,fs.readFileSync(root+'src/'+file,'utf8')]));
const ui=`import React,{createContext,useContext} from 'react';export const AppContext=createContext(null);export const FloatingSurfaceContext=createContext(false);export const useApp=()=>useContext(AppContext);export const useSheetForm=()=>React.useId();export const Control=React.forwardRef(({children,...props},ref)=>React.createElement('button',{...props,ref},children));export function Button({children,secondary,...props}){return React.createElement(Control,{...props,className:'button'},children)}export function Avatar({member}){return member?.photo?React.createElement('img',{src:member.photo,alt:''}):React.createElement('span',null,member?.name?.slice(0,1)||'?')}export function Glyph({name}){return React.createElement('svg',{'data-glyph':name,'aria-hidden':true})}export function MemberBadges(){return null}export function InlineFilters(){return null}export function Popover({open,children}){return open?children:null}export function Sheet({children}){return React.createElement('section',null,children)}`;
// Stop at shared-page and conversation UI, not at the real form controls.
const emptyBoundary=/(?:page-content|page-panels|conversation|MemoryGallery)\.jsx$/;
const empty=`import React from 'react';export const PagePanelLockContext=React.createContext(false);export const usePageContent=()=>({valid:false,allowed:false,editing:false,record:{}});export function SharedPagePanels({children}){return children}export function EditableText({as='span',children}){return React.createElement(as,null,children)}export const safePageMediaUrl=value=>value;export function EditableMedia(){return null}export function PostCard(){return null}export function MemberLink(){return null}export function CommentsView(){return null}export function ReactionBar(){return null}export function MemoryGallery(){return null}`;
const built=await build({stdin:{contents:`import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';import {AppContext} from './src/ui-core.jsx';import {ImageUploadControl} from './src/image-upload-control.jsx';import {InlineDisclosure} from './src/inline-disclosure.jsx';import {EditProfile,ContactCard,ProfileStyleEditor} from './src/profiles.jsx';import {MemoryEditor} from './src/memories.jsx';import {MemberForm} from './src/family.jsx';import {SharedPagePanels} from './src/page-panels.jsx';export function render(name,props,state){const components={ImageUploadControl,InlineDisclosure,EditProfile,ContactCard,ProfileStyleEditor,MemoryEditor,MemberForm,SharedPagePanels};const context={state,theme:'dark',setPreviewColor(){},dispatch(){throw Error('A render must not mutate')},go(){},openSheet(){},setToast(){},replaceRoute(){},goBack(){}};return renderToStaticMarkup(React.createElement(AppContext.Provider,{value:context},React.createElement(components[name],props)));}`,resolveDir:root},bundle:true,platform:'node',format:'cjs',write:false,loader:{'.css':'empty'},plugins:[{name:'read-only-ui-test-boundaries',setup(b){b.onResolve({filter:/ui-core\.jsx$/},()=>({path:'ui-core',namespace:'test-ui'}));b.onLoad({filter:/.*/,namespace:'test-ui'},()=>({contents:ui,resolveDir:root,loader:'js'}));b.onResolve({filter:emptyBoundary},()=>({path:'empty-ui',namespace:'test-empty'}));b.onLoad({filter:/.*/,namespace:'test-empty'},()=>({contents:empty,resolveDir:root,loader:'js'}));}}]});
const module={exports:{}};new Function('require','module','exports',built.outputFiles[0].text)(createRequire(import.meta.url),module,module.exports);const {render}=module.exports;
const state={mode:'preview',selfId:'fictional-self',members:[{id:'fictional-self',name:'Fictional Test Adult',birthday:'1990-01-01',bio:'',socials:{},profileColor:'#4f996c',photo:null}],memories:[],groups:[],memorials:[],households:[],contact:null};

test('offline SSR boundary passes shared-page children through and leaves form controls real',()=>{
 for(const file of ['page-content.jsx','page-panels.jsx','conversation.jsx','field-gallery/MemoryGallery.jsx'])assert.ok(emptyBoundary.test(root+'src/'+file),file);
 for(const file of ['choice-control.jsx','member-picker.jsx','image-upload-control.jsx','inline-disclosure.jsx'])assert.equal(emptyBoundary.test(root+'src/'+file),false,file+' must keep its real implementation');
 assert.equal(render('SharedPagePanels',{page:'memories',children:'Retained synthetic child'},state),'Retained synthetic child');
});
test('image control has honest empty/current states, direct chooser and retry reset',()=>{
 const html=render('ImageUploadControl',{label:'Test photo'},state);assert.match(html,/No photo chosen/);assert.match(html,/Choose image/);assert.doesNotMatch(html,/<img/);assert.match(html,/type="button"[^>]*aria-label="Choose test photo"/);assert.match(html,/type="file"[^>]*tabindex="-1"/);
 const current=render('ImageUploadControl',{label:'Test photo',src:'/api/media/fictional-test',alt:'Fictional test photo'},state);assert.match(current,/<img[^>]*src="\/api\/media\/fictional-test"[^>]*alt="Fictional test photo"/);assert.match(current,/Edit test photo/);assert.match(sources['image-upload-control.jsx'],/picker.current\?\.click\(\)/);assert.match(sources['image-upload-control.jsx'],/event.currentTarget.value=''/);assert.match(sources['image-upload-control.jsx'],/Current photo unavailable/);
});
test('busy chooser is disabled and status/error are accessible',()=>{
 const html=render('ImageUploadControl',{busy:true,progress:'Adding privately',error:'Try another image'},state);assert.match(html,/aria-busy="true"/);assert.match(html,/disabled=""[^>]*aria-label="Choose photo"/);assert.match(html,/role="status">Adding privately/);assert.match(html,/role="alert">Try another image/);assert.match(html,/aria-describedby=/);
});
test('profile compact image leads name and birthday while bio is full-width afterward',()=>{
 const html=render('EditProfile',{},state);assert.match(html,/form-density-scope/);assert.match(html,/Profile photo/);assert.ok(html.indexOf('Profile photo')<html.indexOf('>Name<'));assert.ok(html.indexOf('Your birthday')<html.indexOf('>Bio '));assert.match(html,/aria-describedby="profile-birthday-help"/);assert.match(html,/Your full birth date stays private/);assert.match(html,/Show my age on my family profile/);assert.match(html,/form-label">Bio <span class="field-optional">Optional/);assert.match(html,/maxLength="400"/i);assert.doesNotMatch(html,/profile-style-preview/);
});
test('contact current image follows use-profile preference and first three details stay grouped',()=>{
 const current={...state,members:[{...state.members[0],photo:'/api/media/profile-test'}],contact:{name:'Fictional Test Adult',email:'fictional@example.test',phone:'555-0100',useProfile:true,photo:'/api/media/contact-test',visibility:'Only me',selectedIds:[],optIn:false,address:'',social:''}};
 const html=render('ContactCard',{},current);assert.match(html,/<img[^>]*src="\/api\/media\/profile-test"/);assert.doesNotMatch(html,/src="\/api\/media\/contact-test"/);assert.match(html,/Use profile photo/);assert.ok(html.indexOf('Contact photo')<html.indexOf('>Name<'));assert.ok(html.indexOf('>Name<')<html.indexOf('form-label">Email'));assert.ok(html.indexOf('form-label">Email')<html.indexOf('form-label">Phone'));assert.match(html,/Only you can see this card/);
 const distinct=render('ContactCard',{}, {...current,contact:{...current.contact,useProfile:false}});assert.match(distinct,/<img[^>]*src="\/api\/media\/contact-test"/);assert.match(distinct,/Remove photo/);
});
test('contact validation and audience remain exact and custom photo preference changes only after successful upload',()=>{
 const source=sources['profiles.jsx'];assert.match(source,/file.size>2\*1024\*1024/);assert.match(source,/const upload=await readPreviewFile\(file,state.mode\);setContact\(c=>\(\{\.\.\.c,photo:upload.url,photoFrame:undefined,useProfile:false\}\)\)/);assert.match(source,/contact.optIn&&contact.visibility==='Selected family members'&&!contact.selectedIds.length/);assert.match(source,/options=\{\['Only me','Selected family members','Family leaders','All approved family members'\]\}/);assert.match(source,/if\(photoLock.current\|\|saving\)return/);
});
test('memory image is compact, full arbitrary details survive and short date/year fields pair only when spacious',()=>{
 const memory={id:'fictional-memory',title:'Fictional caption',image:'/api/media/memory-test',mediaType:'image/jpeg',authorId:state.selfId,year:'2008',memberIds:[]};const html=render('MemoryEditor',{id:memory.id},{...state,memories:[memory]});assert.match(html,/Memory photo/);assert.match(html,/Replace media/);assert.ok(html.indexOf('Memory photo')<html.indexOf('form-label">Caption'));assert.match(html,/form-short-row/);assert.match(html,/inputMode="numeric"/i);assert.match(html,/maxLength="4"/i);for(const field of ['Event','Category','Milestone'])assert.match(html,new RegExp('form-label\">'+field+' '));
 assert.match(sources['form-layout.css'],/@container gw-form \(min-width:25rem\)/);assert.match(sources['form-layout.css'],/@container gw-fields \(min-width:24rem\)/);assert.match(sources['memories.jsx'],/set\('year',e.target.value.replace\(\/\\D\/g,''\)\)/);
});
test('video audio and PDF retain correct previews and never pretend to be an image',()=>{
 for(const [type,tag,label] of [['video/mp4','video','Video memory'],['audio/mpeg','audio','Audio memory'],['application/pdf','a','PDF memory']]){const memory={id:'fictional-'+tag,title:'Fictional attachment',image:'/api/media/file-test',mediaType:type,authorId:state.selfId,memberIds:[]};const html=render('MemoryEditor',{id:memory.id},{...state,memories:[memory]});assert.match(html,new RegExp('<'+tag+'\\b'));assert.match(html,new RegExp(label));assert.match(html,/Replace media/);assert.doesNotMatch(html,/<img|Memory photo/);}
});
test('memory upload owns busy/errors, preserves file retry and discloses featured replacement consequences',()=>{
 const source=sources['memories.jsx'];assert.match(source,/if\(uploadLock.current\|\|saving\)return/);assert.match(source,/e.currentTarget.value=''/);assert.match(source,/disabled=\{!m.image\|\|saving\|\|uploading\}/);assert.match(source,/mediaType:upload.type\|\|file.type/);assert.match(source,/x.dateStatus==='suggested'/);const m={id:'featured-test',image:'/api/media/featured-test',mediaType:'image/jpeg',memberIds:[]};const html=render('MemoryEditor',{id:m.id},{...state,memories:[m],featuredMemoryIds:[m.id]});assert.match(html,/Changing the file removes its featured-photo approval when you save/);
});
test('private child record pairs actual supported short fields without inventing photo persistence',()=>{
 const html=render('MemberForm',{child:true},state);assert.match(html,/form-short-row/);assert.match(html,/role="combobox"/);assert.match(html,/Your full birthday stays private/);assert.doesNotMatch(html,/type="file"/);assert.match(sources['family.jsx'],/variant="search" required=\{child\}/);assert.match(sources['family.jsx'],/'Woman','Man','Nonbinary','Self-described','Prefer not to say'/);
});
test('shared profile-style editor supports existing onboarding callers and does not add disclosures',()=>{
 const html=render('ProfileStyleEditor',{name:'Fictional Adult',photo:null,color:'#4f996c',onColor(){},onPhoto(){},onRemove(){}},state);assert.match(html,/Profile photo/);assert.match(html,/Fictional Adult/);assert.match(html,/Profile color/);assert.match(html,/form-density-scope/);assert.doesNotMatch(html,/<details|<summary/);
});
test('approved optional groups use inline glyph buttons and preserve theme-native control styling',()=>{
 assert.equal((sources['profiles.jsx'].match(/<details\b/g)||[]).length,0);assert.equal((sources['memories.jsx'].slice(sources['memories.jsx'].indexOf('export function MemoryEditor')).match(/<details\b/g)||[]).length,0);assert.match(sources['profiles.jsx'],/InlineDisclosure icon="home"/);assert.match(sources['memories.jsx'],/InlineDisclosure icon="people"/);assert.match(sources['memories.jsx'],/InlineDisclosure icon="calendar"/);assert.doesNotMatch(sources['form-layout.css'],/#[0-9a-f]{3,8}|backdrop-filter|opacity|font-family:|--accent:/i);assert.match(sources['form-layout.css'],/color:var\(--text\)/);
});


test('empty inline disclosure keeps its child values mounted, hidden and inert with a real linked glyph button',()=>{
 const html=render('InlineDisclosure',{label:'Add optional fields',openLabel:'Hide optional fields',icon:'home',children:'Saved draft value'},state);assert.match(html,/type="button"/);assert.match(html,/aria-expanded="false"/);assert.match(html,/aria-controls=/);assert.match(html,/data-glyph="home"/);assert.match(html,/class="inline-disclosure-content"[^>]*hidden=""[^>]*inert=""/);assert.match(html,/Saved draft value/);assert.doesNotMatch(html,/<summary|<details|role="dialog"/);
});
test('populated or invalid inline groups are open from their first render',()=>{for(const flag of ['populated','invalid']){const html=render('InlineDisclosure',{label:'Edit optional fields',openLabel:'Hide optional fields',icon:'calendar',[flag]:true,children:'Saved draft value'},state);assert.match(html,/aria-expanded="true"/);assert.match(html,new RegExp(flag==='invalid'?'Edit optional fields':'Hide optional fields'));assert.doesNotMatch(html,/hidden=""|inert=""/);}});
test('closed summary is readable and unknown glyphs never fall back to a bare arrow',()=>{const html=render('InlineDisclosure',{label:'Edit fields',icon:'unknown-glyph',summary:'Existing optional summary'},state);assert.match(html,/Existing optional summary/);assert.match(html,/data-glyph="plus"/);assert.doesNotMatch(html,/data-glyph="arrow"/)});
test('native invalid recovery opens and focuses the first invalid field without discarding children',()=>{const source=sources['inline-disclosure.jsx'];assert.match(source,/onInvalidCapture=\{showInvalid\}/);assert.match(source,/if\(focusing.current\)return/);assert.match(source,/invalidField.current=event.target/);assert.match(source,/invalidField.current\?\.focus\(\)/);assert.match(source,/validationMessage/);assert.match(source,/role="alert"/);assert.match(source,/onChangeCapture=\{recheck\}/);assert.match(source,/hidden=\{!expanded\} inert=\{!expanded\}/);assert.match(source,/needsAttention=invalid\|\|!!validation,expanded=needsAttention\|\|open/);assert.match(source,/if\(needsAttention\)focusInvalid\(\)/);assert.match(source,/input\[aria-invalid=\"true\"\]/);assert.doesNotMatch(source,/open&&children|open\?children/)});
test('inline reveal has reduced-motion handling, 44px targets, opacity transition and explicit hidden rule',()=>{const css=sources['inline-disclosure.css'];assert.match(css,/min-height:44px/);assert.match(css,/200ms/);assert.match(css,/prefers-reduced-motion:reduce/);assert.match(css,/\.inline-disclosure-content\[hidden\]\{display:none\}/);assert.doesNotMatch(css,/#[0-9a-f]{3,8}|backdrop-filter/i)});
test('four meaningful contact visibility choices use required screenshot-approved radio tiles',()=>{const html=render('ContactCard',{},state);const start=html.indexOf('Who can see your details?');const relevant=html.slice(Math.max(0,start-300));assert.match(relevant,/choice-control-chips/);assert.equal((relevant.match(/type="radio"/g)||[]).length,4);assert.match(relevant,/required=""/);assert.match(relevant,/Only me/)});


test('custom HTTPS-invalid contact links keep optional recovery fields visible and marked',()=>{const html=render('ContactCard',{}, {...state,contact:{name:'Fictional Test Adult',email:'',phone:'',address:'',social:'http://example.test',visibility:'Only me',selectedIds:[],optIn:false,useProfile:true,photo:null}});assert.match(html,/aria-expanded="true"/);assert.match(html,/type="url"[^>]*aria-invalid="true"/);assert.doesNotMatch(html,/inline-disclosure-content"[^>]*hidden/);assert.match(html,/Edit address and link/);assert.doesNotMatch(html,/Hide address and link/)});
