import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {installPlatform,embeddedBrowser,installedDisplay,installSteps} from '../src/install-capabilities.js';
test('platform hints distinguish iPad desktop UA, Android, and unknown without pretending installation support',()=>{assert.equal(installPlatform({userAgent:'Mozilla iPhone'}),'apple');assert.equal(installPlatform({platform:'MacIntel',maxTouchPoints:5}),'apple');assert.equal(installPlatform({platform:'MacIntel',maxTouchPoints:0}),'mac');assert.equal(installPlatform({userAgent:'Mozilla Android'}),'android');assert.equal(installPlatform({}),'other');assert.equal(embeddedBrowser('Instagram 55'),true);assert.equal(embeddedBrowser('Chrome Android'),false)});
test('installed display checks actual standalone capability',()=>{assert.equal(installedDisplay({matchMedia:()=>({matches:true})},{}),true);assert.equal(installedDisplay({matchMedia:()=>({matches:false})},{standalone:true}),true);assert.equal(installedDisplay({matchMedia:()=>({matches:false})},{}),false)});
test('both mobile guides retain sequenced visual reinforcement',()=>{assert.equal(installSteps.apple.length,3);assert.equal(installSteps.android.length,3);assert.match(installSteps.apple[0].text,/Page Menu/);assert.match(installSteps.apple[2].text,/if that switch appears/);for(const steps of Object.values(installSteps))for(const step of steps)assert.ok(step.title&&step.text&&step.art)});
test('install code has no notification grants, push subscription, Web Share confusion or automatic prompt',async()=>{const source=await readFile(new URL('../src/install.jsx',import.meta.url),'utf8');assert.doesNotMatch(source,/requestPermission|pushManager|navigator\.share/);assert.match(source,/onClick=\{install\}/);assert.match(source,/steps\.map/);assert.match(source,/alive\.current/);assert.match(source,/appinstalled/);assert.match(source,/Illustrated guide/)});

test('desktop install guidance covers macOS, Windows and ChromeOS without requiring installation for push',()=>{assert.equal(installPlatform({userAgent:'Mozilla Macintosh Mac OS X'}),'mac');assert.equal(installPlatform({userAgent:'Mozilla Windows NT 10.0'}),'windows');assert.equal(installPlatform({userAgent:'Mozilla CrOS x86_64'}),'chromeos');for(const platform of ['mac','windows','chromeos'])assert.match(installSteps[platform].map(s=>s.text).join(' '),/Installation is optional/);assert.match(installSteps.mac[0].text,/Sonoma/);assert.match(installSteps.mac[1].text,/Ventura/)});
