import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,executablePath:process.env.PW_CHROME||undefined});const errors=[];const url='http://127.0.0.1:4174';
await mkdir('docs/live-qa',{recursive:true});
async function person(id,width=390){const page=await browser.newPage({viewport:{width,height:844},reducedMotion:'reduce'});page.on('pageerror',e=>errors.push(e.message));page.on('response',async r=>{if(r.url().includes('/api/')&&r.status()>=400)console.log('API failure',r.status(),r.url(),await r.text())});await page.goto(url+'/__test/signin?user='+id);await page.getByRole('navigation',{name:'Main navigation'}).waitFor();return page}
try{
 const noClip=async page=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1&&[...document.querySelectorAll('input,select,textarea')].filter(e=>e.getClientRects().length).every(e=>{const r=e.getBoundingClientRect();return r.left>=-1&&r.right<=innerWidth+1})), 'mobile form controls stay within viewport');
 const fresh=await browser.newPage({viewport:{width:320,height:720}});fresh.on('pageerror',e=>errors.push(e.message));await fresh.goto(url+'/__test/signin?user=fresh');await fresh.getByRole('heading',{name:'A little about you.'}).waitFor();await noClip(fresh);await fresh.getByLabel('Your name',{exact:true}).fill('Fresh Relative');await fresh.getByLabel('Birthday',{exact:true}).fill('1990-01-01');await fresh.getByLabel(/I understand this profile/).check();await fresh.getByRole('button',{name:'Continue',exact:true}).click();await fresh.getByRole('heading',{name:'Make it yours.'}).waitFor();await fresh.getByLabel('Custom profile color').fill('#ca247c');await noClip(fresh);await fresh.screenshot({path:'docs/live-qa/onboarding-profile-320.png'});await fresh.getByRole('button',{name:'Back',exact:true}).click();assert.equal(await fresh.getByLabel('Your name',{exact:true}).inputValue(),'Fresh Relative');await fresh.getByRole('button',{name:'Continue',exact:true}).click();await fresh.getByRole('button',{name:'Finish joining',exact:true}).click();await fresh.getByRole('button',{name:'Check my status'}).click();await fresh.getByRole('status').filter({hasText:'Still waiting for organizer approval.'}).waitFor();await noClip(fresh);await fresh.close();
 const alice=await person('alice');await alice.getByRole('button',{name:'Post an update',exact:true}).click();await alice.getByRole('textbox',{name:"What's on your mind"}).fill('A real persisted family update');await alice.getByRole('button',{name:'Send post',exact:true}).click();await alice.getByText('A real persisted family update',{exact:true}).waitFor();await alice.reload();await alice.getByText('A real persisted family update',{exact:true}).waitFor();
 const bob=await person('bob',1280);await bob.getByText('A real persisted family update',{exact:true}).waitFor();const article=bob.getByRole('article').filter({hasText:'A real persisted family update'});await article.getByRole('button',{name:/Comments/}).click();await bob.getByRole('textbox',{name:'Write a comment…'}).fill('A reply from another account');await bob.getByRole('button',{name:'Send',exact:true}).click();await bob.getByRole('dialog').getByText('A reply from another account',{exact:true}).waitFor();await bob.getByRole('button',{name:'Close dialog'}).click();await alice.reload();await alice.getByRole('article').filter({hasText:'A real persisted family update'}).getByRole('button',{name:/Comments/}).click();await alice.getByRole('dialog').getByText('A reply from another account',{exact:true}).waitFor();await alice.getByRole('button',{name:'Close dialog'}).click();
 await alice.getByRole('navigation').getByRole('button',{name:'You',exact:true}).click();assert.equal(await alice.getByRole('heading',{name:'Planner tools',exact:true}).count(),0);await alice.getByRole('button',{name:/My RSVP/}).click();await alice.getByLabel('How many people?').selectOption('3');await alice.getByRole('button',{name:'Save RSVP',exact:true}).click();await alice.getByText('Planning to come',{exact:true}).waitFor();await alice.reload();await alice.getByRole('navigation').getByRole('button',{name:'You',exact:true}).click();await alice.getByText('Planning to come',{exact:true}).waitFor();
 const owner=await person('owner',1280);await owner.getByRole('navigation').getByRole('button',{name:'You',exact:true}).click();await owner.getByRole('button',{name:'Open family organizer',exact:true}).click();await owner.getByRole('tab',{name:'People',exact:true}).click();const pending=owner.getByRole('article').filter({hasText:'pending@example.test'});await pending.getByRole('button',{name:'Approve membership',exact:true}).click();await pending.getByText(/active/).waitFor();await owner.getByRole('tab',{name:'RSVPs'}).click();await owner.getByText('Planning to come · 3 people',{exact:true}).waitFor();await owner.screenshot({path:'docs/live-qa/organizer-desktop.png'});
 await alice.getByRole('navigation').getByRole('button',{name:'Family',exact:true}).click();await alice.getByRole('tab',{name:'Memories',exact:true}).click();
 const png={name:'memory.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aHMkAAAAASUVORK5CYII=','base64')};
 const chooserPromise=alice.waitForEvent('filechooser');await alice.getByRole('button',{name:'Add a memory',exact:true}).click();await(await chooserPromise).setFiles(png);await alice.getByText('Your memory is saved. Add any details you know, or close this window.').waitFor();await noClip(alice);await alice.getByRole('button',{name:'Close dialog'}).click();await alice.reload();await alice.getByRole('navigation').getByRole('button',{name:'Family',exact:true}).click();await alice.getByRole('tab',{name:'Memories',exact:true}).click();assert.equal(await alice.locator('.field-memory-open').count(),1);assert.equal(await alice.getByRole('tab',{name:'Featured photos',exact:true}).count(),0);
 await owner.getByRole('button',{name:'Close dialog'}).click();await owner.getByRole('navigation').getByRole('button',{name:'Family',exact:true}).click();await owner.getByRole('tab',{name:'Memories',exact:true}).click();await owner.getByRole('tab',{name:'Featured photos',exact:true}).click();await owner.getByRole('button',{name:'Approve photo',exact:true}).click();await owner.getByRole('button',{name:'Use as main photo',exact:true}).click();await owner.getByText('Main photo',{exact:true}).waitFor();await owner.screenshot({path:'docs/live-qa/featured-photos-desktop.png'});
 await alice.screenshot({path:'docs/live-qa/live-memories-mobile.png'});assert.deepEqual(errors,[]);await writeFile('docs/live-qa/results.json',JSON.stringify({passed:['cross-account post persistence','cross-account comments','RSVP persistence','role-scoped organizer','membership approval','320px two-step onboarding and visible status feedback','one-tap media upload with optional details','admin-only featured photo approval'],errors},null,2));
}catch(e){for(const page of browser.contexts().flatMap(c=>c.pages())){console.log('Failed-page text',await page.locator('body').innerText());await page.screenshot({path:'docs/live-qa/failure-'+Date.now()+'.png'});}await writeFile('docs/live-qa/results.json',JSON.stringify({failure:e.message,errors},null,2));throw e}finally{await browser.close()}
