import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,executablePath:process.env.PW_CHROME||undefined});const errors=[];const url='http://127.0.0.1:4174';
await mkdir('docs/live-qa',{recursive:true});
async function person(id,width=390){const page=await browser.newPage({viewport:{width,height:844},reducedMotion:'reduce'});page.on('pageerror',e=>errors.push(e.message));await page.goto(url+'/__test/signin?user='+id);await page.getByRole('navigation',{name:'Main navigation'}).waitFor();return page}
try{
 const alice=await person('alice');await alice.getByRole('button',{name:'Post an update',exact:true}).click();await alice.getByRole('textbox',{name:"What's on your mind"}).fill('A real persisted family update');await alice.getByRole('button',{name:'Send post',exact:true}).click();await alice.getByText('A real persisted family update',{exact:true}).waitFor();await alice.reload();await alice.getByText('A real persisted family update',{exact:true}).waitFor();
 const bob=await person('bob',1280);await bob.getByText('A real persisted family update',{exact:true}).waitFor();const article=bob.getByRole('article').filter({hasText:'A real persisted family update'});await article.getByRole('button',{name:/Comments/}).click();await bob.getByRole('textbox',{name:'Write a comment…'}).fill('A reply from another account');await bob.getByRole('button',{name:'Send',exact:true}).click();await bob.getByText('A reply from another account',{exact:true}).waitFor();await bob.getByRole('button',{name:'Close dialog'}).click();await alice.reload();await alice.getByRole('article').filter({hasText:'A real persisted family update'}).getByRole('button',{name:/Comments/}).click();await alice.getByText('A reply from another account',{exact:true}).waitFor();await alice.getByRole('button',{name:'Close dialog'}).click();
 await alice.getByRole('navigation').getByRole('button',{name:'You',exact:true}).click();assert.equal(await alice.getByRole('heading',{name:'Planner tools',exact:true}).count(),0);await alice.getByRole('button',{name:/My RSVP/}).click();await alice.getByLabel('How many people?').selectOption('3');await alice.getByRole('button',{name:'Save RSVP',exact:true}).click();await alice.getByText('Planning to come',{exact:true}).waitFor();await alice.reload();await alice.getByRole('navigation').getByRole('button',{name:'You',exact:true}).click();await alice.getByText('Planning to come',{exact:true}).waitFor();
 const owner=await person('owner',1280);await owner.getByRole('navigation').getByRole('button',{name:'You',exact:true}).click();await owner.getByRole('button',{name:'Open family organizer',exact:true}).click();await owner.getByRole('tab',{name:'People',exact:true}).click();const pending=owner.getByRole('article').filter({hasText:'pending@example.test'});await pending.getByRole('button',{name:'Approve membership',exact:true}).click();await pending.getByText(/active/).waitFor();await owner.getByRole('tab',{name:'RSVPs'}).click();await owner.getByText('Planning to come · 3 people',{exact:true}).waitFor();await owner.screenshot({path:'docs/live-qa/organizer-desktop.png'});
 await alice.screenshot({path:'docs/live-qa/live-you-mobile.png'});assert.deepEqual(errors,[]);await writeFile('docs/live-qa/results.json',JSON.stringify({passed:['cross-account post persistence','cross-account comments','RSVP persistence','role-scoped organizer','membership approval'],errors},null,2));
}catch(e){await writeFile('docs/live-qa/results.json',JSON.stringify({failure:e.message,errors},null,2));throw e}finally{await browser.close()}
