// Ordinary built app, fictional anonymous session, no remote API or writes.
import {chromium,webkit,expect} from '@playwright/test';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import assert from 'node:assert/strict';
import {initialState,PREVIEW_KEY} from '../src/data-adapter.js';
const root=resolve('dist'),output=resolve(process.env.GW_ONBOARDING_QA_OUTPUT||'../push-fix-intake/onboarding-source-qa'),engine=process.env.GW_BROWSER==='webkit'?'webkit':'chromium',results=[],writes=[],externalBlocked=[],errors=[];
const server=createServer(async(req,res)=>{try{const path=resolve(root,'.'+new URL(req.url,'http://fixture').pathname.replace(/\/$/,'/index.html'));if(!path.startsWith(root+'/'))throw Error('path');const data=await readFile(path);res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.svg':'image/svg+xml'})[extname(path)]||'application/octet-stream');res.end(data)}catch{res.statusCode=404;res.end('Not found')}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;let browser;
try{
 await mkdir(output,{recursive:true});browser=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'&&process.env.GW_ONBOARDING_CHROMIUM_PATH?{executablePath:process.env.GW_ONBOARDING_CHROMIUM_PATH}:{})});
 const context=await browser.newContext({reducedMotion:'reduce'});
 async function attachRoutes(context,{preview=false}={}){await context.route('**/*',async route=>{const request=route.request(),url=new URL(request.url());if(url.origin!==base){externalBlocked.push(url.origin);return route.abort()}if(url.pathname==='/api/family-invitations/welcome'&&request.method()==='POST'){assert.deepEqual(request.postDataJSON(),{token:'a'.repeat(64)});return route.fulfill({json:{inviterName:'Alex'}})}if(!['GET','HEAD'].includes(request.method())){writes.push(url.pathname);return route.abort()}if(url.pathname==='/api/config')return route.fulfill({json:{configured:!preview,email:true,providers:['google','microsoft','yahoo'],providerMethods:['google','microsoft','yahoo'].map(id=>({id,mode:'access'}))}});if(url.pathname==='/api/session')return route.fulfill({json:{status:'anonymous',signedIn:false,configured:!preview}});if(url.pathname.startsWith('/api/'))throw Error('Unexpected API read '+url.pathname);return route.continue()})}
 await attachRoutes(context);
 const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));
 await page.addInitScript(()=>{localStorage.setItem('gw-font','serif');localStorage.setItem('gw-theme','light');localStorage.setItem('gw-platform','ios')});
 for(const [width,height]of [[430,780],[1280,1000],[375,600]]){
  await page.setViewportSize({width,height});await page.goto(base+'/');await expect(page.getByRole('button',{name:'Email me a code',exact:true})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Come on in.',exact:true})).toBeVisible();
  await expect(page.locator('footer')).toContainText('Green & White. Same roots. New memories.');
  await expect(page.locator('img[src^="/api/media/"], video[src^="/api/media/"], [data-page-field]')).toHaveCount(0);
  await expect(page.getByRole('heading',{name:'Good to see you',exact:true})).toHaveCount(0);for(const provider of ['Google','Microsoft','Yahoo'])await expect(page.getByRole('button',{name:'Sign up with '+provider,exact:true})).toBeVisible();
  const geometry=await page.evaluate(()=>{
   const frame=document.querySelector('.onboarding-frame'),card=frame?.querySelector(':scope > .onboard.card'),preview=frame?.querySelector(':scope > .onboarding-more'),mark=card?.querySelector('.wordmark'),form=card?.querySelector('.sign-in-form');
   if(!frame||!card||!preview||!mark||!form)return null;
   const a=card.getBoundingClientRect(),b=preview.getBoundingClientRect(),f=frame.getBoundingClientRect();return {display:getComputedStyle(frame).display,top:a.top-f.top,bottom:f.bottom-b.bottom,groupHeight:b.bottom-a.top,frameHeight:f.height,previewOutside:preview.parentNode===frame,overflow:document.documentElement.scrollWidth>innerWidth,font:getComputedStyle(mark).fontFamily,rootFont:document.documentElement.dataset.font,separator:getComputedStyle(form).borderTopWidth};
  });
  assert.ok(geometry,'Ordinary source includes onboarding frame and outside preview');assert.equal(geometry.display,'flex');assert.equal(geometry.previewOutside,true);assert.equal(geometry.overflow,false);assert.equal(geometry.separator,'0px');assert.match(geometry.font,/Momo Trust Display/);assert.equal(geometry.rootFont,'serif');
  if(geometry.groupHeight+32<=height)assert.ok(Math.abs(geometry.top-geometry.bottom)<=2,JSON.stringify(geometry));else assert.ok(geometry.top>=15&&geometry.top<=17,JSON.stringify(geometry));
  await page.getByRole('button',{name:'More',exact:true}).focus();await expect(page.getByRole('button',{name:'More',exact:true})).toBeFocused();await page.getByRole('button',{name:'More',exact:true}).click();await expect(page.getByRole('dialog',{name:'More options'})).toBeVisible();await page.getByRole('button',{name:'Help signing in',exact:true}).click();await expect(page.getByRole('dialog',{name:'Help signing in'})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'More',exact:true})).toBeFocused();await expect(page.getByText('Apple sign-in coming soon. Use an email code below.',{exact:true})).toBeVisible();
  await page.screenshot({path:output+'/'+engine+'-'+width+'x'+height+'.png',fullPage:false});results.push({width,height,...geometry});
 }
 for(const os of ['ios','android']){
  const mobile=await browser.newContext({viewport:{width:430,height:932},reducedMotion:'reduce',userAgent:os==='ios'?'Mozilla/5.0 (iPhone; CPU iPhone OS 26_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1':'Mozilla/5.0 (Linux; Android 16; Pixel 9) AppleWebKit/537.36 Chrome/140.0 Mobile Safari/537.36'});await attachRoutes(mobile);const p=await mobile.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/');await p.getByRole('button',{name:'More',exact:true}).click();
  const placement=await p.evaluate(()=>{const menu=document.querySelector('.onboarding-more-pop'),trigger=document.querySelector('.onboarding-more-trigger'),a=menu.getBoundingClientRect(),b=trigger.getBoundingClientRect();return {above:a.bottom<=b.top+1,centerDifference:(a.left+a.right-b.left-b.right)/2}});assert.equal(placement.above,true);assert.ok(Math.abs(placement.centerDifference)<2);
  await p.getByRole('button',{name:'Install GW',exact:true}).click();const guide=p.getByRole('dialog',{name:'Add to Homescreen',exact:true});await expect(guide).toBeVisible();await expect(guide.getByRole('tablist',{name:'Instructions for',exact:true})).toHaveCount(0);await expect(guide.locator('.install-guide-options>span')).toHaveText(os==='ios'?'iPhone / iPad instructions':'Android instructions');
  await guide.getByRole('button',{name:'More',exact:true}).click();await p.getByRole('button',{name:os==='ios'?'View Android instructions':'View iPhone / iPad instructions',exact:true}).click();await expect(guide.locator('.install-guide-options>span')).toHaveText(os==='ios'?'Android instructions':'iPhone / iPad instructions');
  if(os==='android'){
   await p.evaluate(()=>{window.fixtureInstallCalls=0;const event=new Event('beforeinstallprompt',{cancelable:true});event.prompt=async()=>{window.fixtureInstallCalls++};event.userChoice=Promise.resolve({outcome:'dismissed'});window.dispatchEvent(event)});await guide.getByRole('button',{name:'Install Green & White',exact:true}).click();await expect(guide.getByRole('status')).toHaveText('You can install later. The steps below are always here.');assert.equal(await p.evaluate(()=>window.fixtureInstallCalls),1);
  }
  await p.keyboard.press('Escape');await expect(guide).toHaveCount(0);await expect(p.getByRole('button',{name:'More',exact:true})).toBeFocused();results.push({os,entryInstall:true,secondaryGuideSelector:true,syntheticPrompt:os==='android'?'dismissed':'none',...placement});await mobile.close();
 }
 await page.goto(base+'/#/family-invite/'+'a'.repeat(64));await expect(page.getByRole('heading',{name:'Alex invited you to join the fun.',exact:true})).toBeVisible();results.push({anonymousInvitation:true,firstNameOnly:true,readOnlyLookup:true});
 const preview=await browser.newContext({viewport:{width:1280,height:1000},reducedMotion:'reduce'});await attachRoutes(preview,{preview:true});const previewState={...initialState(),onboarding:'done'};await preview.addInitScript(({key,state})=>{localStorage.setItem(key,JSON.stringify({schema:2,mode:'preview',state}))},{key:PREVIEW_KEY,state:previewState});const pp=await preview.newPage();pp.on('pageerror',e=>errors.push(e.message));
 for(const width of [1280,768,430]){
  await pp.setViewportSize({width,height:1000});for(const route of ['you','family']){await pp.goto(base+'/#/'+route);const card=pp.locator('.invitation-sidebar-card');await expect(card).toHaveCount(1);await expect(card.getByRole('button',{name:'Invitations',exact:true})).toBeVisible();const placement=await card.evaluate(el=>({inSide:!!el.closest('.page-panel-zone-side'),lastOnMobile:el.closest('.page-panel-mobile-stack')?.lastElementChild===el||el.closest('.page-panel-mobile-stack')?.lastElementChild?.contains(el),overflow:document.documentElement.scrollWidth>innerWidth}));assert.equal(placement.overflow,false);if(width>=768)assert.equal(placement.inSide,true,JSON.stringify({route,width,...placement}));else assert.equal(placement.lastOnMobile,true,JSON.stringify({route,width,...placement}));results.push({route,width,invitationCard:true,...placement})}
 }
 await pp.goto(base+'/#/you');const about=pp.getByRole('button',{name:/About Green & White/});await about.click();const aboutDialog=pp.getByRole('dialog',{name:'About Green & White',exact:true});await expect(aboutDialog).toBeVisible();await expect(aboutDialog.getByText('Open-source notices',{exact:true})).toBeVisible();await aboutDialog.locator('.about-open-source>summary').click();await expect(aboutDialog.getByRole('heading',{name:'Typography',exact:true})).toBeVisible();await pp.keyboard.press('Escape');await expect(aboutDialog).toHaveCount(0);await expect(about).toBeFocused();results.push({aboutModal:true,noticesRetained:true,escapeAndFocusReturn:true});
 await pp.goto(base+'/#/invitations');await expect(pp.getByRole('heading',{name:'Your invitation link',exact:true})).toBeVisible();const emailPanel=pp.locator('section.card').filter({has:pp.getByRole('heading',{name:'Invite someone by email',exact:true})});await expect(emailPanel.getByRole('button',{name:'Create invitation link',exact:true})).toHaveCount(0);await expect(emailPanel.getByRole('button',{name:'Save sample invitation',exact:true})).toHaveCount(0);await expect(emailPanel.getByRole('button',{name:'Try email invitation',exact:true})).toBeVisible();results.push({emailPanelHasNoLinkCreation:true,reusableLinkCardRetained:true});await preview.close();
 assert.equal(writes.length,0);assert.deepEqual(errors,[]);await writeFile(output+'/'+engine+'-receipt.json',JSON.stringify({engine,ordinarySource:true,fictionalAnonymousSession:true,results,writes,errors,externalRequestsBlocked:[...new Set(externalBlocked)],limits:'Headless source geometry; no actual iOS Safari, mail, push, enrollment or delivery proof.'},null,2));console.log('Onboarding source PASS:',results.length,'viewports, Momo override preserves root font, More/help/Escape, three SignUp providers, Apple note, no writes/errors.');
}finally{await browser?.close();await new Promise(resolve=>server.close(resolve))}
