import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const source=fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');
function setup(){const elements=new Map();const get=s=>{if(!elements.has(s))elements.set(s,{innerHTML:'',textContent:'',value:'',open:false,dataset:{},setAttribute(){},classList:{add(){},remove(){}},showModal(){this.open=true},close(){this.open=false}});return elements.get(s)};const context=vm.createContext({familyPhotos:{garden:'data:image/avif;base64,fixture',generations:'data:image/avif;base64,fixture'},document:{querySelector:get,documentElement:{dataset:{theme:'dark'},style:{setProperty(){}}},addEventListener(){}},window:{scrollTo(){}},setTimeout(){return 1},clearTimeout(){}});vm.runInContext(source,context);return {run:s=>vm.runInContext(s,context),get}}
test('home clearly separates feed and reunion without losing panels',()=>{const {get}=setup();const html=get('#main').innerHTML;for(const text of ['Family feed','Your reunion','Family shirts','Your contribution'])assert.ok(html.includes(text),text)});
test('planner entry lives under You and is explicitly a preview',()=>{const {run,get}=setup();run("go('you')");assert.match(get('#main').innerHTML,/Planner tools/);run("act('planner')");assert.match(get('#main').innerHTML,/Planner preview/);assert.match(get('#main').innerHTML,/Back to You/)});
test('contribution has no configured recipient or fake paid state',()=>{const {run,get}=setup();run("act('contribute')");assert.match(get('#sheet-body').innerHTML,/not configured/);assert.doesNotMatch(get('#sheet-body').innerHTML,/href=/);run("act('sent-preview')");assert.equal(get('#sheet-title').textContent,'Awaiting confirmation');assert.match(get('#sheet-body').innerHTML,/No money was sent/)});
test('theme switches without changing the selected view',()=>{const {run,get}=setup();run("go('family');toggleTheme()");assert.match(get('#main').innerHTML,/Same roots/);assert.equal(run('document.documentElement.dataset.theme'),'light')});
test('RSVP guides to shirts but remains explicitly session-only',()=>{const {run,get}=setup();get('#rsvp-count').value='3';get('#rsvp-status').value='Planning to come';run("act('save-rsvp')");assert.match(get('#sheet-body').innerHTML,/Next: family shirts/);assert.match(get('#sheet-body').innerHTML,/this visit only/)});

test('memories and roots live in Family, not Home',()=>{const {run,get}=setup();assert.doesNotMatch(get('#main').innerHTML,/Shared memories|Find your people/);run("go('family')");assert.match(get('#main').innerHTML,/Shared memories/);assert.match(get('#main').innerHTML,/Find your people/)});
test('profile font choices preserve body text and include four requested faces',()=>{const {run,get}=setup();for(const f of ['Glass Antiqua','Taviraj','Corben','DM Serif Text'])assert.ok(get('#profile-popout').innerHTML.includes(f));run("chooseSerif('Corben')");assert.equal(run('serifFont'),'Corben');assert.equal(run('document.documentElement.dataset.font'),'serif');run("chooseSerif('untrusted')");assert.equal(run('serifFont'),'Corben')});
test('You has its own planner section and creator credit',()=>{const {run,get}=setup();run("go('you')");assert.match(get('#main').innerHTML,/planner-section/);assert.match(get('#main').innerHTML,/https:\/\/loew.fi/);assert.match(get('#main').innerHTML,/Lauren Olivia/)});
test('greetings are short and change when returning Home',()=>{const {run}=setup();assert.ok(run('greetings.every(x=>x.length<40)'));const first=run('greeting');run("go('family');go('home')");assert.notEqual(run('greeting'),first)});
