import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const emojiSource=fs.readFileSync(new URL('../dist/emoji-data.js',import.meta.url),'utf8');
const source=fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');
function setup(){const events={};const elements=new Map();const get=s=>{if(!elements.has(s))elements.set(s,{innerHTML:'',textContent:'',value:'',open:false,dataset:{},setAttribute(){},classList:{add(){},remove(){}},showModal(){this.open=true},close(){this.open=false}});return elements.get(s)};const context=vm.createContext({URL,familyPhotos:{garden:'data:image/avif;base64,fixture',generations:'data:image/avif;base64,fixture'},document:{querySelector:get,documentElement:{dataset:{theme:'dark'},style:{setProperty(){}}},addEventListener(name,fn){(events[name]||=[]).push(fn)}},window:{scrollTo(){}},setTimeout(){return 1},clearTimeout(){}});vm.runInContext(emojiSource,context);vm.runInContext(source,context);return {events,run:s=>vm.runInContext(s,context),get}}
test('home clearly separates feed and reunion without losing panels',()=>{const {get}=setup();const html=get('#main').innerHTML;for(const text of ['Family feed','Your reunion','Family shirts','Your contribution'])assert.ok(html.includes(text),text)});
test('planner entry lives under You and is explicitly a preview',()=>{const {run,get}=setup();run("go('you')");assert.match(get('#main').innerHTML,/Planner tools/);run("act('planner')");assert.match(get('#main').innerHTML,/Planner preview/);assert.match(get('#main').innerHTML,/Back to You/)});
test('contribution has no configured recipient or fake paid state',()=>{const {run,get}=setup();run("act('contribute')");assert.match(get('#sheet-body').innerHTML,/not configured/);assert.doesNotMatch(get('#sheet-body').innerHTML,/href=/);run("act('sent-preview')");assert.equal(get('#sheet-title').textContent,'Awaiting confirmation');assert.match(get('#sheet-body').innerHTML,/No money was sent/)});
test('theme switches without changing the selected view',()=>{const {run,get}=setup();run("go('family');toggleTheme()");assert.match(get('#main').innerHTML,/Our family/);assert.equal(run('document.documentElement.dataset.theme'),'light')});
test('RSVP guides to shirts but remains explicitly session-only',()=>{const {run,get}=setup();get('#rsvp-count').value='3';get('#rsvp-status').value='Planning to come';run("act('save-rsvp')");assert.match(get('#sheet-body').innerHTML,/Next: family shirts/);assert.match(get('#sheet-body').innerHTML,/this visit only/)});

test('Family has People, Memories and later Tree without duplicate Home cards',()=>{const {run,get}=setup();assert.doesNotMatch(get('#main').innerHTML,/Shared memories|Find your people/);run("go('family')");assert.match(get('#main').innerHTML,/Address book/);run("familyTab='memories';render()");assert.match(get('#main').innerHTML,/Shared memories/);run("familyTab='tree';render()");assert.match(get('#main').innerHTML,/Planned for a later phase/)});
test('DM Serif is the chosen decorative face and temporary selector is removed',()=>{const {run,get}=setup();assert.equal(run('serifFont'),'DM Serif Text');assert.doesNotMatch(get('#profile-popout').innerHTML,/serif-picker/);assert.match(get('#profile-popout').innerHTML,/Appearance/);assert.doesNotMatch(get('#profile-popout').innerHTML,/Heading style<\/div>/)});
test('You has its own planner section and creator credit',()=>{const {run,get}=setup();run("go('you')");assert.match(get('#main').innerHTML,/planner-section/);assert.match(get('#main').innerHTML,/https:\/\/loew.fi/);assert.match(get('#main').innerHTML,/Lauren Olivia/)});
test('greetings are short and change when returning Home',()=>{const {run}=setup();assert.ok(run('greetings.every(x=>x.length<40)'));const first=run('greeting');run("go('family');go('home')");assert.notEqual(run('greeting'),first)});

test('notification filtering and contact preview do not imply active services',()=>{const {run,get}=setup();run("notificationScope='leaders';notifications()");assert.match(get('#sheet-body').innerHTML,/planning crew/);assert.doesNotMatch(get('#sheet-body').innerHTML,/new family memory/);run("notificationScope='off';notifications()");assert.match(get('#sheet-body').innerHTML,/No updates/);run("act('contact-card')");assert.match(get('#sheet-body').innerHTML,/Nothing entered here is uploaded/)});

test('all posts, including polls, have React and Comment controls',()=>{const {run,get}=setup();const html=get('#main').innerHTML;for(const id of ['photo','poll']){assert.match(html,new RegExp('data-react-post="'+id+'"'));assert.match(html,new RegExp('data-comment-post="'+id+'"'))}run("preview.posts.push({id:'post-test',name:'Test',text:'Hello',attachment:null});render()");assert.match(get('#main').innerHTML,/data-comment-post="post-test"/)});
test('full emoji corpus includes skin tones, search and pagination',()=>{const {run,get}=setup();assert.equal(run('emojiData.length'),1870);assert.ok(run('emojiChoices().length')>3000);run("showReactions('poll')");assert.match(get('#sheet-body').innerHTML,/Search all emoji/);assert.match(get('#emoji-results').innerHTML,/Show more emoji/);run("emojiQuery='heart';renderEmojiResults()");assert.match(get('#emoji-results').innerHTML,/Heart/i);run("emojiQuery='thisdoesnotexist';renderEmojiResults()");assert.match(get('#emoji-results').innerHTML,/0 of 0/)});
test('reactions toggle independently per preview user and post',()=>{const {run}=setup();assert.equal(run("toggleReaction('photo','❤️')"),true);assert.equal(run("preview.reactions.photo.length"),1);run("toggleReaction('poll','❤️');toggleReaction('photo','❤️')");assert.equal(run('preview.reactions.photo.length'),0);assert.equal(run('preview.reactions.poll.length'),1);assert.equal(run("toggleReaction('poll','<img>')"),false);assert.equal(run("toggleReaction('missing','❤️')"),false)});
test('comments are threaded, bounded and safely rendered',()=>{const {run}=setup();run(`addComment('poll','<img src=x onerror=alert(1)>');addComment('poll','Reply',preview.comments.poll[0].id)`);const html=run("commentTree('poll')");assert.match(html,/&lt;img/);assert.doesNotMatch(html,/<img/);assert.match(html,/Reply/);assert.equal(run("addComment('poll','x'.repeat(1501))"),false);assert.equal(run("addComment('poll','   ')"),false);assert.equal(run("addComment('poll','orphan','missing')"),false);run("addComment('poll','Third',preview.comments.poll[1].id);addComment('poll','Fourth',preview.comments.poll[2].id)");assert.equal(run("addComment('poll','Too deep',preview.comments.poll[3].id)"),false)});
test('URL parsing allowlists exact HTTPS hosts and gives other URLs safe fallbacks',()=>{const {run}=setup();assert.equal(run("parsePreviewLink('Listen https://open.spotify.com/track/123 please').provider"),'Spotify');assert.equal(run("parsePreviewLink('https://youtu.be/123').provider"),'YouTube');assert.equal(run("parsePreviewLink('https://music.apple.com/us/album/test').provider"),'Apple Music');assert.equal(run("parsePreviewLink('https://youtube.com.evil.example/x').supported"),false);assert.equal(run("parsePreviewLink('http://youtube.com/x').supported"),false);assert.equal(run("safeUrl('javascript:alert(1)')"),null);assert.equal(run("safeUrl('https://user:pass@example.com')"),null);assert.equal(run("parsePreviewLink('https://youtu.be/123).').raw"),'https://youtu.be/123')});
test('converting and restoring a link preserves commentary and other URLs',()=>{const {run}=setup();run("composer={text:'Play https://youtu.be/123 with us https://example.com',attachment:null};convertComposerLink(composer)");assert.equal(run('composer.text'),'Play  with us https://example.com');run("composer.text+=' tonight';restoreComposerLink(composer)");assert.equal(run('composer.text'),'Play https://youtu.be/123 with us https://example.com tonight');assert.equal(run('composer.attachment'),null);run("convertComposerLink(composer);composer.removed=composer.attachment;composer.attachment=null;restoreComposerLink(composer)");assert.equal(run('composer.text'),'Play https://youtu.be/123 with us https://example.com tonight')});
test('composer posts locally, escapes text, and clears draft without resurrecting it',()=>{const {run,get}=setup();run("showComposer()");get('#post-text').value='<script>alert(1)</script> Family hello';run('publishPreviewPost()');assert.equal(run('preview.posts.length'),1);assert.equal(run('composer.text'),'');assert.equal(get('#sheet').open,false);assert.match(get('#main').innerHTML,/&lt;script&gt;/);assert.doesNotMatch(get('#main').innerHTML,/<script>/);run('showComposer()');get('#post-text').value='Keep this draft';run('close()');assert.equal(run('composer.text'),'Keep this draft')});
test('composer attachment never invents metadata or loads arbitrary embeds',()=>{const {run}=setup();const html=run("attachmentHtml(parsePreviewLink('https://youtu.be/123'))");assert.match(html,/Metadata pending/);assert.doesNotMatch(html,/<iframe|<script|<img/);assert.match(html,/noopener noreferrer/)});
test('profile validates links and escapes saved profile fields',()=>{const {run,get}=setup();run('showProfile()');get('#profile-name').value='<b>Test</b>';get('#profile-bio').value='<img src=x>';get('#profile-socials').value='javascript:alert(1)';run("savePreviewForm('profile-form')");assert.equal(run('preview.profile.name'),'Lauren');assert.match(get('#profile-error').textContent,/valid/);get('#profile-socials').value='https://instagram.com/example';run("savePreviewForm('profile-form')");assert.match(get('#main').innerHTML,/&lt;b&gt;Test/);assert.match(get('#main').innerHTML,/instagram.com/);assert.doesNotMatch(get('#main').innerHTML,/<img src=x>/)});
test('reunion detail edits appear in Dashboard and Calendar',()=>{const {run,get}=setup();run('showDetails()');get('#reunion-date').value='2027-07-10';get('#reunion-location').value='<Park>';get('#reunion-schedule').value='Noon · Picnic\n6 pm · Dinner';run("savePreviewForm('details-form')");assert.match(get('#main').innerHTML,/2027-07-10/);assert.match(get('#main').innerHTML,/&lt;Park&gt;/);run("reunionTab='weekend';render()");assert.match(get('#main').innerHTML,/Noon · Picnic/);assert.match(get('#main').innerHTML,/6 pm · Dinner/)});
test('RSVP, shirts and contribution flow saves only demo state with back controls',()=>{const {run,get,events}=setup();run('showRsvp()');get('#rsvp-count').value='4';get('#rsvp-status').value='Planning to come';run("savePreviewForm('rsvp-form')");assert.equal(run('preview.rsvp.count'),'4');assert.match(get('#sheet-body').innerHTML,/Next: family shirts/);get('#shirt-size').value='XL';get('#shirt-quantity').value='3';const target={closest:s=>s==='[data-save-shirt]'?{dataset:{saveShirt:'Forest green'}}:null};for(const fn of events.click)fn({target});assert.equal(run('preview.shirt.quantity'),3);assert.match(get('#sheet-body').innerHTML,/Next: contribution/);assert.match(get('#sheet-body').innerHTML,/Back: RSVP/);run('showShirtTotals()');assert.match(get('#sheet-body').innerHTML,/5 shirts/);run("doPreviewAction('review-order')");assert.match(get('#sheet-body').innerHTML,/No order was placed/);run("act('sent-preview');doPreviewAction('demo-approve')");assert.match(get('#sheet-body').innerHTML,/no funds verified/)});
test('contact card is opt-in, private, session-only and resettable',()=>{const {run,get}=setup();run('showContact()');assert.match(get('#sheet-body').innerHTML,/Private by default/);get('#contact-name').value='Sample';get('#contact-email').value='sample@example.com';get('#contact-phone').value='';get('#contact-optin').checked=true;run("savePreviewForm('contact-form')");assert.equal(run('preview.contact.optIn'),true);run('resetPreview()');assert.equal(run('preview.contact'),null)});
test('reset clears all session edits and keeps source sample feed',()=>{const {run,get}=setup();run("preview.profile.name='Test';preview.posts.push({id:'test',name:'Test',text:'Hello'});toggleReaction('poll','❤️');addComment('poll','Hello');preview.details.location='Park';rsvp='4';shirtChoice='M';vote='2';showComposer()");get('#post-text').value='Unsaved text';run('resetPreview()');assert.equal(run('preview.posts.length'),0);assert.equal(run('Object.keys(preview.comments).length'),0);assert.equal(run('preview.profile.name'),'Lauren');assert.equal(run('preview.details.location'),'');assert.equal(run('composer.text'),'');assert.equal(run('rsvp'), '');assert.equal(run('shirtChoice'),'');assert.equal(run('vote'),'');assert.match(get('#main').innerHTML,/Family feed/)});
test('React entry imports the emoji corpus and labels its modal; comparison page remains accessible',()=>{const index=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');const app=fs.readFileSync(new URL('../src/react-app.jsx',import.meta.url),'utf8');const sheet=fs.readFileSync(new URL('../src/ui-core.jsx',import.meta.url),'utf8');const conversation=fs.readFileSync(new URL('../src/conversation.jsx',import.meta.url),'utf8');const alternate=fs.readFileSync(new URL('../dist/alternate.html',import.meta.url),'utf8');assert.match(index,/react-app.js/);assert.match(app,/from'.\/conversation.jsx'/);assert.match(conversation,/from '.\/emoji-data.js'/);assert.match(sheet,/aria-labelledby="sheet-title"/);assert.match(alternate,/react-app.js/);assert.match(alternate,/id="root"/);const comparison=fs.readFileSync(new URL('../dist/comparison.html',import.meta.url),'utf8');assert.match(comparison,/aria-labelledby="sheet-title"/)});
test('interaction source has no network writes and motion honors reduced motion',()=>{assert.doesNotMatch(source,/\bfetch\s*\(|XMLHttpRequest|sendBeacon|WebSocket/);const css=fs.readFileSync(new URL('../dist/style.css',import.meta.url),'utf8');assert.match(css,/prefers-reduced-motion:reduce/);assert.match(css,/animation:none!important/)});

test('composer accepts a local photo or poll without requiring a caption',()=>{const {run,get}=setup();run("composer.photos=[{src:'data:image/png;base64,fixture',name:'Family photo'}]");get('#post-text').value='';assert.equal(run('publishPreviewPost()'),true);assert.match(get('#main').innerHTML,/Family photo/);run("composer.poll={question:'Lunch?',options:['Picnic','Cookout']}");get('#post-text').value='';get('#poll-question').value='Lunch?';get('#poll-options').value='Picnic\nCookout';assert.equal(run('publishPreviewPost()'),true);assert.match(get('#main').innerHTML,/data-local-poll/)});
