import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {socialDrafts,socialHandle,socialUrlFromHandle,serializeSocialDrafts} from '../src/profile-social-model.js';
import {appleSongLookup,catalogSearchUrl,catalogSong,normalizeThemeSongLink,resolveThemeSongLink,searchThemeSongs,lookupThemeSong} from '../src/music-catalog.js';
const song={kind:'song',trackId:456,trackName:'A song',artistName:'An artist',collectionName:'An album',trackViewUrl:'https://music.apple.com/us/album/a-song/123?i=456&uo=4',artworkUrl100:'https://is1-ssl.mzstatic.com/image/thumb/test/100x100bb.jpg'};

test('social usernames construct each supported service URL',()=>{
 for(const [name,handle,url] of [['Instagram','@your.name','https://instagram.com/your.name'],['Facebook','your.name','https://facebook.com/your.name'],['YouTube','@my-channel','https://youtube.com/@my-channel'],['TikTok','@my_name','https://tiktok.com/@my_name'],['Bluesky','yourname','https://bsky.app/profile/yourname.bsky.social'],['Bluesky','you.example.com','https://bsky.app/profile/you.example.com'],['LinkedIn','your-name','https://linkedin.com/in/your-name']])assert.equal(socialUrlFromHandle(name,handle),url);
});
test('social handles reject unsafe, cross-service, path and overlong inputs',()=>{
 for(const value of ['javascript:alert(1)','https://instagram.com.evil.test/you','https://facebook.com/you','user/name','user?foo','user#x','user\\name','two names','a'.repeat(31)])assert.equal(socialUrlFromHandle('Instagram',value),null,value);
 assert.equal(socialUrlFromHandle('Bluesky','-bad.bsky.social'),null);assert.equal(socialUrlFromHandle('Unknown','you'),null);
});
test('pasted canonical social profile links become handles',()=>{assert.equal(socialHandle('YouTube','https://www.youtube.com/@my-channel/'),'my-channel');assert.equal(socialHandle('LinkedIn','https://linkedin.com/in/name'),'name');assert.equal(socialUrlFromHandle('Instagram','https://www.instagram.com/you/'),'https://instagram.com/you');assert.equal(socialHandle('Instagram','https://instagram.com/you?bad=1'),null)});
test('existing saved social URLs round-trip without mutation including legacy shapes',()=>{
 const original={Instagram:'https://www.instagram.com/example/',Facebook:'https://facebook.com/profile.php?id=100001',YouTube:'https://youtube.com/channel/UC-test',LinkedIn:'https://linkedin.com/in/example?trk=profile',Bluesky:'https://bsky.app/profile/example.bsky.social'};
 const entries=socialDrafts(original);assert.equal(entries.Facebook.legacy,true);assert.equal(entries.YouTube.legacy,true);assert.deepEqual(serializeSocialDrafts(entries),{socials:original,errors:{}});
});
test('only added services render and empty additions are not persisted',()=>{
 assert.deepEqual(socialDrafts({}),{});assert.deepEqual(serializeSocialDrafts({Instagram:{handle:'',original:'',initialHandle:''}}),{socials:{},errors:{}});
 const entries=socialDrafts({Instagram:'https://instagram.com/old'});entries.Instagram.handle='new';assert.deepEqual(serializeSocialDrafts(entries).socials,{Instagram:'https://instagram.com/new'});delete entries.Instagram;assert.deepEqual(serializeSocialDrafts(entries).socials,{});
});
test('invalid edits do not fall back silently to saved URLs',()=>{const entries=socialDrafts({Instagram:'https://instagram.com/old'});entries.Instagram.handle='https://evil.test/name';const {socials,errors}=serializeSocialDrafts(entries);assert.deepEqual(socials,{});assert.match(errors.Instagram,/username/)});
test('Spotify international links normalize to existing accepted shape',()=>{const path='track/0Lr4kGOYn9l83EjuK6cZFQ';assert.equal(normalizeThemeSongLink(' https://open.spotify.com/intl-de/'+path+'?si=example '),'https://open.spotify.com/'+path)});
test('music links enforce exact HTTPS service hosts and song-only URLs',()=>{for(const bad of ['javascript:alert(1)','http://open.spotify.com/track/0Lr4kGOYn9l83EjuK6cZFQ','https://open.spotify.com.evil.test/track/0Lr4kGOYn9l83EjuK6cZFQ','https://user:password@open.spotify.com/track/0Lr4kGOYn9l83EjuK6cZFQ','https://open.spotify.com/playlist/0Lr4kGOYn9l83EjuK6cZFQ','https://music.apple.com/us/album/name/123'])assert.equal(normalizeThemeSongLink(bad),null,bad)});
test('Apple album track links keep only their required track identifier',()=>{assert.equal(normalizeThemeSongLink(song.trackViewUrl),'https://music.apple.com/us/album/a-song/123?i=456');assert.equal(normalizeThemeSongLink(song.trackViewUrl.replace('music.apple','itunes.apple')),'https://music.apple.com/us/album/a-song/123?i=456')});
test('Apple direct song share links use a real ID lookup',async()=>{assert.deepEqual(appleSongLookup('https://music.apple.com/us/song/a-song/456'),{country:'us',id:'456'});let requested='';const result=await resolveThemeSongLink('https://music.apple.com/us/song/a-song/456',{fetchImpl:async url=>{requested=url;return {ok:true,json:async()=>({results:[song]})}}});assert.match(requested,/lookup\?id=456/);assert.equal(result.url,'https://music.apple.com/us/album/a-song/123?i=456')});
test('catalog results are genuine Apple songs with allowlisted artwork',()=>{const result=catalogSong(song);assert.equal(result.title,'A song');assert.match(result.artwork,/mzstatic.com/);assert.equal(catalogSong({...song,kind:'music-video'}),null);assert.equal(catalogSong({...song,trackViewUrl:'https://evil.test/a'}),null);assert.equal(catalogSong({...song,artworkUrl100:'https://mzstatic.com.evil.test/a'}).artwork,'')});
test('catalog search uses a bounded encoded public request',()=>{const url=new URL(catalogSearchUrl('A & B + C'));assert.equal(url.hostname,'itunes.apple.com');assert.equal(url.searchParams.get('term'),'A & B + C');assert.equal(url.searchParams.get('entity'),'song');assert.equal(url.searchParams.get('limit'),'8');assert.equal(url.searchParams.get('country'),'US')});
test('catalog search returns normalized results and omits credentials',async()=>{let options;const songs=await searchThemeSongs('unique test song one',{fetchImpl:async(url,init)=>{options=init;return {ok:true,json:async()=>({results:[song,song]})}}});assert.equal(songs.length,1);assert.equal(options.credentials,'omit');assert.equal(options.referrerPolicy,'no-referrer');assert.equal(songs[0].url,'https://music.apple.com/us/album/a-song/123?i=456')});
test('repeat catalog searches use the bounded session cache',async()=>{let calls=0;const fetchImpl=async()=>{calls++;return {ok:true,json:async()=>({results:[song]})}};await searchThemeSongs('unique cache query',{fetchImpl});await searchThemeSongs('unique cache query',{fetchImpl});assert.equal(calls,1)});
test('catalog failures offer a paste-link recovery path',async()=>{await assert.rejects(searchThemeSongs('unique failure query',{fetchImpl:async()=>({ok:false})}),/paste a song link/);await assert.rejects(searchThemeSongs('unique malformed query',{fetchImpl:async()=>({ok:true,json:async()=>({})})}),/paste a song link/)});
test('aborted catalog requests stay aborted without a misleading error',async()=>{const controller=new AbortController();controller.abort();await assert.rejects(searchThemeSongs('unique aborted query',{signal:controller.signal,fetchImpl:async()=>{throw Error('Should not fetch')}}),{name:'AbortError'});assert.deepEqual(await searchThemeSongs('a'),[])});
test('profile editor removes the expanded URL grid and integrates progressive pickers',async()=>{const source=await readFile(new URL('../src/profiles.jsx',import.meta.url),'utf8');assert.ok(source.includes('<SocialLinksEditor'));assert.ok(source.includes('<ThemeSongEditor'));assert.ok(source.includes('<MemberPicker label="Family who can see your contact card"'));assert.equal(source.includes('socialServices.map'),false)});

test('saved Apple song resolves title and artwork when the editor reopens',async()=>{const stored='https://music.apple.com/us/album/reopened/900?i=901';const result=await lookupThemeSong(stored,{fetchImpl:async()=>({ok:true,json:async()=>({results:[{...song,trackId:901,trackViewUrl:stored}]})})});assert.equal(result.title,'A song');assert.ok(result.artwork);assert.equal(await lookupThemeSong('https://open.spotify.com/track/0Lr4kGOYn9l83EjuK6cZFQ'),null)});
