import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {initialState,PREVIEW_KEY} from '../src/data-adapter.js';
const url='http://127.0.0.1:4173',browser=await chromium.launch({headless:true,executablePath:process.env.PW_CHROME||undefined}),results=[],errors=[],writes=[];
await mkdir('docs/recovery-qa',{recursive:true});
async function pageFor(width=390,theme='dark',platform='ios',state=initialState()){
 const page=await browser.newPage({viewport:{width,height:844},reducedMotion:'reduce'});page.setDefaultTimeout(7000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!['GET','HEAD'].includes(r.method()))writes.push(r.url())});
 await page.goto(url);await page.evaluate(({state,theme,platform,key})=>{localStorage.setItem(key,JSON.stringify({schema:2,mode:'preview',state:{...state,onboarding:'done'}}));localStorage.setItem('gw-theme',theme);localStorage.setItem('gw-platform',platform);localStorage.setItem('gw-install-dismissed','true');localStorage.setItem('gw-preview-notice:v1','seen')},{state,theme,platform,key:PREVIEW_KEY});await page.reload();return page;
}
async function noOverflow(page,label){assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),label+' overflow')}
async function close(page){await page.getByRole('button',{name:'Close dialog',exact:true}).click()}
try{
 const returning=await pageFor();let releaseConfig;const configGate=new Promise(resolve=>{releaseConfig=resolve});
 await returning.route('**/api/config',async route=>{await configGate;await route.fulfill({contentType:'application/json',body:JSON.stringify({configured:true,email:true,providers:[],origin:url})})});
 await returning.route('**/api/session',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({signedIn:false,configured:true})}));
 await returning.reload();await returning.getByRole('status').filter({hasText:'Getting things ready'}).waitFor();assert.equal(await returning.getByRole('navigation',{name:'Main navigation'}).count(),0);assert.equal(await returning.getByRole('heading',{name:'Family feed',exact:true}).count(),0);releaseConfig();await returning.getByRole('button',{name:'Email me a code',exact:true}).waitFor();results.push('returning preview state never flashes while live session loads');await returning.close();
 for(const width of [390,768,1280])for(const theme of ['light','dark'])for(const platform of ['ios','android']){
  const page=await pageFor(width,theme,platform);await noOverflow(page,'home');assert.equal(await page.locator('.bottom').count(),1);
  if(platform==='android')assert.equal(await page.locator('.liquid-glass,.liquid-glass-effect,svg.liquid-glass-svg').count(),0);
  const nav=page.getByRole('navigation',{name:'Main navigation'});const bounds=await nav.getByRole('button',{name:'Home',exact:true}).evaluate(b=>{const i=b.querySelector('svg').getBoundingClientRect(),l=b.querySelector('span').getBoundingClientRect();return {icon:i.bottom,label:l.top}});assert.ok(bounds.icon<=bounds.label+2,'nav icon above label');
  if(width!==768)await page.screenshot({path:`docs/recovery-qa/home-${width}-${theme}-${platform}.png`,fullPage:true});
  await page.getByRole('button',{name:'Post an update',exact:true}).click();assert.equal(await page.locator('dialog button.liquid-glass').count(),0,'no glass controls layered inside a sheet');const solid=await page.getByRole('button',{name:'Close dialog',exact:true}).evaluate(e=>getComputedStyle(e).backgroundColor);assert.ok(!solid.startsWith('rgba('),'sheet controls are opaque');await close(page);
  await nav.getByRole('button',{name:'Reunion',exact:true}).click();assert.equal(await page.getByRole('button',{name:'See reunion plans in progress'}).evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)','eyebrow has no background');
  await nav.getByRole('button',{name:'You',exact:true}).click();assert.equal(await page.locator('.you-rows').getByRole('button',{name:/Your household/}).count(),1);assert.equal(await page.locator('.profile-overview .profile-counts').count(),1);assert.ok(await page.locator('.profile-cover').evaluate(e=>e.getBoundingClientRect().width>=e.parentElement.clientWidth-2),'profile cover fills its card');await noOverflow(page,'profile overview');
  assert.ok(await page.locator('.profile-overview-head>.avatar').evaluate(e=>e.getBoundingClientRect().width)>=88,'profile avatar has visual weight');
  await page.getByRole('button',{name:'Edit profile',exact:true}).click();
  const swatches=await page.locator('.profile-color-options').evaluate(e=>({wrap:getComputedStyle(e).flexWrap,ys:[...e.children].map(c=>c.getBoundingClientRect().top)}));assert.equal(swatches.wrap,'nowrap');assert.ok(Math.max(...swatches.ys)-Math.min(...swatches.ys)<8,'color controls stay on one row');
  const iconAlignment=await page.getByRole('button',{name:/Add photo|Change photo/}).evaluate(e=>{const r=e.querySelector('svg').getBoundingClientRect(),b=e.getBoundingClientRect();return Math.abs((r.top+r.bottom-b.top-b.bottom)/2)});assert.ok(iconAlignment<3,'photo button glyph centered');await close(page);
  await nav.getByRole('button',{name:'Family',exact:true}).click();await page.getByRole('tab',{name:'Memories',exact:true}).click();assert.equal(await page.locator('.memory-hero-art').count(),0,'memory intro leaves photos to gallery');
  const memoryGaps=await page.locator('.memories-page>.section-head').evaluate(e=>{const h=e.querySelector('h2').getBoundingClientRect(),a=e.querySelector('.memory-actions').getBoundingClientRect(),g=e.nextElementSibling.getBoundingClientRect();return {headingGap:a.top-h.bottom,galleryGap:g.top-e.getBoundingClientRect().bottom,height:e.getBoundingClientRect().height}});assert.ok(memoryGaps.headingGap<25&&memoryGaps.galleryGap<35&&memoryGaps.height<190,'memory controls use compact natural spacing');await noOverflow(page,'memories');

  await nav.getByRole('button',{name:'Family',exact:true}).click();await noOverflow(page,'family');await page.getByRole('tab',{name:'People',exact:true}).click();assert.ok(await page.getByRole('heading',{name:'Address book',exact:true}).isVisible());await page.getByRole('tab',{name:'Family tree'}).click();await page.getByRole('button',{name:/Annie White/}).click();await page.getByRole('heading',{name:'Annie White (née Green)',exact:true}).waitFor();assert.equal(await page.locator('dialog').getByRole('button',{name:'Edit profile'}).count(),0);await page.keyboard.press('Escape');assert.equal(await page.locator('dialog').count(),0);
  await nav.getByRole('button',{name:'You',exact:true}).click();await noOverflow(page,'you');assert.ok(await page.getByRole('heading',{name:'Leader Tools',exact:true}).isVisible());
  await page.getByRole('button',{name:'Profile and appearance'}).click();await page.getByRole('button',{name:'Momo',exact:true}).click();assert.equal(await page.locator('html').getAttribute('data-font'),'sans');await page.getByRole('button',{name:'Serif',exact:true}).click();await page.keyboard.press('Escape');
  for(let n=0;n<2;n++){await page.getByRole('button',{name:'Post an update',exact:true}).first().click();await page.getByRole('textbox',{name:"What's on your mind"}).waitFor();await page.keyboard.press('Escape');assert.equal(await page.locator('dialog').count(),0)}
  results.push({width,theme,platform,checks:'home/family/tree/you, material DOM, nav geometry, font switch, repeated modal/Escape',passed:true});await page.close();
 }
 // Real interaction flow in the modified UI.
 const page=await pageFor();const nav=page.getByRole('navigation',{name:'Main navigation'});
 await page.getByRole('button',{name:'Post an update',exact:true}).click();await page.getByRole('textbox',{name:"What's on your mind"}).fill('Recoverable caption');
 const png={name:'sample.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aHMkAAAAASUVORK5CYII=','base64')};
 await page.locator('dialog input[type=file]').first().setInputFiles(png);await page.getByText('sample.png',{exact:true}).waitFor();await close(page);await page.reload();
 await page.getByRole('button',{name:'Post an update',exact:true}).click();assert.equal(await page.getByRole('textbox',{name:"What's on your mind"}).inputValue(),'Recoverable caption');await page.getByText('sample.png',{exact:true}).waitFor();await page.getByRole('button',{name:'Send post',exact:true}).click();await page.getByText('Recoverable caption',{exact:true}).waitFor();
 assert.equal(await page.locator('#post-1 img').count(),1,'one attachment is not duplicated');await page.reload();await page.locator('#post-1 img').waitFor();assert.ok((await page.locator('#post-1 img').getAttribute('src')).startsWith('data:'));
 await page.locator('#post-1').getByRole('button',{name:/Comments/}).click();await page.getByRole('textbox',{name:'Write a comment…'}).fill('Comment draft');await page.locator('dialog input[type=file]').setInputFiles(png);await page.getByText('sample.png',{exact:true}).waitFor();await close(page);await page.reload();await page.locator('#post-1').getByRole('button',{name:/Comments/}).click();assert.equal(await page.getByRole('textbox',{name:'Write a comment…'}).inputValue(),'Comment draft');await page.getByText('sample.png',{exact:true}).waitFor();await page.getByRole('button',{name:'Send',exact:true}).click();await page.getByRole('heading',{name:'1 Comment',exact:true}).waitFor();await page.getByRole('button',{name:'Reply',exact:true}).click();await page.getByRole('textbox',{name:'Write a reply…'}).fill('Reply saved');assert.ok(await page.locator('.reply-connectors path').count()>0);await page.getByRole('textbox',{name:'Write a reply…'}).press('Enter');await page.getByRole('heading',{name:'2 Comments',exact:true}).waitFor();await page.screenshot({path:'docs/recovery-qa/comments-390-dark-ios.png'});await close(page);
 await nav.getByRole('button',{name:'You',exact:true}).click();await page.getByRole('button',{name:'Edit profile',exact:true}).click();await page.getByLabel('Custom profile color').fill('#ca247c');await page.locator('summary').filter({hasText:'Social links and theme song'}).click();await page.getByLabel('Theme song').fill('https://open.spotify.com/track/0Lr4kGOYn9l83EjuK6cZFQ');await page.getByRole('button',{name:'Save profile',exact:true}).click();await page.getByRole('tab',{name:'Media',exact:true}).click();assert.ok(await page.getByText('Recoverable caption',{exact:true}).isVisible());assert.equal(await page.locator('iframe').count(),0,'theme song does not load automatically');await page.screenshot({path:'docs/recovery-qa/profile-390-dark-ios.png'});await close(page);
 await page.getByRole('button',{name:/Your household/}).click();await page.getByRole('button',{name:'Add a child',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Fictional Child');await page.getByLabel('Birthday',{exact:true}).fill('2020-01-01');await page.getByLabel('Gender').selectOption('Prefer not to say');await page.getByRole('button',{name:'Add child'}).click();await page.getByRole('button',{name:/Fictional Child/}).click();await page.getByLabel('Name',{exact:true}).fill('Fictional Child Updated');await page.getByRole('button',{name:'Save details',exact:true}).click();await page.getByText('Fictional Child Updated',{exact:true}).waitFor();await close(page);
 await nav.getByRole('button',{name:'Family',exact:true}).click();await page.getByRole('button',{name:/Set up my contact card/}).click();await page.getByText('More information',{exact:true}).click();await page.getByLabel('Address',{exact:true}).fill('Preview address');await page.getByLabel('Who can see your details?').selectOption('Selected family members');await page.getByLabel('Aaron Rivers',{exact:true}).check();await page.getByRole('button',{name:'Save contact card',exact:true}).click();
 await nav.getByRole('button',{name:'You',exact:true}).click();await page.getByText('App settings',{exact:true}).click();await page.getByRole('button',{name:'Reset preview',exact:true}).click();await page.getByRole('button',{name:'Reset local preview',exact:true}).click();await page.getByRole('button',{name:'Set up your profile',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Monique Rivers');await page.getByLabel('Email',{exact:true}).fill('fictional@example.test');await page.getByLabel('Birthday',{exact:true}).fill('2000-01-01');await page.getByRole('dialog').getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('heading',{name:'Make it yours.',exact:true}).waitFor();await page.getByLabel('Custom profile color').fill('#936b91');await page.locator('dialog input[type=file]').setInputFiles(png);await page.getByRole('button',{name:'Create profile'}).click();await page.getByRole('heading',{name:'Your household',exact:true}).waitFor();const registered=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).state,PREVIEW_KEY);assert.notEqual(registered.selfId,'monique');assert.equal(registered.members.find(m=>m.id===registered.selfId).profileColor,'#936b91');assert.ok(registered.members.find(m=>m.id===registered.selfId).photo.startsWith('data:'));assert.equal(registered.members.find(m=>m.id==='monique').registered,false);results.push({flow:'attachments/drafts/reload/comments/replies/profile/media/household/contact/reset/signup',passed:true});await page.close();
 const welcome=await browser.newPage({viewport:{width:390,height:844}});await welcome.goto(url);await welcome.getByRole('button',{name:'Continue',exact:true}).click();await welcome.getByRole('button',{name:'Continue using preview',exact:true}).waitFor();await welcome.getByRole('button',{name:'Continue using preview',exact:true}).click();await welcome.getByRole('navigation',{name:'Main navigation'}).waitFor();assert.equal(await welcome.locator('.preview-notice').count(),0);await welcome.reload();assert.equal(await welcome.getByRole('button',{name:'Continue using preview',exact:true}).count(),0);await welcome.close();results.push({flow:'one-time preview onboarding and clean chrome',passed:true});
 // Field gallery geometry edge cases; source geometry remains unedited.
 for(const width of [390,1280])for(const count of [0,1,2,5]){
  const state=initialState();state.memories=Array.from({length:count},(_,i)=>({...state.memories[i%2],id:'gallery-'+i,title:'Preview '+i}));const p=await pageFor(width,'dark','android',state);await p.getByRole('navigation').getByRole('button',{name:'Family',exact:true}).click();await p.getByRole('tab',{name:'Memories',exact:true}).click();
  for(const view of ['Grid','Natural','Strip','Carousel']){await p.getByRole('button',{name:view+' view',exact:true}).click();await noOverflow(p,`${view}/${count}/${width}`);assert.equal(await p.locator('.field-memory-open').count(),count);if(count>1&&['Strip','Carousel'].includes(view)){await p.locator('.field-memory-open').first().focus();await p.keyboard.press('End');assert.equal(await p.locator('.field-memory-open').last().evaluate(e=>document.activeElement===e),true);await p.keyboard.press('Home')}if(width===390&&count===5)await p.screenshot({path:`docs/recovery-qa/gallery-${view.toLowerCase()}-390.png`,fullPage:true});}
  results.push({width,galleryItems:count,views:5,passed:true});await p.close();
 }
 assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);await writeFile('docs/recovery-qa/results.json',JSON.stringify({results,errors,writes},null,2));console.log(JSON.stringify({passed:results.length,errors,writes}));
}catch(e){await writeFile('docs/recovery-qa/results.json',JSON.stringify({results,errors,writes,failure:e.message},null,2));console.error(e);process.exitCode=1}finally{await browser.close()}
