import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
function setup(){const elements=new Map(),events={};const get=s=>{if(!elements.has(s))elements.set(s,{innerHTML:'',textContent:'',value:'',open:false,dataset:{},style:{setProperty(){}},setAttribute(){},addEventListener(){},classList:{add(){},remove(){},toggle(){}},querySelector(){return true},showModal(){this.open=true},close(){this.open=false},showPopover(){this.open=true},hidePopover(){this.open=false},matches(){return this.open},focus(){}});return elements.get(s)};const context=vm.createContext({URL,Intl,Date,familyPhotos:{garden:'data:image/avif;base64,fixture',generations:'data:image/avif;base64,fixture'},document:{querySelector:get,documentElement:{dataset:{theme:'dark'},style:{setProperty(){}}},addEventListener(name,fn){(events[name]||=[]).push(fn)}},window:{scrollTo(){}},setTimeout(){return 1},clearTimeout(){}});for(const file of ['emoji-data.js','app.js','review.js'])vm.runInContext(fs.readFileSync(new URL('../dist/'+file,import.meta.url),'utf8'),context);return {run:s=>vm.runInContext(s,context),get,events}}
test('review boots with normal product copy and inline reaction control',()=>{const {run,get}=setup();assert.doesNotMatch(get('#main').innerHTML,/session.only|design preview/i);run("showReactions('photo')");assert.match(get('#main').innerHTML,/inline-reactions/);assert.equal(get('#sheet').open,false);run("toggleReaction('photo','❤️');render()");assert.match(get('#main').innerHTML,/reaction-summary/);assert.doesNotMatch(get('#main').innerHTML,/reaction-chips/)});
test('individual post includes content, bubbles and one-line composer',()=>{const {run,get}=setup();run("addComment('photo','Hi family');showComments('photo')");const h=get('#sheet-body').innerHTML;assert.match(h,/It starts with our people/);assert.match(h,/chat-bubble/);assert.match(h,/rows="1"/);assert.match(h,/data-emoji-target="comment-text"/);assert.match(h,/send-button/);assert.equal(get('#sheet').dataset.postId,'photo')});
test('posted comments clear the draft and keep exact reply text safe',()=>{const {run,get}=setup();run("showComments('photo')");get('#comment-text').value='<b>Hello</b>';run("savePreviewForm('comment-form')");assert.equal(run("preview.comments.photo[0].text"),'<b>Hello</b>');assert.equal(run("commentDrafts.photo"),'');assert.match(get('#sheet-body').innerHTML,/&lt;b&gt;Hello/)});
test('composer is focused with attachment actions and no formatting toolbar',()=>{const {run,get}=setup();run('showComposer()');assert.match(get('#sheet-body').innerHTML,/Upload media/);assert.match(get('#sheet-body').innerHTML,/Create poll/);assert.match(get('#sheet-body').innerHTML,/post-writing/);assert.doesNotMatch(get('#sheet-body').innerHTML,/Preview link|Post in preview|toolbar/)});
test('notifications use their own popover',()=>{const {run,get}=setup();run('notifications()');assert.equal(get('#notifications-popout').open,true);assert.equal(get('#sheet').open,false)});
test('contact card defaults to profile photo and has optional details',()=>{const {run,get}=setup();run("preview.profile.photo='data:image/png;base64,x';showContact()");assert.match(get('#sheet-body').innerHTML,/data:image\/png/);assert.match(get('#sheet-body').innerHTML,/Use profile photo/);assert.match(get('#sheet-body').innerHTML,/More information/);assert.match(get('#sheet-body').innerHTML,/contact-visibility/)});
test('My fees preserves pending versus confirmed distinction',()=>{const {run,get}=setup();run("act('sent-preview')");assert.equal(get('#sheet-title').textContent,'My fees');assert.match(get('#sheet-body').innerHTML,/Awaiting confirmation/);assert.doesNotMatch(get('#sheet-body').innerHTML,/>Confirmed</)});
test('relative time has exact accessible timestamp',()=>{const {run}=setup();assert.equal(run('friendlyTime(Date.now()-7*60000)'),'7 minutes ago');assert.match(run('timeMarkup(Date.now())'),/datetime=/);assert.match(run('timeMarkup(Date.now())'),/data-exact-time=/)});

test('close glyph has two equal centered diagonals and button dismisses repeatedly',()=>{const {run,get}=setup();assert.equal(run("paths.close"),'M6 6L18 18M6 18L18 6');for(let i=0;i<3;i++){run('showComposer()');assert.equal(get('#sheet').open,true);get('#close').onclick();assert.equal(get('#sheet').open,false)}});
test('mobile conversation explicitly removes dialog width cap; post uses centered sheet',()=>{const css=fs.readFileSync(new URL('../dist/review.css',import.meta.url),'utf8');const js=fs.readFileSync(new URL('../dist/review.js',import.meta.url),'utf8');assert.match(css,/#sheet\.focus-surface\{[^}]*max-width:none/);assert.match(css,/#sheet\.composer-surface\{[^}]*margin:auto/);assert.match(js,/showComposer=function[\s\S]*?classList.add\('composer-surface'\)/)});
test('comment avatars and names open profile cards in feed and conversation',()=>{const {run,get}=setup();run("preview.profile.photo='data:image/png;base64,x';addComment('photo','Hello');render();showComments('photo')");assert.match(get('#sheet-body').innerHTML,/data-member-card="self"/);assert.match(get('#sheet-body').innerHTML,/data:image\/png;base64,x/);assert.match(run("postActions('photo')"),/data-member-card="self"/);run("showMemberProfile('self')");assert.match(get('#sheet-body').innerHTML,/member-full-profile/);assert.match(get('#sheet-body').innerHTML,/Back to conversation/)});
test('tap surface suppression leaves keyboard focus styling',()=>{const css=fs.readFileSync(new URL('../dist/review.css',import.meta.url),'utf8');assert.match(css,/data-input-mode=pointer/);assert.match(css,/data-input-mode=keyboard/)});
