import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {defaultPanelLayout,createSharedPanel,addSharedPanel,changeSharedPanel,removeSharedPanel,restoreSharedPanel,moveSharedPanel,stepSharedPanel,validatePanelTransition,sharedPageMedia,PANEL_PAGES} from '../src/shared-panels.js';
import {sharedPageDefaults,validateSharedPageContent,sharedMarkdownSource} from '../src/shared-content-schema.js';
const clone=x=>JSON.parse(JSON.stringify(x));
function sample(){let layout=defaultPanelLayout('home');layout=changeSharedPanel(layout,'hero',{locked:false});layout=addSharedPanel(layout,createSharedPanel('panel-one','main','text'));layout=addSharedPanel(layout,createSharedPanel('panel-two','side','photo'));return layout;}
test('all shared pages start with a locked primary hero and footer never accepts panels',()=>{for(const page of PANEL_PAGES){const layout=sharedPageDefaults(page).panelLayout;assert.deepEqual(layout.desktopOrder,['hero']);assert.equal(layout.panels[0].locked,true)}assert.deepEqual(defaultPanelLayout('global').panels,[]);assert.throws(()=>validateSharedPageContent('global',{panelLayout:sample()}));});
test('schema accepts only typed premade content with complete independent permutations',()=>{const content=sharedPageDefaults('home');content.panelLayout=sample();assert.deepEqual(validateSharedPageContent('home',content),content);for(const mutation of [l=>l.panels[1].kind='member',l=>l.panels[1].layout='html',l=>l.panels[1].html='<script>',l=>l.panels[1].zone='private',l=>l.panels.push({...l.panels[1]}),l=>l.desktopOrder.pop(),l=>l.mobileOrder.push('unknown'),l=>l.panels.splice(0,1),l=>l.panels[1].memberId='alice']){const bad=clone(content);mutation(bad.panelLayout);assert.throws(()=>validateSharedPageContent('home',bad));}});
test('desktop drag designation does not change separately stored mobile order',()=>{const layout=sample(),moved=moveSharedPanel(layout,'panel-one',{zone:'side',beforeId:'panel-two'});assert.equal(moved.panels[1].zone,'side');assert.deepEqual(moved.mobileOrder,layout.mobileOrder);assert.deepEqual(moved.desktopOrder,['hero','panel-one','panel-two']);const mobile=moveSharedPanel(moved,'panel-two',{mobile:true,beforeId:'hero'});assert.deepEqual(mobile.mobileOrder,['panel-two','hero','panel-one']);assert.deepEqual(mobile.desktopOrder,moved.desktopOrder);assert.equal(mobile.panels[2].zone,'side');});
test('removal remains recoverable with both old positions and content intact',()=>{const layout=sample();layout.panels[1].body='Keep **all** of this';const removed=removeSharedPanel(layout,'panel-one');assert.equal(removed.panels[1].body,'Keep **all** of this');assert.equal(removed.panels[1].removed,true);assert.deepEqual(removed.mobileOrder,['hero','panel-two']);assert.deepEqual(restoreSharedPanel(removed,'panel-one',{desktop:1,mobile:1}),layout);});
test('locks block changes, removing, moving and crossing their position; Leaders can unlock explicitly',()=>{let layout=changeSharedPanel(sample(),'hero',{locked:true});assert.equal(moveSharedPanel(layout,'hero',{zone:'side'}),layout);assert.equal(removeSharedPanel(layout,'hero'),layout);assert.equal(changeSharedPanel(layout,'hero',{zone:'side'}),layout);assert.equal(stepSharedPanel(layout,'panel-one',-1),layout);assert.equal(moveSharedPanel(layout,'panel-two',{mobile:true,beforeId:'hero'}),layout);const before={...sharedPageDefaults('home'),panelLayout:layout},after=clone(before);after.hero={mode:'image',media:[{id:'x',alt:''}]};assert.throws(()=>validatePanelTransition('home',before,after),/Unlock/);after.panelLayout.panels[0].locked=false;assert.doesNotThrow(()=>validatePanelTransition('home',before,after));});
test('a locked panel may be locked after editing, but cannot disappear from a save',()=>{const before={...sharedPageDefaults('home'),panelLayout:sample()},after=clone(before);after.panelLayout.panels[1].body='Edited';after.panelLayout.panels[1].locked=true;assert.doesNotThrow(()=>validatePanelTransition('home',before,after));after.panelLayout.panels.splice(1,1);assert.throws(()=>validatePanelTransition('home',before,after),/recoverable/);});
test('untrusted media URL/type transport is never accepted in content',()=>{const content={...sharedPageDefaults('home'),panelLayout:sample()};content.panelLayout.panels[2].media=[{id:'upload',alt:'Family photo',url:'https://outside.test/photo'}];assert.throws(()=>validateSharedPageContent('home',content),/Unsupported/);content.panelLayout.panels[2].media=[{id:'../private',alt:''}];assert.throws(()=>validateSharedPageContent('home',content));});
test('removed media is retained for recovery but grants no active shared visibility',()=>{const content={...sharedPageDefaults('home'),panelLayout:sample()};content.panelLayout.panels[2].media=[{id:'archive',alt:''}];content.panelLayout=removeSharedPanel(content.panelLayout,'panel-two');assert.equal(sharedPageMedia(content).some(m=>m.id==='archive'),false);assert.equal(sharedPageMedia(content,{includeRemoved:true}).some(m=>m.id==='archive'),true);});
test('Markdown source preserves exact unsupported syntax and whitespace and refuses control characters',()=>{const source='  **hello**\r\n\n<table>literal HTML</table>\n:unsupported:  ';assert.equal(sharedMarkdownSource(source),source);const content=sharedPageDefaults('reunion');content.text.intro=source;content.bodyFormats={intro:'markdown'};assert.equal(validateSharedPageContent('reunion',content).text.intro,source);assert.throws(()=>sharedMarkdownSource('bad\u0000'));content.bodyFormats={heading:'markdown'};assert.throws(()=>validateSharedPageContent('reunion',content));});
test('only Add Panel and Reorder for mobile use modal sheets in the page editor',()=>{const panels=fs.readFileSync(new URL('../src/page-panels.jsx',import.meta.url),'utf8'),editor=fs.readFileSync(new URL('../src/page-content.jsx',import.meta.url),'utf8');assert.deepEqual([...panels.matchAll(/<Sheet title="([^"]+)"/g)].map(x=>x[1]),['Add Panel','Reorder for mobile']);assert.doesNotMatch(editor,/<Sheet/);assert.match(editor,/aria-label="Page history"/);assert.match(editor,/aria-label="Page media"/);assert.match(panels,/onPointerMove/);assert.match(panels,/onPointerCancel/);assert.match(panels,/Move .* earlier on mobile/);assert.match(panels,/aria-label=\{'Location for '/);});
test('shared panels do not register member, private, menu or system components',()=>{const source=fs.readFileSync(new URL('../src/shared-panels.js',import.meta.url),'utf8');assert.doesNotMatch(source,/eval\(|new Function\(|dangerouslySetInnerHTML|component:/);for(const page of ['profile','post','chat','leader-tools','planner','notification-settings'])assert.equal(PANEL_PAGES.includes(page),false);});
test('recovery draft model keeps desktop/mobile, locked state, Markdown and media descriptions in fingerprints',async()=>{const {pageContentFingerprint,mergePageDraft,reconcilePageRecord}=await import('../src/page-content-model.js');const base=sharedPageDefaults('home'),mine=clone(base),latest=clone(base);mine.panelLayout=sample();latest.text.heading='New heading';let merged=mergePageDraft(base,mine,latest);assert.equal(merged.content.text.heading,'New heading');assert.deepEqual(merged.content.panelLayout,mine.panelLayout);assert.equal(merged.conflicts.length,0);latest.panelLayout=addSharedPanel(latest.panelLayout,createSharedPanel('panel-remote','main','text'));merged=mergePageDraft(base,mine,latest);assert.equal(merged.conflicts[0].field,'panelLayout');const old={...base};delete old.panelLayout;delete old.bodyFormats;const next=reconcilePageRecord('home',{content:base,revision:1,canEdit:true},null,{draft:old,base:old,revision:1});assert.deepEqual(next.draft.panelLayout,base.panelLayout);assert.equal(pageContentFingerprint(next.draft),pageContentFingerprint(base));});
