import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {fakeClock} from './toast-fake-clock.mjs';
const same=(a,b)=>a?.length===b?.length&&a?.every((item,index)=>Object.is(item,b[index]));
class Target extends EventTarget{listeners=new Map();addEventListener(type,fn){if(!this.listeners.has(type))this.listeners.set(type,new Set());this.listeners.get(type).add(fn);super.addEventListener(type,fn);}removeEventListener(type,fn){this.listeners.get(type)?.delete(fn);super.removeEventListener(type,fn);}get count(){return [...this.listeners.values()].reduce((sum,set)=>sum+set.size,0);}}
async function harness(){
 const time=fakeClock(),slots=[],layouts=[],effects=[],documentRef=Object.assign(new Target(),{visibilityState:'visible'}),windowRef=new Target();let cursor=0,scopeKey='preview:synthetic-owner',routeKey='edit';
 const hooks={
  useState(initial){const i=cursor++;if(!(i in slots))slots[i]={value:typeof initial==='function'?initial():initial};return [slots[i].value,value=>{slots[i].value=typeof value==='function'?value(slots[i].value):value;}];},
  useRef(initial){const i=cursor++;if(!(i in slots))slots[i]={current:initial};return slots[i];},
  useCallback(fn,deps){const i=cursor++;if(!same(slots[i]?.deps,deps))slots[i]={fn,deps};return slots[i].fn;},
 };
 for(const [name,queue]of [['useEffect',effects],['useLayoutEffect',layouts]])hooks[name]=(fn,deps)=>{const i=cursor++,previous=slots[i];if(!same(previous?.deps,deps)){slots[i]={fn,deps,cleanup:previous?.cleanup,effect:true};queue.push(()=>{previous?.cleanup?.();slots[i].cleanup=fn();});}};
 const saved=globalThis.__gwToastHookHarness;globalThis.__gwToastHookHarness=hooks;
 const source=(await readFile(new URL('../src/use-toast.js',import.meta.url),'utf8')).replace("import {useCallback,useEffect,useLayoutEffect,useRef,useState} from 'react';","const {useCallback,useEffect,useLayoutEffect,useRef,useState}=globalThis.__gwToastHookHarness;").replace("'./toast-model.js'",JSON.stringify(new URL('../src/toast-model.js',import.meta.url).href));
 const module=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64')+'#'+crypto.randomUUID());
 return {time,documentRef,windowRef,render(next={}){scopeKey=next.scopeKey??scopeKey;routeKey=next.routeKey??routeKey;cursor=0;const result=module.useToast({scopeKey,routeKey,clock:time.clock,documentRef,windowRef});for(const fn of layouts.splice(0))fn();for(const fn of effects.splice(0))fn();return result;},replayStrictEffects(){for(const slot of slots)if(slot?.effect){slot.cleanup?.();slot.cleanup=slot.fn();}},close(){for(const slot of slots)slot?.cleanup?.();if(saved===undefined)delete globalThis.__gwToastHookHarness;else globalThis.__gwToastHookHarness=saved;}};
}
test('actual hook creates new instances for identical legacy strings and expires without render events',async()=>{const h=await harness();try{let ui=h.render();ui.setToast('Saved.');const first=h.render().toast.id;h.time.advance(4000);ui.setToast('Saved.');assert.ok(h.render().toast.id>first);h.time.advance(5000);assert.equal(h.render().toast,null);}finally{h.close();}});
test('actual hook clears account feedback before paint and rejects stale setters even after A -> B -> A',async()=>{const h=await harness();try{const first=h.render();first.setToast('Old private synthetic notice.');assert.ok(h.render().toast);const second=h.render({scopeKey:'live:other-owner'});assert.equal(second.toast,null);assert.equal(h.time.pending.size,0);assert.equal(first.setToast('Late old result.'),false);second.setToast('New result.');assert.equal(h.render().toast.message,'New result.');const returned=h.render({scopeKey:'preview:synthetic-owner'});assert.equal(returned.toast,null);assert.equal(first.setToast('Late result after returning to account.'),false);assert.equal(second.setToast('Late other result.'),false);assert.equal(returned.setToast('Fresh result.'),true);}finally{h.close();}});
test('actual hook route effects preserve confirmation while respecting original expiry',async()=>{const h=await harness();try{h.render().setToast('Contact card saved.');h.time.advance(2000);assert.ok(h.render({routeKey:'family'}).toast);h.time.advance(3000);assert.equal(h.render().toast,null);}finally{h.close();}});
test('visibility and page lifecycle listeners clear obsolete notices on resume',async()=>{const h=await harness();try{h.render().setToast('Saved.');h.documentRef.visibilityState='hidden';h.documentRef.dispatchEvent(new Event('visibilitychange'));assert.equal(h.time.pending.size,0);h.time.elapse(7000);h.documentRef.visibilityState='visible';h.windowRef.dispatchEvent(new Event('pageshow'));assert.equal(h.render().toast,null);h.render().setToast('Saved again.');h.windowRef.dispatchEvent(new Event('pagehide'));assert.equal(h.time.pending.size,0);h.time.elapse(6000);h.windowRef.dispatchEvent(new Event('pageshow'));assert.equal(h.render().toast,null);}finally{h.close();}});
test('focus reconciles wall-clock expiry after background timer throttling',async()=>{const h=await harness();try{h.render().setToast('Saved.');h.time.elapse(6000);h.windowRef.dispatchEvent(new Event('focus'));assert.equal(h.render().toast,null);}finally{h.close();}});
test('Strict Mode cleanup/setup attaches each listener once and remains usable',async()=>{const h=await harness();try{h.render();assert.equal(h.documentRef.count,1);assert.equal(h.windowRef.count,3);h.replayStrictEffects();assert.equal(h.documentRef.count,1);assert.equal(h.windowRef.count,3);assert.equal(h.render().setToast('Saved.'),true);assert.equal(h.time.pending.size,1);h.time.advance(5000);assert.equal(h.render().toast,null);}finally{h.close();}});
test('unmount removes every listener and timer and rejects a captured late setter',async()=>{const h=await harness();const ui=h.render();ui.setToast('Saved.');h.close();assert.equal(h.documentRef.count,0);assert.equal(h.windowRef.count,0);assert.equal(h.time.pending.size,0);assert.equal(ui.setToast('Late result.'),false);for(const callback of h.time.cancelled)callback();});
