import test from 'node:test';
import assert from 'node:assert/strict';
import {createToastController,normalizeToast,TOAST_DURATION_MS,TOAST_ERROR_DURATION_MS,TOAST_MAX_DURATION_MS,TOAST_MAX_RESIDENCE_MS} from '../src/toast-model.js';
import {fakeClock} from './toast-fake-clock.mjs';
function harness(){const time=fakeClock(),changes=[],controller=createToastController({scopeKey:'preview:synthetic-owner',clock:time.clock,onChange:value=>changes.push(value)});controller.activate();return {time,changes,controller,get toast(){return controller.snapshot().toast;}};}

test('legacy confirmation becomes a bounded status notice and empty values clear it',()=>{
 assert.deepEqual(normalizeToast('Contact card saved.'),{message:'Contact card saved.',kind:'status',duration:TOAST_DURATION_MS});
 for(const value of ['',null,undefined,{},17,{message:'   '}])assert.equal(normalizeToast(value),null);
 const h=harness();h.controller.show('Saved.');assert.ok(h.toast);h.controller.show('');assert.equal(h.toast,null);assert.equal(h.time.pending.size,0);
});
test('ordinary confirmation expires after five seconds with no animation event',()=>{const h=harness();h.controller.show('Saved.');h.time.advance(4999);assert.ok(h.toast);h.time.advance(1);assert.equal(h.toast,null);assert.equal(h.time.pending.size,0);});
test('repeated identical text creates a fresh instance, announcement and expiry',()=>{const h=harness();h.controller.show('Saved.');const first=h.toast.id;h.time.advance(4000);h.controller.show('Saved.');assert.ok(h.toast.id>first);h.time.advance(4000);assert.ok(h.toast);h.time.advance(1000);assert.equal(h.toast,null);assert.equal(h.changes.filter(x=>x.toast).length,2);});
test('replacing text cancels the original timer and rejects its already queued callback',()=>{const h=harness();h.controller.show('First.');h.time.advance(1000);h.controller.show('Second.');const old=h.time.cancelled[0];old();assert.equal(h.toast.message,'Second.');assert.equal(h.time.pending.size,1);h.time.advance(5000);assert.equal(h.toast,null);});
test('dismissal is instance-specific and cancels all scheduling',()=>{const h=harness();h.controller.show('First.');const old=h.toast.id;h.controller.show('Second.');assert.equal(h.controller.dismiss(old),false);assert.equal(h.controller.dismiss(h.toast.id),true);assert.equal(h.toast,null);assert.equal(h.time.pending.size,0);});
test('typing an error extends reading time while keeping an explicit dismissal path',()=>{const h=harness();h.controller.show({kind:'error',message:'That could not be sent. Your draft is still here.'});assert.equal(h.toast.kind,'error');h.time.advance(TOAST_ERROR_DURATION_MS-1);assert.ok(h.toast);h.time.advance(1);assert.equal(h.toast,null);});
test('duration cannot be zero, infinite, negative or longer than the transient limit',()=>{for(const value of [-1,0,1])assert.equal(normalizeToast({message:'Saved.',duration:value}).duration,TOAST_DURATION_MS);for(const value of [Infinity,NaN,'1'])assert.equal(normalizeToast({message:'Saved.',duration:value}).duration,TOAST_DURATION_MS);assert.equal(normalizeToast({message:'Saved.',duration:1e9}).duration,TOAST_MAX_DURATION_MS);});
test('persistent unsaved or conflict conditions are rejected, never turned into expiring notices',()=>{const h=harness();h.controller.show('Saved.');const id=h.toast.id;assert.equal(h.controller.show({persistent:true,kind:'error',message:'Unsaved changes.'}),false);assert.equal(h.toast.id,id);assert.equal(normalizeToast({persistent:true,message:'Conflict.'}),null);});
test('hover pause preserves remaining reading time rather than starting over',()=>{const h=harness();h.controller.show('Saved.');h.time.advance(2000);h.controller.pause('hover');h.time.advance(10000);assert.ok(h.toast);h.controller.resume('hover');h.time.advance(2999);assert.ok(h.toast);h.time.advance(1);assert.equal(h.toast,null);});
test('focus and hover pause reasons are independent',()=>{const h=harness();h.controller.show({kind:'error',message:'Please try again.'});h.time.advance(1000);h.controller.pause('hover');h.controller.pause('focus');h.controller.resume('hover');h.time.advance(10000);assert.ok(h.toast);h.controller.resume('focus');h.time.advance(11000);assert.equal(h.toast,null);});
test('paused feedback still has finite residence and cannot obstruct the app forever',()=>{const h=harness();h.controller.show('Saved.');h.controller.pause('hover');h.controller.pause('focus');h.time.advance(TOAST_MAX_RESIDENCE_MS-1);assert.ok(h.toast);h.time.advance(1);assert.equal(h.toast,null);assert.equal(h.time.pending.size,0);});
test('late pause events and old-node pointer events cannot affect a replacement',()=>{const h=harness();h.controller.show('First.');const id=h.toast.id;h.controller.show('Second.');assert.equal(h.controller.pause('focus',id),false);assert.equal(h.controller.resume('focus',id),false);h.time.advance(5000);assert.equal(h.toast,null);});
test('route navigation preserves the fresh save confirmation without extending its deadline',()=>{const h=harness();h.controller.setRoute('edit');h.controller.show('Contact card saved.');h.time.advance(2000);h.controller.setRoute('family');assert.ok(h.toast);h.time.advance(3000);assert.equal(h.toast,null);});
test('navigation reconciles elapsed wall time when a timer callback was throttled',()=>{const h=harness();h.controller.show('Saved.');h.time.elapse(6000);h.controller.setRoute('family');assert.equal(h.toast,null);assert.equal(h.time.pending.size,0);});
test('backgrounding clears timers; expired confirmation does not replay on resume',()=>{const h=harness();h.controller.show('Saved.');h.time.advance(1000);h.controller.setVisible(false);assert.equal(h.time.pending.size,0);h.time.elapse(10000);h.controller.setVisible(true);assert.equal(h.toast,null);assert.equal(h.time.pending.size,0);});
test('short background retains only the remaining wall-clock lifetime',()=>{const h=harness();h.controller.show('Saved.');h.time.advance(1000);h.controller.setVisible(false);h.time.elapse(1000);h.controller.setVisible(true);assert.ok(h.toast);h.time.advance(3000);assert.equal(h.toast,null);});
test('feedback created in a hidden app ages without timers or stale resume playback',()=>{const h=harness();h.controller.setVisible(false);h.controller.show('Saved.');assert.equal(h.time.pending.size,0);h.time.elapse(6000);h.controller.setVisible(true);assert.equal(h.toast,null);});
test('backgrounding releases interaction pauses instead of retaining them across app switches',()=>{const h=harness();h.controller.show('Saved.');h.time.advance(2000);h.controller.pause('focus');h.controller.setVisible(false);h.time.elapse(4000);h.controller.setVisible(true);assert.equal(h.toast,null);});
test('account replacement immediately clears old feedback and cancels its timer',()=>{const h=harness();h.controller.show('Private synthetic notice.');h.controller.setScope('live:other-synthetic-owner');assert.equal(h.toast,null);assert.equal(h.time.pending.size,0);assert.equal(h.controller.show('Old operation completed.','preview:synthetic-owner'),false);h.controller.show('New operation completed.','live:other-synthetic-owner');for(const callback of h.time.cancelled)callback();assert.equal(h.toast.message,'New operation completed.');});
test('unmount prevents captured setters and callbacks from publishing after teardown',()=>{const h=harness();h.controller.show('Saved.');const count=h.changes.length;h.controller.deactivate();assert.equal(h.time.pending.size,0);assert.equal(h.controller.show('Late result.'),false);for(const callback of h.time.cancelled)callback();assert.equal(h.changes.length,count);assert.equal(h.toast,null);});
test('Strict Mode cleanup and setup leaves a live, empty controller with one timer on reuse',()=>{const h=harness();h.controller.deactivate();h.controller.activate();h.controller.show('Saved.');assert.equal(h.time.pending.size,1);h.time.advance(5000);assert.equal(h.toast,null);});
test('functional legacy setters receive the current text and create a new notice',()=>{const h=harness();h.controller.show('Saved.');const first=h.toast.id;h.controller.show(previous=>previous);assert.equal(h.toast.message,'Saved.');assert.ok(h.toast.id>first);});
