import test from 'node:test';import assert from 'node:assert/strict';import {gzipSync} from 'node:zlib';import {coreAssetResponse} from '../src/core-assets.mjs';
const assets={'index.html':{gzip:gzipSync('exact markup').toString('base64'),type:'text/html; charset=utf-8'},'react-app.js':{gzip:gzipSync('exact script').toString('base64'),type:'application/javascript; charset=utf-8'}};
test('core response preserves exact bytes and ignores cache-buster queries',async()=>{const response=await coreAssetResponse(new Request('https://example.test/?v=test'),assets);assert.equal(await response.text(),'exact markup');assert.equal(response.headers.get('cache-control'),'no-store, max-age=0');assert.equal(response.headers.get('x-content-type-options'),'nosniff');assert.equal(response.headers.get('etag'),null);});
test('HEAD and unsupported methods never return an asset body',async()=>{const head=await coreAssetResponse(new Request('https://example.test/react-app.js',{method:'HEAD'}),assets);assert.equal(await head.text(),'');assert.equal(head.status,200);const post=await coreAssetResponse(new Request('https://example.test/react-app.js',{method:'POST'}),assets);assert.equal(post.status,405);assert.equal(post.headers.get('allow'),'GET, HEAD');});
test('API, health, other assets and absent embedded maps remain outside this handler',async()=>{for(const path of ['/api/config','/health','/tree-artwork.png'])assert.equal(await coreAssetResponse(new Request('https://example.test'+path),assets),null);assert.equal(await coreAssetResponse(new Request('https://example.test/')),null);});

test('service-worker script is source-owned, root-scoped, executable and never served from retained ASSETS',async()=>{
 const source='self.fixtureVersion = 2;',map={'sw.js':{gzip:gzipSync(source).toString('base64'),type:'application/javascript; charset=utf-8'}};
 for(const suffix of ['', '?v=fictional']){const response=await coreAssetResponse(new Request('https://example.test/sw.js'+suffix),map);assert.equal(response.status,200);assert.equal(await response.text(),source);assert.equal(response.headers.get('Content-Type'),'application/javascript; charset=utf-8');assert.equal(response.headers.get('Service-Worker-Allowed'),'/');assert.equal(response.headers.get('Cache-Control'),'no-store, max-age=0')}
 const response=await coreAssetResponse(new Request('https://example.test/sw.js',{method:'HEAD'}),map);assert.equal(await response.text(),'');assert.equal(response.headers.get('Service-Worker-Allowed'),'/');
 assert.equal((await coreAssetResponse(new Request('https://example.test/sw.js',{method:'POST'}),map)).status,405);
});
