import test from 'node:test';import assert from 'node:assert/strict';
import {database,seed} from './test-db.mjs';import {command,familyState,readPost,validDate} from '../src/family-service.mjs';import {createApp} from '../src/worker.mjs';import {createRateStorage,createAuth} from '../src/auth.mjs';
const member=(id,roles=[])=>({id,status:'active',group:'family',roles,canPost:true,isLeader:id==='owner'});
function setup(){const {sqlite,DB}=database();seed(sqlite);return {sqlite,DB,owner:member('owner',['admin','moderator','planner','treasurer']),alice:member('alice'),bob:member('bob')}}
const send=(DB,actor,type,data={})=>command(DB,actor,{type,requestId:crypto.randomUUID(),...data});
test('group post and comment reads cannot leak to another member or admin',async()=>{const {DB,sqlite,alice,bob,owner}=setup();const p=await send(DB,alice,'ADD_POST',{post:{text:'Private',groupId:'private-group'}});await send(DB,alice,'ADD_COMMENT',{targetId:p.id,text:'Private reply'});assert.equal(await readPost(DB,bob,p.id),null);assert.equal(await readPost(DB,owner,p.id),null);assert.equal((await familyState(DB,bob)).posts.length,0);assert.equal((await familyState(DB,alice)).comments[p.id].length,1);await assert.rejects(()=>send(DB,bob,'ADD_COMMENT',{targetId:p.id,text:'Probe'}),e=>e.status===404)});
test('receipt makes repeated post and shirt claim idempotent',async()=>{const {DB,alice,sqlite}=setup();const cmd={type:'ADD_POST',post:{text:'Only once'},requestId:crypto.randomUUID()};const first=await command(DB,alice,cmd),second=await command(DB,alice,cmd);assert.deepEqual(first,second);assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM posts').get().n,1);const claim={type:'CLAIM_ORDER',lines:[{productId:'forest',size:'M',quantity:2}],requestId:crypto.randomUUID()};await command(DB,alice,claim);await command(DB,alice,claim);assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM shirt_claims').get().n,1)});
test('full birthday and children stay out of other family member state',async()=>{const {DB,alice,bob}=setup();await send(DB,alice,'ADD_PERSON',{child:true,member:{name:'Fictional Child',birthday:'2020-04-05',gender:'Prefer not to say'}});const own=await familyState(DB,alice),other=await familyState(DB,bob);assert.equal(own.members.find(m=>m.id==='alice').birthday,'1991-02-03');assert.equal(other.members.find(m=>m.id==='alice').birthday,undefined);assert.equal(other.members.some(m=>m.origin==='dependent'),false);const child=own.members.find(m=>m.origin==='dependent');await assert.rejects(()=>send(DB,bob,'UPDATE_DEPENDENT',{member:{...child,name:'Wrong'}}),e=>e.status===404)});
test('profile ownership and fields cannot grant roles',async()=>{const {DB,alice,bob,sqlite}=setup();await assert.rejects(()=>send(DB,bob,'SAVE_MEMBER',{member:{id:'alice',name:'Changed'}}),e=>e.status===403);await send(DB,alice,'SAVE_MEMBER',{member:{id:'alice',name:'Alice New',roles:['admin'],moderator:true,birthday:'1991-02-03',socials:{}}});assert.equal(sqlite.prepare("SELECT roles_json FROM members WHERE id='alice'").get().roles_json,'[]')});
test('self-reported payment never becomes confirmation, admin alone is not treasurer',async()=>{const {DB,alice,owner,sqlite}=setup();const fee=await send(DB,alice,'SET_FEES',{value:'paid'});assert.equal((await familyState(DB,alice)).fees,'reported');await assert.rejects(()=>send(DB,alice,'CONFIRM_FEE',{id:fee.id,status:'confirmed'}),e=>e.status===403);await assert.rejects(()=>send(DB,member('owner',['admin']),'CONFIRM_FEE',{id:fee.id,status:'confirmed'}),e=>e.status===403);await send(DB,owner,'CONFIRM_FEE',{id:fee.id,status:'confirmed'});assert.equal((await familyState(DB,alice)).fees,'confirmed')});
test('poll choices are validated, totals and my selections survive refresh',async()=>{const {DB,alice,bob}=setup();const p=await send(DB,alice,'ADD_POST',{post:{text:'Poll',poll:{question:'Pick',mode:'single',options:['A','B']}}});await assert.rejects(()=>send(DB,bob,'POLL_VOTE',{postId:p.id,options:[0,1]}));await send(DB,bob,'POLL_VOTE',{postId:p.id,options:[1]});const a=await familyState(DB,alice),b=await familyState(DB,bob);assert.equal(a.posts[0].poll.votes[1],1);assert.deepEqual(b.pollSelections[p.id],[1]);assert.deepEqual(b.posts[0].poll.votes,{})});
test('atomic rate storage enforces limit and expires it',async()=>{const {DB,sqlite}=setup(),limit=createRateStorage(DB);assert.equal((await limit.consume('key',{window:60,max:1})).allowed,true);assert.equal((await limit.consume('key',{window:60,max:1})).allowed,false);sqlite.prepare("UPDATE app_rate_limits SET reset_at=0 WHERE key='key'").run();assert.equal((await limit.consume('key',{window:60,max:1})).allowed,true)});
test('dates reject rollover and future values',()=>{assert.equal(validDate('2026-02-30'),false);assert.equal(validDate('2099-01-01'),false);assert.equal(validDate('2000-02-29'),true)});
test('API contact visibility applies exact audience and origin writes are rejected',async()=>{const {DB,alice}=setup();const env={DB,BETTER_AUTH_SECRET:'test-secret-with-over-thirty-two-characters',AUTH_ORIGIN:'https://greenwhitefamily.com'},app=createApp(()=>({api:{getSession:async({headers})=>({user:{id:headers.get('x-test-user'),emailVerified:true}})}}));await send(DB,alice,'SAVE_CONTACT',{contact:{name:'Alice',phone:'555-0100',optIn:true,visibility:'Selected family members',selectedIds:['owner']}});const request=(id)=>app.request('https://greenwhitefamily.com/api/directory',{headers:{'x-test-user':id}},env);assert.equal((await(await request('bob')).json()).cards.length,0);assert.equal((await(await request('owner')).json()).cards[0].phone,'555-0100');assert.equal((await app.request('https://greenwhitefamily.com/api/commands',{method:'POST',headers:{'x-test-user':'alice',Origin:'https://evil.test','Content-Type':'application/json'},body:JSON.stringify({type:'RSVP',requestId:crypto.randomUUID(),value:{status:'Planning to come',count:1}})},env)).status,403)});
test('real Better Auth email code is hashed, signs in, and cannot be replayed',async()=>{const {DB}=database();let sent;const env={DB,BETTER_AUTH_SECRET:'test-only-long-secret-not-used-by-any-real-service',AUTH_ORIGIN:'https://greenwhitefamily.com',AUTH_EMAIL_ENABLED:'true',EMAIL:{async send(mail){sent=mail}}};const auth=createAuth(env);const headers={Origin:env.AUTH_ORIGIN,'Content-Type':'application/json','cf-connecting-ip':'192.0.2.1'};const request=(path,body)=>auth.handler(new Request(env.AUTH_ORIGIN+'/api/auth'+path,{method:'POST',headers,body:JSON.stringify(body)}));const sentResponse=await request('/email-otp/send-verification-otp',{email:'fictional@example.test',type:'sign-in'});assert.equal(sentResponse.status,200,await sentResponse.text());const code=sent.text.match(/\b\d{6}\b/)[0];const row=await DB.prepare('SELECT value FROM verification LIMIT 1').bind().first();assert.ok(!row.value.includes(code));const signed=await request('/sign-in/email-otp',{email:'fictional@example.test',otp:code,name:'Fictional Person'});assert.equal(signed.status,200,await signed.clone().text());assert.ok(signed.headers.get('set-cookie')?.includes('HttpOnly'));const repeated=await request('/sign-in/email-otp',{email:'fictional@example.test',otp:code,name:'Fictional Person'});assert.notEqual(repeated.status,200)});

test('live state starts with usable feed and directory filters',async()=>{const {DB,alice}=setup();await send(DB,alice,'ADD_POST',{post:{text:'Visible on first load'}});const state=await familyState(DB,alice);assert.equal(state.feedFilter,'all');assert.equal(state.peopleFilter,'all');assert.deepEqual(state.memoryFilters,{});assert.equal(state.posts[0].text,'Visible on first load')});

test('unverified sessions cannot read family records and group directory stays scoped',async()=>{const {DB}=setup();const env={DB,BETTER_AUTH_SECRET:'test-only-long-enough-secret-not-real',AUTH_ORIGIN:'https://greenwhitefamily.com'};const app=createApp(()=>({api:{getSession:async({headers})=>({user:{id:headers.get('x-test-user'),emailVerified:headers.get('x-test-verified')==='yes'}})}}));const get=(id,path,verified=true)=>app.request(env.AUTH_ORIGIN+path,{headers:{'x-test-user':id,'x-test-verified':verified?'yes':'no'}},env);assert.equal((await get('alice','/api/state',false)).status,403);assert.equal((await(await get('bob','/api/groups')).json()).groups.length,0);assert.equal((await(await get('owner','/api/groups')).json()).groups.length,0);assert.equal((await(await get('alice','/api/groups')).json()).groups.length,1)});
test('media stays private until attached to an authorized conversation',async()=>{const {DB,alice}=setup();const env={DB,BETTER_AUTH_SECRET:'test-only-long-enough-secret-not-real',AUTH_ORIGIN:'https://greenwhitefamily.com',R2:{get:async()=>({body:new Uint8Array([1,2,3])})}};await DB.prepare('INSERT INTO media(id,owner_id,object_key,name,mime_type,size_bytes) VALUES(?,?,?,?,?,?)').bind('private-file','alice','test-key','example.txt','text/plain',3).run();const app=createApp(()=>({api:{getSession:async({headers})=>({user:{id:headers.get('x-test-user'),emailVerified:true}})}}));const get=id=>app.request(env.AUTH_ORIGIN+'/api/media/private-file',{headers:{'x-test-user':id}},env);assert.equal((await get('alice')).status,200);assert.equal((await get('bob')).status,404);assert.equal((await get('owner')).status,404);await send(DB,alice,'ADD_POST',{post:{text:'Group only',groupId:'private-group',files:[{id:'private-file'}]}});assert.equal((await get('bob')).status,404);await send(DB,alice,'ADD_POST',{post:{text:'Family attachment',files:[{id:'private-file'}]}});const response=await get('bob');assert.equal(response.status,200);assert.equal(response.headers.get('Cache-Control'),'private, no-store');assert.ok(response.headers.get('Content-Disposition').startsWith('attachment'))});

test('birthday sharing is opt-in, adult-only, and never exposes year or household dates',async()=>{const {DB,sqlite,alice,bob}=setup();assert.deepEqual((await familyState(DB,bob)).birthdayCalendar,[]);await send(DB,alice,'SET_BIRTHDAY_CELEBRATION',{enabled:true});const state=await familyState(DB,bob);assert.deepEqual(state.birthdayCalendar,[{memberId:'alice',name:'Alice',monthDay:'02-03'}]);assert.equal(state.members.find(m=>m.id==='alice').birthday,undefined);await send(DB,alice,'SET_BIRTHDAY_CELEBRATION',{enabled:false});assert.deepEqual((await familyState(DB,bob)).birthdayCalendar,[]);sqlite.prepare("UPDATE profiles SET birthday='2020-02-03' WHERE member_id='alice'").run();await assert.rejects(()=>send(DB,alice,'SET_BIRTHDAY_CELEBRATION',{enabled:true}),/adult profiles/)});
test('birthday scheduler creates at most one consented post at 9am family time',async()=>{const {DB,sqlite,alice}=setup();const {celebrateBirthdays,familyDate}=await import('../src/birthdays.mjs');sqlite.prepare("UPDATE profiles SET birthday='1991-10-05' WHERE member_id='alice'").run();assert.equal((await celebrateBirthdays(DB,new Date('2026-10-05T13:00:00Z'))).created,0);await send(DB,alice,'SET_BIRTHDAY_CELEBRATION',{enabled:true});assert.equal((await celebrateBirthdays(DB,new Date('2026-10-05T12:00:00Z'))).created,0);assert.equal((await celebrateBirthdays(DB,new Date('2026-10-05T13:00:00Z'))).created,1);assert.equal((await celebrateBirthdays(DB,new Date('2026-10-05T13:30:00Z'))).created,0);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM posts').get().n,1);assert.equal(JSON.parse(sqlite.prepare('SELECT metadata_json FROM posts').get().metadata_json).systemBirthday,true);assert.deepEqual(familyDate(new Date('2026-12-05T14:00:00Z')),{date:'2026-12-05',hour:9})});

test('contact card photo honors the exact contact audience',async()=>{const {DB,alice}=setup();await DB.prepare('INSERT INTO media(id,owner_id,object_key,name,mime_type,size_bytes) VALUES(?,?,?,?,?,?)').bind('contact-file','alice','test-key','contact.png','image/png',3).run();await send(DB,alice,'SAVE_CONTACT',{contact:{name:'Alice',photo:'/api/media/contact-file',useProfile:false,optIn:true,visibility:'Selected family members',selectedIds:['owner']}});const env={DB,BETTER_AUTH_SECRET:'test-only-long-enough-secret-not-real',AUTH_ORIGIN:'https://greenwhitefamily.com',R2:{get:async()=>({body:new Uint8Array([1,2,3])})}},app=createApp(()=>({api:{getSession:async({headers})=>({user:{id:headers.get('x-test-user'),emailVerified:true}})}}));const get=id=>app.request(env.AUTH_ORIGIN+'/api/media/contact-file',{headers:{'x-test-user':id}},env);assert.equal((await get('owner')).status,200);assert.equal((await get('bob')).status,404);await send(DB,alice,'SAVE_CONTACT',{contact:{name:'Alice',photo:'/api/media/contact-file',useProfile:false,optIn:false,visibility:'Selected family members',selectedIds:['owner']}});assert.equal((await get('owner')).status,404)});

test('memory details are optional; only admins feature exact approved photos',async()=>{
 const {DB,sqlite,alice,bob,owner}=setup();
 for(const [id,type] of [['photo-one','image/jpeg'],['photo-two','image/png'],['video-one','video/mp4']])await DB.prepare('INSERT INTO media(id,owner_id,object_key,name,mime_type,size_bytes) VALUES(?,?,?,?,?,?)').bind(id,'alice',id,id,type,12).run();
 const m={id:'memory-one',image:'/api/media/photo-one',title:''};await send(DB,alice,'ADD_MEMORY',{memory:m});
 assert.equal((await familyState(DB,bob)).memories[0].title,'');assert.deepEqual((await familyState(DB,bob)).featuredMemoryIds,[]);
 await assert.rejects(()=>send(DB,alice,'FEATURE_MEMORY',{id:m.id,approved:true}),e=>e.status===403);
 await send(DB,owner,'FEATURE_MEMORY',{id:m.id,approved:true,primary:true});assert.equal((await familyState(DB,bob)).primaryMemoryId,m.id);
 await assert.rejects(()=>send(DB,alice,'SAVE_MEMORY',{memory:{...m,capturedDate:'2026-02-30'}}));await assert.rejects(()=>send(DB,alice,'SAVE_MEMORY',{memory:{...m,memberIds:['private-child']}}));
 await send(DB,alice,'SAVE_MEMORY',{memory:{...m,title:'Optional caption',capturedDate:'2001-02-03',dateStatus:'approximate',memberIds:['bob']}});assert.equal((await familyState(DB,bob)).featuredPhotos.length,1);
 await send(DB,alice,'SAVE_MEMORY',{memory:{...m,image:'/api/media/photo-two'}});assert.deepEqual((await familyState(DB,bob)).featuredMemoryIds,[]);assert.equal(JSON.parse(sqlite.prepare('SELECT metadata_json FROM posts WHERE id=?').get(m.id).metadata_json).files[0].url,'/api/media/photo-two');
 await send(DB,alice,'ADD_MEMORY',{memory:{id:'memory-video',image:'/api/media/video-one'}});await assert.rejects(()=>send(DB,owner,'FEATURE_MEMORY',{id:'memory-video',approved:true}));
});
test('pending member can upload only their own onboarding photo without family read access',async()=>{
 const {DB,sqlite}=setup(),objects=new Map(),env={DB,BETTER_AUTH_SECRET:'test-only-long-enough-secret-not-real',AUTH_ORIGIN:'https://greenwhitefamily.com',R2:{put:async(k,b)=>objects.set(k,b),delete:async k=>objects.delete(k)}};
 const app=createApp(()=>({api:{getSession:async({headers})=>headers.get('x-test-user')?{user:{id:headers.get('x-test-user'),emailVerified:true}}:null}}));
 const request=(user,origin=env.AUTH_ORIGIN,bytes=new Uint8Array([137,80,78,71,13,10,26,10]))=>{const form=new FormData();form.append('file',new Blob([bytes],{type:'image/png'}),'photo.png');return app.request(env.AUTH_ORIGIN+'/api/onboarding/photo',{method:'POST',headers:{Origin:origin,'x-test-user':user},body:form},env)};
 assert.equal((await request('pending','https://evil.test')).status,403);assert.equal((await request('pending',env.AUTH_ORIGIN,new Uint8Array([1,2,3]))).status,400);
 const r=await request('pending');assert.equal(r.status,201,await r.clone().text());const {url}=await r.json();assert.equal(sqlite.prepare("SELECT image FROM user WHERE id='pending'").get().image,url);assert.equal(sqlite.prepare("SELECT image FROM user WHERE id='alice'").get().image,null);assert.equal(objects.size,1);
 assert.equal((await app.request(env.AUTH_ORIGIN+'/api/state',{headers:{'x-test-user':'pending'}},env)).status,403);
 sqlite.exec("UPDATE members SET status='suspended' WHERE id='pending'");assert.equal((await request('pending')).status,403);
});

test('reaction identities are visible only with the authorized conversation',async()=>{const{DB,alice,bob,owner}=setup();const p=await send(DB,alice,'ADD_POST',{post:{text:'Group only',groupId:'private-group'}});await send(DB,alice,'TOGGLE_REACTION',{targetId:p.id,emoji:'❤️'});assert.deepEqual((await familyState(DB,alice)).reactionMembers[p.id]['❤️'],['alice']);assert.equal((await familyState(DB,bob)).reactionMembers[p.id],undefined);assert.equal((await familyState(DB,owner)).reactionMembers[p.id],undefined);await send(DB,alice,'TOGGLE_REACTION',{targetId:p.id,emoji:'❤️'});assert.equal((await familyState(DB,alice)).reactionMembers[p.id],undefined)});
