// Test-only HTTP harness. Never imported into the Worker bundle.
import {createServer} from 'node:http';import {readFile} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {database,seed} from './test-db.mjs';import {createApp} from '../src/worker.mjs';
const {sqlite,DB}=database();seed(sqlite);const root=fileURLToPath(new URL('../../dist/',import.meta.url));
const store=new Map();const env={DB,BETTER_AUTH_SECRET:'local-fixture-only-secret-with-no-production-access',AUTH_ORIGIN:'https://greenwhitefamily.com',R2:{async put(k,v){store.set(k,v)},async get(k){return store.has(k)?{body:store.get(k)}:null},async delete(k){store.delete(k)}}};
const auth=()=>({api:{async getSession({headers}){const match=/(?:^|; )fixture-user=([^;]+)/.exec(headers.get('cookie')||'');return match?{user:{id:match[1],emailVerified:true,email:match[1]+'@example.test',name:match[1]}}:null}},handler:async()=>new Response('{}',{status:404,headers:{'Content-Type':'application/json'}})});
const app=createApp(auth);
createServer(async(req,res)=>{try{const url=new URL(req.url,env.AUTH_ORIGIN);if(url.pathname==='/__test/signin'){const user=url.searchParams.get('user');if(!['owner','alice','bob','pending'].includes(user)){res.writeHead(400);res.end();return}res.writeHead(302,{'Set-Cookie':`fixture-user=${user}; Path=/; HttpOnly; SameSite=Lax`,Location:'/'});res.end();return}
 if(url.pathname==='/api/config'){res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({configured:true,email:false,providers:[],origin:env.AUTH_ORIGIN}));return}
 if(url.pathname.startsWith('/api/')){const chunks=[];for await(const c of req)chunks.push(c);const request=new Request(url,{method:req.method,headers:{...req.headers,...(req.headers.origin==='http://127.0.0.1:4174'?{origin:env.AUTH_ORIGIN}:{})},...(!['GET','HEAD'].includes(req.method)?{body:Buffer.concat(chunks)}:{})});const response=await app.fetch(request,env);res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));return}
 const p=path.resolve(root,'.'+(url.pathname==='/'?'/index.html':decodeURIComponent(url.pathname)));if(!p.startsWith(root)){res.writeHead(403);res.end();return}const bytes=await readFile(p);const ext=path.extname(p),types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.webmanifest':'application/manifest+json'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});res.end(bytes);
}catch(error){console.error(error.message);res.writeHead(500,{'Content-Type':'application/json'});res.end(JSON.stringify({error:'Fixture request failed'}))}}).listen(4174,'127.0.0.1',()=>console.log('GW fixture server ready'));
