import test from 'node:test';import assert from 'node:assert/strict';
import {database,seed} from './test-db.mjs';import {createApp} from '../src/worker.mjs';import {command} from '../src/family-service.mjs';
const actor=id=>({id,status:'active',group:'family',roles:[],canPost:true,isLeader:false});
async function setup(){const {sqlite,DB}=database();seed(sqlite);await DB.prepare('INSERT INTO media(id,owner_id,object_key,name,mime_type,size_bytes) VALUES(?,?,?,?,?,?)').bind('profile-file','alice','profile-key','alice.png','image/png',3).run();await DB.prepare('UPDATE user SET image=? WHERE id=?').bind('/api/media/profile-file','alice').run();const env={DB,BETTER_AUTH_SECRET:'test-only-long-secret-not-a-real-service',AUTH_ORIGIN:'https://greenwhitefamily.com',R2:{get:async()=>({body:new Uint8Array([1,2,3])})}},app=createApp(()=>({api:{getSession:async({headers})=>headers.has('x-test-user')?{user:{id:headers.get('x-test-user'),emailVerified:headers.get('x-test-verified')!=='no'}}:null}}));const get=(id,path,headers={})=>app.request(env.AUTH_ORIGIN+path,{headers:{...(id?{'x-test-user':id}:{}),...headers}},env);const send=(id,input)=>command(DB,actor(id),{requestId:crypto.randomUUID(),...input});return {DB,sqlite,app,env,get,send};}
const target={kind:'profile',id:'alice',index:0,photo:'/api/media/profile-file'};
test('photo discussions require a verified active member and do not create a thread on read',async()=>{const s=await setup();assert.equal((await s.get(null,'/api/photo-discussions/profile/alice')).status,401);assert.equal((await s.get('pending','/api/photo-discussions/profile/alice')).status,403);assert.equal((await s.get('bob','/api/photo-discussions/profile/alice',{'x-test-verified':'no'})).status,403);const r=await(await s.get('bob','/api/photo-discussions/profile/alice')).json();assert.equal(r.photo.url,target.photo);assert.deepEqual(r.comments,[]);assert.equal(s.sqlite.prepare('SELECT count(*) n FROM photo_comments').get().n,0);});
test('comments and reactions persist across accounts with existing idempotent command receipts',async()=>{const s=await setup(),view=await(await s.get('bob','/api/photo-discussions/profile/alice')).json(),input={type:'ADD_COMMENT',requestId:crypto.randomUUID(),targetId:view.threadId,photoTarget:target,text:'A lovely family photo'};const first=await command(s.DB,actor('bob'),input),again=await command(s.DB,actor('bob'),input);assert.deepEqual(first,again);let read=await(await s.get('alice','/api/photo-discussions/profile/alice')).json();assert.equal(read.comments.length,1);assert.equal(read.comments[0].authorId,'bob');await s.send('alice',{type:'TOGGLE_REACTION',targetId:view.threadId,photoTarget:target,emoji:'💚',photoSelected:true});await s.send('alice',{type:'TOGGLE_REACTION',targetId:view.threadId,photoTarget:target,emoji:'💚',photoSelected:true});read=await(await s.get('bob','/api/photo-discussions/profile/alice')).json();assert.equal(read.reactions.length,1);await s.send('alice',{type:'TOGGLE_REACTION',targetId:view.threadId,photoTarget:target,emoji:'💚',photoSelected:false});assert.equal((await(await s.get('bob','/api/photo-discussions/profile/alice')).json()).reactions.length,0);assert.equal(s.sqlite.prepare('SELECT count(*) n FROM posts').get().n,0,'photo conversation does not publish a fake feed post');});
test('profile optout blocks others download but leaves visible photo and owner download available',async()=>{const s=await setup();await s.send('alice',{type:'SAVE_MEMBER',member:{id:'alice',name:'Alice',photo:target.photo,allowPhotoSave:false}});const read=await(await s.get('bob','/api/photo-discussions/profile/alice')).json();assert.equal(read.photo.canSave,false);assert.equal((await s.get('bob','/api/photo-discussions/profile/alice/download')).status,403);assert.equal((await s.get('alice','/api/photo-discussions/profile/alice/download')).status,200);});
test('changed or removed profile photo cannot accept stale writes',async()=>{const s=await setup();await s.DB.prepare('UPDATE user SET image=NULL WHERE id=?').bind('alice').run();await assert.rejects(()=>s.send('bob',{type:'ADD_COMMENT',targetId:'stale',photoTarget:target,text:'Stale'}),e=>e.status===404);assert.equal(s.sqlite.prepare('SELECT count(*) n FROM photo_comments').get().n,0);});
test('private group photo does not expose discussion or download to other members',async()=>{const s=await setup();const post=await s.send('alice',{type:'ADD_POST',post:{text:'Private',groupId:'private-group',files:[{id:'profile-file'}]}});assert.equal((await s.get('alice','/api/photo-discussions/post/'+post.id)).status,200);assert.equal((await s.get('bob','/api/photo-discussions/post/'+post.id)).status,404);assert.equal((await s.get('bob','/api/photo-discussions/post/'+post.id+'/download')).status,404);});
test('photo comments reject foreign reply parents and command origin remains enforced',async()=>{const s=await setup();await assert.rejects(()=>s.send('bob',{type:'ADD_COMMENT',targetId:'photo',photoTarget:target,text:'Reply',parentId:'foreign-comment'}),e=>e.status===404);const response=await s.app.request(s.env.AUTH_ORIGIN+'/api/commands',{method:'POST',headers:{'x-test-user':'bob',Origin:'https://evil.example','Content-Type':'application/json'},body:JSON.stringify({type:'ADD_COMMENT',requestId:crypto.randomUUID(),photoTarget:target,text:'No'})},s.env);assert.equal(response.status,403);});
