import test from 'node:test';
import assert from 'node:assert/strict';
import {database,seed} from './test-db.mjs';
import {PUSH_IMPLEMENTATION_READY,validateSubscription,genericPayload,retryOutcome} from '../src/push-policy.mjs';
import {registerDevice,revokeDevice,claimDelivery,authorizedDelivery,finishDelivery,drainWithInjectedSender} from '../src/push-store.mjs';
// Non-cryptographic structural placeholders. No key generation, encryption,
// signature, credentials, real subscription, provider or remote request involved.
const structuralSub={endpoint:'https://web.push.apple.com/fictional-offline-only',keys:{p256dh:Buffer.from([4,...Array(64).fill(0)]).toString('base64url'),auth:Buffer.alloc(16).toString('base64url')}};
const actor={id:'bob'};
function setup(){const x=database();seed(x.sqlite);x.sqlite.exec(`INSERT INTO session(id,expiresAt,token,createdAt,updatedAt,userId) VALUES('fictional-session',9999999999999,'fictional-not-authentic',0,0,'bob'); DELETE FROM notifications; DELETE FROM notification_events;`);return x}
async function subscribe(x){return registerDevice(x.DB,actor,'fictional-session','bob',structuralSub,'future-version')}
function notice(x,id='event1'){
 x.sqlite.prepare(`INSERT INTO notification_events(id,event_key,kind,actor_id,resource_kind,resource_id,category,audience,direct_ids_json) VALUES(?,?,'membership.role_changed','owner','member','bob','membership','direct','["bob"]')`).run(id,id);
 return x.sqlite.prepare('SELECT * FROM push_outbox').all();
}
test('implementation is available behind deployment, schema and database activation gates',()=>assert.equal(PUSH_IMPLEMENTATION_READY,true));
test('allowlisted strict endpoint and browser-key structural validation',()=>{
 assert.deepEqual(validateSubscription(structuralSub),structuralSub);
 for(const endpoint of ['http://web.push.apple.com/a','https://127.0.0.1/a','https://web.push.apple.com.evil.test/a','https://user@web.push.apple.com/a','https://web.push.apple.com:8443/a','https://web.push.apple.com/a#x','https://web.push.apple.com/a?x','https://WEB.PUSH.APPLE.COM/a'])assert.throws(()=>validateSubscription({...structuralSub,endpoint}));
 assert.throws(()=>validateSubscription({...structuralSub,keys:{...structuralSub.keys,auth:'bad'}}));
});
test('payload has no private content or arbitrary URL',()=>{const p=genericPayload('opaque-id',123);assert.equal(p.url,'/?gwNotice=opaque-id');assert.equal(p.title,'Green & White Family');assert.throws(()=>genericPayload('https://bad.test',1));assert.equal(Object.keys(p).length,7)});
test('disabled migration does not enqueue and opt-in never backfills',async()=>{const x=setup();await subscribe(x);notice(x);assert.equal(x.sqlite.prepare('SELECT count(*) n FROM push_outbox').get().n,0);x.sqlite.exec('UPDATE push_control SET enabled=1');await subscribe(x);assert.equal(x.sqlite.prepare('SELECT count(*) n FROM push_outbox').get().n,0)});
test('account guards and session ownership reject stale registration',async()=>{const x=setup();await assert.rejects(()=>registerDevice(x.DB,actor,'fictional-session','alice',structuralSub,'v'));await assert.rejects(()=>registerDevice(x.DB,{id:'alice'},'fictional-session','alice',structuralSub,'v'));assert.equal(x.sqlite.prepare('SELECT count(*) n FROM push_devices').get().n,0)});
test('commit fanout dedupe and one exclusive lease',async()=>{const x=setup();await subscribe(x);x.sqlite.exec('UPDATE push_control SET enabled=1');assert.equal(notice(x).length,1);const first=await claimDelivery(x.DB);assert.ok(first);assert.equal(await claimDelivery(x.DB),null);assert.ok(await authorizedDelivery(x.DB,first,Date.now()));});
test('global Off revokes devices and cancels queued rows; On does not revive',async()=>{const x=setup();await subscribe(x);x.sqlite.exec('UPDATE push_control SET enabled=1');notice(x);x.sqlite.exec("INSERT OR IGNORE INTO notification_settings(member_id) VALUES('bob'); UPDATE notification_settings SET global_off=1 WHERE member_id='bob'; UPDATE notification_settings SET global_off=0 WHERE member_id='bob';");assert.equal(x.sqlite.prepare('SELECT state FROM push_outbox').get().state,'cancelled');assert.ok(x.sqlite.prepare('SELECT revoked_at FROM push_devices').get().revoked_at);assert.equal(await claimDelivery(x.DB),null)});
test('revocation after lease prevents sending and stale completion cannot restore',async()=>{const x=setup();const d=await subscribe(x);x.sqlite.exec('UPDATE push_control SET enabled=1');notice(x);const row=await claimDelivery(x.DB);await revokeDevice(x.DB,actor,'bob',d.id);assert.equal(await authorizedDelivery(x.DB,row,Date.now()),null);await finishDelivery(x.DB,row,{state:'accepted',status:'accepted'},Date.now());assert.equal(x.sqlite.prepare('SELECT state FROM push_outbox').get().state,'cancelled')});
test('read, expiry, category, membership and session revocation suppress delivery',async()=>{
 for(const sql of ["UPDATE notifications SET read_at=CURRENT_TIMESTAMP","UPDATE notification_events SET expires_at='2000-01-01'","INSERT INTO notification_settings(member_id,categories_json) VALUES('bob','{\"membership\":false}')","UPDATE members SET status='suspended' WHERE id='bob'","UPDATE session SET expiresAt=0"]){const x=setup();await subscribe(x);x.sqlite.exec('UPDATE push_control SET enabled=1');notice(x);x.sqlite.exec(sql);let count=0;await drainWithInjectedSender(x.DB,{sender:async()=>{count++;return {status:201}}});assert.equal(count,0,sql)}
});
test('session deletion cascades device and outbox',async()=>{const x=setup();await subscribe(x);x.sqlite.exec('UPDATE push_control SET enabled=1');notice(x);x.sqlite.exec("DELETE FROM session WHERE id='fictional-session'");assert.equal(x.sqlite.prepare('SELECT count(*) n FROM push_outbox').get().n,0)});
test('provider acceptance, transient retry, auth circuit breaker, and gone handling',async()=>{
 for(const [status,state] of [[201,'accepted'],[429,'pending'],[503,'pending'],[410,'cancelled'],[401,'failed'],[400,'failed']]){const x=setup();await subscribe(x);x.sqlite.exec('UPDATE push_control SET enabled=1');notice(x);let count=0;await drainWithInjectedSender(x.DB,{sender:async({payload,timeoutMs})=>{count++;assert.equal(payload.title,'Green & White Family');assert.equal(timeoutMs,10000);return {status,retryAfter:'60'}}});assert.equal(count,1);assert.equal(x.sqlite.prepare('SELECT state FROM push_outbox').get().state,state);if(status===401)assert.equal(x.sqlite.prepare('SELECT enabled FROM push_control').get().enabled,0)}
});
test('retry respects hard expiry, Retry-After and bounded attempts',()=>{assert.equal(retryOutcome(429,1,1000,10000,'30').state,'expired');assert.equal(retryOutcome(503,8,0,9999999).state,'failed');assert.equal(retryOutcome(302,1,0,9999999).state,'failed');assert.equal(retryOutcome(429,1,0,9999999,'120').nextAt,120000)});
test('domain/event/outbox transaction rolls back together',async()=>{const x=setup();await subscribe(x);x.sqlite.exec('UPDATE push_control SET enabled=1');x.sqlite.exec('BEGIN');assert.equal(notice(x).length,1);x.sqlite.exec('ROLLBACK');assert.equal(x.sqlite.prepare('SELECT count(*) n FROM notification_events').get().n,0);assert.equal(x.sqlite.prepare('SELECT count(*) n FROM push_outbox').get().n,0)});

test('reassignment is atomic on rejected global-Off registration',async()=>{const x=setup();const first=await subscribe(x);x.sqlite.exec("INSERT INTO session(id,expiresAt,token,createdAt,updatedAt,userId) VALUES('alice-session',9999999999999,'fictional-alice-token',0,0,'alice'); INSERT INTO notification_settings(member_id,global_off) VALUES('alice',1)");await assert.rejects(()=>registerDevice(x.DB,{id:'alice'},'alice-session','alice',structuralSub,'v'));assert.equal(x.sqlite.prepare('SELECT id FROM push_devices').get().id,first.id)});
test('expired lease is reclaimed; stale response cannot accept new lease',async()=>{const x=setup();await subscribe(x);x.sqlite.exec('UPDATE push_control SET enabled=1');notice(x);const now=Date.now();const first=await claimDelivery(x.DB,now);const second=await claimDelivery(x.DB,now+61000);assert.equal(second.id,first.id);assert.notEqual(second.lease_token,first.lease_token);await finishDelivery(x.DB,first,{state:'accepted',status:'accepted'},now+62000);assert.equal(x.sqlite.prepare('SELECT lease_token FROM push_outbox').get().lease_token,second.lease_token)});
