import test from 'node:test';import assert from 'node:assert/strict';
import {database,seed} from './test-db.mjs';import {createApp} from '../src/worker.mjs';
import {runtimeReady,createPushSender,drainPush} from '../src/push-runtime.mjs';
function setup(){const d=database();seed(d.sqlite);const env={DB:d.DB,BETTER_AUTH_SECRET:'fictional-unused-auth-fixture',AUTH_ORIGIN:'https://fictional.example.test'};const app=createApp(()=>({api:{getSession:async({headers})=>headers.get('x-fictional-user')?{user:{id:headers.get('x-fictional-user'),emailVerified:true},session:{id:'fictional-session'}}:null}}));return {...d,env,call:(user,path,method='GET',body,origin=env.AUTH_ORIGIN)=>app.request(origin+path,{method,headers:{Origin:origin,'x-fictional-user':user,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})},env)}}
test('disabled routes expose no key or device and preserve auth/origin/account guards',async()=>{const {call}=setup();assert.equal((await call('','/api/me/push')).status,401);assert.equal((await call('pending','/api/me/push')).status,403);let r=await call('bob','/api/me/push');assert.deepEqual(await r.json(),{accountId:'bob',ready:false,pushEnabled:false,devices:[],reason:'activation-required'});assert.equal((await call('bob','/api/me/push/devices','POST',{expectedAccountId:'alice'})).status,409);assert.equal((await call('bob','/api/me/push/devices','POST',{expectedAccountId:'bob'})).status,503);assert.equal((await call('bob','/api/me/push/devices','POST',{expectedAccountId:'bob'},'https://foreign.example.test')).status,403)});
test('disabled sender and drain never read secrets, load package or fetch',async()=>{const env={PUSH_ENABLED:'true',get PUSH_VAPID_PRIVATE_KEY(){throw Error('must not inspect')},get DB(){throw Error('must not query')}};assert.equal(runtimeReady(env),false);let count=0;const sender=createPushSender(env,{load:()=>{count++;throw Error('must not load')},fetcher:()=>{count++;throw Error('must not fetch')}});assert.deepEqual(await sender({}),{status:403});assert.deepEqual(await drainPush(env),{attempted:0,disabled:true});assert.equal(count,0)});
test('disabled delete/revoke-session require exact account and do not opt in',async()=>{const {call,sqlite}=setup();assert.equal((await call('bob','/api/me/push/revoke-session','POST',{expectedAccountId:'alice'})).status,409);assert.equal((await call('bob','/api/me/push/revoke-session','POST',{expectedAccountId:'bob'})).status,200);assert.equal((await call('bob','/api/me/push/devices/fictional','DELETE',{expectedAccountId:'bob'})).status,200);assert.equal(sqlite.prepare('SELECT count(*) n FROM push_devices').get().n,0)});

test('prepared transport rejects changed endpoints and enforces redirect/abort/status-only boundary',async()=>{
 const {transmitPreparedPush}=await import('../src/push-runtime.mjs');const endpoint='https://web.push.apple.com/fictional-offline-only';let calls=0;
 const fetcher=async(url,options)=>{calls++;assert.equal(url,endpoint);assert.equal(options.redirect,'error');assert.equal(options.method,'POST');assert.ok(options.signal);return new Response('must not be logged',{status:429,headers:{'Retry-After':'90'}})};
 assert.deepEqual(await transmitPreparedPush({endpoint,method:'POST',headers:{},body:'fictional-body'},endpoint,{fetcher}),{status:429,retryAfter:'90'});
 await assert.rejects(()=>transmitPreparedPush({endpoint:'https://evil.example.test',method:'POST'},endpoint,{fetcher}));assert.equal(calls,1);
});
test('revocation stays available with delivery disabled after schema activation',async()=>{const {call,env,sqlite}=setup();env.PUSH_SCHEMA_VERSION='1';sqlite.exec("INSERT INTO session(id,expiresAt,token,createdAt,updatedAt,userId) VALUES('fictional-session',9999999999999,'fictional-offline-session',0,0,'bob'); INSERT INTO push_devices(id,member_id,session_id,endpoint,p256dh,auth,key_version,created_at,confirmed_at) VALUES('fictional-device','bob','fictional-session','https://web.push.apple.com/fictional','','','future',0,0)");const r=await call('bob','/api/me/push');const status=await r.json();assert.equal(status.ready,false);assert.equal(status.devices.length,1);assert.equal(status.publicKey,undefined);assert.equal((await call('bob','/api/me/push/revoke-session','POST',{expectedAccountId:'bob'})).status,200);assert.ok(sqlite.prepare('SELECT revoked_at FROM push_devices').get().revoked_at)});

test('destination safety is revalidated at transport even when both endpoints match',async()=>{
 const {transmitPreparedPush}=await import('../src/push-runtime.mjs');const {validatePushEndpoint,validateSubscription}=await import('../src/push-policy.mjs');let requests=0;
 const forbidden=['https://evil.example.test/path','https://web.push.apple.com.evil.example.test/path','https://127.0.0.1/path','https://10.0.0.1/path','https://172.16.0.1/path','https://192.168.1.1/path','https://169.254.169.254/latest/meta-data','https://0.0.0.0/path','https://192.0.2.1/path','https://[::1]/path','https://[fc00::1]/path','https://[fe80::1]/path','https://[::ffff:127.0.0.1]/path','https://localhost/path','https://user:password@web.push.apple.com/path','https://web.push.apple.com:444/path','https://web.push.apple.com:443/path','http://web.push.apple.com/path','https://web.push.apple.com/path?','https://web.push.apple.com/path#','https://%77eb.push.apple.com/path'];
 const keys={p256dh:Buffer.from([4,...Array(64).fill(0)]).toString('base64url'),auth:Buffer.alloc(16).toString('base64url')};
 for(const endpoint of forbidden){assert.throws(()=>validatePushEndpoint(endpoint),endpoint);assert.throws(()=>validateSubscription({endpoint,keys}),endpoint);await assert.rejects(()=>transmitPreparedPush({endpoint,method:'POST'},endpoint,{fetcher:async()=>{requests++;throw Error('must not fetch')}}),endpoint)}
 assert.equal(requests,0);
 for(const host of ['fcm.googleapis.com','updates.push.services.mozilla.com','web.push.apple.com'])assert.equal(validatePushEndpoint('https://'+host+'/fictional-offline-only'),'https://'+host+'/fictional-offline-only');
});
test('redirect response is never followed or considered accepted',async()=>{const {transmitPreparedPush}=await import('../src/push-runtime.mjs');const {retryOutcome}=await import('../src/push-policy.mjs');let requests=0;const endpoint='https://web.push.apple.com/fictional-offline-only';const response=await transmitPreparedPush({endpoint,method:'POST'},endpoint,{fetcher:async(_,options)=>{requests++;assert.equal(options.redirect,'error');return new Response(null,{status:302,headers:{Location:'http://169.254.169.254/'}})}});assert.equal(requests,1);assert.equal(response.status,302);assert.equal(retryOutcome(response.status,1,0,100000).state,'failed')});

test('documented Apple and Microsoft provider families are supported without weakening URL trust boundaries',async()=>{
 const {validatePushEndpoint}=await import('../src/push-policy.mjs');
 for(const endpoint of ['https://web.push.apple.com/fictional','https://region.push.apple.com/fictional','https://wns2-fictional.notify.windows.com/w/?token=fictional%2Btoken%3D'])assert.equal(validatePushEndpoint(endpoint),endpoint);
 for(const endpoint of ['https://notify.windows.com/w/?token=fictional','https://fake.notify.windows.com.evil.example/w/?token=fictional','https://evilpush.apple.com/fictional','https://push.apple.com/fictional','https://foo.push.apple.com.evil.example/fictional','https://x.notify.windows.com/w/?token=one&token=two','https://x.notify.windows.com/w/?token=','https://x.notify.windows.com/w/?url=https://evil.example','https://x.notify.windows.com/w/?token=x&url=https://evil.example','https://x.notify.windows.com/other?token=x','https://x.notify.windows.com/w/?token=%0A','https://x.notify.windows.com/w/?token=%zz','https://user@x.notify.windows.com/w/?token=x','https://x.notify.windows.com:444/w/?token=x','https://x.notify.windows.com/w/?token=x#fragment'])assert.throws(()=>validatePushEndpoint(endpoint),endpoint);
});
