// Focused SQLite write tests use canonical 0001–0005 plus explicit receipt
// columns required by the command API. They do not replace the full-chain suite.
import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {command} from '../src/family-service.mjs';
import {readCalendar} from '../src/calendar.mjs';
import {resolveReunion} from '../src/reunions.mjs';
function fixture({date='',location='Old hall'}={}){
 const sqlite=new DatabaseSync(':memory:');
 for(const name of ['0001_auth.sql','0002_family.sql','0003_complete_family.sql','0004_birthdays.sql','0005_featured_memories.sql'])sqlite.exec(readFileSync(new URL('../migrations/'+name,import.meta.url),'utf8'));
 sqlite.exec("ALTER TABLE command_receipts ADD COLUMN operation TEXT; ALTER TABLE command_receipts ADD COLUMN fingerprint TEXT; INSERT INTO user(id,name,email,emailVerified,createdAt,updatedAt) VALUES('owner','Owner','owner@example.test',1,0,0),('alice','Alice','alice@example.test',1,0,0); INSERT INTO members(id,status,roles_json,is_leader) VALUES('owner','active','[\"planner\",\"treasurer\"]',1),('alice','active','[]',0); INSERT INTO products(id,name) VALUES('forest','Original shirt'); INSERT INTO rsvps(member_id,status,count) VALUES('alice','Planning to come',2); INSERT INTO fee_reports(id,member_id,status) VALUES('old-fee','alice','confirmed'); INSERT INTO shirt_claims(id,member_id,lines_json) VALUES('old-order','alice','[]');");
 sqlite.prepare("INSERT INTO reunion_settings(id,data_json,updated_by) VALUES('current',?,'owner')").run(JSON.stringify({date,location,payment:{amount:'$50'}}));
 const settingsBefore=sqlite.prepare("SELECT data_json FROM reunion_settings WHERE id='current'").get().data_json;
 sqlite.exec("CREATE TABLE fixture_notifications(id TEXT); CREATE TRIGGER fixture_reunion_insert AFTER INSERT ON reunion_settings WHEN json_extract(NEW.data_json,'$.date')!='' OR json_extract(NEW.data_json,'$.location')!='' BEGIN INSERT INTO fixture_notifications(id) VALUES(NEW.id); END;");
 sqlite.exec(readFileSync(new URL('../migrations/0017_reunion_years.sql',import.meta.url),'utf8'));
 class Statement{constructor(sql,args=[]){this.sql=sql;this.args=args}bind(...args){return new Statement(this.sql,args)}async all(){const s=sqlite.prepare(this.sql);if(s.columns().length)return {results:s.all(...this.args),success:true};return {results:[],success:true,meta:s.run(...this.args)}}async first(){return (await this.all()).results[0]||null}async run(){return this.all()}}
 const DB={prepare:sql=>new Statement(sql),async batch(statements){sqlite.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.all());sqlite.exec('COMMIT');return results}catch(e){sqlite.exec('ROLLBACK');throw e}}};
 return {DB,sqlite,settingsBefore};
}
const owner={id:'owner',status:'active',group:'family',roles:['planner','treasurer'],isLeader:true},member={id:'alice',status:'active',group:'family',roles:[],isLeader:false};
const write=(DB,actor,type,extra={})=>command(DB,actor,{type,requestId:crypto.randomUUID(),...extra});
test('backfill retains old settings and RSVP, defaults every financial/catalog record to legacy and sends no migration notices',()=>{
 for(const date of ['', '2026-07-01','1800-01-01']){const {sqlite,settingsBefore}=fixture({date});assert.equal(sqlite.prepare("SELECT data_json FROM reunion_settings WHERE id='current'").get().data_json,settingsBefore);assert.equal(sqlite.prepare('SELECT count(*) AS n FROM fixture_notifications').get().n,0);assert.equal(sqlite.prepare("SELECT year FROM reunions WHERE id='legacy'").get().year,date==='2026-07-01'?2026:null);assert.equal(sqlite.prepare("SELECT count FROM reunion_rsvps WHERE reunion_id='legacy' AND member_id='alice'").get().count,2);assert.equal(sqlite.prepare("SELECT count FROM rsvps WHERE member_id='alice'").get().count,2);for(const table of ['products','shirt_claims','fee_reports'])assert.ok(sqlite.prepare('SELECT reunion_id FROM '+table).all().every(r=>r.reunion_id==='legacy'));}
});
test('actual commands and calendar writes isolate concurrent years and preserve one active reunion',async()=>{
 const {DB,sqlite}=fixture();await write(DB,owner,'CREATE_REUNION',{year:2028});await write(DB,owner,'CREATE_REUNION',{year:2031});await write(DB,member,'RSVP',{reunionId:'reunion-2028',value:{status:'Can’t make it',count:1}});await write(DB,owner,'SET_PAYMENT',{reunionId:'reunion-2028',value:{amount:'$60',methods:[{provider:'cashApp',recipient:'$Fixture'}]}});
 assert.equal(sqlite.prepare("SELECT count FROM reunion_rsvps WHERE reunion_id='legacy'").get().count,2);assert.equal(sqlite.prepare("SELECT count FROM reunion_rsvps WHERE reunion_id='reunion-2028'").get().count,1);assert.equal(JSON.parse(sqlite.prepare("SELECT data_json FROM reunion_settings WHERE id='current'").get().data_json).payment.amount,'$50');assert.equal(JSON.parse(sqlite.prepare("SELECT data_json FROM reunion_settings WHERE id='reunion-2028'").get().data_json).payment.amount,'$60');
 for(const [reunionId,schedule]of [['legacy','Old schedule'],['reunion-2028','New schedule']])await write(DB,owner,'SAVE_CALENDAR',{reunionId,expectedAccountId:'owner',expectedRevision:0,settings:{visibility:'family',timezone:'UTC',schedule}});
 assert.equal((await readCalendar(DB,owner,'legacy')).schedule,'Old schedule');assert.equal((await readCalendar(DB,owner,'reunion-2028')).schedule,'New schedule');await write(DB,owner,'ACTIVATE_REUNION',{id:'reunion-2028',archivePrevious:true});assert.equal((await resolveReunion(DB)).id,'reunion-2028');assert.equal(sqlite.prepare("SELECT count(*) AS n FROM reunions WHERE status='active'").get().n,1);await assert.rejects(()=>write(DB,member,'RSVP',{reunionId:'legacy',value:{status:'Planning to come',count:4}}),e=>e.status===409);await write(DB,owner,'RESTORE_REUNION',{id:'legacy'});assert.equal((await resolveReunion(DB,'legacy')).status,'planned');assert.equal(sqlite.prepare("SELECT count FROM reunion_rsvps WHERE reunion_id='legacy'").get().count,2);
});
test('server denies non-treasurer destination changes, mismatched year IDs and cross-member receipt updates',async()=>{
 const {DB,sqlite}=fixture();await write(DB,owner,'CREATE_REUNION',{year:2028});await assert.rejects(()=>write(DB,{...owner,roles:['planner']},'SET_PAYMENT',{reunionId:'legacy',value:{amount:'$90'}}),e=>e.status===403);await assert.rejects(()=>write(DB,owner,'CONFIRM_FEE',{reunionId:'reunion-2028',id:'old-fee',status:'rejected'}),e=>e.status===404);await assert.rejects(()=>write(DB,owner,'UPDATE_CLAIM',{reunionId:'reunion-2028',id:'old-order',status:'delivered'}),e=>e.status===404);await assert.rejects(()=>write(DB,member,'CLAIM_ORDER',{reunionId:'reunion-2028',lines:[{productId:'forest',size:'M',quantity:1}]}),/unavailable/);await assert.rejects(()=>write(DB,owner,'ORDER_RECEIVED',{reunionId:'legacy',id:'old-order'}),e=>e.status===404);await assert.rejects(()=>write(DB,owner,'SAVE_PRODUCT',{reunionId:'reunion-2028',product:{id:'forest',name:'Overwrite'}}),e=>e.status===404);assert.equal(sqlite.prepare("SELECT status FROM fee_reports WHERE id='old-fee'").get().status,'confirmed');
});
test('request receipts bind year and legacy clients never write newly active year',async()=>{
 const {DB,sqlite}=fixture();await write(DB,owner,'CREATE_REUNION',{year:2028});await write(DB,owner,'ACTIVATE_REUNION',{id:'reunion-2028'});const payload={type:'RSVP',requestId:crypto.randomUUID(),reunionId:'legacy',value:{status:'Planning to come',count:4}};await command(DB,member,payload);await command(DB,member,payload);await assert.rejects(()=>command(DB,member,{...payload,reunionId:'reunion-2028'}),e=>e.status===409);const report=await write(DB,member,'SET_FEES',{value:'reported'});assert.equal(sqlite.prepare('SELECT reunion_id FROM fee_reports WHERE id=?').get(report.id).reunion_id,'legacy');
});
test('archive race rolls back the entire write, audit and receipt',async()=>{
 const {DB,sqlite}=fixture();await write(DB,owner,'CREATE_REUNION',{year:2028});const before=sqlite.prepare('SELECT count(*) AS n FROM fee_reports').get().n;const race={...DB,batch:async statements=>{sqlite.exec("UPDATE reunions SET status='archived' WHERE id='legacy';UPDATE reunions SET status='active' WHERE id='reunion-2028';");return DB.batch(statements)}};await assert.rejects(()=>write(race,member,'SET_FEES',{reunionId:'legacy',value:'reported'}),e=>e.status===409);assert.equal(sqlite.prepare('SELECT count(*) AS n FROM fee_reports').get().n,before);assert.equal(sqlite.prepare("SELECT count(*) AS n FROM command_receipts WHERE operation='SET_FEES'").get().n,0);
});
