import test from 'node:test';import assert from 'node:assert/strict';
import {database,seed} from './test-db.mjs';
import {createApp} from '../src/worker.mjs';
import {sharedPageDefaults} from '../../src/shared-content-schema.js';
import {defaultPanelLayout,createSharedPanel,addSharedPanel,removeSharedPanel,restoreSharedPanel,moveSharedPanel,changeSharedPanel,panelPayload} from '../../src/shared-panels.js';
function setup(){
 const value=database();seed(value.sqlite);
 value.sqlite.exec(`UPDATE members SET is_leader=1 WHERE id='alice';UPDATE members SET roles_json='["planner","moderator"]' WHERE id='bob';`);
 const objects=new Map();
 const env={DB:value.DB,R2:{head:async key=>objects.get(key)||null,get:async key=>objects.has(key)?{body:objects.get(key).bytes}:null,put:async(key,bytes,options)=>objects.set(key,{bytes,...options}),delete:async key=>objects.delete(key)},BETTER_AUTH_SECRET:'synthetic-page-content-test-secret',AUTH_ORIGIN:'https://family.example.test'};
 const sessions=new Set(['owner','alice','bob','pending']);
 const app=createApp(()=>({api:{getSession:async({headers})=>{const id=headers.get('Cookie')?.match(/session=([^;]+)/)?.[1];return sessions.has(id)?{user:{id,emailVerified:true}}:null;}}}));
 async function call(user,path,method='GET',body,headers={}){
  const response=await app.request(env.AUTH_ORIGIN+path,{method,headers:{...(user?{Cookie:'session='+user}:{}),Origin:env.AUTH_ORIGIN,...(body!==undefined?{'Content-Type':'application/json'}:{}),...headers},...(body!==undefined?{body:JSON.stringify(body)}:{})},env);
  const type=response.headers.get('Content-Type')||'';
  return {status:response.status,data:type.includes('application/json')?await response.json():await response.text(),headers:response.headers};
 }
 const get=(page='home',user='bob')=>call(user,'/api/page-content/'+page);
 const write=(content,expectedRevision=0,user='alice',page='home',requestId=crypto.randomUUID())=>call(user,'/api/page-content/'+page,'PATCH',{requestId,expectedRevision,content});
 const restore=(revision,expectedRevision,user='alice',page='home',requestId=crypto.randomUUID())=>call(user,'/api/page-content/'+page+'/restore','POST',{requestId,expectedRevision,revision});
 const upload=(id,owner='alice',type='image/jpeg',options={})=>{
  const key=`family/${owner}/${id}`,size=options.size??5;
  value.sqlite.prepare('INSERT INTO media(id,owner_id,object_key,name,mime_type,size_bytes,deleted_at) VALUES(?,?,?,?,?,?,?)').run(id,owner,options.key??key,id,type,size,options.deleted?'2026-01-01':null);
  if(!options.missing)objects.set(key,{bytes:new Uint8Array([255,216,255,224,0]),size});
  return {id,alt:'Family photo'};
 };
 return {...value,env,app,call,get,write,restore,upload,objects};
}

const snapshot=(content)=>({...content,hero:{mode:content.hero.mode,media:content.hero.media.map(({id,alt})=>({id,alt}))},panelLayout:panelPayload(content.panelLayout)});
const added=()=>{const content=sharedPageDefaults('home');content.panelLayout=addSharedPanel(content.panelLayout,createSharedPanel('panel-test','main','text'));content.panelLayout.panels.find(panel=>panel.id==='panel-test').body='**Shared** message\n\n[Family](/?page=family)';return content;};
test('Admins and Leaders can save shared panels; regular roles and forged panel fields are rejected',async()=>{const {write,get}=setup(),content=added();for(const user of [null,'pending','bob'])assert.equal((await write(content,0,user)).status,user?403:401);assert.equal((await write(content)).status,200);assert.equal((await get()).data.content.panelLayout.panels.find(panel=>panel.id==='panel-test').body,content.panelLayout.panels.find(panel=>panel.id==='panel-test').body);for(const property of ['html','component','memberId','privateRecord','onClick']){const bad=structuredClone(content);bad.panelLayout.panels.find(panel=>panel.id==='panel-test')[property]='injected';assert.equal((await write(bad,1)).status,400)}});
test('locked hero text/media/order are server guarded; explicit unlock allows revisioned changes',async()=>{const {write,get}=setup(),content=sharedPageDefaults('home');content.text.heroTitle='Changed';assert.equal((await write(content)).status,400);content.panelLayout=changeSharedPanel(content.panelLayout,'hero',{locked:false});let result=await write(content);assert.equal(result.status,200);assert.equal(result.data.content.text.heroTitle,'Changed');content.panelLayout=changeSharedPanel(content.panelLayout,'hero',{locked:true});result=await write(content,1);assert.equal(result.status,200);content.text.heroTitle='Blocked';assert.equal((await write(content,2)).status,400);assert.equal((await get()).data.revision,2)});
test('panel movement is CAS protected, idempotent and independently preserves mobile order',async()=>{const {write,get,sqlite}=setup(),content=added(),key='panel-idempotency-key';let saved=await write(content,0,'alice','home',key);assert.equal(saved.status,200);assert.equal((await write(content,0,'alice','home',key)).data.replayed,true);const moved=snapshot(saved.data.content);moved.panelLayout=moveSharedPanel(moved.panelLayout,'panel-test',{zone:'side'});assert.equal((await write(moved,0)).status,409);saved=await write(moved,1);assert.equal(saved.status,200);assert.equal(saved.data.content.panelLayout.panels.find(panel=>panel.id==='panel-test').zone,'side');assert.deepEqual(saved.data.content.panelLayout.mobileOrder,['hero','native-feed','native-reunion','panel-test']);assert.equal(sqlite.prepare('SELECT count(*) n FROM page_content_revisions').get().n,2);assert.equal((await get()).data.revision,2)});
test('soft remove, undo and restoring history retain the exact Markdown and attribution',async()=>{const {write,restore,call,sqlite}=setup(),content=added();assert.equal((await write(content)).status,200);const removed={...content,panelLayout:removeSharedPanel(content.panelLayout,'panel-test')};assert.equal((await write(removed,1)).status,200);assert.equal((await call('owner','/api/page-content/home/revisions')).data.revisions[0].content.panelLayout.panels.find(panel=>panel.id==='panel-test').body,content.panelLayout.panels.find(panel=>panel.id==='panel-test').body);const undone={...removed,panelLayout:restoreSharedPanel(removed.panelLayout,'panel-test',{desktop:1,mobile:1})};assert.equal((await write(undone,2)).status,200);assert.equal((await restore(1,3,'owner')).status,200);const row=sqlite.prepare('SELECT editor_id,restored_from FROM page_content_revisions WHERE revision=4').get();assert.deepEqual({...row},{editor_id:'owner',restored_from:1});assert.deepEqual((await restore(0,4)).data.content.panelLayout.panels.map(panel=>panel.id),['hero','native-feed','native-reunion'])});
test('removing the hero is recoverable and revoked published media visibility applies to hidden heroes',async()=>{const {write,upload,call}=setup(),content=sharedPageDefaults('home');content.hero={mode:'image',media:[upload('primary')]};content.panelLayout=changeSharedPanel(content.panelLayout,'hero',{locked:false});assert.equal((await write(content)).status,200);assert.equal((await call('bob','/api/media/primary')).status,200);content.panelLayout=removeSharedPanel(content.panelLayout,'hero');assert.equal((await write(content,1)).status,200);assert.equal((await call('bob','/api/media/primary')).status,404)});
test('panel photos enforce owner/type/object guards, enrich safe paths, and cease granting access when removed',async()=>{const {write,upload,call}=setup(),content=added();content.panelLayout.panels.find(panel=>panel.id==='panel-test').layout='photo';const own=upload('panel-photo'),other=upload('other-photo','bob');content.panelLayout.panels.find(panel=>panel.id==='panel-test').media=[other];assert.equal((await write(content)).status,400);content.panelLayout.panels.find(panel=>panel.id==='panel-test').media=[own];const result=await write(content);assert.equal(result.status,200);assert.equal(result.data.content.panelLayout.panels.find(panel=>panel.id==='panel-test').media[0].url,'/api/media/panel-photo');assert.equal((await call('bob','/api/media/panel-photo')).status,200);content.panelLayout=removeSharedPanel(content.panelLayout,'panel-test');assert.equal((await write(content,1)).status,200);assert.equal((await call('bob','/api/media/panel-photo')).status,404);assert.equal((await call('alice','/api/media/panel-photo')).status,200)});
test('legacy clients cannot erase an existing layout and all revision rows remain recoverable',async()=>{const {write,sqlite}=setup(),content=added();assert.equal((await write(content)).status,200);assert.equal((await write({text:{heading:'Legacy stale UI'}},1)).status,409);const erased=structuredClone(content);erased.panelLayout.panels.pop();erased.panelLayout.desktopOrder=['hero'];erased.panelLayout.mobileOrder=['hero'];assert.equal((await write(erased,1)).status,400);assert.equal(sqlite.prepare('SELECT count(*) n FROM page_content_revisions').get().n,1)});
test('body format opt-in preserves source including literal HTML while unknown formats and heading formats fail',async()=>{const {write,get,restore}=setup(),content=sharedPageDefaults('reunion');content.text.intro='  **Hello**\r\n<table>not executable</table>  ';content.bodyFormats={intro:'markdown'};assert.equal((await write(content,0,'alice','reunion')).status,200);assert.equal((await get('reunion')).data.content.text.intro,content.text.intro);const bad={...content,bodyFormats:{heading:'markdown'}};assert.equal((await write(bad,1,'alice','reunion')).status,400);const original=await restore(0,1,'alice','reunion');assert.deepEqual(original.data.content.bodyFormats,{})});
test('revision extensions are additive, atomic, and legacy content JSON remains compatible',async()=>{const {write,sqlite}=setup(),content=added();content.panelLayout.panels.find(panel=>panel.id==='panel-test').body='Exact new panel body';sqlite.exec("CREATE TRIGGER panel_write_failure BEFORE INSERT ON page_content_extensions BEGIN SELECT RAISE(ABORT,'fictional transaction failure'); END");assert.equal((await write(content)).status,500);for(const table of ['page_content','page_content_revisions','page_content_requests','page_content_extensions'])assert.equal(sqlite.prepare('SELECT count(*) n FROM '+table).get().n,0,table);sqlite.exec('DROP TRIGGER panel_write_failure');assert.equal((await write(content)).status,200);const row=sqlite.prepare('SELECT content_json FROM page_content_revisions').get(),extension=sqlite.prepare('SELECT extension_json FROM page_content_extensions').get();assert.deepEqual(Object.keys(JSON.parse(row.content_json)).sort(),['hero','text']);assert.equal(JSON.parse(extension.extension_json).panelLayout.panels.find(panel=>panel.id==='panel-test').body,'Exact new panel body')});
test('hidden hero media is absent from the legacy readable snapshot but retained in extension history',async()=>{const {write,upload,sqlite}=setup(),content=sharedPageDefaults('home');content.hero={mode:'image',media:[upload('hidden-primary')]};content.panelLayout=changeSharedPanel(content.panelLayout,'hero',{locked:false});assert.equal((await write(content)).status,200);content.panelLayout=removeSharedPanel(content.panelLayout,'hero');assert.equal((await write(content,1)).status,200);const legacy=JSON.parse(sqlite.prepare('SELECT content_json FROM page_content_revisions WHERE revision=2').get().content_json),ext=JSON.parse(sqlite.prepare('SELECT extension_json FROM page_content_extensions WHERE revision=2').get().extension_json);assert.deepEqual(legacy.hero,{mode:'default',media:[]});assert.equal(ext.hero.media[0].id,'hidden-primary')});
test('old clients cannot silently drop body format metadata even without custom panels',async()=>{const {write}=setup(),content=sharedPageDefaults('reunion');content.text.intro='**Keep formatting**';content.bodyFormats={intro:'markdown'};assert.equal((await write(content,0,'alice','reunion')).status,200);const old={text:{intro:'**Keep formatting**'},hero:content.hero};assert.equal((await write(old,1,'alice','reunion')).status,409)});
test('missing archived photos do not block unrelated edits and cannot be restored without revalidation',async()=>{const {write,upload,sqlite,objects}=setup(),content=added();content.panelLayout.panels.find(panel=>panel.id==='panel-test').layout='photo';content.panelLayout.panels.find(panel=>panel.id==='panel-test').media=[upload('later-missing')];assert.equal((await write(content)).status,200);content.panelLayout=removeSharedPanel(content.panelLayout,'panel-test');assert.equal((await write(content,1)).status,200);sqlite.exec("UPDATE media SET deleted_at='2026-10-01' WHERE id='later-missing'");objects.delete('family/alice/later-missing');content.text.heading='Unrelated copy edit';assert.equal((await write(content,2)).status,200);content.panelLayout=restoreSharedPanel(content.panelLayout,'panel-test');assert.equal((await write(content,3)).status,400)});
test('new references hidden in removed panels never launder another member’s private image',async()=>{const {write,upload}=setup(),content=added();content.panelLayout.panels.find(panel=>panel.id==='panel-test').layout='photo';content.panelLayout.panels.find(panel=>panel.id==='panel-test').media=[upload('private-hidden','bob')];content.panelLayout=removeSharedPanel(content.panelLayout,'panel-test');assert.equal((await write(content)).status,400)});
