PRAGMA foreign_keys=ON;
CREATE TABLE app_rate_limits(key TEXT PRIMARY KEY,count INTEGER NOT NULL,reset_at INTEGER NOT NULL);
CREATE TABLE profiles(member_id TEXT PRIMARY KEY REFERENCES members(id),bio TEXT NOT NULL DEFAULT '',profile_color TEXT NOT NULL DEFAULT '#4f996c',theme_song TEXT NOT NULL DEFAULT '',socials_json TEXT NOT NULL DEFAULT '{}',birthday TEXT,gender TEXT NOT NULL DEFAULT '',contact_json TEXT NOT NULL DEFAULT '{}',completed INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE dependents(id TEXT PRIMARY KEY,guardian_id TEXT NOT NULL REFERENCES members(id),name TEXT NOT NULL,birthday TEXT NOT NULL,gender TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,deleted_at TEXT);
CREATE TABLE reunion_settings(id TEXT PRIMARY KEY DEFAULT 'current',data_json TEXT NOT NULL DEFAULT '{}',updated_by TEXT REFERENCES members(id),updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE rsvps(member_id TEXT PRIMARY KEY REFERENCES members(id),status TEXT NOT NULL,count INTEGER NOT NULL CHECK(count BETWEEN 1 AND 50),updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE posts ADD COLUMN metadata_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE comments ADD COLUMN files_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE products ADD COLUMN data_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE products ADD COLUMN deleted_at TEXT;
ALTER TABLE notifications ADD COLUMN data_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE notifications ADD COLUMN dismissed_at TEXT;
CREATE TABLE memories(id TEXT PRIMARY KEY,author_id TEXT NOT NULL REFERENCES members(id),data_json TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,deleted_at TEXT);
CREATE TABLE media(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL REFERENCES members(id),object_key TEXT NOT NULL UNIQUE,name TEXT NOT NULL,mime_type TEXT NOT NULL,size_bytes INTEGER NOT NULL,visibility TEXT NOT NULL DEFAULT 'private',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,deleted_at TEXT);
CREATE TABLE saved_items(member_id TEXT NOT NULL REFERENCES members(id),target_id TEXT NOT NULL,PRIMARY KEY(member_id,target_id));
CREATE TABLE poll_votes(member_id TEXT NOT NULL REFERENCES members(id),post_id TEXT NOT NULL REFERENCES posts(id),options_json TEXT NOT NULL,PRIMARY KEY(member_id,post_id));
CREATE TABLE moderation_reports(id TEXT PRIMARY KEY,reporter_id TEXT NOT NULL REFERENCES members(id),target_id TEXT NOT NULL,reason TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',resolved_by TEXT REFERENCES members(id),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE command_receipts(member_id TEXT NOT NULL REFERENCES members(id),request_id TEXT NOT NULL,result_json TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(member_id,request_id));
CREATE TABLE birthday_events(member_id TEXT NOT NULL REFERENCES members(id),event_year INTEGER NOT NULL,post_id TEXT REFERENCES posts(id),PRIMARY KEY(member_id,event_year));
CREATE TABLE memorials(id TEXT PRIMARY KEY,name TEXT NOT NULL,maiden_name TEXT,founder INTEGER NOT NULL DEFAULT 0,story TEXT NOT NULL DEFAULT '',created_by TEXT NOT NULL REFERENCES members(id));
CREATE TABLE family_relationships(id TEXT PRIMARY KEY,from_id TEXT NOT NULL,to_id TEXT NOT NULL,kind TEXT NOT NULL CHECK(kind IN ('parent','stepparent','siblings')),confirmed_by TEXT NOT NULL REFERENCES members(id));
CREATE INDEX media_owner ON media(owner_id);
CREATE INDEX dependent_guardian ON dependents(guardian_id);
CREATE INDEX notifications_owner ON notifications(recipient_id,created_at);
CREATE INDEX rate_expiry ON app_rate_limits(reset_at);
