import {householdHead,householdAdult} from './households.mjs';
import {UserError} from './family-service.mjs';
import {createRateStorage} from './auth.mjs';
import {familyEmail} from './email-template.mjs';
const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const hash=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const wrap=fn=>async c=>{try{return await fn(c)}catch(e){if(e instanceof UserError)throw e;if(e.status)throw new UserError(e.message,e.status);throw e}};
async function invitation(c,token){if(typeof token!=='string'||!/^[a-f0-9]{64}$/.test(token))throw new UserError('This invitation is unavailable',404);const actor=c.get('actor'),email=(await c.env.DB.prepare('SELECT email FROM user WHERE id=?').bind(actor.id).first())?.email?.toLowerCase(),row=await c.env.DB.prepare('SELECT i.*,h.name FROM household_email_invites i JOIN households h ON h.id=i.household_id WHERE i.token_hash=?').bind(await hash(token)).first();if(!row||row.expires_at<Date.now()||row.accepted_at||row.recipient_email!==email)throw new UserError('This invitation is unavailable or belongs to another email address',404);return row}
export function registerHouseholdInvites(app){
 app.post('/api/household-invites',wrap(async c=>{const actor=c.get('actor'),v=await c.req.json(),h=await householdHead(c.env.DB,actor,v.householdId),email=String(v.email||'').trim().toLowerCase();if(email.length>254||!/^\S+@[^\s@]+\.[^\s@]+$/.test(email))throw new UserError('Enter the recipient’s email address');const rate=await createRateStorage(c.env.DB).consume('household-invite:'+actor.id,{window:86400,max:10});if(!rate.allowed)throw new UserError('Please wait before creating more invitations',429);if(v.sendEmail===true&&!c.env.EMAIL)throw new UserError('Email delivery is not configured',503);
  const token=crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-',''),id=crypto.randomUUID(),expires=Date.now()+7*86400000,url=c.env.AUTH_ORIGIN+'/#/household-invite/'+token;
  await c.env.DB.prepare('INSERT INTO household_email_invites(id,household_id,sender_id,recipient_email,token_hash,expires_at) VALUES(?,?,?,?,?,?)').bind(id,h.id,actor.id,email,await hash(token),expires).run();
  if(v.sendEmail===true){try{await c.env.EMAIL.send({from:{email:'family@greenwhitefamily.com',name:'Green & White Family'},to:email,subject:'An invitation to '+h.name,text:`You’ve been invited to join ${h.name} in Green & White Family. Sign in with this email address and accept if you’d like to join: ${url}\nThis invitation expires in seven days. Joining requires an approved family account.`,html:familyEmail({title:'You’re invited.',preview:'An invitation to join '+h.name,body:`<p style="font-size:16px;line-height:1.6">A head of ${escape(h.name)} invited you to join their household. Sign in with this email address, then choose whether to accept.</p><a href="${escape(url)}" style="display:inline-block;padding:14px 22px;border-radius:24px;background:#245637;color:#fff;text-decoration:none">View invitation</a><p style="font-size:14px;line-height:1.6">This invitation expires in seven days. You’ll need an approved family account; the link does not grant access by itself.</p>`})})}catch{await c.env.DB.prepare('UPDATE household_email_invites SET expires_at=? WHERE id=?').bind(Date.now()-1,id).run();throw new UserError('We could not confirm email delivery. Please wait before trying again.',502)}}
  return c.json({ok:true,url,emailSent:v.sendEmail===true,expiresAt:expires});
 }));
 app.post('/api/household-invites/inspect',wrap(async c=>{const v=await c.req.json(),r=await invitation(c,v.token);return c.json({householdId:r.household_id,name:r.name,expiresAt:r.expires_at})}));
 app.post('/api/household-invites/accept',wrap(async c=>{const actor=c.get('actor'),v=await c.req.json(),r=await invitation(c,v.token);await householdAdult(c.env.DB,actor.id);if(await c.env.DB.prepare('SELECT member_id FROM household_members WHERE member_id=?').bind(actor.id).first())throw new UserError('You already belong to a household');await c.env.DB.batch([c.env.DB.prepare("INSERT INTO household_members(household_id,member_id,role) VALUES(?,?,'member')").bind(r.household_id,actor.id),c.env.DB.prepare('UPDATE household_email_invites SET accepted_by=?,accepted_at=CURRENT_TIMESTAMP WHERE id=? AND accepted_at IS NULL').bind(actor.id,r.id)]);return c.json({ok:true,householdId:r.household_id})}));
}
