import {adultOn} from './birthdays.mjs';
const heritageRoles={'ancestral-head':{kind:'ancestor',titles:['Ancestral head','Matriarch','Patriarch']},'torch-bearer':{kind:'member',titles:['Torch bearer','Matriarch','Patriarch']}};
const rows=r=>r.results||[];
const error=(message,status=400)=>Object.assign(new Error(message),{status});
const clean=(v,max=100)=>{if(typeof v!=='string'||!v.trim()||v.length>max)throw error('Check the household details');return v.trim()};
export async function householdAdult(db,id){const p=await db.prepare("SELECT p.birthday FROM profiles p JOIN members m ON m.id=p.member_id WHERE p.member_id=? AND m.status='active'").bind(id).first();if(!p||!adultOn(p.birthday))throw error('Registered adults can join a household. Children stay in their guardian’s private records.');}
export async function householdHead(db,actor,id){const h=await db.prepare("SELECT h.*,m.role FROM households h JOIN household_members m ON m.household_id=h.id JOIN members a ON a.id=m.member_id AND a.status='active' WHERE h.id=? AND m.member_id=?").bind(id,actor.id).first();if(!h||h.role!=='head')throw error('Only a head of this household can do that',403);return h}
export async function householdState(db,actor){
 const hs=rows(await db.prepare('SELECT * FROM households ORDER BY name').all());
 const ms=rows(await db.prepare("SELECT hm.* FROM household_members hm JOIN members m ON m.id=hm.member_id WHERE m.status='active'").all());
 const heritage=rows(await db.prepare("SELECT hh.* FROM household_heritage hh WHERE (hh.person_kind='ancestor' AND EXISTS(SELECT 1 FROM memorials m WHERE m.id=hh.person_id)) OR (hh.person_kind='member' AND EXISTS(SELECT 1 FROM members m WHERE m.id=hh.person_id AND m.status='active')) ORDER BY hh.updated_at,hh.id").all());
 const rs=rows(await db.prepare("SELECT * FROM household_requests WHERE status='pending' AND (requester_id=? OR recipient_id=? OR household_id IN (SELECT household_id FROM household_members WHERE member_id=? AND role='head')) ORDER BY created_at").bind(actor.id,actor.id,actor.id).all());
 return {
  householdId:ms.find(m=>m.member_id===actor.id)?.household_id||null,
  households:hs.map(h=>({id:h.id,name:h.name,color:h.color_mode==='custom'?h.color:null,colorMode:h.color_mode,photo:h.photo_url,founderId:h.founder_id,
   memberIds:ms.filter(m=>m.household_id===h.id).map(m=>m.member_id),headIds:ms.filter(m=>m.household_id===h.id&&m.role==='head').map(m=>m.member_id),
   canManage:ms.some(m=>m.household_id===h.id&&m.member_id===actor.id&&m.role==='head'),
   heritage:heritage.filter(x=>x.household_id===h.id).map(x=>({id:x.id,personId:x.person_id,personKind:x.person_kind,role:x.role,title:x.title}))})),
  householdRequests:rs.map(r=>({id:r.id,householdId:r.household_id,requesterId:r.requester_id,recipientId:r.recipient_id,kind:r.kind,createdAt:r.created_at}))
 }
}
export async function householdCommand(db,actor,input,q,audit){const id=input.householdId;switch(input.type){
case 'CREATE_HOUSEHOLD':{await householdAdult(db,actor.id);if(await db.prepare('SELECT member_id FROM household_members WHERE member_id=?').bind(actor.id).first())throw error('You already belong to a household');const hid=crypto.randomUUID();q('INSERT INTO households(id,name,founder_id) VALUES(?,?,?)',hid,clean(input.name),actor.id);q("INSERT INTO household_members(household_id,member_id,role) VALUES(?,?,'head')",hid,actor.id);audit('household-create',hid);return{id:hid};}
case 'SAVE_HOUSEHOLD':{const h=await householdHead(db,actor,id),name=clean(input.name),colorMode=input.colorMode??(input.color?'custom':h.color_mode),color=input.color||h.color,photo=input.photo||null;if(!['custom','inherit'].includes(colorMode)||!/^#[a-f0-9]{6}$/i.test(color))throw error('Choose a household color or use personal colors');if(photo&&photo!==h.photo_url){const mid=/^\/api\/media\/([a-zA-Z0-9-]+)$/.exec(photo)?.[1],m=mid&&await db.prepare('SELECT owner_id,mime_type FROM media WHERE id=? AND deleted_at IS NULL').bind(mid).first();if(!m||m.owner_id!==actor.id||!/^image\/(png|jpeg|webp|gif)$/.test(m.mime_type))throw error('Upload a household photo from your account');}q('UPDATE households SET name=?,color=?,photo_url=?,color_mode=? WHERE id=?',name,color,photo,colorMode,id);audit('household-edit',id);return{id};}
case 'SAVE_HOUSEHOLD_HERITAGE':{
 await householdHead(db,actor,id);const entry=input.entry||{},role=Object.hasOwn(heritageRoles,entry.role)?heritageRoles[entry.role]:null,personId=clean(entry.personId,100);
 if(!role||!role.titles.includes(entry.title))throw error('Choose an ancestral head or torch bearer title');
 if(role.kind==='ancestor'){
  if(!await db.prepare('SELECT id FROM memorials WHERE id=?').bind(personId).first())throw error('Choose an ancestor from the family tree');
 }else await householdAdult(db,personId);
 const existing=await db.prepare('SELECT id FROM household_heritage WHERE household_id=? AND person_id=? AND role=?').bind(id,personId,entry.role).first(),heritageId=existing?.id||crypto.randomUUID();
 q('INSERT INTO household_heritage(id,household_id,person_id,person_kind,role,title,updated_by) VALUES(?,?,?,?,?,?,?) ON CONFLICT(household_id,person_id,role) DO UPDATE SET title=excluded.title,updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP',heritageId,id,personId,role.kind,entry.role,entry.title,actor.id);
 audit('household-heritage-saved',heritageId);return{id:heritageId};
}
case 'REMOVE_HOUSEHOLD_HERITAGE':{
 await householdHead(db,actor,id);const heritageId=clean(input.heritageId,100);
 if(!await db.prepare('SELECT id FROM household_heritage WHERE id=? AND household_id=?').bind(heritageId,id).first())throw error('Heritage entry not found',404);
 q('DELETE FROM household_heritage WHERE id=? AND household_id=?',heritageId,id);audit('household-heritage-removed',heritageId);return{id:heritageId};
}
case 'REQUEST_HOUSEHOLD_JOIN':case 'INVITE_HOUSEHOLD_MEMBER':{const invite=input.type==='INVITE_HOUSEHOLD_MEMBER',target=invite?clean(input.memberId,80):actor.id,h=invite?await householdHead(db,actor,id):await db.prepare('SELECT * FROM households WHERE id=?').bind(id).first();if(!h)throw error('Household not found',404);await householdAdult(db,target);if(await db.prepare('SELECT member_id FROM household_members WHERE member_id=?').bind(target).first())throw error('This person already belongs to a household');if(await db.prepare("SELECT id FROM household_requests WHERE household_id=? AND status='pending' AND ((kind='join' AND requester_id=?) OR (kind='invite' AND recipient_id=?))").bind(id,target,target).first())throw error('A request is already waiting');const rid=crypto.randomUUID();q('INSERT INTO household_requests(id,household_id,requester_id,recipient_id,kind) VALUES(?,?,?,?,?)',rid,id,actor.id,invite?target:h.founder_id,invite?'invite':'join');audit('household-request',rid);return{id:rid};}
case 'REQUEST_HOUSEHOLD_HEAD':{const h=await householdHead(db,actor,id),target=clean(input.memberId,80);await householdAdult(db,target);if(!await db.prepare('SELECT member_id FROM household_members WHERE household_id=? AND member_id=?').bind(id,target).first())throw error('Choose a member of this household');if(h.founder_id===actor.id){q("UPDATE household_members SET role='head' WHERE household_id=? AND member_id=?",id,target);audit('household-head-approved',target);return{id:target};}const rid=crypto.randomUUID();q("INSERT INTO household_requests(id,household_id,requester_id,recipient_id,kind) VALUES(?,?,?,?,'head')",rid,id,target,h.founder_id);audit('household-head-request',rid);return{id:rid};}
case 'RESOLVE_HOUSEHOLD_REQUEST':{const r=await db.prepare("SELECT r.*,h.founder_id FROM household_requests r JOIN households h ON h.id=r.household_id WHERE r.id=? AND r.status='pending'").bind(input.id).first();if(!r)throw error('This request is no longer waiting',404);if(r.kind==='join')await householdHead(db,actor,r.household_id);else if(r.recipient_id!==actor.id)throw error('This request belongs to someone else',403);if(r.kind==='head'&&r.founder_id!==actor.id)throw error('The first head must approve additional heads',403);if(input.accept===true){const target=r.kind==='invite'?r.recipient_id:r.requester_id;await householdAdult(db,target);if(r.kind==='head')q("UPDATE household_members SET role='head' WHERE household_id=? AND member_id=?",r.household_id,target);else{if(await db.prepare('SELECT member_id FROM household_members WHERE member_id=?').bind(target).first())throw error('This person already belongs to a household');q("INSERT INTO household_members(household_id,member_id,role) VALUES(?,?,'member')",r.household_id,target);}}q('UPDATE household_requests SET status=?,resolved_at=CURRENT_TIMESTAMP WHERE id=?',input.accept===true?'accepted':'declined',r.id);audit('household-request-resolved',r.id);return{id:r.id};}
case 'REMOVE_HOUSEHOLD_MEMBER':case 'LEAVE_HOUSEHOLD':{const target=input.type==='LEAVE_HOUSEHOLD'?actor.id:clean(input.memberId,80),h=await db.prepare('SELECT * FROM households WHERE id=?').bind(id).first();if(!h)throw error('Household not found',404);if(target!==actor.id)await householdHead(db,actor,id);const m=await db.prepare('SELECT role FROM household_members WHERE household_id=? AND member_id=?').bind(id,target).first();if(!m)throw error('Household member not found',404);if(h.founder_id===target)throw error('The founding head must keep this household managed. Contact a family organizer before leaving.');if(m.role==='head'&&actor.id!==h.founder_id&&target!==actor.id)throw error('Only the first head can remove another head',403);q('DELETE FROM household_members WHERE household_id=? AND member_id=?',id,target);q("UPDATE household_requests SET status='cancelled',resolved_at=CURRENT_TIMESTAMP WHERE household_id=? AND status='pending' AND (requester_id=? OR recipient_id=?)",id,target,target);q('UPDATE household_email_invites SET expires_at=? WHERE household_id=? AND sender_id=? AND accepted_at IS NULL',Date.now()-1,id,target);audit('household-member-removed',target);return{id:target};}
default:return null;
}}
