import {deriveAccountPlan,planningReminderAllowed} from '../../src/planning-model.js';
// Membership labels describe belonging; explicit capabilities govern privileged actions.
export const MEMBER_GROUPS=Object.freeze(['family','loved_ones']);
export const NOTIFICATION_SCOPES=Object.freeze(['all','family','loved_ones','selected','leaders','off']);
export function isMember(actor){return !!actor?.id&&actor.status==='active'&&MEMBER_GROUPS.includes(actor.group)}
export function can(actor,action,resource={}){if(!isMember(actor))return false;const roles=new Set(actor.roles||[]),admin=roles.has('admin');switch(action){case 'read_family':case 'comment':case 'react':case 'claim_shirts':return true;case 'post':return admin||roles.has('moderator')||actor.canPost===true;case 'manage_reunion':return admin||roles.has('planner');case 'moderate':return admin||roles.has('moderator');case 'confirm_fees':case 'set_payment_destination':return roles.has('treasurer');case 'manage_members':return admin;case 'edit_pages':case 'leader_tools':return admin||actor.isLeader===true;case 'edit_profile':return resource.memberId===actor.id||admin;case 'edit_group':return admin||(resource.managerIds||[]).includes(actor.id);case 'read_conversation':return (resource.participantIds||[]).includes(actor.id);default:return false}}
export function shouldNotify(recipient,sender,preference){if(!isMember(recipient)||!isMember(sender)||recipient.id===sender.id)return false;switch(preference?.scope){case 'all':return true;case 'family':return sender.group==='family';case 'loved_ones':return sender.group==='loved_ones';case 'leaders':return sender.isLeader===true;case 'selected':return (preference.selectedMemberIds||[]).includes(sender.id);default:return false}}
export function suggestFamilyName(members,override=''){const edited=String(override).trim();if(edited)return edited.slice(0,120);const counts=new Map();for(const member of members){const name=String(member.familyName||'').normalize('NFC').trim();if(!name)continue;const key=name.toLocaleLowerCase('en-US'),entry=counts.get(key)||{name,count:0};entry.count++;counts.set(key,entry)}const names=[...counts.values()].sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,'en',{sensitivity:'base'}));if(!names.length)return 'Our family';// Two recurring surnames qualify when each appears at least twice and the second is at least half as common.
const chosen=names.length>1&&names[1].count>=2&&names[1].count>=names[0].count/2?names.slice(0,2):names.slice(0,1);return chosen.map(x=>x.name).sort((a,b)=>a.localeCompare(b,'en',{sensitivity:'base'})).join('-')+' family'}
export function validateShirtSelection(lines){if(!Array.isArray(lines)||!lines.length||lines.length>30)throw new Error('Choose at least one size');const seen=new Set();return lines.map(row=>{if(!/^[a-zA-Z0-9_-]{1,80}$/.test(row.productId)||!['YXS','YS','YM','YL','YXL','XS','S','M','L','XL','2XL','3XL','4XL','5XL'].includes(row.size)||!Number.isInteger(row.quantity)||row.quantity<1||row.quantity>25)throw new Error('Invalid shirt selection');const key=row.productId+':'+row.size;if(seen.has(key))throw new Error('Duplicate product size');seen.add(key);return {productId:row.productId,size:row.size,quantity:row.quantity}})}
export function claimShirts(actor,lines,feeStatus,rsvp=null){if(!can(actor,'claim_shirts'))throw new Error('Membership required');return {memberId:actor.id,lines:validateShirtSelection(lines),status:'claimed',feeReminder:planningReminderAllowed(deriveAccountPlan({memberId:actor.id,feeStatus,rsvp}),'fees',{authorized:true})}}
