import React,{useEffect} from 'react';
import {useApp} from './ui-core.jsx';
import notices from './about-notices.json';
import {version as releaseVersion} from '../package.json';
import './about.css';
export function AboutPage(){
 const build=document.querySelector('meta[name="gw-build"]')?.content||'Unavailable';
 return <section className="stack about-page"><div className="stack about-summary"><p>A family space for stories, gatherings and the people who connect them.</p><dl className="about-version"><div><dt>App version</dt><dd>{document.querySelector('meta[name="gw-release"]')?.content||releaseVersion}</dd></div><div><dt>Installed build</dt><dd><code>{build}</code></dd></div></dl><p className="about-credit">© 2026 · a <a href="https://loew.fi" target="_blank" rel="noreferrer">loew.fi</a> experience by Lauren Olivia</p></div><details className="about-open-source"><summary>Open-source notices</summary><div className="stack about-license-content"><section><h3>Typography</h3><p>Interface and heading fonts are served through Google Fonts.</p>{notices.fonts.map(font=><details className="about-notice" key={font.name}><summary><strong>{font.name}</strong><span>{font.license}</span></summary><pre>{font.notice}</pre><a href={font.source} target="_blank" rel="noreferrer">Font license source</a></details>)}</section><section><h3>Software</h3><p>Libraries used by the app and its backend, with the versions and license notices from the installed packages.</p>{notices.packages.map(pkg=><details className="about-notice" key={pkg.name+'@'+pkg.version}><summary><strong>{pkg.name} <span>{pkg.version}</span></strong><span>{typeof pkg.license==='string'?pkg.license:JSON.stringify(pkg.license)}</span></summary>{pkg.notice?<pre>{pkg.notice}</pre>:<p className="field-help">The installed package declares this license but does not include a separate license notice.</p>}</details>)}</section><section><h3>Artwork and preview photography</h3><p>The family tree artwork was supplied for Green &amp; White.</p><p>Preview photography illustrates sample content. It does not identify actual family members.</p><p><a href="https://www.pexels.com/photo/a-family-taking-a-groupie-photo-5082952/" target="_blank" rel="noreferrer">Vanessa Loring</a> and <a href="https://www.pexels.com/photo/three-women-smiling-and-sitting-side-by-side-7358347/" target="_blank" rel="noreferrer">KATRIN BOLOVTSOVA</a>, via Pexels.</p><a href="https://www.pexels.com/license/" target="_blank" rel="noreferrer">Pexels license</a></section></div></details></section>;
}
// Preserve old bookmarks while presenting About through the existing modal.
export function AboutRoute(){const {openSheet,replaceRoute}=useApp();useEffect(()=>{replaceRoute({type:'you'});openSheet({type:'about'})},[]);return null}
