import React,{useEffect,useRef,useState} from 'react';
import {MeshGradient} from '@paper-design/shaders-react';
export const backgroundColors=[['Ivory','#f4ecda'],['Cream','#e8d8b8'],['Sand','#ceb18b'],['Taupe','#a18c7d'],['Warm gray','#777169'],['Cocoa','#715042'],['Espresso','#382b27'],['Red','#a83540'],['Orange','#c2652b'],['Yellow','#e8bf42'],['Green','#286849'],['Blue','#285b96'],['Indigo','#4d458d'],['Violet','#874f91'],['Rose','#ad647a'],['Forest','#143d2b']];
export const backgroundDesigns=[['solid','Solid'],['gradient','Gradient'],['mesh','Mesh flow'],['dots','Dots'],['stripes','Stripes'],['roots','Roots']];
const legacy={forest:['solid','#143d2b'],cream:['solid','#e8d8b8'],sage:['gradient','#6a9274'],sunset:['gradient','#ad647a'],pattern:['dots','#286849'],media:['solid','#143d2b']};
export function parseBackground(value){if(legacy[value])return legacy[value];const [kind,color]=(value||'').split('|');return [backgroundDesigns.some(([k])=>k===kind)?kind:'solid',/^#[0-9a-f]{6}$/i.test(color||'')?color:'#143d2b'];}
const blend=(hex,amount)=>{const n=parseInt(hex.slice(1),16);return '#'+[n>>16,(n>>8)&255,n&255].map(v=>Math.round(amount>0?v+(255-v)*amount:v*(1+amount))).map(v=>v.toString(16).padStart(2,'0')).join('')};
export function posterStyle(value){const [kind,color]=parseBackground(value),n=parseInt(color.slice(1),16),l=((n>>16)*.2126+((n>>8)&255)*.7152+(n&255)*.0722)/255;return {backgroundColor:color,'--poster-tree':"url('tree-artwork.png')",'--poster-color':color,'--poster-light':blend(color,.23),'--poster-dark':blend(color,-.22),'--poster-text':l>.58?'#172b21':'#fffaf0'};}
export function BackgroundEffect({value}){const [kind,color]=parseBackground(value),ref=useRef(null),[moving,setMoving]=useState(false);useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');let visible=true;const update=()=>setMoving(visible&&!media.matches&&!document.hidden);const observer=new IntersectionObserver(entries=>{visible=entries[0]?.isIntersecting;update()});if(ref.current)observer.observe(ref.current);media.addEventListener('change',update);document.addEventListener('visibilitychange',update);update();return()=>{observer.disconnect();media.removeEventListener('change',update);document.removeEventListener('visibilitychange',update)}},[]);return <div ref={ref} aria-hidden="true" className={'poster-art poster-art-'+kind} style={posterStyle(value)}>{kind==='mesh'&&<MeshGradient style={{width:'100%',height:'100%'}} colors={[color,blend(color,.23),blend(color,-.22),blend(color,.12)]} distortion={.65} swirl={.25} grainMixer={0} grainOverlay={0} speed={moving ? 0.16 : 0}/>}</div>}
export function BackgroundPicker({value,onChange}){const [kind,color]=parseBackground(value);return <div className="background-picker"><div className="background-designs" role="group" aria-label="Background design">{backgroundDesigns.map(([k,label])=><button key={k} type="button" aria-pressed={kind===k} onClick={()=>onChange(k+'|'+color)}>{label}</button>)}</div><div className="background-swatches" role="group" aria-label="Background colors">{backgroundColors.map(([name,c])=><button key={c} type="button" style={{background:c}} aria-label={name+' background'} aria-pressed={color.toLowerCase()===c} title={name} onClick={()=>onChange(kind+'|'+c)}>{color.toLowerCase()===c?'✓':''}</button>)}</div><label className="background-custom">Custom color<input type="color" value={color} onChange={e=>onChange(kind+'|'+e.target.value)}/></label></div>}

export function BackgroundMedia({media}){const [reduced,setReduced]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches);useEffect(()=>{const query=matchMedia('(prefers-reduced-motion: reduce)'),change=()=>setReduced(query.matches);query.addEventListener('change',change);return()=>query.removeEventListener('change',change)},[]);return media?.type.startsWith('video/')?<video key={String(reduced)+media.url} className="poster-media" src={media.url} muted loop autoPlay={!reduced} controls={reduced} playsInline/>:<img className="poster-media" src={media?.url} alt=""/>}
