import React,{useEffect,useRef,useState} from 'react';
import {api} from './live-adapter.js';
import {Button,Glyph,useApp} from './ui-core.jsx';
import {EditableText} from './page-content.jsx';
import {pendingFamilyInvitation,clearFamilyInvitation} from './family-invitation-model.js';
import './family-invitations.css';
export function rememberFamilyInvitation(){let storage;try{storage=sessionStorage}catch{}return pendingFamilyInvitation(location.hash,storage)}
export function FamilyInvitationEditor(){
 const {state,data,dispatch}=useApp(),preview=state.mode==='preview',scope=state.mode+':'+state.selfId,scopeRef=useRef(scope),lock=useRef(false),[email,setEmail]=useState(''),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false);
 scopeRef.current=scope;useEffect(()=>{setResult(null);setEmail('');setError('');setCopied(false);setBusy(false)},[scope]);useEffect(()=>()=>{scopeRef.current=null},[]);
 async function create(sendEmail){if(lock.current)return;lock.current=true;setBusy(true);setError('');setResult(null);setCopied(false);const expectedScope=scope;
  try{if(preview){await dispatch({type:'SAVE_INVITE_DRAFT',recipient:email.trim()||'Sample family invitation',groupId:null});if(scopeRef.current===expectedScope)setResult({preview:true,emailSent:false})}
   else{const value=await api('/api/family-invitations',{method:'POST',body:JSON.stringify({email,sendEmail,expectedAccountId:state.selfId})});if(scopeRef.current===expectedScope)setResult(value)}}catch(e){if(scopeRef.current===expectedScope)setError(e.message)}finally{lock.current=false;if(scopeRef.current===expectedScope)setBusy(false)}
 }
 const enabled=preview||data.config?.familyInvitations;
 return <div className="stack family-invitation"><p>{preview?'Try an invitation with sample data. Nothing is sent and no access is granted.':'Create an invitation attributed to your account. The recipient signs in and an organizer still approves membership.'}</p><label>{preview?'Sample recipient email':'Recipient email'}<input type="email" autoComplete="off" value={email} disabled={busy||!enabled} onChange={e=>setEmail(e.target.value)}/></label><div className="card-actions"><Button disabled={busy||!email.trim()||!enabled||!preview&&!data.config?.familyInvitationEmail} onClick={()=>create(true)}>{preview?'Try email invitation':'Send email invitation'}</Button></div>{!enabled&&<p className="note">Family invitations are prepared but have not been enabled.</p>}{result&&(result.preview?<p role="status">Sample invitation saved. No email was sent.</p>:<div className="stack"><p role="status">{result.emailSent?'Invitation email sent.':'Invitation link created.'} It expires {new Date(result.expiresAt).toLocaleDateString()}.</p><label>Invitation link<input readOnly value={result.url} onFocus={e=>e.target.select()}/></label><Button secondary onClick={async()=>{try{await navigator.clipboard.writeText(result.url);setCopied(true)}catch{setError('Copy the invitation link from the field above.')}}}>{copied?'Copied':'Copy invitation link'}</Button></div>)}{error&&<p role="alert">{error}</p>}{preview&&<><p className="small muted">{state.inviteDrafts?.length||0} sample invitation drafts</p><Button secondary disabled={busy} onClick={()=>{dispatch({type:'RESET_INVITE_DRAFTS'});setResult(null);setEmail('');setError('')}}>Reset invitation test data</Button><details><summary>Preview read-only welcome</summary><ProvisionalContent feed={{posts:[{id:'sample',author:'Sample family member',text:'A fictional family update for testing.',photos:[]}],memories:[]}}/></details></>}</div>;
}
export function useFamilyInviteWelcome(token){
 const [result,setResult]=useState(null);
 useEffect(()=>{const controller=new AbortController();setResult(null);if(token)api('/api/family-invitations/welcome',{method:'POST',body:JSON.stringify({token}),signal:controller.signal}).then(value=>{if(!controller.signal.aborted)setResult({token,...value})}).catch(error=>{if(!controller.signal.aborted)setResult({token,error:error.message})});return()=>controller.abort()},[token]);
 return result?.token===token?result:null;
}
export function FamilyInvitationClaim(){
 const {data,route,replaceRoute}=useApp(),account=data.session?.user?.id;
 const [token,setToken]=useState(()=>rememberFamilyInvitation()),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const welcome=useFamilyInviteWelcome(data.preview?null:token),active=data.session?.status==='active',scope=(data.preview?'preview':'live')+':'+account+':'+token,scopeRef=useRef(scope),identity=useRef(account),lock=useRef(false);
 identity.current=account;scopeRef.current=scope;useEffect(()=>{setToken(rememberFamilyInvitation());setMessage('');setBusy(false)},[account,route?.id,data.preview]);useEffect(()=>()=>{scopeRef.current=null},[]);
 const leave=()=>{clearFamilyInvitation(sessionStorage);setToken(null);replaceRoute({type:'home'})};
 async function accept(){if(lock.current)return;lock.current=true;setBusy(true);setMessage('');const expected=scope;try{await api('/api/family-invitations/accept',{method:'POST',body:JSON.stringify({token,expectedAccountId:account})});if(scopeRef.current!==expected)return;clearFamilyInvitation(sessionStorage);setToken(null);await data.refresh();if(identity.current===account)replaceRoute({type:'home'})}catch(error){if(scopeRef.current===expected)setMessage(error.message)}finally{lock.current=false;if(scopeRef.current===expected)setBusy(false)}}
 if(data.preview)return null;
 // Pending entry without an invitation continues its ordinary approval screen.
 if(!active&&!token)return null;
 return <section className={active?'onboard card family-invitation-welcome':'stack family-invitation-welcome'}>{active&&<div className="welcome-mark"><img src="tree-artwork.png" alt="Green & White oak"/><span className="wordmark"><span className="wordmark-top"><span className="wordmark-green">green</span> <span className="wordmark-amp">&amp;</span> <span className="wordmark-white">white</span></span><span className="wordmark-bottom">family</span></span></div>}<h2>{welcome?.inviterName?welcome.inviterName+' invited you to join the fun.':'You’re invited.'}</h2><p>{welcome?.error||(!token?'This invitation has already been handled.':active?'You’re already part of the family. Head home to join in.':'Join your family for stories, plans, and new memories.')}</p>{!active&&token&&!welcome?.error&&<Button disabled={busy||!welcome||!data.config?.familyInvitations||!account} onClick={accept}>{busy?'Joining…':'Accept invitation'}</Button>}<Button secondary={!active} disabled={busy} onClick={leave}>{active?'Go to Home':'Back to GW'}</Button>{message&&<p role="alert">{message}</p>}</section>;
}
export function InvitationCard({page}){
 const {state,data,go}=useApp();if(state.mode!=='preview'&&!data.config?.familyInvitations)return null;
 return <section className="card stack invitation-sidebar-card"><EditableText page={page} field="inviteTitle" as="h2">Bring your people.</EditableText><EditableText page={page} field="inviteBody" as="p">Share your invitation link and make room for more family memories.</EditableText><Button secondary onClick={()=>go({type:'invitations'})}>Invitations</Button></section>;
}
function ProvisionalContent({feed}){return <section className="stack provisional-family"><header><h2>A look at your family space</h2><p className="note">Read-only access. Posting, reactions, messages, and other actions become available after membership approval.</p></header>{feed.posts.map(post=><article className="card stack" key={post.id}><strong>{post.author}</strong><p className="provisional-copy">{post.text}</p>{post.photos.map(photo=><img key={photo.id} src={photo.url} alt={photo.alt} loading="lazy"/>)}</article>)}{feed.memories.map(memory=><figure className="card" key={memory.id}><img src={memory.photo.url} alt={memory.photo.alt} loading="lazy"/><figcaption>{memory.title}</figcaption></figure>)}{!feed.posts.length&&!feed.memories.length&&<p>No family updates are available yet.</p>}</section>}
export function ProvisionalFamilyView(){const [feed,setFeed]=useState(null),[error,setError]=useState('');useEffect(()=>{const controller=new AbortController();api('/api/provisional/feed',{signal:controller.signal}).then(value=>{if(!controller.signal.aborted)setFeed(value)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>controller.abort()},[]);return error?<p role="alert">{error}</p>:feed?<ProvisionalContent feed={feed}/>:<p role="status">Loading family updates…</p>}

export function InvitationsPage(){
 const {state,data,dispatch}=useApp(),preview=state.mode==='preview',scope=state.mode+':'+state.selfId,scopeRef=useRef(scope),lock=useRef(false),[url,setUrl]=useState(null),[loadingLink,setLoadingLink]=useState(!preview&&!!data.config?.familyInvitations),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false),[confirmReset,setConfirmReset]=useState(false);
 scopeRef.current=scope;
 useEffect(()=>{const controller=new AbortController();setUrl(null);setError('');setCopied(false);setConfirmReset(false);setBusy(false);setLoadingLink(!preview&&!!data.config?.familyInvitations);if(!preview&&data.config?.familyInvitations)api('/api/family-invitation-link',{signal:controller.signal}).then(value=>{if(!controller.signal.aborted)setUrl(value.url)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoadingLink(false)});return()=>{controller.abort();scopeRef.current=null}},[scope,data.config?.familyInvitations]);
 async function create(reset=false){if(lock.current)return;lock.current=true;setBusy(true);setError('');const expected=scope;try{if(preview){await dispatch({type:'SAVE_INVITE_DRAFT',recipient:'Reusable profile invitation · Sample only',groupId:null});if(scopeRef.current===expected)setUrl('Sample invitation — no real access is granted')}else{const result=await api('/api/family-invitation-link',{method:'POST',body:JSON.stringify({expectedAccountId:state.selfId,reset})});if(scopeRef.current===expected)setUrl(result.url)}if(scopeRef.current===expected){setCopied(false);setConfirmReset(false)}}catch(e){if(scopeRef.current===expected)setError(e.message)}finally{lock.current=false;if(scopeRef.current===expected)setBusy(false)}}
 return <section className="stack invitations-page"><h1>Invitations</h1><section className="card stack family-invitation"><h2>Your invitation link</h2><p>Share one link with as many people as you like. No email address is needed, and the link stays available until you replace it.</p><p className="field-help">People sign in and complete their profiles. An organizer still approves membership.</p>{preview&&<p className="note">This is an isolated sample invitation. Nothing is sent and no real invitation link is created.</p>}{url?<><label>{preview?'Sample invitation':'Your reusable invitation link'}<input readOnly value={url} onFocus={e=>e.target.select()}/></label><div className="card-actions"><Button secondary disabled={busy||preview} onClick={async()=>{try{await navigator.clipboard.writeText(url);setCopied(true)}catch{setError('Select and copy the link from the field above.')}}}><Glyph name="copy"/>{copied?'Copied':'Copy link'}</Button><Button secondary disabled={busy} onClick={()=>setConfirmReset(true)}><Glyph name="history"/>Replace link</Button></div>{confirmReset&&<div className="note stack" role="alert"><p>Replace this link? The old link will stop accepting new invitations. Recorded invitations stay intact.</p><div className="card-actions"><Button disabled={busy} onClick={()=>create(true)}>Replace invitation link</Button><Button secondary disabled={busy} onClick={()=>setConfirmReset(false)}>Keep current link</Button></div></div>}</>:<Button disabled={busy||loadingLink||!preview&&!data.config?.familyInvitations} onClick={()=>create(false)}><Glyph name="link"/>{loadingLink?'Loading invitation link…':busy?'Creating…':preview?'Try a sample link':'Create your invitation link'}</Button>}{error&&<p role="alert">{error}</p>}</section><section className="card stack"><h2>Invite someone by email</h2><FamilyInvitationEditor/></section></section>;
}
