import React,{useEffect,useRef,useState} from 'react';
import {api} from './live-adapter.js';
import {Button,useApp} from './ui-core.jsx';
import {pendingFamilyInvitation,clearFamilyInvitation} from './family-invitation-model.js';
import './family-invitations.css';
export function rememberFamilyInvitation(){let storage;try{storage=sessionStorage}catch{}return pendingFamilyInvitation(location.hash,storage)}
export function FamilyInvitationEditor(){
 const {state,data,dispatch}=useApp(),preview=state.mode==='preview',scope=state.mode+':'+state.selfId,scopeRef=useRef(scope),lock=useRef(false),[email,setEmail]=useState(''),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false);
 scopeRef.current=scope;useEffect(()=>{setResult(null);setEmail('');setError('');setCopied(false);setBusy(false)},[scope]);useEffect(()=>()=>{scopeRef.current=null},[]);
 async function create(sendEmail){if(lock.current)return;lock.current=true;setBusy(true);setError('');setResult(null);setCopied(false);const expectedScope=scope;
  try{if(preview){await dispatch({type:'SAVE_INVITE_DRAFT',recipient:email.trim()||'Sample family invitation',groupId:null});if(scopeRef.current===expectedScope)setResult({preview:true,emailSent:false})}
   else{const value=await api('/api/family-invitations',{method:'POST',body:JSON.stringify({email,sendEmail,expectedAccountId:state.selfId})});if(scopeRef.current===expectedScope)setResult(value)}}catch(e){if(scopeRef.current===expectedScope)setError(e.message)}finally{lock.current=false;if(scopeRef.current===expectedScope)setBusy(false)}
 }
 const enabled=preview||data.config?.familyInvitations;
 return <div className="stack family-invitation"><p>{preview?'Try an invitation with sample data. Nothing is sent and no access is granted.':'Create an invitation attributed to your account. The recipient signs in and an organizer still approves membership.'}</p><label>{preview?'Sample recipient email (optional)':'Recipient email (optional for a link)'}<input type="email" autoComplete="off" value={email} disabled={busy||!enabled} onChange={e=>setEmail(e.target.value)}/></label><div className="card-actions"><Button disabled={busy||!enabled} onClick={()=>create(false)}>{preview?'Save sample invitation':'Create invitation link'}</Button><Button secondary disabled={busy||!email.trim()||!enabled||!preview&&!data.config?.familyInvitationEmail} onClick={()=>create(true)}>{preview?'Try email invitation':'Send email invitation'}</Button></div>{!enabled&&<p className="note">Family invitations are prepared but have not been enabled.</p>}{result&&(result.preview?<p role="status">Sample invitation saved. No email was sent.</p>:<div className="stack"><p role="status">{result.emailSent?'Invitation email sent.':'Invitation link created.'} It expires {new Date(result.expiresAt).toLocaleDateString()}.</p><label>Invitation link<input readOnly value={result.url} onFocus={e=>e.target.select()}/></label><Button secondary onClick={async()=>{try{await navigator.clipboard.writeText(result.url);setCopied(true)}catch{setError('Copy the invitation link from the field above.')}}}>{copied?'Copied':'Copy invitation link'}</Button></div>)}{error&&<p role="alert">{error}</p>}{preview&&<><p className="small muted">{state.inviteDrafts?.length||0} sample invitation drafts</p><Button secondary disabled={busy} onClick={()=>{dispatch({type:'RESET_INVITE_DRAFTS'});setResult(null);setEmail('');setError('')}}>Reset invitation test data</Button><details><summary>Preview read-only welcome</summary><ProvisionalContent feed={{posts:[{id:'sample',author:'Sample family member',text:'A fictional family update for testing.',photos:[]}],memories:[]}}/></details></>}</div>;
}
export function FamilyInvitationClaim(){
 const {data,route,replaceRoute}=useApp(),account=data.session?.user?.id,scope=(data.preview?'preview':'live')+':'+(data.session?.user?.id||'')+':'+(route?.id||''),scopeRef=useRef(scope),lock=useRef(false),[token,setToken]=useState(()=>rememberFamilyInvitation()),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 scopeRef.current=scope;useEffect(()=>{setToken(rememberFamilyInvitation());setBusy(false)},[scope]);useEffect(()=>{setMessage('')},[account,data.preview]);useEffect(()=>()=>{scopeRef.current=null},[]);
 if(data.preview)return null;if(!token)return message?<p role="status">{message}</p>:null;
 async function accept(){if(lock.current)return;lock.current=true;setBusy(true);setMessage('');const expectedScope=scope;try{await api('/api/family-invitations/accept',{method:'POST',body:JSON.stringify({token,expectedAccountId:account})});if(scopeRef.current!==expectedScope)return;clearFamilyInvitation(sessionStorage);setToken(null);setMessage('Invitation recorded. Membership approval remains with your family organizer.');if(route?.type==='family-invite')replaceRoute({type:'family-invite'});await data.refresh()}catch(e){if(scopeRef.current===expectedScope)setMessage(e.message)}finally{lock.current=false;if(scopeRef.current===expectedScope)setBusy(false)}}
 return <section className="stack card"><h2>Your family invitation</h2><p>Accept to record who invited you. This does not change your membership or permissions.</p><Button disabled={busy||!data.config?.familyInvitations||!account} onClick={accept}>{busy?'Recording…':'Accept invitation'}</Button><Button secondary disabled={busy} onClick={()=>{clearFamilyInvitation(sessionStorage);setToken(null);if(route?.type==='family-invite')replaceRoute({type:'family-invite'})}}>Dismiss invitation</Button>{!data.config?.familyInvitations&&<p>Invitations are not enabled yet.</p>}{message&&<p role="status">{message}</p>}</section>;
}
function ProvisionalContent({feed}){return <section className="stack provisional-family"><header><h2>A look at your family space</h2><p className="note">Read-only access. Posting, reactions, messages, and other actions become available after membership approval.</p></header>{feed.posts.map(post=><article className="card stack" key={post.id}><strong>{post.author}</strong><p className="provisional-copy">{post.text}</p>{post.photos.map(photo=><img key={photo.id} src={photo.url} alt={photo.alt} loading="lazy"/>)}</article>)}{feed.memories.map(memory=><figure className="card" key={memory.id}><img src={memory.photo.url} alt={memory.photo.alt} loading="lazy"/><figcaption>{memory.title}</figcaption></figure>)}{!feed.posts.length&&!feed.memories.length&&<p>No family updates are available yet.</p>}</section>}
export function ProvisionalFamilyView(){const [feed,setFeed]=useState(null),[error,setError]=useState('');useEffect(()=>{const controller=new AbortController();api('/api/provisional/feed',{signal:controller.signal}).then(value=>{if(!controller.signal.aborted)setFeed(value)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>controller.abort()},[]);return error?<p role="alert">{error}</p>:feed?<ProvisionalContent feed={feed}/>:<p role="status">Loading family updates…</p>}
