import {canCreateMemorial} from './memorials.jsx';
export {MemorialProfile as Memorial} from './memorials.jsx';
import {familyBranch} from './family-branch-model.js';
import {CardContentLayout} from './card-content-layout.jsx';
import {SharedPagePanels} from './page-panels.jsx';
import {EditableText,EditableMedia} from './page-content.jsx';
import {ChoiceControl} from './choice-control.jsx';
import {ProfileStyleEditor} from './profiles.jsx';
import {readPreviewFile} from './uploads.js';
import React,{useRef,useState} from 'react';
import {Avatar,Button,Control,Glyph,useApp,useSheetForm} from './ui-core.jsx';
import {validateMember,localDate,birthdayEntries} from './member-model.js';
export function MemberForm({signup=false,child=false,id}){
 const {state,dispatch,openSheet,go}=useApp(),existing=state.members.find(m=>m.id===id);
 const [values,setValues]=useState(existing||{name:'',birthday:'',gender:'',email:'',circle:'family',profileColor:'#4f996c',photo:null}),[error,setError]=useState(''),[step,setStep]=useState(1),[saving,setSaving]=useState(false),[photoBusy,setPhotoBusy]=useState(false);
 const initialValues=useRef(JSON.stringify(values)),saveLock=useRef(false),formId=useSheetForm({label:existing?'Save child details':null,busy:saving||photoBusy,disabled:saving||photoBusy,dirty:JSON.stringify(values)!==initialValues.current});
 const set=(key,value)=>setValues(v=>({...v,[key]:value}));
 async function submit(e){e.preventDefault();if(saveLock.current||photoBusy)return;const error=validateMember(values,{signup,child});if(error){setError(error);return}if(signup&&step===1){setError('');setStep(2);return}saveLock.current=true;setSaving(true);try{if(!await dispatch({type:existing?'UPDATE_DEPENDENT':'ADD_PERSON',member:values,signup,child}))return;if(signup)await dispatch({type:'ONBOARD',step:'done'});go({type:'household'})}finally{saveLock.current=false;setSaving(false)}}
 return <form id={formId} className="gw-form form-density-scope" onSubmit={submit}>{signup&&<div className="onboarding-progress" aria-label={'Step '+step+' of 2'}><span className={step===1?'current':''}>1 · Your details</span><span className={step===2?'current':''}>2 · Your profile</span></div>}{step===1?<><p className="field-help">{signup?'A little about you, so your family knows who’s here.':'Household details are private to you. Adding a child does not create a sign-in account or share their birthday with other members.'}</p><label>Name<input autoComplete="off" required maxLength="80" value={values.name} onChange={e=>set('name',e.target.value)}/></label>{signup&&<label>Email<input type="email" autoComplete="off" required value={values.email} onChange={e=>set('email',e.target.value)}/></label>}<div className="form-short-row"><label>Birthday<input type="date" required min="1900-01-01" max={localDate()} value={values.birthday||''} aria-describedby="member-birthday-help" onChange={e=>set('birthday',e.target.value)}/></label><ChoiceControl label={child?'Gender':'Gender · optional'} variant="search" required={child} value={values.gender||''} onChange={value=>set('gender',value)} options={[...(!child?[{value:'',label:'Not specified'}]:[]),'Woman','Man','Nonbinary','Self-described','Prefer not to say']}/></div><p id="member-birthday-help" className="field-help">Your full birthday stays private.</p></>:<><div className="form-heading"><h2>Make it yours.</h2><p>Add a photo and pick your color. Both are optional.</p></div><ProfileStyleEditor name={values.name} photo={values.photo} color={values.profileColor} busy={photoBusy} onColor={v=>set('profileColor',v)} onRemove={()=>set('photo',null)} onPhoto={async file=>{setPhotoBusy(true);setError('');try{set('photo',(await readPreviewFile(file,'preview')).url)}catch(e){setError(e.message)}finally{setPhotoBusy(false)}}}/></>}{error&&<p role="alert" className="form-error">{error}</p>}<div className="form-save"><Control data-button-level="primary" type="submit" className="button form-primary" disabled={saving||photoBusy}>{saving?'Saving…':signup&&step===1?'Continue':existing?'Save details':signup?'Create profile':child?'Add child':'Add person'}</Control>{signup&&step===2&&<div className="onboarding-secondary"><Button secondary onClick={()=>setStep(1)} disabled={saving}>Back</Button><span className="field-help">You can change these later.</span></div>}</div></form>
}
export function Household(){const {state,openSheet}=useApp(),children=state.members.filter(m=>m.managedBy===state.selfId);return <div className="stack"><p>Add children during setup or come back here later. Only you can see and edit these household details.</p>{children.map(m=><Control key={m.id} className="list-row" onClick={()=>openSheet({type:'edit-child',id:m.id})}><Avatar member={m}/><span><strong>{m.name}</strong><p>Edit birthday and details</p></span><Glyph name="arrow"/></Control>)}<Button onClick={()=>openSheet({type:'add-child'})}>Add a child</Button></div>}
// Memorial rows show the memorial photo, or a small angel on an avatar-sized plate.
function MemorialAvatar({person}){return person?.photo?<Avatar member={person}/>:<span className="avatar memorial-avatar-empty" aria-hidden="true"><Glyph name="angel"/></span>}
export function FamilyTree(){const {state,openSheet,go}=useApp();const name=id=>[...state.members,...state.memorials].find(m=>m.id===id)?.name;return <div className="stack">{canCreateMemorial(state)&&<div className="card-actions"><Button secondary onClick={()=>openSheet({type:'memorial'})}><Glyph name="plus"/>Add memorial profile</Button></div>}<SharedPagePanels page="tree" nativePanels={{'native-founders':<section className="card tree-founders"><div className="founder-pair">{!state.memorials.some(member=>member.founder)&&<p className="muted">Family founder records haven’t been added to this family space yet.</p>}{state.memorials.filter(m=>m.founder).map(m=><Control key={m.id} className="memorial-entry" onClick={()=>openSheet({type:'memorial',id:m.id})}><MemorialAvatar person={m}/><strong>{m.name}</strong>{m.maidenName&&<small>née {m.maidenName}</small>}<span className="small muted">In loving memory</span></Control>)}</div></section>,'native-memorials':<section className="card"><EditableText page="tree" field="memorialsTitle" as="h3">Held in our hearts</EditableText>{!state.memorials.some(member=>!member.founder)&&<p className="muted">No memorial records have been added yet.</p>}{state.memorials.filter(m=>!m.founder).map(m=><Control key={m.id} className="list-row" onClick={()=>openSheet({type:'memorial',id:m.id})}><MemorialAvatar person={m}/><span><strong>{m.name}</strong><p>In loving memory</p></span><Glyph name="arrow"/></Control>)}</section>,'native-connections':<section className="card"><EditableText page="tree" field="connectionsTitle" as="h3">Family connections</EditableText><EditableText page="tree" field="connectionsBody" as="p" className="small muted">Only confirmed connections are shown. Close family groups do not imply parentage.</EditableText><FamilyBranch/>{state.groups[0]&&<Button secondary onClick={()=>go({type:'group',id:state.groups[0].id})}>Close family group</Button>}</section>}}><section className="card tree-later"><CardContentLayout page="tree" items={{
 media:<EditableMedia page="tree" field="hero" className="tree-hero-media"><img src="tree-artwork.png" alt="Green & White oak"/></EditableMedia>,
 title:<EditableText page="tree" field="heroTitle" as="h2">Our roots run deep.</EditableText>,
 body:<EditableText page="tree" field="heroBody" as="p" className="muted">Remembering those who came before us.</EditableText>
 }}/></section></SharedPagePanels></div>}
export function Birthdays(){const {state,dispatch}=useApp(),[busy,setBusy]=useState(false),now=new Date(),month=now.toLocaleDateString(undefined,{month:'long'}),entries=state.mode==='live'?(state.birthdayCalendar||[]).filter(m=>Number(m.monthDay.slice(0,2))===now.getMonth()+1).sort((a,b)=>a.monthDay.localeCompare(b.monthDay)):birthdayEntries(state.members);return <section className="card stack"><h3><EditableText page="birthdays" field="monthTitle" as="span">Birthdays in</EditableText> {month}</h3>{entries.length?entries.map(m=><p key={m.id||m.memberId}>{m.name} <span className="muted">· {month} {Number(m.monthDay?.slice(3)||m.birthday.slice(8))}</span></p>):<div className="muted">{state.mode==='live'?<EditableText page="birthdays" field="emptyBody" as="div">No shared birthdays this month.</EditableText>:'No preview birthdays added for this month.'}</div>}{state.mode==='live'?<><EditableText page="birthdays" field="privacyNote" as="p" className="muted small">Only adult members who opt in appear here. Your birth year and household birthdays stay private.</EditableText><label className="check-row"><input type="checkbox" checked={Boolean(state.birthdayCelebration)} disabled={busy} onChange={async e=>{setBusy(true);try{await dispatch({type:'SET_BIRTHDAY_CELEBRATION',enabled:e.target.checked})}finally{setBusy(false)}}}/>Include my month and day and an automatic birthday celebration</label></>:<><p className="muted small">Seeded family members have no birthday on file. These examples stay on this device.</p><Button secondary onClick={()=>dispatch({type:'PREVIEW_BIRTHDAYS',date:localDate()})}>Try today’s birthday posts locally</Button></>}</section>}

function FamilyBranch(){
 const {state,openSheet}=useApp(),[focus,setFocus]=useState(state.selfId),[page,setPage]=useState(0),people=[...state.members,...state.memorials],branch=familyBranch(state,focus),pages=Math.max(1,Math.ceil(branch.parents.length/2),Math.ceil(branch.children.length/3),Math.ceil(branch.siblings.length/2));
 const explore=id=>{setFocus(id);setPage(0)},node=(relation,label)=>{const person=people.find(person=>person.id===relation.id);return person&&<Control key={relation.id+relation.type} type="button" className="tree-branch-person" aria-label={'Explore '+person.name+' · '+label} onClick={()=>explore(person.id)}><Avatar member={person}/><strong>{person.name}</strong><small>{label}</small></Control>};
 return <div className="family-branch"><ChoiceControl label="Explore a branch" aria-label="Explore a family branch" variant="search" value={focus} onChange={explore} options={people.map(person=>({value:person.id,label:person.name}))}/><div className="family-branch-diagram" aria-label={'Confirmed family branch for '+(branch.person?.name||'you')}>
 <div className="tree-branch-generation tree-branch-parents">{branch.parents.slice(page*2,page*2+2).map(relation=>node(relation,relation.type==='stepparent'?'Stepparent':'Parent'))}</div>
 <div className="tree-branch-center">{branch.person&&<Control type="button" className="tree-branch-person is-focus" onClick={()=>openSheet({type:state.memorials.some(person=>person.id===focus)?'memorial':'profile',id:focus})}><Avatar member={branch.person}/><strong>{branch.person.name}</strong><small>{focus===state.selfId?'You':'View profile'}</small></Control>}</div>
 <div className="tree-branch-generation tree-branch-children">{branch.children.slice(page*3,page*3+3).map(relation=>node(relation,relation.type==='stepparent'?'Stepchild':'Child'))}</div>
 {branch.siblings.length>0&&<div className="tree-branch-generation tree-branch-siblings">{branch.siblings.slice(page*2,page*2+2).map(relation=>node(relation,'Sibling'))}</div>}
 </div>{!branch.parents.length&&!branch.children.length&&!branch.siblings.length&&<p className="small muted">No confirmed connections for this person yet.</p>}{pages>1&&<div className="tree-branch-paging"><Control type="button" disabled={page===0} onClick={()=>setPage(value=>value-1)}>Previous</Control><span className="small muted">{page+1} of {pages}</span><Control type="button" disabled={page===pages-1} onClick={()=>setPage(value=>value+1)}>More connections</Control></div>}</div>
}
