import {ProfileStyleEditor} from './profiles.jsx';
import {readPreviewFile} from './uploads.js';
import React,{useState} from 'react';
import {Avatar,Button,Control,Glyph,useApp} from './ui-core.jsx';
import {validateMember,localDate,birthdayEntries} from './member-model.js';
export function MemberForm({signup=false,child=false,id}){
 const {state,dispatch,openSheet}=useApp(),existing=state.members.find(m=>m.id===id);
 const [values,setValues]=useState(existing||{name:'',birthday:'',gender:'',email:'',circle:'family',profileColor:'#4f996c',photo:null}),[error,setError]=useState(''),[step,setStep]=useState(1),[saving,setSaving]=useState(false),[photoBusy,setPhotoBusy]=useState(false);
 const set=(key,value)=>setValues(v=>({...v,[key]:value}));
 async function submit(e){e.preventDefault();const error=validateMember(values,{signup,child});if(error){setError(error);return}if(signup&&step===1){setError('');setStep(2);return}setSaving(true);try{if(!await dispatch({type:existing?'UPDATE_DEPENDENT':'ADD_PERSON',member:values,signup,child}))return;if(signup)await dispatch({type:'ONBOARD',step:'done'});openSheet({type:'household'})}finally{setSaving(false)}}
 return <form className="gw-form" onSubmit={submit}>{signup&&<div className="onboarding-progress" aria-label={'Step '+step+' of 2'}><span className={step===1?'current':''}>1 · Your details</span><span className={step===2?'current':''}>2 · Your profile</span></div>}{step===1?<><p className="field-help">{signup?'A little about you, so your family knows who’s here.':'Household details are private to you. Adding a child does not create a sign-in account or share their birthday with other members.'}</p><label>Name<input autoComplete="off" required maxLength="80" value={values.name} onChange={e=>set('name',e.target.value)}/></label>{signup&&<label>Email<input type="email" autoComplete="off" required value={values.email} onChange={e=>set('email',e.target.value)}/></label>}<label>Birthday<input type="date" required min="1900-01-01" max={localDate()} value={values.birthday||''} onChange={e=>set('birthday',e.target.value)}/></label><p className="field-help">Your full birthday stays private.</p><label>Gender{!child?' · optional':''}<select required={child} value={values.gender||''} onChange={e=>set('gender',e.target.value)}><option value="">Choose</option>{['Woman','Man','Nonbinary','Self-described','Prefer not to say'].map(g=><option key={g}>{g}</option>)}</select></label></>:<><div className="form-heading"><h2>Make it yours.</h2><p>Add a photo and pick your color. Both are optional.</p></div><ProfileStyleEditor name={values.name} photo={values.photo} color={values.profileColor} busy={photoBusy} onColor={v=>set('profileColor',v)} onRemove={()=>set('photo',null)} onPhoto={async file=>{setPhotoBusy(true);setError('');try{set('photo',(await readPreviewFile(file,'preview')).url)}catch(e){setError(e.message)}finally{setPhotoBusy(false)}}/></>}{error&&<p role="alert" className="form-error">{error}</p>}<div className="form-save"><Control type="submit" className="button form-primary" disabled={saving||photoBusy}>{saving?'Saving…':signup&&step===1?'Continue':existing?'Save details':signup?'Create profile':child?'Add child':'Add person'}</Control>{signup&&step===2&&<div className="onboarding-secondary"><Button secondary onClick={()=>setStep(1)} disabled={saving}>Back</Button><span className="field-help">You can change these later.</span></div>}</div></form>
}
export function Household(){const {state,openSheet}=useApp(),children=state.members.filter(m=>m.managedBy===state.selfId);return <div className="stack"><p>Add children during setup or come back here later. Only you can see and edit these household details.</p>{children.map(m=><Control key={m.id} className="list-row" onClick={()=>openSheet({type:'edit-child',id:m.id})}><Avatar member={m}/><span><strong>{m.name}</strong><p>Edit birthday and details</p></span><Glyph name="arrow"/></Control>)}<Button onClick={()=>openSheet({type:'add-child'})}>Add a child</Button><Button secondary onClick={()=>openSheet(null)}>Done for now</Button></div>}
export function FamilyTree(){const {state,openSheet,go}=useApp();const name=id=>[...state.members,...state.memorials].find(m=>m.id===id)?.name;return <div className="stack"><section className="card tree-later"><img src="tree-artwork.png" alt="Green & White oak"/><h2>Our roots run deep.</h2><p className="muted">Remembering those who came before us.</p><div className="founder-pair">{state.memorials.filter(m=>m.founder).map(m=><Control key={m.id} className="memorial-entry" onClick={()=>openSheet({type:'memorial',id:m.id})}><Glyph name="tree"/><strong>{m.name}</strong>{m.maidenName&&<small>née {m.maidenName}</small>}<span className="small muted">In loving memory</span></Control>)}</div></section><section className="card"><h3>Held in our hearts</h3>{state.memorials.filter(m=>!m.founder).map(m=><Control key={m.id} className="list-row" onClick={()=>openSheet({type:'memorial',id:m.id})}><Glyph name="tree"/><span><strong>{m.name}</strong><p>In loving memory</p></span><Glyph name="arrow"/></Control>)}</section><section className="card"><h3>Family connections</h3><p className="small muted">Only confirmed connections are shown. Close family groups do not imply parentage.</p>{state.relationships.map((r,i)=><p className="family-connection" key={i}>{name(r.from)} <span className="muted">{r.type==='parent'?'· parent of':r.type==='stepparent'?'· stepparent of':'· sibling of'}</span> {name(r.to)}</p>)}{state.groups[0]&&<Button secondary onClick={()=>go({type:'group',id:state.groups[0].id})}>Close family group</Button>}</section></div>}
export function Memorial({id}){const {state}=useApp(),m=state.memorials.find(m=>m.id===id);return m&&<div className="memorial-profile stack"><img src="tree-artwork.png" alt=""/><span className="eyebrow">In loving memory</span><h3>{m.name}{m.maidenName&&<> (née {m.maidenName})</>}</h3><p>{m.founder?'A founder of the Green & White family.':'Remembered with love by the Green & White family.'}</p><p className="muted small">A memorial tree entry. Dates and personal stories can be added when the family confirms them.</p></div>}
export function Birthdays(){const {state,dispatch}=useApp(),[busy,setBusy]=useState(false),now=new Date(),month=now.toLocaleDateString(undefined,{month:'long'}),entries=state.mode==='live'?(state.birthdayCalendar||[]).filter(m=>Number(m.monthDay.slice(0,2))===now.getMonth()+1).sort((a,b)=>a.monthDay.localeCompare(b.monthDay)):birthdayEntries(state.members);return <section className="card stack"><h3>Birthdays in {month}</h3>{entries.length?entries.map(m=><p key={m.id||m.memberId}>{m.name} <span className="muted">· {month} {Number(m.monthDay?.slice(3)||m.birthday.slice(8))}</span></p>):<p className="muted">{state.mode==='live'?'No shared birthdays this month.':'No preview birthdays added for this month.'}</p>}{state.mode==='live'?<><p className="muted small">Only adult members who opt in appear here. Your birth year and household birthdays stay private.</p><label className="check-row"><input type="checkbox" checked={Boolean(state.birthdayCelebration)} disabled={busy} onChange={async e=>{setBusy(true);try{await dispatch({type:'SET_BIRTHDAY_CELEBRATION',enabled:e.target.checked})}finally{setBusy(false)}}}/>Include my month and day and an automatic birthday celebration</label></>:<><p className="muted small">Seeded family members have no birthday on file. These examples stay on this device.</p><Button secondary onClick={()=>dispatch({type:'PREVIEW_BIRTHDAYS',date:localDate()})}>Try today’s birthday posts locally</Button></>}</section>}
