import {photoFrameStyle} from './photo-framing-model.js';
import {reunionArchived} from './reunion-model.js';
import {SharedPagePanels} from './page-panels.jsx';
import {EditableText,EditableMedia} from './page-content.jsx';
import {itemVariants} from './merchandise-model.js';
import {derivePlanning,planningReminderAllowed} from './planning-model.js';
import {ContactDirectory} from './contact-directory.jsx';
export {Profile,EditProfile,ContactCard} from './profiles.jsx';
import {PeopleFilters} from './people-filters.jsx';
import {emptyPeopleFilters,publicDirectoryMembers,filterDirectoryMembers,groupDirectoryHouseholds} from './people-directory-model.js';
import React,{useId,useRef,useState} from 'react';
import {Control,Button,Glyph,InlineFilters,useApp} from './ui-core.jsx';
import {DirectoryPersonRow} from './directory-person-row.jsx';
import './family-destinations.css';
import './people-flow.css';
import {MemberLink,PostCard,CommentsView,ComposerBox,FileView} from './conversation.jsx';
const shirtProducts=[{id:'classic',name:'Green & White Reunion Shirt',color:'Forest green',price:null},{id:'cream',name:'Family Roots Tee',color:'Warm white',price:null}];
const productsFor=state=>state.mode==='live'?(state.products||[]):[...shirtProducts,...(state.products||[])].filter(p=>p.active!==false);
const sizes=['XS','S','M','L','XL','2XL','3XL'];
export function ProductList(){const {state,openSheet}=useApp();const products=<><div className="section-head"><EditableText page="shop" field="heading" as="h2">Family merchandise</EditableText><Control className="text-button" onClick={()=>openSheet({type:'bag'})}>Bag · {state.bag.reduce((n,x)=>n+Object.values(x.sizes).reduce((a,b)=>a+b,0),0)}</Control></div><div className="product-grid">{productsFor(state).map(p=><article className="card shirt-card" key={p.id}><div className="shirt">{p.photo?<img src={p.photo} alt={p.name} style={photoFrameStyle(p.photoFrame)}/>:<Glyph name="shirt"/>}</div><h3>{p.name}</h3><p className="muted">{p.price||p.description}</p><Button disabled={reunionArchived(state)} onClick={()=>openSheet({type:'product',id:p.id})}>Choose options</Button></article>)}</div>{!productsFor(state).length&&<EditableText page="shop" field="emptyBody" as="p" className="muted">The leaders haven’t added merchandise yet.</EditableText>}</>;return <section className="stack"><SharedPagePanels page="shop" mediaOnly nativePanels={{'native-products':products,'native-order':state.order?<OrderTracking/>:null}}><EditableMedia page="shop" field="hero"/></SharedPagePanels></section>}
export function ProductDetail({id}){const {state,dispatch,openSheet}=useApp(),product=productsFor(state).find(p=>p.id===id)||{name:'Item',color:''},sizes=itemVariants(product),[quantities,setQuantities]=useState(state.bag.find(x=>x.productId===id)?.sizes||{}),count=Object.values(quantities).reduce((a,b)=>a+b,0);return <div className="stack"><div className="shirt product-art">{product.photo?<img src={product.photo} alt={product.name} style={photoFrameStyle(product.photoFrame)}/>:<Glyph name="shirt"/>}</div><h2>{product.name}</h2><p>{product.description}</p><p>{product.price||'Price not set'}</p><div className="size-choices" role="group" aria-label="Item options">{sizes.map(s=><Control key={s} className="size-choice" aria-pressed={!!quantities[s]} onClick={()=>setQuantities(q=>({...q,[s]:q[s]?0:1}))}>{s}</Control>)}</div><div className="size-list">{sizes.filter(s=>quantities[s]>0).map(s=><label key={s} className="size-row"><span>{s}</span><input type="number" min="0" max="25" inputMode="numeric" aria-label={s+' quantity'} value={quantities[s]||0} onChange={e=>setQuantities(q=>({...q,[s]:Math.max(0,Math.min(25,Number(e.target.value)||0))}))}/></label>)}</div><Button disabled={!count} onClick={()=>{dispatch({type:'BAG_ADD',item:{productId:id,name:product.name,sizes:quantities}});openSheet({type:'bag'})}}>Select {count} {count===1?'item':'items'}</Button></div>}
export function Bag(){const {state,dispatch,openSheet}=useApp(),count=state.bag.reduce((n,item)=>n+Object.values(item.sizes).reduce((a,b)=>a+b,0),0);return <div className="stack">{state.bag.map(item=><div className="card" key={item.productId}><strong>{item.name}</strong><p>{Object.entries(item.sizes).filter(([,n])=>n).map(([s,n])=>`${s} × ${n}`).join(' · ')}</p><Control className="text-button" onClick={()=>openSheet({type:'product',id:item.productId})}>Edit options</Control><Control className="text-button" onClick={()=>dispatch({type:'BAG_REMOVE',productId:item.productId})}>Remove</Control></div>)}{!count&&<p className="muted">Your bag is empty.</p>}{count>0&&<><p>{count} {count===1?'item':'items'} selected</p><Button onClick={async()=>{if(await dispatch({type:'CLAIM_ORDER'}))openSheet({type:'claim'})}}>Place order</Button></>}</div>}
export function Claim(){const {state,openSheet}=useApp();return <div className="stack"><h3>Order placed</h3><p>{state.mode==='live'?'Your selection is saved. The planning crew can now confirm ordering and pickup.':'Your selection is recorded locally in preview.'}</p>{planningReminderAllowed(derivePlanning(state),'fees',{authorized:true})&&<p className="note">Your reunion contribution still needs attention. You can handle them separately under My fees; your order stays in place.</p>}<Button onClick={()=>openSheet(null)}>Done</Button></div>}
export function OrderTracking(){const {state,dispatch}=useApp();return <div className="card stack"><h3>Your order</h3><p>Status: <strong>{['received','delivered'].includes(state.order.status)?'Received':state.order.status==='shipped'?'Shipped':state.order.status==='ready'?'Ready for pickup':state.order.status==='ordered'?'Ordered':'Claimed · awaiting the planning crew'}</strong></p><p className="muted">Claimed {new Date(state.order.claimedAt).toLocaleDateString()}</p>{!['received','delivered'].includes(state.order.status)&&<Button secondary disabled={reunionArchived(state)} onClick={()=>dispatch({type:'ORDER_RECEIVED'})}>I received it</Button>}</div>}
export function GroupPage({id}){
 const {state,dispatch}=useApp(),group=(state.groups||[]).find(g=>g.id===id),members=(state.members||[]).filter(m=>group?.memberIds?.includes(m.id)),[editing,setEditing]=useState(false),[name,setName]=useState(group?.name||''),[saving,setSaving]=useState(false);
 if(!group)return <p className="muted">This family group is not available.</p>;
 return <div className="stack"><div className="card"><h1>{group.name}</h1><p>{members.length} members · shared across this group</p>{editing?<form className="stack" onSubmit={async event=>{event.preventDefault();if(saving||!name.trim())return;setSaving(true);try{if(await dispatch({type:'RENAME_GROUP',id:group.id,name:name.trim()}))setEditing(false)}finally{setSaving(false)}}}><label>Group name<input required value={name} disabled={saving} onChange={event=>setName(event.target.value)}/></label><div className="card-actions"><Button secondary disabled={saving} onClick={()=>{setName(group.name);setEditing(false)}}>Cancel</Button><Control type="submit" className="button" disabled={saving||!name.trim()}>{saving?'Saving…':'Save group name'}</Control></div></form>:<Button secondary onClick={()=>setEditing(true)}>Edit group name</Button>}</div><section className="card stack"><h2>Our people</h2>{members.map(member=><DirectoryPersonRow key={member.id} member={member}/>)}{!members.length&&<p className="muted">No members are shown in this group.</p>}</section></div>
}
function FamilyDirectory({all=false}){
 const {state,go,openSheet}=useApp(),[filters,setFilters]=useState({...emptyPeopleFilters}),members=filterDirectoryMembers(state,publicDirectoryMembers(state),filters),{groups,unassigned}=groupDirectoryHouseholds(state,members,{sort:filters.sort});
 return <section className="card stack family-people-directory"><div className="family-directory-heading"><EditableText page="people" field="peopleTitle" as="h2">Our people</EditableText>{!all&&<Button secondary icon="people" onClick={()=>go({type:'all-family'})}>All family</Button>}</div><PeopleFilters state={state} value={filters} onChange={setFilters} resultCount={members.length}/>{state.mode==='preview'&&<p className="small muted">Preview profiles and activity are fictional. A matching name never claims an account.</p>}{all?members.map(member=><DirectoryPersonRow key={member.id} member={member}/>):<div className="family-household-directory">{groups.map(({household,members})=><section className="family-household-group" key={household.id}><div className="family-household-heading"><div><h3>{household.name}</h3><p className="small muted">{members.length} {members.length===1?'person':'people'}</p></div><Button secondary onClick={()=>go({type:'household',id:household.id})}>View household</Button></div><p className="small muted">{members.map(member=>member.name).join(', ')}</p></section>)}{!groups.length&&members.length>0&&<p className="muted">No shared households match yet. Find everyone in All family, or open your household profile to get started.</p>}{unassigned.length>0&&<details className="family-household-unassigned" open={Boolean(filters.query)||undefined}><summary>{unassigned.length} {unassigned.length===1?'person':'people'} without a household</summary>{unassigned.map(member=><DirectoryPersonRow key={member.id} member={member}/>)}</details>}</div>}{!members.length&&<EditableText page="people" field="noResults" as="p" className="muted">No people match these filters.</EditableText>}<Button secondary onClick={()=>openSheet({type:state.mode==='preview'?'add-person':'invite'})}>{state.mode==='preview'?'Add a person in preview':'Invite someone'}</Button></section>;
}
export function AllFamily(){return <div className="stack all-family-page"><h1>All family</h1><FamilyDirectory all/></div>}
export function People(){
 const {state,go}=useApp(),contact=state.contact||{},self=state.members.find(member=>member.id===state.selfId),contactIdentity={...self,name:contact.name||self?.name,photo:contact.useProfile?self?.photo:contact.photo||self?.photo,photoFrame:contact.useProfile?self?.photoFrame:contact.photo?contact.photoFrame:self?.photoFrame};
 const profiles=<section className="card profile-destinations"><EditableText page="people" field="profilesTitle" as="h3">Your family profiles</EditableText><div className="profile-destination-buttons"><Button secondary onClick={()=>go({type:'household'})}><Glyph name="home"/>Household profile</Button><Button secondary onClick={()=>go({type:'profile',id:state.selfId})}><Glyph name="user"/>Your profile</Button></div><Button secondary onClick={()=>go({type:'birthdays'})}><Glyph name="calendar"/>Birthdays</Button></section>;
 const address=<section className="card family-people-contact"><EditableText page="people" field="heading" as="h2">Address book</EditableText><EditableText page="people" field="intro" as="p" className="muted address-intro">A trusted place for the details each person chooses to share.</EditableText><EditableText page="people" field="sharingNote" as="p" className="field-help">Contact cards are opt-in. Sharing a detail is your choice.</EditableText>{contact.name?<div className="directory-empty"><Avatar member={contactIdentity} size="contact-summary-avatar"/><h3>{contact.name}</h3><p className="muted small">{contact.optIn?'Opted in for family sharing':'Private by default'}</p><Button secondary onClick={()=>go({type:'contact'})}>Edit my contact card</Button></div>:<div className="directory-empty"><Glyph name="people"/><EditableText page="people" field="emptyTitle" as="h3">Start with your own card.</EditableText><EditableText page="people" field="emptyBody" as="p" className="muted small">Add your details, then choose who can see them. No contact information is shared yet.</EditableText><Button onClick={()=>go({type:'contact'})}>Set up my contact card <Glyph name="arrow"/></Button></div>}</section>;
 return <div className="stack family-people-section"><SharedPagePanels page="people" mediaOnly nativePanels={{'native-directory':<FamilyDirectory/>,'native-profiles':profiles,'native-contact':address,'native-shared-contacts':state.mode==='live'?<ContactDirectory/>:null}}><EditableMedia page="people" field="hero"/></SharedPagePanels></div>;
}
export function ReportForm({targetId}){
 const {dispatch,openSheet}=useApp(),[reason,setReason]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState(''),reasonId=useId(),saveLock=useRef(false);
 async function submit(event){
  event.preventDefault();if(saveLock.current||!reason.trim())return;
  saveLock.current=true;setSaving(true);setError('');
  try{if(await dispatch({type:'REPORT',targetId,reason:reason.trim()}))openSheet(null);else setError('Your report could not be saved. Your reason is still here; try again.')}
  catch{setError('Your report could not be saved. Your reason is still here; try again.')}
  finally{saveLock.current=false;setSaving(false)}
 }
 return <form className="stack" aria-busy={saving} onSubmit={submit}><p>Tell the moderators what needs attention.</p><label htmlFor={reasonId}>Reason for reporting</label><textarea id={reasonId} required maxLength="1000" disabled={saving} value={reason} onChange={event=>setReason(event.target.value)} placeholder="What happened?"/>{error&&<p role="alert">{error}</p>}<Control className="button" type="submit" disabled={saving||!reason.trim()}>{saving?'Submitting…':'Submit report'}</Control></form>
}
export function Moderation(){const {state,dispatch}=useApp();return <div className="stack"><h2>Reports for moderators</h2>{state.reports.filter(r=>r.status==='open').map(r=><article key={r.id} className="card"><strong>{r.targetId}</strong><p>{r.reason}</p><div className="row"><Button secondary onClick={()=>dispatch({type:'MODERATE',id:r.id,status:'dismissed'})}>Dismiss</Button><Button onClick={()=>dispatch({type:'MODERATE',id:r.id,targetId:r.targetId,status:'removed'})}>Remove item</Button></div></article>)}{!state.reports.some(r=>r.status==='open')&&<p>No open reports.</p>}</div>}
export {FamilyInvitationEditor as Invite} from './family-invitations.jsx';
