import {SharedPagePanels} from './page-panels.jsx';
import {EditableText,EditableMedia} from './page-content.jsx';
import {itemVariants} from './merchandise-model.js';
import {ContactDirectory} from './contact-directory.jsx';
export {Profile,EditProfile,ContactCard} from './profiles.jsx';
import {memberMatches} from './data-adapter.js';
import React,{useState} from 'react';
import {Control,Avatar,Button,Glyph,MemberBadges,InlineFilters,useApp} from './ui-core.jsx';
import {MemberLink,PostCard,CommentsView,ComposerBox,FileView} from './conversation.jsx';
const shirtProducts=[{id:'classic',name:'Green & White Reunion Shirt',color:'Forest green',price:null},{id:'cream',name:'Family Roots Tee',color:'Warm white',price:null}];
const productsFor=state=>state.mode==='live'?(state.products||[]):[...shirtProducts,...(state.products||[])].filter(p=>p.active!==false);
const sizes=['XS','S','M','L','XL','2XL','3XL'];
export function ProductList(){const {state,openSheet}=useApp();return <section className="stack"><div className="section-head"><EditableText page="shop" field="heading" as="h2">Family merchandise</EditableText><Control className="text-button" onClick={()=>openSheet({type:'bag'})}>Bag · {state.bag.reduce((n,x)=>n+Object.values(x.sizes).reduce((a,b)=>a+b,0),0)}</Control></div><SharedPagePanels page="shop" mediaOnly><EditableMedia page="shop" field="hero"/></SharedPagePanels><div className="product-grid">{productsFor(state).map(p=><article className="card shirt-card" key={p.id}><div className="shirt">{p.photo?<img src={p.photo} alt={p.name}/>:<Glyph name="shirt"/>}</div><h3>{p.name}</h3><p className="muted">{p.price||p.description}</p><Button onClick={()=>openSheet({type:'product',id:p.id})}>Choose options</Button></article>)}</div>{!productsFor(state).length&&<EditableText page="shop" field="emptyBody" as="p" className="muted">The leaders haven’t added merchandise yet.</EditableText>}{state.order&&<OrderTracking/>}</section>}
export function ProductDetail({id}){const {state,dispatch,openSheet}=useApp(),product=productsFor(state).find(p=>p.id===id)||{name:'Item',color:''},sizes=itemVariants(product),[quantities,setQuantities]=useState(state.bag.find(x=>x.productId===id)?.sizes||{}),count=Object.values(quantities).reduce((a,b)=>a+b,0);return <div className="stack"><div className="shirt product-art">{product.photo?<img src={product.photo} alt={product.name}/>:<Glyph name="shirt"/>}</div><h2>{product.name}</h2><p>{product.description}</p><p>{product.price||'Price not set'}</p><div className="size-choices" role="group" aria-label="Item options">{sizes.map(s=><Control key={s} className="size-choice" aria-pressed={!!quantities[s]} onClick={()=>setQuantities(q=>({...q,[s]:q[s]?0:1}))}>{s}</Control>)}</div><div className="size-list">{sizes.filter(s=>quantities[s]>0).map(s=><label key={s} className="size-row"><span>{s}</span><input type="number" min="0" max="25" inputMode="numeric" aria-label={s+' quantity'} value={quantities[s]||0} onChange={e=>setQuantities(q=>({...q,[s]:Math.max(0,Math.min(25,Number(e.target.value)||0))}))}/></label>)}</div><Button disabled={!count} onClick={()=>{dispatch({type:'BAG_ADD',item:{productId:id,name:product.name,sizes:quantities}});openSheet({type:'bag'})}}>Select {count} {count===1?'item':'items'}</Button></div>}
export function Bag(){const {state,dispatch,openSheet}=useApp(),count=state.bag.reduce((n,item)=>n+Object.values(item.sizes).reduce((a,b)=>a+b,0),0);return <div className="stack">{state.bag.map(item=><div className="card" key={item.productId}><strong>{item.name}</strong><p>{Object.entries(item.sizes).filter(([,n])=>n).map(([s,n])=>`${s} × ${n}`).join(' · ')}</p><Control className="text-button" onClick={()=>openSheet({type:'product',id:item.productId})}>Edit options</Control><Control className="text-button" onClick={()=>dispatch({type:'BAG_REMOVE',productId:item.productId})}>Remove</Control></div>)}{!count&&<p className="muted">Your bag is empty.</p>}{count>0&&<><p>{count} {count===1?'item':'items'} selected</p><Button onClick={async()=>{if(await dispatch({type:'CLAIM_ORDER'}))openSheet({type:'claim'})}}>Place order</Button></>}</div>}
export function Claim(){const {state,openSheet}=useApp();return <div className="stack"><h3>Order placed</h3><p>{state.mode==='live'?'Your selection is saved. The planning crew can now confirm ordering and pickup.':'Your selection is recorded locally in preview.'}</p>{state.fees==='unpaid'&&<p className="note">Reunion fees are still marked unpaid. You can handle them separately under My fees; your order stays in place.</p>}<Button onClick={()=>openSheet(null)}>Done</Button></div>}
export function OrderTracking(){const {state,dispatch}=useApp();return <div className="card stack"><h3>Your order</h3><p>Status: <strong>{['received','delivered'].includes(state.order.status)?'Received':state.order.status==='shipped'?'Shipped':state.order.status==='ready'?'Ready for pickup':state.order.status==='ordered'?'Ordered':'Claimed · awaiting the planning crew'}</strong></p><p className="muted">Claimed {new Date(state.order.claimedAt).toLocaleDateString()}</p>{!['received','delivered'].includes(state.order.status)&&<Button secondary onClick={()=>dispatch({type:'ORDER_RECEIVED'})}>I received it</Button>}</div>}
export function GroupPage({id}){const {state,dispatch,go}=useApp(),group=state.groups.find(g=>g.id===id)||state.groups[0],members=state.members.filter(m=>group?.memberIds?.includes(m.id)),[editing,setEditing]=useState(false),[name,setName]=useState(group?.name||'');if(!group)return <p className="muted">This family group is not available.</p>;return <div className="stack"><div className="card"><span className="eyebrow">Close family group</span><h1>{group.name}</h1><p>{members.length} members · shared across this group</p>{editing?<div className="row"><input aria-label="Group name" value={name} onChange={e=>setName(e.target.value)}/><Button onClick={()=>{if(name.trim())dispatch({type:'RENAME_GROUP',id,name:name.trim()});setEditing(false)}}>Save</Button></div>:<Button secondary onClick={()=>setEditing(true)}>Edit group name</Button>}</div><h2>Our people</h2><div className="card">{members.map(m=><Control className="list-row" key={m.id} onClick={()=>go({type:'profile',id:m.id})}><Avatar member={m}/><strong>{m.name}</strong><MemberBadges member={m}/></Control>)}</div></div>}
export function People(){
  const {state,dispatch,go,openSheet}=useApp(),contact=state.contact||{},[query,setQuery]=useState('');
  return <div className="stack family-people-section"><SharedPagePanels page="people" mediaOnly><EditableMedia page="people" field="hero"/></SharedPagePanels><div className="columns family-people-columns"><section className="card"><EditableText page="people" field="heading" as="h2">Address book</EditableText><EditableText page="people" field="intro" as="p" className="muted address-intro">A trusted place for the details each person chooses to share.</EditableText><EditableText page="people" field="sharingNote" as="p" className="field-help">Contact cards are opt-in. Sharing a detail is your choice.</EditableText>{contact.name?<div className="directory-empty"><Glyph name="people"/><h3>{contact.name}</h3><p className="muted small">{contact.optIn?'Opted in for family sharing':'Private by default'}</p><Button secondary onClick={()=>openSheet({type:'contact'})}>Edit my contact card</Button></div>:<div className="directory-empty"><Glyph name="people"/><EditableText page="people" field="emptyTitle" as="h3">Start with your own card.</EditableText><EditableText page="people" field="emptyBody" as="p" className="muted small">Add your details, then choose who can see them. No contact information is shared yet.</EditableText><Button onClick={()=>openSheet({type:'contact'})}>Set up my contact card <Glyph name="arrow"/></Button></div>}</section><aside className="stack"><section className="card profile-destinations"><EditableText page="people" field="profilesTitle" as="h3">Your family profiles</EditableText><div className="profile-destination-buttons"><Button secondary onClick={()=>go({type:'household'})}><Glyph name="home"/>Household profile</Button><Button secondary onClick={()=>go({type:'profile',id:state.selfId})}><Glyph name="user"/>Your profile</Button></div><Button secondary onClick={()=>go({type:'birthdays'})}><Glyph name="calendar"/>Birthdays</Button></section></aside></div>
  <ContactDirectory/><section className="card stack"><div className="section-head"><EditableText page="people" field="peopleTitle" as="h2">Our people</EditableText><InlineFilters label="Filter people"><div className="filter-choices">{[['all','All'],['family','Family'],['loved','Loved Ones'],['leaders','Leaders']].map(([v,l])=><Control key={v} aria-pressed={state.peopleFilter===v} onClick={()=>dispatch({type:'SET_PEOPLE_FILTER',value:v})}>{l}</Control>)}</div></InlineFilters></div><label>Find someone<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search names"/></label>{state.mode==='preview'&&<p className="small muted">Preview profiles and activity are fictional. A matching name never claims an account.</p>}{state.members.filter(m=>memberMatches(m,state.peopleFilter)&&m.name.toLowerCase().includes(query.toLowerCase())).map(m=><Control className="list-row" key={m.id} onClick={()=>go({type:'profile',id:m.id})}><Avatar member={m}/><span><strong>{m.name}</strong><MemberBadges member={m}/></span><Glyph name="arrow"/></Control>)}{!state.members.some(m=>memberMatches(m,state.peopleFilter)&&m.name.toLowerCase().includes(query.toLowerCase()))&&<EditableText page="people" field="noResults" as="p" className="muted">No people match these filters.</EditableText>}<Button secondary onClick={()=>openSheet({type:state.mode==='preview'?'add-person':'invite'})}>{state.mode==='preview'?'Add a person in preview':'Invite someone'}</Button></section></div>
}
export function ReportForm({targetId}){const {dispatch,openSheet}=useApp(),[reason,setReason]=useState('');return <form className="stack" onSubmit={e=>{e.preventDefault();if(reason.trim())dispatch({type:'REPORT',targetId,reason:reason.trim()});openSheet(null)}}><p>Tell the moderators what needs attention.</p><textarea required maxLength="1000" value={reason} onChange={e=>setReason(e.target.value)} placeholder="What happened?"/><Control className="button" type="submit">Submit report</Control></form>}
export function Moderation(){const {state,dispatch}=useApp();return <div className="stack"><h2>Reports for moderators</h2>{state.reports.filter(r=>r.status==='open').map(r=><article key={r.id} className="card"><strong>{r.targetId}</strong><p>{r.reason}</p><div className="row"><Button secondary onClick={()=>dispatch({type:'MODERATE',id:r.id,status:'dismissed'})}>Dismiss</Button><Button onClick={()=>dispatch({type:'MODERATE',id:r.id,targetId:r.targetId,status:'removed'})}>Remove item</Button></div></article>)}{!state.reports.some(r=>r.status==='open')&&<p>No open reports.</p>}</div>}
export function Invite(){const {state,dispatch}=useApp(),[recipient,setRecipient]=useState(''),[copied,setCopied]=useState(false),url=state.mode==='live'?'Join our Green & White family space: https://greenwhitefamily.com. Sign in and a family organizer will approve your membership.':'GW Family preview invitation — sample only; no membership or sign-in access.';return <div className="stack"><p>{state.mode==='live'?'Copy this invitation and share it with your family. New members still need an organizer’s approval.':'Try a preview invitation. Nothing is sent and no membership is granted.'}</p>{state.mode==='preview'&&<><label>Name or email<input value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="Who are you inviting?"/></label><Button onClick={()=>{if(recipient.trim()){dispatch({type:'SAVE_INVITE_DRAFT',recipient:recipient.trim(),groupId:null});setRecipient('')}}}>Save invite draft</Button></>}<Button secondary onClick={async()=>{try{await navigator.clipboard.writeText(url);setCopied(true)}catch{setCopied(false)}}}>{copied?'Invitation copied':state.mode==='live'?'Copy invitation':'Copy preview invitation'}</Button><p className="muted small">{state.mode==='preview'?'Invite drafts stay in isolated preview storage. ':''}Membership is set by an organizer, never inferred from a name.</p></div>}
