import {MemberPicker} from './member-picker.jsx';
import {directoryPerson} from './member-directory.js';
import {heritageRoles,heritageTitle} from './household-heritage.js';
import {householdAccent} from './household-model.js';
import React,{useEffect,useState} from 'react';
import {Avatar,Button,Control,Glyph,useApp} from './ui-core.jsx';
import {MemberLink,PostCard} from './conversation.jsx';
import {Household as PrivateChildren} from './family.jsx';
import {ProfileStyleEditor} from './profiles.jsx';
import {profilePalette,hasPostMedia} from './profile-model.js';
import {readPreviewFile} from './uploads.js';
import {api} from './live-adapter.js';
export function HouseholdProfile({id}){const{state,go,dispatch,theme,personalThemes}=useApp(),[name,setName]=useState(''),[tab,setTab]=useState('posts'),[busy,setBusy]=useState(false),h=(state.households||[]).find(h=>h.id===(id||state.householdId));const create=async e=>{e.preventDefault();setBusy(true);try{if(await dispatch({type:'CREATE_HOUSEHOLD',name}))go({type:'household'})}finally{setBusy(false)}};
 if(id&&!h)return <section><h1>Household not found</h1><p>This household is unavailable.</p></section>;
 if(!h)return <section className="stack household-page"><h1>Household</h1><p className="muted">A shared home for your close family’s posts, photos, and plans.</p><HouseholdRequests/><form className="card gw-form" onSubmit={create}><h2>Start your household</h2><label>Household name<input required maxLength="100" value={name} onChange={e=>setName(e.target.value)} placeholder="The name your family uses"/></label><p className="field-help">You’ll be the first head. Registered adults choose whether to join; children’s records stay private to their guardian.</p><Control type="submit" className="button" disabled={busy||!name.trim()}>{busy?'Creating…':'Create household'}</Control></form>{(state.households||[]).length>0&&<section className="stack"><h2>Find your household</h2>{state.households.map(h=><Button secondary key={h.id} onClick={()=>go({type:'household',id:h.id})}>{h.name}</Button>)}</section>}<section className="card"><h2>Children’s private records</h2><PrivateChildren/></section></section>;
 const members=state.members.filter(m=>h.memberIds.includes(m.id)),posts=state.posts.filter(p=>h.memberIds.includes(p.authorId)&&(tab==='posts'||hasPostMedia(p))),own=h.memberIds.includes(state.selfId),memories=(state.memories||[]).filter(m=>h.memberIds.includes(m.authorId));
 return <section className="stack household-page" style={personalThemes&&householdAccent(h)?profilePalette(householdAccent(h),theme):undefined}><div className="household-profile-head">{h.photo?<img className="household-group-photo" src={h.photo} alt={h.name+' group photo'}/>:null}<div className={'household-portrait-bar '+(members.length>6?'many':'')}>{members.map(m=><MemberLink key={m.id} id={m.id} compact/>)}</div><div className="household-title"><div><p className="small muted">Household</p><h1>{h.name}</h1><p>{members.length} {members.length===1?'member':'members'}</p></div>{h.canManage?<Button onClick={()=>go({type:'household-manage',id:h.id})}>Manage household</Button>:!own&&!state.householdId?<Button disabled={(state.householdRequests||[]).some(r=>r.householdId===h.id&&r.requesterId===state.selfId)} onClick={()=>dispatch({type:'REQUEST_HOUSEHOLD_JOIN',householdId:h.id})}>Request to join</Button>:null}</div></div>{own&&<><HouseholdRequests householdId={h.id}/><details className="form-more"><summary>Children’s private records</summary><PrivateChildren/></details></>}<HouseholdHeritage key={h.id} household={h}/><div className="segmented" role="tablist" aria-label="Household content">{[['posts','Posts'],['media','Media']].map(([v,label])=><Control key={v} role="tab" aria-selected={tab===v} onClick={()=>setTab(v)}>{label}</Control>)}</div>{posts.length?posts.map(p=><PostCard key={p.id} post={p}/>):<p className="muted">{tab==='media'?'Household photos and media will appear here.':'Posts from household members will appear here.'}</p>}{tab==='media'&&memories.length>0&&<section className="household-media-grid">{memories.map(m=><Control key={m.id} onClick={()=>go({type:'memory',id:m.id})}>{(m.mediaType||'image/jpeg').startsWith('image/')?<img src={m.image} alt={m.title||'Family memory'}/>:<Glyph name="image"/>}<span>{m.title||'Family memory'}</span></Control>)}</section>}{own&&!h.canManage&&<details className="form-more"><summary>Household membership</summary><p>Leaving the household keeps your personal profile and posts.</p><Button secondary onClick={()=>dispatch({type:'LEAVE_HOUSEHOLD',householdId:h.id})}>Leave household</Button></details>}</section>}
export function HouseholdRequests({householdId}){const{state,dispatch}=useApp();const requests=(state.householdRequests||[]).filter(r=>!householdId||r.householdId===householdId);return requests.length?<section className="card stack household-requests"><h2>Household requests</h2>{requests.map(r=>{const h=state.households.find(h=>h.id===r.householdId),from=state.members.find(m=>m.id===r.requesterId),to=state.members.find(m=>m.id===r.recipientId),canResolve=r.kind==='join'?h?.headIds.includes(state.selfId):r.recipientId===state.selfId;return <article key={r.id}><strong>{r.kind==='invite'?`${h?.name} invited ${to?.name||'you'}`:r.kind==='head'?`${from?.name} as an additional head`:`${from?.name} wants to join ${h?.name}`}</strong>{canResolve?<div className="row"><Button onClick={()=>dispatch({type:'RESOLVE_HOUSEHOLD_REQUEST',id:r.id,accept:true})}>Accept request</Button><Button secondary onClick={()=>dispatch({type:'RESOLVE_HOUSEHOLD_REQUEST',id:r.id,accept:false})}>Decline</Button></div>:<><p className="muted small">Waiting for {r.kind==='head'?'the first head’s approval':r.kind==='invite'?'their response':'a head’s approval'}.</p>{state.mode==='preview'&&<Button secondary onClick={()=>dispatch({type:'RESOLVE_HOUSEHOLD_REQUEST',id:r.id,accept:true})}>Simulate acceptance in preview</Button>}</>}</article>})}</section>:null}
export function HouseholdManager({id}){
 const {state,dispatch,go,setToast}=useApp(),h=(state.households||[]).find(h=>h.id===(id||state.householdId));
 const personalColor=state.members.find(m=>m.id===state.selfId)?.profileColor||'#4f996c';
 const [tab,setTab]=useState('appearance'),[values,setValues]=useState(h?{name:h.name,color:householdAccent(h)||personalColor,colorMode:householdAccent(h)?'custom':'inherit',photo:h.photo}:{});
 const [photoBusy,setPhotoBusy]=useState(false),[memberId,setMemberId]=useState(''),[email,setEmail]=useState(''),[sendEmail,setSendEmail]=useState(false),[invite,setInvite]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(h)setValues({name:h.name,color:householdAccent(h)||personalColor,colorMode:householdAccent(h)?'custom':'inherit',photo:h.photo});setMemberId('');setInvite(null);setError('')},[h?.id]);
 if(!h?.canManage)return <section><h1>Household</h1><p>Only a head of this household can manage it.</p></section>;
 const set=(key,value)=>setValues(v=>({...v,[key]:value})),members=state.members.filter(m=>h.memberIds.includes(m.id));
 const available=m=>!h.memberIds.includes(m.id)&&!state.households.some(x=>x.memberIds.includes(m.id));
 const invitationPending=(state.householdRequests||[]).some(r=>r.householdId===h.id&&r.recipientId===memberId&&r.kind==='invite');
 async function createInvite(e){e.preventDefault();setError('');setBusy(true);try{if(state.mode==='preview'){setInvite({preview:true});return}setInvite(await api('/api/household-invites',{method:'POST',body:JSON.stringify({householdId:h.id,email,sendEmail})}))}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function saveProfile(e){e.preventDefault();setBusy(true);try{if(await dispatch({type:'SAVE_HOUSEHOLD',householdId:h.id,...values})){setToast('Household saved.');go({type:'household',id:h.id})}}finally{setBusy(false)}}
 return <section className="stack household-page"><h1>Manage {h.name}</h1>
  <div className="segmented" role="tablist" aria-label="Household management">{[['appearance','Profile'],['members','Members'],['invites','Invitations']].map(([v,label])=><Control key={v} type="button" role="tab" aria-selected={tab===v} onClick={()=>setTab(v)}>{label}</Control>)}</div>
  {tab==='appearance'?<form className="card gw-form" onSubmit={saveProfile}>
   <label>Household name<input required maxLength="100" value={values.name||''} onChange={e=>set('name',e.target.value)}/></label>
   <label className="check-row"><input type="checkbox" checked={values.colorMode==='inherit'} onChange={e=>setValues(v=>({...v,colorMode:e.target.checked?'inherit':'custom',color:e.target.checked?personalColor:v.color}))}/>Use each viewer’s personal color</label>
   <p className="field-help">{values.colorMode==='inherit'?'Your household follows each person’s appearance settings. Choose a color below to give this household its own accent.':'This household has its own chosen color. Turn on personal colors to inherit each viewer’s appearance.'}</p>
   <ProfileStyleEditor name={values.name} photo={values.photo} color={values.color||personalColor} busy={photoBusy} onColor={color=>setValues(v=>({...v,color,colorMode:'custom'}))} onRemove={()=>set('photo',null)} onPhoto={async file=>{setPhotoBusy(true);try{set('photo',(await readPreviewFile(file,state.mode)).url)}catch(e){setError(e.message)}finally{setPhotoBusy(false)}}}/>
   <p className="field-help">Without a group photo, the profile shows your members’ portraits.</p>{error&&<p role="alert">{error}</p>}<Control className="button" type="submit" disabled={photoBusy||busy}>{busy?'Saving…':'Save household'}</Control>
  </form>:tab==='members'?<>
   <HouseholdRequests householdId={h.id}/><section className="card stack"><h2>Members</h2>{members.map(m=><article key={m.id} className="household-member-row"><MemberLink id={m.id} compact/><span className="small muted">{m.id===h.founderId?'Founding account head':h.headIds.includes(m.id)?'Account head':'Member'}</span>{m.id!==h.founderId&&<details><summary>Manage member</summary>{!h.headIds.includes(m.id)&&<Button secondary onClick={()=>dispatch({type:'REQUEST_HOUSEHOLD_HEAD',householdId:h.id,memberId:m.id})}>{state.selfId===h.founderId?'Approve as account head':'Request as account head'}</Button>}<p className="field-help">Removing someone affects this household only. Their account and posts stay intact.</p><Button secondary onClick={()=>dispatch({type:'REMOVE_HOUSEHOLD_MEMBER',householdId:h.id,memberId:m.id})}>Remove from household</Button></details>}</article>)}</section>
   <HouseholdHeritage key={h.id} household={h} editable/>
   <section className="card"><h2>Children’s private records</h2><PrivateChildren/></section>
  </>:<>
   <section className="card stack"><h2>Invite a registered member</h2><MemberPicker label="Find a family member" value={memberId} onChange={setMemberId} filter={available} help="Registered adults choose whether to join. People already in a household cannot be invited here."/><Button secondary disabled={!memberId||invitationPending} onClick={async()=>{if(await dispatch({type:'INVITE_HOUSEHOLD_MEMBER',householdId:h.id,memberId}))setMemberId('')}}>{invitationPending?'Invitation waiting':'Invite selected member'}</Button></section>
   <form className="card gw-form" onSubmit={createInvite}><h2>Invite by email</h2><p className="field-help">They sign in with the invited email and choose whether to join. Family membership approval still applies.</p><label>Email<input required type="email" value={email} onChange={e=>{setEmail(e.target.value);setInvite(null)}}/></label><label className="check-row"><input type="checkbox" checked={sendEmail} onChange={e=>setSendEmail(e.target.checked)}/>Send the invitation email</label><Control type="submit" className="button" disabled={busy}>{busy?'Preparing…':sendEmail?'Send invitation':'Create invitation link'}</Control>{error&&<p role="alert">{error}</p>}{invite&&(invite.preview?<p role="status">Preview invitation prepared. No email or real link was sent.</p>:<div><p role="status">{invite.emailSent?'Invitation email sent.':'Invitation link ready.'}</p><label>Private invitation link<input readOnly value={invite.url} onFocus={e=>e.target.select()}/></label><p className="field-help">Valid for seven days, for this recipient only.</p></div>)}</form>
  </>}
 </section>
}
export function HouseholdHeritage({household:h,editable=false}){
 const {state,dispatch,go,openSheet,setToast}=useApp(),[role,setRole]=useState('ancestral-head'),[personId,setPersonId]=useState(''),[title,setTitle]=useState('Ancestral head'),[busy,setBusy]=useState(false);
 const heritage=h.heritage||[],canEdit=editable&&h.canManage;
 if(!heritage.length&&!canEdit)return null;
 async function save(e){e.preventDefault();if(!personId)return;setBusy(true);try{if(await dispatch({type:'SAVE_HOUSEHOLD_HERITAGE',householdId:h.id,entry:{personId,role,title}})){setPersonId('');setToast('Household heritage saved.')}}finally{setBusy(false)}}
 return <section className="card stack household-heritage"><div><h2>Household heritage</h2><p className="field-help">Honor the ancestors who led the way and the next generation carrying their legacy. These commemorative titles don’t grant account access or household management.</p></div>
  {Object.entries(heritageRoles).map(([key,definition])=>{const entries=heritage.filter(x=>x.role===key);return entries.length>0&&<div key={key} className="stack"><h3>{definition.label}</h3>{entries.map(entry=>{const person=directoryPerson(state,entry.personId);return <article className="household-heritage-row stack" key={entry.id}><Control type="button" className="list-row" disabled={!person} onClick={()=>entry.personKind==='ancestor'?openSheet({type:'memorial',id:entry.personId}):go({type:'profile',id:entry.personId})}><Avatar member={person}/><span><strong>{person?.name||'Family member'}</strong><small>{heritageTitle(entry)}{entry.personKind==='ancestor'?' · In loving memory':' · Next generation'}</small></span></Control>{canEdit&&<div className="row"><label>Commemorative title<select aria-label={'Title for '+(person?.name||'family member')} value={entry.title} disabled={busy} onChange={e=>dispatch({type:'SAVE_HOUSEHOLD_HERITAGE',householdId:h.id,entry:{...entry,title:e.target.value}})}>{definition.titles.map(title=><option key={title}>{title}</option>)}</select></label><Button secondary disabled={busy} onClick={()=>dispatch({type:'REMOVE_HOUSEHOLD_HERITAGE',householdId:h.id,heritageId:entry.id})}>Remove title</Button></div>}</article>})}</div>})}
  {canEdit&&<form className="gw-form" onSubmit={save}><h3>Add a heritage role</h3><label>Role<select value={role} disabled={busy} onChange={e=>{setRole(e.target.value);setTitle(heritageRoles[e.target.value].defaultTitle);setPersonId('')}}>{Object.entries(heritageRoles).map(([value,r])=><option value={value} key={value}>{r.defaultTitle}</option>)}</select></label><MemberPicker key={role} value={personId} onChange={setPersonId} purpose={role==='ancestral-head'?'ancestral-head':'member'} label={role==='ancestral-head'?'Ancestor':'Torch bearer'} disabled={busy} help={role==='ancestral-head'?'Choose an ancestor from the family tree to honor as an ancestral head.':'Choose a living adult family member to honor as a torch bearer, matriarch, or patriarch.'}/><label>Commemorative title<select value={title} onChange={e=>setTitle(e.target.value)} disabled={busy}>{heritageRoles[role].titles.map(t=><option key={t}>{t}</option>)}</select></label><Control type="submit" className="button" disabled={!personId||busy}>{busy?'Saving…':'Save heritage role'}</Control></form>}
 </section>
}
export function HouseholdInvitation({token}){const{state,data,go}=useApp(),[invite,setInvite]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{let active=true;if(state.mode==='preview'){setError('Sign in with the invited email to accept a real invitation.');return}api('/api/household-invites/inspect',{method:'POST',body:JSON.stringify({token})}).then(v=>{if(active)setInvite(v)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[token,state.mode]);return <section className="card stack"><h1>Household invitation</h1>{error?<p role="alert">{error}</p>:invite?<><p>You’re invited to join {invite.name}.</p><p className="field-help">Your own account and private contact-sharing choices stay yours.</p><Button disabled={busy} onClick={async()=>{setBusy(true);try{const r=await api('/api/household-invites/accept',{method:'POST',body:JSON.stringify({token})});await data.refresh();go({type:'household',id:r.householdId})}catch(e){setError(e.message)}finally{setBusy(false)}}}>Accept invitation</Button></>:<p role="status">Checking your invitation…</p>}</section>}
