import {ChoiceControl} from './choice-control.jsx';
import {MemberPicker} from './member-picker.jsx';
import {directoryPerson} from './member-directory.js';
import {heritageRoles,heritageTitle} from './household-heritage.js';
import {householdAccent} from './household-model.js';
import React,{useEffect,useRef,useState} from 'react';
import {PersonIdentity} from './person-identity.jsx';
import {ViewSwitcher} from './view-switcher.jsx';
import {imageFileError} from './form-consumer-model.js';
import './form-layout.css';
import './form-consumers.css';
import {Avatar,Button,Control,Glyph,useApp} from './ui-core.jsx';
import {MemberLink,PostCard} from './conversation.jsx';
import {Household as PrivateChildren} from './family.jsx';
import {ProfileStyleEditor,ProfileColorEditor} from './profiles.jsx';
import {profilePalette,hasPostMedia} from './profile-model.js';
import {readPreviewFile} from './uploads.js';
import {api} from './live-adapter.js';
export function HouseholdProfile({id}){const{state,go,dispatch,openSheet,theme,personalThemes,route}=useApp(),[name,setName]=useState(''),[tab,setTab]=useState('posts'),[busy,setBusy]=useState(false),[error,setError]=useState(''),createLock=useRef(false),h=(state.households||[]).find(h=>h.id===(id||state.householdId));const create=async e=>{e.preventDefault();if(createLock.current)return;if(!name.trim()){setError('Enter a household name.');return}createLock.current=true;setError('');setBusy(true);try{if(await dispatch({type:'CREATE_HOUSEHOLD',name}))go({type:'household'});else setError('The household wasn’t created. Try again.')}catch(e){setError(e.message||'The household wasn’t created. Try again.')}finally{createLock.current=false;setBusy(false)}};
 if(id&&!h)return <section><h1>Household not found</h1><p>This household is unavailable.</p></section>;
 if(!h)return <section className="stack household-page"><h1>Household</h1><p className="muted">A shared home for your close family’s posts, photos, and plans.</p><HouseholdRequests/><form className="card gw-form" onSubmit={create} aria-busy={busy}><h2>Start your household</h2><label>Household name<input required maxLength="100" disabled={busy} value={name} onChange={e=>setName(e.target.value)} placeholder="The name your family uses"/></label><p className="field-help">You’ll be the first head. Registered adults choose whether to join; children’s records stay private to their guardian.</p>{error&&<p role="alert">{error}</p>}<Control type="submit" className="button" disabled={busy||!name.trim()}>{busy?'Creating…':'Create household'}</Control></form>{(state.households||[]).length>0&&<section className="stack"><h2>Find your household</h2>{state.households.map(h=><Button secondary key={h.id} onClick={()=>go({type:'household',id:h.id})}>{h.name}</Button>)}</section>}<HouseholdChildrenLink/></section>;
 const members=state.members.filter(m=>h.memberIds.includes(m.id)),posts=state.posts.filter(p=>h.memberIds.includes(p.authorId)&&(tab==='posts'||hasPostMedia(p))),own=h.memberIds.includes(state.selfId),memories=(state.memories||[]).filter(m=>h.memberIds.includes(m.authorId));
 return <section className="stack household-page" style={personalThemes&&householdAccent(h)?profilePalette(householdAccent(h),theme):undefined}><div className="household-profile-head">{h.photo?<img className="household-group-photo" src={h.photo} alt={h.name+' group photo'}/>:null}<div className={'household-portrait-bar '+(members.length>6?'many':'')}>{members.map(m=><MemberLink key={m.id} id={m.id} compact/>)}</div><div className="household-title"><div><p className="small muted">Household</p><h1>{h.name}</h1><p>{members.length} {members.length===1?'member':'members'}</p></div>{h.canManage?<Button onClick={()=>go({type:'household-manage',id:h.id})}>Manage household</Button>:!own&&!state.householdId?<Button disabled={(state.householdRequests||[]).some(r=>r.householdId===h.id&&r.requesterId===state.selfId)} onClick={()=>dispatch({type:'REQUEST_HOUSEHOLD_JOIN',householdId:h.id})}>Request to join</Button>:null}</div></div>{route?.section==='email-invitation'&&<p className="help-status">This update relates to an email invitation. Its response link is in your invitation email.</p>}<HouseholdRequests householdId={h.id}/>{own&&<HouseholdChildrenLink householdId={h.id}/>}<HouseholdHeritage key={h.id} household={h}/><ViewSwitcher label="Household content" value={tab} onChange={setTab} options={[['posts','Posts','chat'],['media','Media','image']]}/>{posts.length?posts.map(p=><PostCard key={p.id} post={p}/>):<p className="muted">{tab==='media'?'Household photos and media will appear here.':'Posts from household members will appear here.'}</p>}{tab==='media'&&memories.length>0&&<section className="household-media-grid">{memories.map(m=><Control key={m.id} onClick={()=>go({type:'memory',id:m.id})}>{(m.mediaType||'image/jpeg').startsWith('image/')?<img src={m.image} alt={m.title||'Family memory'}/>:<Glyph name="image"/>}<span>{m.title||'Family memory'}</span></Control>)}</section>}{own&&!h.canManage&&<Button secondary onClick={()=>openSheet({type:'household-membership-task',householdId:h.id})}><Glyph name="people"/>Household membership</Button>}</section>}
function HouseholdChildrenLink({householdId}){
 const {go}=useApp();
 return <section className="household-children-link"><h2>Children’s private records</h2><p className="field-help">Only you can see and edit the children’s details you manage. A household head does not gain access to these records.</p><Button secondary onClick={()=>go({type:'household-children',id:householdId})}><Glyph name="people"/>View private records</Button></section>;
}
// App owns routing. showBack=false avoids duplicating its standard Back row.
export function HouseholdChildrenPage({id,showBack=true}){
 const {state,go,goBack}=useApp(),h=(state.households||[]).find(h=>h.id===(id||state.householdId));
 return <section className="stack household-children-page">{showBack&&<Control type="button" className="page-back" onClick={()=>goBack?goBack():go({type:'household',id:h?.id})}><Glyph name="arrow"/>Back</Control>}<h1>Children’s private records</h1><p className="field-help">These records stay private to their guardian. Adding a child does not create a sign-in account or share a birthday with the family.</p><PrivateChildren/></section>;
}
// One bounded person task belongs in App's existing centered Sheet. Account
// authority and the founding-head guard remain the existing model's decisions.
export function HouseholdMemberTask({householdId,memberId}){
 const {state,dispatch,openSheet,setToast}=useApp(),h=(state.households||[]).find(h=>h.id===householdId),m=state.members.find(m=>m.id===memberId);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),lock=useRef(false),active=useRef(true),epoch=useRef(0);
 useEffect(()=>{active.current=true;epoch.current++;lock.current=false;setBusy(false);setError('');return()=>{active.current=false;epoch.current++}},[state.selfId,state.mode,householdId,memberId]);
 if(!h?.canManage||!m||!h.memberIds.includes(m.id)||m.id===h.founderId)return <p role="alert">This household member cannot be managed here.</p>;
 async function act(type){if(lock.current)return;lock.current=true;const version=epoch.current;setBusy(true);setError('');try{if(await dispatch({type,householdId:h.id,memberId:m.id})){if(active.current&&version===epoch.current){setToast(type==='REQUEST_HOUSEHOLD_HEAD'?'Account-head request updated.':'Member removed from this household.');openSheet(null)}}else if(active.current&&version===epoch.current)setError('The change wasn’t saved. Try again.')}catch(e){if(active.current&&version===epoch.current)setError(e.message||'The change wasn’t saved. Try again.')}finally{if(version===epoch.current){lock.current=false;if(active.current)setBusy(false)}}}
 return <div className="household-bounded-task" aria-busy={busy}><PersonIdentity memberId={m.id}/><p className="field-help">{h.headIds.includes(m.id)?'This member is already an account head.':'Additional account heads follow the existing approval process. Private children’s records stay with their guardian.'}</p>{!h.headIds.includes(m.id)&&<Button secondary disabled={busy} onClick={()=>act('REQUEST_HOUSEHOLD_HEAD')}>{state.selfId===h.founderId?'Approve as account head':'Request as account head'}</Button>}<p className="field-help">Removing someone affects this household only. Their account and posts stay intact.</p>{error&&<p role="alert">{error}</p>}<div className="row"><Button secondary disabled={busy} onClick={()=>act('REMOVE_HOUSEHOLD_MEMBER')}>{busy?'Saving…':'Remove from household'}</Button><Button secondary disabled={busy} onClick={()=>openSheet(null)}>Cancel</Button></div></div>;
}
export function HouseholdMembershipTask({householdId}){
 const {state,dispatch,go,openSheet}=useApp(),h=(state.households||[]).find(h=>h.id===householdId),[busy,setBusy]=useState(false),[error,setError]=useState(''),lock=useRef(false),active=useRef(true),epoch=useRef(0);
 useEffect(()=>{active.current=true;epoch.current++;lock.current=false;setBusy(false);setError('');return()=>{active.current=false;epoch.current++}},[state.selfId,state.mode,householdId]);
 if(!h||!h.memberIds.includes(state.selfId)||h.canManage)return <p role="alert">This membership action is unavailable.</p>;
 async function leave(){if(lock.current)return;lock.current=true;const version=epoch.current;setBusy(true);setError('');try{if(await dispatch({type:'LEAVE_HOUSEHOLD',householdId:h.id})){if(active.current&&version===epoch.current)go({type:'household'})}else if(active.current&&version===epoch.current)setError('Your membership wasn’t changed. Try again.')}catch(e){if(active.current&&version===epoch.current)setError(e.message||'Your membership wasn’t changed. Try again.')}finally{if(version===epoch.current){lock.current=false;if(active.current)setBusy(false)}}}
 return <div className="household-bounded-task" aria-busy={busy}><p>Leave {h.name}?</p><p className="field-help">Leaving keeps your personal profile and posts. Your private children’s records remain yours.</p>{error&&<p role="alert">{error}</p>}<div className="row"><Button secondary disabled={busy} onClick={leave}>{busy?'Leaving…':'Leave household'}</Button><Button secondary disabled={busy} onClick={()=>openSheet(null)}>Stay in household</Button></div></div>;
}
export function HouseholdRequests({householdId}){
 const {state,dispatch}=useApp(),[pendingId,setPendingId]=useState(''),[error,setError]=useState(''),lock=useRef(false);
 const requests=(state.householdRequests||[]).filter(r=>!householdId||r.householdId===householdId);
 async function resolve(r,accept){if(lock.current)return;lock.current=true;setPendingId(r.id);setError('');try{if(!await dispatch({type:'RESOLVE_HOUSEHOLD_REQUEST',id:r.id,accept}))setError('The request wasn’t updated. Try again.')}catch(e){setError(e.message||'The request wasn’t updated. Try again.')}finally{lock.current=false;setPendingId('')}}
 return requests.length?<section className="card stack household-requests"><h2>Household requests</h2>{error&&<p role="alert">{error}</p>}{requests.map(r=>{const h=state.households.find(h=>h.id===r.householdId),from=state.members.find(m=>m.id===r.requesterId),to=state.members.find(m=>m.id===r.recipientId),canResolve=r.kind==='join'?h?.headIds.includes(state.selfId):r.recipientId===state.selfId;return <article key={r.id} aria-busy={pendingId===r.id}><PersonIdentity memberId={r.kind==='invite'?r.recipientId:r.requesterId} fallbackName="Family member"/><p><strong>{r.kind==='invite'?`${h?.name} invited ${to?.name||'you'}`:r.kind==='head'?`${from?.name} as an additional head`:`${from?.name} wants to join ${h?.name}`}</strong></p>{canResolve?<div className="row"><Button disabled={!!pendingId} onClick={()=>resolve(r,true)}>Accept request</Button><Button secondary disabled={!!pendingId} onClick={()=>resolve(r,false)}>Decline</Button></div>:<><p className="muted small">Waiting for {r.kind==='head'?'the first head’s approval':r.kind==='invite'?'their response':'a head’s approval'}.</p>{state.mode==='preview'&&<Button secondary disabled={!!pendingId} onClick={()=>resolve(r,true)}>Simulate acceptance in preview</Button>}</>}</article>})}</section>:null;
}
export function HouseholdManager({id}){
 const {state,dispatch,go,openSheet,setToast}=useApp(),h=(state.households||[]).find(h=>h.id===(id||state.householdId));
 const personalColor=state.members.find(m=>m.id===state.selfId)?.profileColor||'#4f996c';
 const [tab,setTab]=useState('appearance'),[values,setValues]=useState(h?{name:h.name,color:householdAccent(h)||personalColor,colorMode:householdAccent(h)?'custom':'inherit',photo:h.photo}:{});
 const [photoBusy,setPhotoBusy]=useState(false),[photoError,setPhotoError]=useState(''),photoLock=useRef(false),mutationLock=useRef(false),photoVersion=useRef(0),[memberId,setMemberId]=useState(''),[email,setEmail]=useState(''),[sendEmail,setSendEmail]=useState(false),[invite,setInvite]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(h)setValues({name:h.name,color:householdAccent(h)||personalColor,colorMode:householdAccent(h)?'custom':'inherit',photo:h.photo});setMemberId('');setEmail('');setSendEmail(false);setInvite(null);setError('');setPhotoError('');setPhotoBusy(false);setBusy(false);photoLock.current=false;mutationLock.current=false;photoVersion.current++;return()=>{photoVersion.current++}},[h?.id,state.selfId,state.mode]);
 if(!h?.canManage)return <section><h1>Household</h1><p>Only a head of this household can manage it.</p></section>;
 const set=(key,value)=>setValues(v=>({...v,[key]:value})),members=state.members.filter(m=>h.memberIds.includes(m.id));
 const available=m=>!h.memberIds.includes(m.id)&&!state.households.some(x=>x.memberIds.includes(m.id));
 const invitationPending=(state.householdRequests||[]).some(r=>r.householdId===h.id&&r.recipientId===memberId&&r.kind==='invite');
 async function createInvite(e){e.preventDefault();if(mutationLock.current||photoLock.current)return;mutationLock.current=true;const version=photoVersion.current;setError('');setInvite(null);setBusy(true);try{if(state.mode==='preview'){setInvite({preview:true});return}const result=await api('/api/household-invites',{method:'POST',body:JSON.stringify({householdId:h.id,email,sendEmail})});if(version===photoVersion.current)setInvite(result)}catch(e){if(version===photoVersion.current)setError(e.message||'The invitation couldn’t be prepared. Try again.')}finally{if(version===photoVersion.current){mutationLock.current=false;setBusy(false)}}}
 async function saveProfile(e){e.preventDefault();if(photoLock.current||mutationLock.current)return;if(!values.name?.trim()){setError('Enter a household name.');return}mutationLock.current=true;const version=photoVersion.current;setError('');setBusy(true);try{const saved=await dispatch({type:'SAVE_HOUSEHOLD',householdId:h.id,...values});if(version!==photoVersion.current)return;if(saved){setToast('Household saved.');go({type:'household',id:h.id})}else setError('The household wasn’t saved. Try again.')}catch(e){if(version===photoVersion.current)setError(e.message||'The household wasn’t saved. Try again.')}finally{if(version===photoVersion.current){mutationLock.current=false;setBusy(false)}}}
 async function inviteMember(){if(mutationLock.current||photoLock.current||!memberId||invitationPending)return;mutationLock.current=true;const version=photoVersion.current;setError('');setBusy(true);try{const saved=await dispatch({type:'INVITE_HOUSEHOLD_MEMBER',householdId:h.id,memberId});if(version===photoVersion.current){if(saved)setMemberId('');else setError('The invitation wasn’t saved. Try again.')}}catch(e){if(version===photoVersion.current)setError(e.message||'The invitation wasn’t saved. Try again.')}finally{if(version===photoVersion.current){mutationLock.current=false;setBusy(false)}}}
 async function uploadPhoto(file){if(photoLock.current||busy)return;photoLock.current=true;const version=photoVersion.current;setPhotoBusy(true);setPhotoError('');try{const validation=imageFileError(file,'household photo');if(validation)throw Error(validation);const upload=await readPreviewFile(file,state.mode);if(version===photoVersion.current)set('photo',upload.url)}catch(e){if(version===photoVersion.current)setPhotoError(e.message||'The photo couldn’t be added. Choose it again to retry.')}finally{if(version===photoVersion.current){photoLock.current=false;setPhotoBusy(false)}}}
 return <section className="stack household-page"><h1>Manage {h.name}</h1>
  <ViewSwitcher label="Household management" value={tab} onChange={setTab} disabled={busy||photoBusy} options={[['appearance','Profile','user'],['members','Members','people'],['invites','Invitations','chat']]}/>
  {tab==='appearance'?<form className="card gw-form form-density-scope household-profile-form" onSubmit={saveProfile} aria-busy={busy||photoBusy}>
   <ProfileStyleEditor name={values.name} photo={values.photo} photoLabel="Household photo" color={values.color||personalColor} busy={photoBusy} disabled={busy} error={photoError} showColors={false} onColor={color=>setValues(v=>({...v,color,colorMode:'custom'}))} onRemove={()=>{set('photo',null);setPhotoError('')}} onPhoto={uploadPhoto}>
    <label>Household name<input required maxLength="100" value={values.name||''} disabled={busy} onChange={e=>set('name',e.target.value)}/></label>
    <p className="field-help">Without a group photo, the profile shows your members’ portraits.</p>
   </ProfileStyleEditor>
   <label className="check-row"><input type="checkbox" checked={values.colorMode==='inherit'} disabled={busy} onChange={e=>setValues(v=>({...v,colorMode:e.target.checked?'inherit':'custom',color:e.target.checked?personalColor:v.color}))}/>Use each viewer’s personal color</label>
   <p className="field-help">{values.colorMode==='inherit'?'Your household follows each person’s appearance settings. Choose a color below to give this household its own accent.':'This household has its own chosen color. Turn on personal colors to inherit each viewer’s appearance.'}</p>
   <ProfileColorEditor color={values.color||personalColor} disabled={busy} onColor={color=>setValues(v=>({...v,color,colorMode:'custom'}))}/>{error&&<p role="alert">{error}</p>}<Control className="button" type="submit" disabled={photoBusy||busy}>{busy?'Saving…':'Save household'}</Control>
  </form>:tab==='members'?<>
   <HouseholdRequests householdId={h.id}/><section className="card stack"><h2>Members</h2>{members.map(m=><article key={m.id} className="household-member-row"><div className="household-member-copy"><MemberLink id={m.id} compact/><span className="small muted">{m.id===h.founderId?'Founding account head':h.headIds.includes(m.id)?'Account head':'Member'}</span></div>{m.id!==h.founderId&&<Button secondary aria-label={'Manage '+m.name+' in this household'} onClick={()=>openSheet({type:'household-member-task',id:m.id,householdId:h.id})}><Glyph name="settings"/>Manage member</Button>}</article>)}</section>
   <HouseholdHeritage key={h.id} household={h} editable/>
   <HouseholdChildrenLink householdId={h.id}/>
  </>:<>
   <section className="card stack"><h2>Invite a registered member</h2><MemberPicker label="Find a family member" disabled={busy} value={memberId} onChange={setMemberId} filter={available} help="Registered adults choose whether to join. People already in a household cannot be invited here."/><Button secondary disabled={!memberId||invitationPending||busy} onClick={inviteMember}>{invitationPending?'Invitation waiting':'Invite selected member'}</Button></section>
   <form className="card gw-form" onSubmit={createInvite}><h2>Invite by email</h2><p className="field-help">They sign in with the invited email and choose whether to join. Family membership approval still applies.</p><label>Email<input required type="email" autoComplete="email" disabled={busy} value={email} onChange={e=>{setEmail(e.target.value);setInvite(null)}}/></label><label className="check-row"><input type="checkbox" checked={sendEmail} disabled={busy} onChange={e=>setSendEmail(e.target.checked)}/>Send the invitation email</label><Control type="submit" className="button" disabled={busy}>{busy?'Preparing…':sendEmail?'Send invitation':'Create invitation link'}</Control>{error&&<p role="alert">{error}</p>}{invite&&(invite.preview?<p role="status">Preview invitation prepared. No email or real link was sent.</p>:<div><p role="status">{invite.emailSent?'Invitation email sent.':'Invitation link ready.'}</p><label>Private invitation link<input readOnly value={invite.url} onFocus={e=>e.target.select()}/></label><p className="field-help">Valid for seven days, for this recipient only.</p></div>)}</form>
  </>}
 </section>
}
export function HouseholdHeritage({household:h,editable=false}){
 const {state,dispatch,go,openSheet,setToast}=useApp(),[role,setRole]=useState('ancestral-head'),[personId,setPersonId]=useState(''),[title,setTitle]=useState('Ancestral head'),[busy,setBusy]=useState(false),[error,setError]=useState(''),lock=useRef(false);
 const heritage=h.heritage||[],canEdit=editable&&h.canManage;
 if(!heritage.length&&!canEdit)return null;
 async function updateHeritage(action){if(lock.current)return;lock.current=true;setError('');setBusy(true);try{if(!await dispatch(action))setError('The heritage title wasn’t updated. Try again.')}catch(e){setError(e.message||'The heritage title wasn’t updated. Try again.')}finally{lock.current=false;setBusy(false)}}
 async function save(e){e.preventDefault();if(lock.current)return;if(!personId){setError('Choose a person from the family directory.');return}lock.current=true;setError('');setBusy(true);try{if(await dispatch({type:'SAVE_HOUSEHOLD_HERITAGE',householdId:h.id,entry:{personId,role,title}})){setPersonId('');setToast('Household heritage saved.')}else setError('The heritage role wasn’t saved. Try again.')}catch(e){setError(e.message||'The heritage role wasn’t saved. Try again.')}finally{lock.current=false;setBusy(false)}}
 return <section className="card stack household-heritage" aria-busy={busy}>{error&&<p role="alert">{error}</p>}<div><h2>Household heritage</h2><p className="field-help">Honor the ancestors who led the way and the next generation carrying their legacy. These commemorative titles don’t grant account access or household management.</p></div>
  {Object.entries(heritageRoles).map(([key,definition])=>{const entries=heritage.filter(x=>x.role===key);return entries.length>0&&<div key={key} className="stack"><h3>{definition.label}</h3>{entries.map(entry=>{const person=directoryPerson(state,entry.personId);return <article className="household-heritage-row stack" key={entry.id}><Control type="button" className="list-row" disabled={!person} onClick={()=>entry.personKind==='ancestor'?openSheet({type:'memorial',id:entry.personId}):go({type:'profile',id:entry.personId})}><Avatar member={person}/><span><strong>{person?.name||'Family member'}</strong><small>{heritageTitle(entry)}{entry.personKind==='ancestor'?' · In loving memory':' · Next generation'}</small></span></Control>{canEdit&&<div className="row"><ChoiceControl required label="Commemorative title" aria-label={'Title for '+(person?.name||'family member')} value={entry.title} disabled={busy} onChange={title=>updateHeritage({type:'SAVE_HOUSEHOLD_HERITAGE',householdId:h.id,entry:{...entry,title}})} options={definition.titles}/><Button secondary disabled={busy} onClick={()=>updateHeritage({type:'REMOVE_HOUSEHOLD_HERITAGE',householdId:h.id,heritageId:entry.id})}>Remove title</Button></div>}</article>})}</div>})}
  {canEdit&&<form className="gw-form form-density-scope household-heritage-form" onSubmit={save} aria-busy={busy}><h3>Add a heritage role</h3><ChoiceControl required label="Role" value={role} disabled={busy} onChange={value=>{setRole(value);setTitle(heritageRoles[value].defaultTitle);setPersonId('')}} options={Object.entries(heritageRoles).map(([value,r])=>({value,label:r.defaultTitle}))}/><MemberPicker key={role} value={personId} onChange={setPersonId} purpose={role==='ancestral-head'?'ancestral-head':'member'} label={role==='ancestral-head'?'Ancestor':'Torch bearer'} disabled={busy} help={role==='ancestral-head'?'Choose an ancestor from the family tree to honor as an ancestral head.':'Choose a living adult family member to honor as a torch bearer, matriarch, or patriarch.'}/><ChoiceControl required label="Commemorative title" value={title} onChange={setTitle} disabled={busy} options={heritageRoles[role].titles}/><Control type="submit" className="button" disabled={!personId||busy}>{busy?'Saving…':'Save heritage role'}</Control></form>}
 </section>
}
export function HouseholdInvitation({token}){const{state,data,go}=useApp(),[invite,setInvite]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{let active=true;if(state.mode==='preview'){setError('Sign in with the invited email to accept a real invitation.');return}api('/api/household-invites/inspect',{method:'POST',body:JSON.stringify({token})}).then(v=>{if(active)setInvite(v)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[token,state.mode]);return <section className="card stack"><h1>Household invitation</h1>{error?<p role="alert">{error}</p>:invite?<><p>You’re invited to join {invite.name}.</p><p className="field-help">Your own account and private contact-sharing choices stay yours.</p><Button disabled={busy} onClick={async()=>{setBusy(true);try{const r=await api('/api/household-invites/accept',{method:'POST',body:JSON.stringify({token})});await data.refresh();go({type:'household',id:r.householdId})}catch(e){setError(e.message)}finally{setBusy(false)}}}>Accept invitation</Button></>:<p role="status">Checking your invitation…</p>}</section>}
