import React,{useEffect,useRef,useState} from 'react';
import {Button,Control,Glyph,useApp} from './ui-core.jsx';
import {ViewSwitcher} from './view-switcher.jsx';
import {InstallStepText} from './install-inline-controls.jsx';
import {InstallGuideVisual} from './install-guide-visuals.jsx';
import {installPlatform,embeddedBrowser,installedDisplay,installSteps,installGuideSources} from './install-capabilities.js';
import './help.css';
let availablePrompt=null;
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();availablePrompt=event;window.dispatchEvent(new Event('gw-install-ready'));});
export const isInstalled=()=>installedDisplay();
export function InstallGuide(){
 const {openSheet,route,goBack}=useApp(),[platform,setPlatform]=useState(()=>installPlatform(navigator)==='android'?'android':'apple'),[ready,setReady]=useState(!!availablePrompt),[installed,setInstalled]=useState(isInstalled),[busy,setBusy]=useState(false),[status,setStatus]=useState('');const lock=useRef(false),alive=useRef(true);
 useEffect(()=>{alive.current=true;const ready=()=>setReady(!!availablePrompt),check=()=>setInstalled(isInstalled()),done=()=>{availablePrompt=null;setReady(false);setInstalled(true);setStatus('Green & White was added. You can open it from your new app icon.')};const display=window.matchMedia('(display-mode: standalone)');window.addEventListener('gw-install-ready',ready);window.addEventListener('appinstalled',done);window.addEventListener('focus',check);document.addEventListener('visibilitychange',check);display.addEventListener?.('change',check);return()=>{alive.current=false;window.removeEventListener('gw-install-ready',ready);window.removeEventListener('appinstalled',done);window.removeEventListener('focus',check);document.removeEventListener('visibilitychange',check);display.removeEventListener?.('change',check)}},[]);
 const dismiss=()=>{try{localStorage.setItem('gw-install-dismissed','yes')}catch{}if(route?.type==='install')goBack();else openSheet(null)};
 const install=async()=>{if(lock.current||!availablePrompt)return;lock.current=true;setBusy(true);setStatus('');const prompt=availablePrompt;availablePrompt=null;setReady(false);try{await prompt.prompt();const result=await prompt.userChoice;if(alive.current){setInstalled(isInstalled());setStatus(result?.outcome==='accepted'?'Installation requested. Look for your new app icon.':'You can install later. The steps below are always here.')}}catch{if(alive.current)setStatus('Your browser could not open the install prompt. Use the steps below, or try again from the browser menu.')}finally{lock.current=false;if(alive.current)setBusy(false)}};
 return <div className="stack install-guide guided-help"><div className="install-intro"><img src="tree-artwork.png" alt=""/><div><h3>{installed?'Your family, one tap away.':'Keep family close.'}</h3><p>{installed?'You’re using the app view. Installation on other devices is separate.':'Add Green & White to your iOS or Android phone or tablet.'}</p></div></div>{status&&<p role="status" className="help-status">{status}</p>}{!installed&&ready&&<Button disabled={busy} aria-busy={busy} onClick={install}>{busy?'Opening install prompt…':'Install Green & White'}<Glyph name="plus"/></Button>}{!installed&&embeddedBrowser(navigator.userAgent)&&<p className="help-status">This looks like an in-app browser. Open this page in a full browser: Safari on iPhone/iPad, or Chrome on an Android phone or tablet.</p>}<ViewSwitcher label="Instructions for" value={platform} onChange={setPlatform} options={[{value:'apple',label:'iPhone / iPad',icon:'phone'},{value:'android',label:'Android',icon:'phone'}]}/><ol className="install-steps">{installSteps[platform].map((step,index)=><li key={step.title}><div className="install-step-copy"><span className="install-step-number" aria-hidden="true">{index+1}</span><div><h4>{step.title}</h4><p><InstallStepText platform={platform} step={index} text={step.text}/></p></div></div><InstallGuideVisual platform={platform} step={index}/></li>)}</ol><p className="install-guide-note muted">Illustrated guide with native-control recreations, not device screenshots. Browser versions and layouts vary. Adding the app does not turn on device notifications.</p>{!!installGuideSources[platform]?.length&&<nav className="install-source-links" aria-label="Official installation instructions">{(installGuideSources[platform]||[]).map(source=><a key={source.url} href={source.url} target="_blank" rel="noopener noreferrer">{source.label}</a>)}</nav>}<Control className="text-button" onClick={dismiss}>{route?.type==='install'?'Back':installed?'Done':'Not now'}</Control></div>
}
if('serviceWorker' in navigator&&location.protocol==='https:'&&!location.pathname.startsWith('/__review/')){const register=()=>navigator.serviceWorker.register('/sw.js',{updateViaCache:'none'}).then(reg=>reg.update()).catch(()=>{});if(document.readyState==='complete')register();else window.addEventListener('load',register,{once:true});}
