import React,{useEffect,useRef,useState} from 'react';
import {Button,Control,Glyph,useApp} from './ui-core.jsx';
import {ChoiceControl} from './choice-control.jsx';
import {installPlatform,embeddedBrowser,installedDisplay,installSteps} from './install-capabilities.js';
import './help.css';
let availablePrompt=null;
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();availablePrompt=event;window.dispatchEvent(new Event('gw-install-ready'));});
export const isInstalled=()=>installedDisplay();
export function InstallDiagram({kind,apple=false}){
 return <div className={'install-diagram install-diagram-'+kind} aria-hidden="true">{kind==='icon'?<><img src="tree-artwork.png" alt=""/><span>Green &amp; White</span></>:<><div className="install-address"><span>Green &amp; White</span>{kind==='menu'?<svg viewBox="0 0 24 24"><circle cx="12" cy="5" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="12" cy="19" r="1.5"/></svg>:<svg viewBox="0 0 24 24" fill="none"><path d="M12 15V3m-4 4 4-4 4 4M7 10H4v11h16V10h-3"/></svg>}</div><div className="install-action">{kind==='share'?<><svg viewBox="0 0 24 24" fill="none"><path d="M12 15V3m-4 4 4-4 4 4M7 10H4v11h16V10h-3"/></svg><span>Share</span></>:<><Glyph name="plus"/><span>{apple?'Add to Home Screen':'Install and create shortcut'}</span></>}</div></>}</div>
}
export function InstallGuide(){
 const {openSheet}=useApp(),[platform,setPlatform]=useState(()=>installPlatform(navigator)),[ready,setReady]=useState(!!availablePrompt),[installed,setInstalled]=useState(isInstalled),[busy,setBusy]=useState(false),[status,setStatus]=useState('');const lock=useRef(false),alive=useRef(true);
 useEffect(()=>{alive.current=true;const ready=()=>setReady(!!availablePrompt),check=()=>setInstalled(isInstalled()),done=()=>{availablePrompt=null;setReady(false);setInstalled(true);setStatus('Green & White was added. You can open it from your new app icon.')};const display=window.matchMedia('(display-mode: standalone)');window.addEventListener('gw-install-ready',ready);window.addEventListener('appinstalled',done);window.addEventListener('focus',check);document.addEventListener('visibilitychange',check);display.addEventListener?.('change',check);return()=>{alive.current=false;window.removeEventListener('gw-install-ready',ready);window.removeEventListener('appinstalled',done);window.removeEventListener('focus',check);document.removeEventListener('visibilitychange',check);display.removeEventListener?.('change',check)}},[]);
 const dismiss=()=>{try{localStorage.setItem('gw-install-dismissed','yes')}catch{}openSheet(null)};
 const install=async()=>{if(lock.current||!availablePrompt)return;lock.current=true;setBusy(true);setStatus('');const prompt=availablePrompt;availablePrompt=null;setReady(false);try{await prompt.prompt();const result=await prompt.userChoice;if(alive.current){setInstalled(isInstalled());setStatus(result?.outcome==='accepted'?'Installation requested. Look for your new app icon.':'You can install later. The steps below are always here.')}}catch{if(alive.current)setStatus('Your browser could not open the install prompt. Use the steps below, or try again from the browser menu.')}finally{lock.current=false;if(alive.current)setBusy(false)}};
 return <div className="stack install-guide guided-help"><div className="install-intro"><img src="tree-artwork.png" alt=""/><div><h3>{installed?'Your family, one tap away.':'Keep family close.'}</h3><p>{installed?'You’re using the app view. Installation on other devices is separate.':'Add Green & White to your device for an app-like view.'}</p></div></div>{status&&<p role="status" className="help-status">{status}</p>}{!installed&&ready&&<Button disabled={busy} aria-busy={busy} onClick={install}>{busy?'Opening install prompt…':'Install Green & White'}<Glyph name="plus"/></Button>}{!installed&&embeddedBrowser(navigator.userAgent)&&<p className="help-status">This looks like an in-app browser. Open this page in a full browser: Safari on iPhone/iPad, or a supported browser on Android, Mac, Windows or ChromeOS.</p>}<ChoiceControl label="Instructions for" variant="chips" value={platform} onChange={setPlatform} options={[{value:'apple',label:'iPhone / iPad'},{value:'android',label:'Android'},{value:'mac',label:'macOS'},{value:'windows',label:'Windows'},{value:'chromeos',label:'ChromeOS'},{value:'other',label:'Other browser'}]}/><ol className="install-steps">{installSteps[platform].map((step,index)=><li key={step.title}><div className="install-step-copy"><span className="install-step-number" aria-hidden="true">{index+1}</span><div><h4>{step.title}</h4><p>{step.text}</p></div></div><InstallDiagram kind={step.art} apple={platform==='apple'}/></li>)}</ol><p className="small muted">Illustrated guide. Browser menus may look different. Adding the app does not turn on device notifications.</p><Control className="text-button" onClick={dismiss}>{installed?'Done':'Not now'}</Control></div>
}
if('serviceWorker' in navigator&&location.protocol==='https:'&&!location.pathname.startsWith('/__review/')){const register=()=>navigator.serviceWorker.register('/sw.js',{updateViaCache:'none'}).then(reg=>reg.update()).catch(()=>{});if(document.readyState==='complete')register();else window.addEventListener('load',register,{once:true});}
