import {leaderPreview} from './leader-preview.js';
import React,{useEffect,useState} from 'react';
import {Button,Control,Glyph,useApp} from './ui-core.jsx';
import {api} from './live-adapter.js';
import {ManageFamily} from './manage-family.jsx';
import {DetailsForm} from './planner.jsx';
export function LeaderTools({section='overview'}){
 const {state,go,theme}=useApp(),preview=state.mode==='preview',caps=state.capabilities||{},canPlan=preview||caps.manageReunion,canPeople=preview||caps.manageMembers,canFees=preview||caps.treasurer;
 const [data,setData]=useState(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 const allowed=canPlan||canPeople||canFees;
 useEffect(()=>{if(!allowed)return;let alive=true;setError('');if(preview){setData(leaderPreview(state));return}api('/api/manage').then(value=>{if(alive)setData(value)}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[allowed,preview,refresh,preview?state:null]);
 if(!allowed)return <section className="stack"><h1>Leader Tools</h1><p>You don’t have access to these tools.</p><Button secondary onClick={()=>go({type:'you'})}>Back to You</Button></section>;
 const tabs=[['overview','Overview','grid'],canPlan&&['details','Reunion details','calendar'],canPeople&&['members','People','people'],canPlan&&['shirts','Merchandise','shirt'],canFees&&['fees','Fees','wallet']].filter(Boolean),active=tabs.some(([id])=>id===section)?section:'overview';
 const open=id=>go({type:'leader-tools',section:id});const pending=data?.members.filter(m=>m.status==='pending').length||0,going=data?.rsvps.filter(r=>r.status==='Planning to come')||[],unverified=data?.fees.filter(f=>f.status==='reported').length||0,openOrders=data?.claims.filter(o=>!['delivered','cancelled'].includes(o.status)).length||0;
 const deadlines=[['Reunion',state.details?.date],['RSVP closes',state.details?.rsvpDeadline]].filter(([,date])=>date).map(([label,date])=>({label,date,days:Math.ceil((new Date(date+'T12:00:00').getTime()-Date.now())/86400000)}));
 return <section className="stack leader-page"><header className="leader-page-heading"><div><h1>Leader Tools</h1><p className="muted">Your family plans, in one place.</p></div><Button secondary onClick={()=>setRefresh(n=>n+1)}>Refresh</Button></header><nav className="leader-tabs" aria-label="Leader tools sections">{tabs.map(([id,label,icon])=><Control key={id} aria-current={active===id?'page':undefined} onClick={()=>open(id)}><Glyph name={icon}/><span>{label}</span></Control>)}</nav>{preview&&<p className="note">Isolated preview. No real members, orders, payments, or emails are changed.</p>}{error&&<p role="alert">{error} <Control className="text-button" onClick={()=>setRefresh(n=>n+1)}>Try again</Control></p>}{!data&&!error?<p role="status">Loading the latest family activity…</p>:active==='overview'?<div className="leader-overview"><section className="leader-priorities"><h2>Needs attention</h2>{data&&<>{canPeople&&<SummaryRow icon="people" label="Membership requests" detail={pending?'Review who’s waiting to join.':'No requests waiting.'} value={pending} onClick={()=>open('members')}/>} {canFees&&<SummaryRow icon="wallet" label="Payment reports" detail={unverified?'Check the payment service before confirming.':'No payments waiting for verification.'} value={unverified} onClick={()=>open('fees')}/>} {canPlan&&<SummaryRow icon="shirt" label="Orders to fulfill" detail={openOrders?'Review ordering, pickup, and delivery.':'No open orders.'} value={openOrders} onClick={()=>open('shirts')}/>}</>}</section><section className="leader-reunion-summary"><h2>The next gathering</h2>{canPlan&&<><p className="leader-attendance"><strong>{going.reduce((n,r)=>n+Number(r.count||0),0)}</strong><span>people planning to come<br/>{going.length} household replies</span></p><Button secondary onClick={()=>open('details')}>Manage reunion details</Button></>}{deadlines.length?<dl className="leader-deadlines">{deadlines.map(d=><div key={d.label}><dt>{d.label}</dt><dd><time dateTime={d.date}>{new Date(d.date+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'})}</time><span>{d.days<0?'Date passed':d.days===0?'Today':d.days+' days away'}</span></dd></div>)}</dl>:<p className="muted">Dates haven’t been set yet.</p>}</section></div>:active==='details'?<div className="leader-details-layout"><section className="card"><h2>Reunion details</h2><DetailsForm onSaved={()=>setRefresh(n=>n+1)}/></section><section className="card"><ManageFamily section="rsvp" embedded/></section></div>:<ManageFamily key={active} section={active} embedded/>}</section>;
}
function SummaryRow({icon,label,detail,value,onClick}){return <Control className="leader-summary-row" onClick={onClick}><Glyph name={icon}/><span><strong>{label}</strong><small>{detail}</small></span><b>{value}</b><Glyph name="arrow"/></Control>}
