import React,{useEffect,useState} from 'react';
import {api} from './live-adapter.js';
import {Button,Control,useApp} from './ui-core.jsx';
export function ManageFamily(){const {state,dispatch}=useApp(),[items,setItems]=useState(null),[error,setError]=useState(''),[tab,setTab]=useState('members'),[name,setName]=useState(''),[description,setDescription]=useState(''),[price,setPrice]=useState('');
 const load=()=>api('/api/manage').then(setItems).catch(e=>setError(e.message));useEffect(()=>{load()},[]);
 const act=async action=>{setError('');if(await dispatch(action))await load()};
 const options=[state.capabilities?.manageMembers&&['members','People'],state.capabilities?.manageReunion&&['rsvp','RSVPs'],state.capabilities?.manageReunion&&['shirts','Shirts'],state.capabilities?.treasurer&&['fees','Fees']].filter(Boolean);
 const active=options.some(x=>x[0]===tab)?tab:options[0]?.[0];if(!options.length)return <p>You don’t have access to these tools.</p>;
 return <section className="stack"><h2>Family organizer</h2><div className="segmented" role="tablist" aria-label="Organizer tools">{options.map(([id,label])=><Control key={id} role="tab" aria-selected={active===id} onClick={()=>setTab(id)}>{label}</Control>)}</div>{error&&<p role="alert">{error}</p>}{!items?<p role="status">Loading family details…</p>:<>
 {active==='members'&&<div className="stack">{!items.members.some(m=>m.status==='pending')&&<p className="muted">No new requests waiting.</p>}{items.members.map(m=><MemberReview key={m.id} member={m} selfId={state.selfId} onSave={act}/>)}</div>}
 {active==='rsvp'&&<div className="card stack"><h3>Household replies</h3>{items.rsvps.map(r=><div className="list-row" key={r.member_id}><span><strong>{r.name}</strong><p>{r.status} · {r.count} {r.count===1?'person':'people'}</p></span></div>)}{!items.rsvps.length&&<p>No replies yet.</p>}</div>}
 {active==='shirts'&&<><form className="card stack" onSubmit={async e=>{e.preventDefault();if(await dispatch({type:'SAVE_PRODUCT',product:{name,description,price}})){setName('');setDescription('');setPrice('');load()}}}><h3>Add this year’s shirt</h3><label>Name<input required value={name} onChange={e=>setName(e.target.value)} maxLength="100"/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength="1000"/></label><label>Price or contribution note<input value={price} onChange={e=>setPrice(e.target.value)} maxLength="60" placeholder="Leave empty until confirmed"/></label><Control className="button" type="submit">Add shirt</Control></form><div className="card stack"><h3>Claims and fulfillment</h3>{items.claims.map(c=><div className="stack" key={c.id}><strong>{c.name}</strong><p>{JSON.parse(c.lines_json).map(l=>`${l.size} × ${l.quantity}`).join(' · ')}</p><label>Order status<select value={c.status} onChange={e=>act({type:'UPDATE_CLAIM',id:c.id,status:e.target.value})} disabled={c.status==='delivered'}>{['claimed','ordered','ready','shipped','delivered'].map(v=><option key={v} value={v}>{v}</option>)}</select></label></div>)}{!items.claims.length&&<p>No shirt claims yet.</p>}</div></>}
 {active==='fees'&&<div className="card stack"><h3>Payment reports</h3><p className="muted">Check the actual payment service before confirming receipt.</p>{items.fees.map(f=><div key={f.id} className="stack"><strong>{f.name}</strong><p>{f.status}</p>{f.status==='reported'&&<div className="card-actions"><Button secondary onClick={()=>act({type:'CONFIRM_FEE',id:f.id,status:'rejected'})}>Not received</Button><Button onClick={()=>act({type:'CONFIRM_FEE',id:f.id,status:'confirmed'})}>Receipt verified</Button></div>}</div>)}{!items.fees.length&&<p>No payments reported yet.</p>}</div>}
 </>}</section>
}
function MemberReview({member:m,selfId,onSave}){const [roles,setRoles]=useState(()=>JSON.parse(m.roles_json||'[]')),[post,setPost]=useState(Boolean(m.can_post));return <article className="card stack"><div><h3>{m.name}</h3><p className="muted small">{m.email} · {m.status}</p></div>{m.id===selfId?<p className="muted small">Your account</p>:<><label className="check-row"><input type="checkbox" checked={post} onChange={e=>setPost(e.target.checked)}/>Can post updates</label><details><summary>Organizer roles</summary>{['admin','moderator','planner','treasurer'].map(role=><label key={role} className="check-row"><input type="checkbox" checked={roles.includes(role)} onChange={e=>setRoles(r=>e.target.checked?[...r,role]:r.filter(x=>x!==role))}/>{role[0].toUpperCase()+role.slice(1)}</label>)}</details><div className="card-actions"><Button secondary onClick={()=>onSave({type:'APPROVE_MEMBER',id:m.id,status:'suspended',roles,canPost:post})}>Pause access</Button><Button onClick={()=>onSave({type:'APPROVE_MEMBER',id:m.id,status:'active',roles,canPost:post})}>{m.status==='active'?'Save membership':'Approve membership'}</Button></div></>}</article>}
