import {MerchandiseManager} from './merchandise-manager.jsx';
import React,{useEffect,useState} from 'react';
import {api} from './live-adapter.js';
import {Button,Control,useApp} from './ui-core.jsx';
export function ManageFamily({section,embedded=false}){const {state,dispatch}=useApp(),[items,setItems]=useState(null),[error,setError]=useState(''),[tab,setTab]=useState(section||'members'),[name,setName]=useState(''),[description,setDescription]=useState(''),[price,setPrice]=useState('');
 const preview=state.mode==='preview';const load=()=>preview?Promise.resolve(setItems({members:[],rsvps:state.rsvp?[{...state.rsvp,member_id:state.selfId,name:state.members.find(m=>m.id===state.selfId)?.name}]:[],claims:[],fees:[]})):api('/api/manage').then(setItems).catch(e=>setError(e.message));useEffect(()=>{load()},[]);useEffect(()=>{if(section)setTab(section)},[section]);
 const act=async action=>{setError('');if(await dispatch(action))await load()};
 const options=[(preview||state.capabilities?.manageMembers)&&['members','People'],(preview||state.capabilities?.manageReunion)&&['rsvp','RSVPs'],(preview||state.capabilities?.manageReunion)&&['shirts','Merchandise'],(preview||state.capabilities?.treasurer)&&['fees','Fees']].filter(Boolean);
 const active=options.some(x=>x[0]===tab)?tab:options[0]?.[0];if(!options.length)return <p>You don’t have access to these tools.</p>;
 return <section className="stack">{!embedded&&<><h2>Family organizer</h2><div className="segmented" role="tablist" aria-label="Organizer tools">{options.map(([id,label])=><Control key={id} role="tab" aria-selected={active===id} onClick={()=>setTab(id)}>{label}</Control>)}</div></>}{error&&<p role="alert">{error}</p>}{!items?<p role="status">Loading family details…</p>:<>
 {active==='members'&&<div className="stack">{!items.members.some(m=>m.status==='pending')&&<p className="muted">No new requests waiting.</p>}{items.members.map(m=><MemberReview key={m.id} member={m} selfId={state.selfId} onSave={act}/>)}</div>}
 {active==='rsvp'&&<div className="card stack"><h3>Household replies</h3>{items.rsvps.map(r=><div className="list-row" key={r.member_id}><span><strong>{r.name}</strong><p>{r.status} · {r.count} {r.count===1?'person':'people'}</p></span></div>)}{!items.rsvps.length&&<p>No replies yet.</p>}</div>}
 {active==='shirts'&&<MerchandiseManager items={items} onRefresh={load}/>}
 {active==='fees'&&<div className="card stack"><h3>Payment reports</h3><p className="muted">Check the actual payment service before confirming receipt.</p>{items.fees.map(f=><div key={f.id} className="stack"><strong>{f.name}</strong><p>{f.status}</p>{f.status==='reported'&&<div className="card-actions"><Button secondary onClick={()=>act({type:'CONFIRM_FEE',id:f.id,status:'rejected'})}>Not received</Button><Button onClick={()=>act({type:'CONFIRM_FEE',id:f.id,status:'confirmed'})}>Receipt verified</Button></div>}</div>)}{!items.fees.length&&<p>No payments reported yet.</p>}</div>}
 </>}</section>
}
function MemberReview({member:m,selfId,onSave}){const [roles,setRoles]=useState(()=>JSON.parse(m.roles_json||'[]')),[post,setPost]=useState(Boolean(m.can_post));return <article className="card stack"><div><h3>{m.name}</h3><p className="muted small">{m.email} · {m.status}</p></div>{m.id===selfId?<p className="muted small">Your account</p>:<><label className="check-row"><input type="checkbox" checked={post} onChange={e=>setPost(e.target.checked)}/>Can post updates</label><details><summary>Organizer roles</summary>{['admin','moderator','planner','treasurer'].map(role=><label key={role} className="check-row"><input type="checkbox" checked={roles.includes(role)} onChange={e=>setRoles(r=>e.target.checked?[...r,role]:r.filter(x=>x!==role))}/>{role[0].toUpperCase()+role.slice(1)}</label>)}</details><div className="card-actions"><Button secondary onClick={()=>onSave({type:'APPROVE_MEMBER',id:m.id,status:'suspended',roles,canPost:post})}>Pause access</Button><Button onClick={()=>onSave({type:'APPROVE_MEMBER',id:m.id,status:'active',roles,canPost:post})}>{m.status==='active'?'Save membership':'Approve membership'}</Button></div></>}</article>}
