import {PhotoViewer} from './photo-viewer.jsx';
import {CardContentLayout} from './card-content-layout.jsx';
import {BrowseControls} from './browse-controls.jsx';
import {SharedPagePanels} from './page-panels.jsx';
import {EditableText,EditableMedia,usePageContent} from './page-content.jsx';
import {ChoiceControl} from './choice-control.jsx';
import {ImageUploadControl} from './image-upload-control.jsx';
import {InlineDisclosure} from './inline-disclosure.jsx';
import './form-layout.css';
import './memory-details.css';
import {TaggedFamily} from './member-tags.jsx';
import {directoryPerson} from './member-directory.js';
import {MemberPicker} from './member-picker.jsx';
import {memoryMetadata} from './memory-metadata.js';
import {readPreviewFile} from './uploads.js';
import {MemoryGallery} from './field-gallery/MemoryGallery.jsx';
import React,{useState,useRef} from 'react';
import {Control,Avatar,Button,Glyph,MemberBadges,InlineFilters,useApp,useSheetForm} from './ui-core.jsx';
import {CommentsView,ReactionBar} from './conversation.jsx';
const layouts=[['Grid','grid'],['Natural','mosaic'],['Strip','image'],['Carousel','carousel']];
export function Memories(){
 const memoryPage=usePageContent('memories');
  const {state,openSheet,dispatch,setToast}=useApp(),[layout,setLayout]=useState('Grid'),[search,setSearch]=useState(''),[uploading,setUploading]=useState(false),[progress,setProgress]=useState(''),[recent,setRecent]=useState([]),[section,setSection]=useState('all'),picker=useRef(null),filters=state.memoryFilters||{},admin=state.mode==='preview'||state.capabilities?.manageMembers;
  async function addFiles(selected){if(uploading)return;const files=[...selected].slice(0,10);setUploading(true);setRecent([]);const added=[];try{for(let i=0;i<files.length;i++){setProgress('Adding '+(i+1)+' of '+files.length+'…');try{const file=files[i],metadata=await memoryMetadata(file),upload=await readPreviewFile(file,state.mode),memory={id:crypto.randomUUID(),title:'',image:upload.url,photoFrame:undefined,mediaType:upload.type||file.type,authorId:state.selfId,category:'',tags:[],memberIds:[],event:'',year:'',milestone:'',...metadata};if(await dispatch({type:'ADD_MEMORY',memory}))added.push(memory.id)}catch(e){setToast({kind:'error',message:files[i].name+': '+e.message})}}setRecent(added);setProgress(added.length+' '+(added.length===1?'memory added.':'memories added.'));if(added.length===1)openSheet({type:'memory-edit',id:added[0]})}finally{setUploading(false)}}
  const shown=state.memories.filter(m=>[m.title,m.category,m.event,m.year,m.milestone].filter(Boolean).join(' ').toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())).filter(m=>Object.entries(filters).every(([k,v])=>!v||(k==='member'?m.memberIds?.includes(v):m[k]===v)));
  return <div className="stack memories-page"><SharedPagePanels page="memories" nativePanels={{'native-gallery':<>{progress&&<p role="status" className="memory-upload-status">{progress}</p>}{recent.length>1&&<details className="form-more"><summary>Add details or tag family · optional</summary>{recent.map(id=><Button secondary key={id} onClick={()=>openSheet({type:'memory-edit',id})}>Add details</Button>)}</details>}{admin&&<div className="segmented" role="tablist" aria-label="Memories sections"><Control role="tab" aria-selected={section==='all'} onClick={()=>setSection('all')}>All memories</Control><Control role="tab" aria-selected={section==='featured'} onClick={()=>setSection('featured')}>Featured photos</Control></div>}{section==='featured'&&admin?<FeaturedPhotos/>:<><div className="section-head"><EditableText page="memories" field="listTitle" as="h2">Shared memories</EditableText></div><BrowseControls label="Memory" search={search} onSearch={setSearch} placeholder="Find a memory" views={layouts.map(([name,icon])=>({value:name,label:name,icon}))} view={layout} onView={setLayout} filters={<MemoryFilters/>} organize={<div className="stack"><Button secondary disabled={uploading} onClick={()=>picker.current?.click()}>Add a memory</Button>{admin&&<Button secondary onClick={()=>setSection('featured')}>Manage featured photos</Button>}</div>}/><MemoryGallery items={shown} view={layout.toLowerCase()} onOpen={id=>openSheet({type:'memory',id})}/>{!shown.length&&<EditableText page="memories" field="emptyBody" as="p">No memories match these filters.</EditableText>}</>}</>}}><section className="card memories-hero"><CardContentLayout page="memories" hidden={memoryPage.editing||memoryPage.content?.hero?.mode!=='default'?[]:['media']} items={{
 eyebrow:<EditableText page="memories" field="heroEyebrow" as="span" className="eyebrow">Memory lane</EditableText>,
 title:<EditableText page="memories" field="heroTitle" as="h2">Little moments.<br/>Big stories.</EditableText>,
 body:<EditableText page="memories" field="heroBody" as="p" className="muted">The photos and stories we keep coming back to.</EditableText>,
 action:<Button secondary disabled={uploading} onClick={()=>picker.current?.click()}>{uploading?progress:'Add a memory'}</Button>,
 media:<EditableMedia page="memories" field="hero"/>
 }}/><input ref={picker} type="file" className="sr-only" aria-label="Add memory files" multiple accept="image/png,image/jpeg,image/webp,image/gif,video/mp4,video/webm,audio/*,.pdf" onChange={e=>{const files=[...e.target.files];e.target.value='';void addFiles(files)}}/></section></SharedPagePanels></div>
}
export function MemoryFilters(){
  const {state,dispatch}=useApp(),filters=state.memoryFilters||{};
  const fields=['category','member','event','year','milestone'];
  const choices=field=>[...new Set(state.memories.flatMap(m=>field==='member'?m.memberIds||[]:[m[field]]).filter(Boolean))];
  return <div className="memory-filters">{fields.map(field=><ChoiceControl key={field} label={field[0].toUpperCase()+field.slice(1)} variant="search" value={filters[field]||''} onChange={value=>dispatch({type:'SET_MEMORY_FILTERS',value:{...filters,[field]:value}})} options={[{value:'',label:'All'},...choices(field).map(value=>({value,label:field==='member'?directoryPerson(state,value)?.name||'Unavailable person':value}))]}/>)}<Button secondary onClick={()=>dispatch({type:'SET_MEMORY_FILTERS',value:{}})}>Clear filters</Button></div>
}
export function MemoryMedia({memory:m,className='memory-large'}){const type=m.mediaType||'image/jpeg';return type.startsWith('video/')?<video className={className} src={m.image} controls playsInline preload="metadata"/>:type.startsWith('audio/')?<audio className={className} src={m.image} controls preload="metadata"/>:type.startsWith('image/')?<img className={className} src={m.image} alt={m.title||'Family memory'}/>:<a className="button" href={m.image} target="_blank" rel="noreferrer">Open memory file</a>}
export function FeaturedPhotos(){const {state,dispatch}=useApp(),[busy,setBusy]=useState('');const ids=new Set(state.featuredMemoryIds||[]);async function feature(m,approved,primary=false){setBusy(m.id);try{await dispatch({type:'FEATURE_MEMORY',id:m.id,approved,primary})}finally{setBusy('')}}return <section className="stack featured-photos"><div><h2>Photos for the family space</h2><p className="muted">Approve photos for the home and Memories pages. Only signed-in family members can see them.</p></div>{state.memories.filter(m=>!m.mediaType||m.mediaType.startsWith('image/')).map(m=><article key={m.id} className="featured-photo-row"><img src={m.image} alt={m.title||'Family memory'}/><div><strong>{m.title||'Family photo'}</strong><p className="muted small">{state.primaryMemoryId===m.id?'Main photo':ids.has(m.id)?'Approved for the UI':'Not featured'}</p><div className="row"><Button secondary disabled={!!busy} onClick={()=>feature(m,!ids.has(m.id))}>{busy===m.id?'Saving…':ids.has(m.id)?'Remove from featured':'Approve photo'}</Button>{ids.has(m.id)&&state.primaryMemoryId!==m.id&&<Button secondary disabled={!!busy} onClick={()=>feature(m,true,true)}>Use as main photo</Button>}</div></div></article>)}{!state.memories.length&&<p className="muted">Add photos to Memories first. They won’t be featured until you approve them here.</p>}</section>}
export function MemoryViewer({id}){const {state,openSheet,go}=useApp(),m=state.memories.find(x=>x.id===id);if(!m)return null;const author=state.members.find(x=>x.id===m.authorId);if((m.mediaType||'image/jpeg').startsWith('image/'))return <PhotoViewer kind="memory" id={id}>{m.title&&<h2>{m.title}</h2>}<p className="muted">{[m.category,m.event,m.dateStatus==='suggested'?'Date not confirmed':m.capturedDate||m.year,m.milestone].filter(Boolean).join(' · ')}</p><TaggedFamily ids={m.memberIds||[]}/>{(m.authorId===state.selfId||state.capabilities?.moderate||state.mode==='preview')&&<Button secondary onClick={()=>openSheet({type:'memory-edit',id:m.id})}>Add or edit details</Button>}</PhotoViewer>;return <div className="stack"><MemoryMedia memory={m}/>{m.title&&<h2>{m.title}</h2>}<Control className="member-link" onClick={()=>{openSheet(null);go({type:'profile',id:m.authorId})}}><Avatar member={author}/><span>{author?.name}</span></Control><p className="muted">{[m.category,m.event,m.dateStatus==='suggested'?'Date not confirmed':m.capturedDate||m.year,m.milestone].filter(Boolean).join(' · ')}</p><TaggedFamily ids={m.memberIds||[]}/><ReactionBar targetId={m.id}/>{(m.authorId===state.selfId||state.capabilities?.moderate||state.mode==='preview')&&<Button secondary onClick={()=>openSheet({type:'memory-edit',id:m.id})}>Add or edit details</Button>}<h3>Comments</h3><CommentsView targetId={m.id}/></div>}
export function MemoryEditor({id}){
 const {state,dispatch,openSheet}=useApp(),existing=state.memories.find(x=>x.id===id),[m,setM]=useState(existing||{id:crypto.randomUUID(),title:'',image:null,authorId:state.selfId,category:'',tags:[],memberIds:[],event:'',year:'',milestone:''}),[error,setError]=useState(''),[fileError,setFileError]=useState(''),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),uploadLock=useRef(false),otherMedia=useRef(null),set=(k,v)=>setM(x=>({...x,[k]:v}));
 const initialMemory=useRef(JSON.stringify(m)),saveLock=useRef(false),formId=useSheetForm({label:'Save memory details',busy:saving||uploading,disabled:!m.image||saving||uploading,dirty:JSON.stringify(m)!==initialMemory.current});
 const image=!m.mediaType||m.mediaType.startsWith('image/'),featured=existing&&(state.featuredMemoryIds||[]).includes(existing.id),mediaLabel=m.mediaType?.startsWith('video/')?'Video memory':m.mediaType?.startsWith('audio/')?'Audio memory':'PDF memory';
 async function chooseFile(file){if(uploadLock.current||saving)return;uploadLock.current=true;setUploading(true);setFileError('');try{if(!/^(image\/(png|jpeg|webp|gif|avif)|video\/(mp4|webm)|audio\/[\w.+-]+|application\/pdf)$/.test(file.type))throw Error('Choose a photo, MP4 or WebM video, audio, or PDF memory.');const metadata=await memoryMetadata(file),upload=await readPreviewFile(file,state.mode);setM(x=>({...x,image:upload.url,photoFrame:undefined,mediaType:upload.type||file.type,...(x.dateStatus==='suggested'?{capturedDate:'',dateStatus:'unknown',dateSource:''}:{}),...metadata}))}catch(e){setFileError(e.message)}finally{uploadLock.current=false;setUploading(false)}}
 async function save(e){e.preventDefault();if(!m.image||uploadLock.current||saveLock.current)return;saveLock.current=true;setSaving(true);setError('');try{if(await dispatch({type:existing?'SAVE_MEMORY':'ADD_MEMORY',memory:m}))openSheet(null)}catch(e){setError(e.message)}finally{saveLock.current=false;setSaving(false)}}
 return <form id={formId} className="gw-form memory-details-form form-density-scope" onSubmit={save}><p className="field-help">{existing?'Your memory is saved. Add any details you know, or close this window.':'Choose a file. Details are optional.'}</p>{featured&&<p className="field-help">Changing the file removes its featured-photo approval when you save. A family organizer can approve the new photo again.</p>}<div className="form-image-intro">
  <div className="form-image-control">{image?<ImageUploadControl label="Memory photo" src={m.image||''} alt={m.title||'Current memory photo'} showReplace={false} shape="profile" accept="image/png,image/jpeg,image/webp,image/gif,image/avif" busy={uploading} disabled={saving} error={fileError} frame={m.photoFrame} onFrameChange={frame=>set('photoFrame',frame)} onFiles={files=>chooseFile(files[0])}/>:<div className="form-media-control"><span className="form-media-label">{mediaLabel}</span><MemoryMedia memory={m} className="memory-edit-compact-media"/>{uploading&&<p role="status" className="field-help">Adding file…</p>}{fileError&&<p className="form-error" role="alert">{fileError}</p>}</div>}<Button secondary type="button" disabled={uploading||saving} onClick={()=>otherMedia.current?.click()}><Glyph name="image"/>Replace media</Button><input ref={otherMedia} className="sr-only" type="file" tabIndex={-1} aria-label="Replace memory file" accept="image/png,image/jpeg,image/webp,image/gif,image/avif,video/mp4,video/webm,audio/*,.pdf" disabled={uploading||saving} onChange={e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';if(file)void chooseFile(file)}}/></div>
  <div className="form-image-fields"><label><span className="form-label">Caption <span className="field-optional">Optional</span></span><input value={m.title||''} maxLength="120" placeholder="What would you like to remember?" disabled={saving} onChange={e=>set('title',e.target.value)}/></label><div className="form-short-row"><label><span className="form-label">Date <span className="field-optional">If known</span></span><input type="date" value={m.capturedDate||''} max={new Date().toISOString().slice(0,10)} disabled={saving} onChange={e=>setM(x=>({...x,capturedDate:e.target.value,dateStatus:e.target.value?'confirmed':'unknown',dateSource:'entered'}))}/></label><label><span className="form-label">Year <span className="field-optional">If that’s all you know</span></span><input inputMode="numeric" maxLength="4" value={m.year||''} placeholder="e.g. 2008" disabled={saving} onChange={e=>set('year',e.target.value.replace(/\D/g,''))}/></label></div></div>
 </div>{m.dateStatus==='suggested'&&m.capturedDate&&<div className="memory-date-question"><strong>Was this taken on {m.capturedDate}?</strong><p className="field-help">The file includes this date. Your best recollection is enough.</p><div className="row"><Button secondary disabled={uploading||saving} onClick={()=>set('dateStatus','confirmed')}>Looks right</Button><Button secondary disabled={uploading||saving} onClick={()=>setM(x=>({...x,capturedDate:'',dateStatus:'unknown',dateSource:''}))}>Not sure</Button></div></div>}{m.capturedDate&&<label className="check-row"><input type="checkbox" checked={m.dateStatus==='approximate'} disabled={saving} onChange={e=>set('dateStatus',e.target.checked?'approximate':'confirmed')}/>This date is approximate</label>}<InlineDisclosure icon="people" className="memory-details-disclosure" chevron label="Tag family" openLabel="Hide family tags" summary={(m.memberIds||[]).map(id=>directoryPerson(state,id)?.name).filter(Boolean).join(', ')} populated={!!m.memberIds?.length} disabled={saving}><div className="form-section"><MemberPicker label="Find family to tag" purpose="tag" multiple value={m.memberIds||[]} disabled={saving} onChange={ids=>set('memberIds',ids)}/></div></InlineDisclosure><InlineDisclosure icon="calendar" className="memory-details-disclosure" chevron label={m.event||m.category||m.milestone?'Edit event details':'Add event details'} openLabel="Hide event details" summary={[m.event,m.category,m.milestone].filter(Boolean).join(' · ')} populated={!!(m.event||m.category||m.milestone)} disabled={saving}><div className="form-section memory-event-fields"><label><span className="form-label">Event <span className="field-optional">Optional</span></span><input maxLength="100" value={m.event||''} disabled={saving} onChange={e=>set('event',e.target.value)}/></label><label><span className="form-label">Category <span className="field-optional">Optional</span></span><input maxLength="60" value={m.category||''} disabled={saving} onChange={e=>set('category',e.target.value)}/></label><label><span className="form-label">Milestone <span className="field-optional">Optional</span></span><input maxLength="100" value={m.milestone||''} disabled={saving} onChange={e=>set('milestone',e.target.value)}/></label></div></InlineDisclosure>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-save"><Control className="button form-primary" type="submit" disabled={!m.image||saving||uploading}>{saving?'Saving…':existing?'Save details':'Save memory'}</Control></div></form>
}
