import {readPreviewFile} from './uploads.js';
import {MemoryGallery} from './field-gallery/MemoryGallery.jsx';
import React,{useState} from 'react';
import {Control,Avatar,Button,Glyph,MemberBadges,InlineFilters,useApp} from './ui-core.jsx';
import {CommentsView,ReactionBar} from './conversation.jsx';
const layouts=['Grid','Natural','Strip','Story','Carousel'];
export function Memories(){
  const {state,openSheet}=useApp(),[layout,setLayout]=useState('Grid'),filters=state.memoryFilters||{};
  const shown=state.memories.filter(m=>Object.entries(filters).every(([k,v])=>!v||(k==='member'?m.memberIds?.includes(v):m[k]===v)));
  return <div className="stack memories-page"><section className="card memories-hero"><div><span className="eyebrow">Memory lane</span><h2>Little moments.<br/>Big stories.</h2><p className="muted">The photos and stories we keep coming back to.</p><Button secondary onClick={()=>openSheet({type:'memory-edit'})}>Add a memory</Button></div><div className="memory-hero-art"><img src="photos/garden.jpg" alt="Family enjoying the garden"/><img src="photos/generations.jpg" alt="Three generations together"/></div></section><div className="section-head"><h2>Shared memories</h2><div className="memory-actions"><InlineFilters label="Filter memories"><MemoryFilters/></InlineFilters><div className="view-icons" role="group" aria-label="Memory layout">{[['Grid','grid'],['Natural','mosaic'],['Strip','image'],['Story','book'],['Carousel','carousel']].map(([name,icon])=><Control key={name} aria-label={name+' view'} title={name+' view'} aria-pressed={layout===name} onClick={()=>setLayout(name)}><Glyph name={icon}/></Control>)}</div></div></div><MemoryGallery items={shown} view={layout.toLowerCase()} onOpen={id=>openSheet({type:'memory',id})}/>{!shown.length&&<p>No memories match these filters.</p>}</div>
}
export function MemoryFilters(){
  const {state,dispatch}=useApp(),filters=state.memoryFilters||{};
  const fields=['category','member','event','year','milestone'];
  const choices=field=>[...new Set(state.memories.flatMap(m=>field==='member'?m.memberIds||[]:[m[field]]).filter(Boolean))];
  return <div className="memory-filters">{fields.map(field=><label key={field}>{field[0].toUpperCase()+field.slice(1)}<select value={filters[field]||''} onChange={e=>dispatch({type:'SET_MEMORY_FILTERS',value:{...filters,[field]:e.target.value}})}><option value="">All</option>{choices(field).map(x=><option key={x} value={x}>{field==='member'?state.members.find(m=>m.id===x)?.name:x}</option>)}</select></label>)}<Button secondary onClick={()=>dispatch({type:'SET_MEMORY_FILTERS',value:{}})}>Clear filters</Button></div>
}
export function MemoryViewer({id}){const {state,openSheet,go}=useApp(),m=state.memories.find(x=>x.id===id);if(!m)return null;const author=state.members.find(x=>x.id===m.authorId);return <div className="stack"><img className="memory-large" src={m.image} alt={m.title}/><h2>{m.title}</h2><Control className="member-link" onClick={()=>{openSheet(null);go({type:'profile',id:m.authorId})}}><Avatar member={author}/><span>{author?.name}</span></Control><p className="muted">{[m.category,m.event,m.year,m.milestone].filter(Boolean).join(' · ')}</p><ReactionBar targetId={m.id}/><Button secondary onClick={()=>openSheet({type:'memory-edit',id:m.id})}>Edit tags</Button><h3>Comments</h3><CommentsView targetId={m.id}/></div>}
export function MemoryEditor({id}){const {state,dispatch,openSheet,setToast}=useApp(),existing=state.memories.find(x=>x.id===id),[m,setM]=useState(existing||{title:'',image:null,authorId:state.selfId,category:'Family moments',tags:[],memberIds:[],event:'',year:new Date().getFullYear().toString(),milestone:''}),set=(k,v)=>setM(x=>({...x,[k]:v}));return <form className="stack" onSubmit={e=>{e.preventDefault();if(!m.image)return;dispatch({type:existing?'SAVE_MEMORY':'ADD_MEMORY',memory:m});openSheet(null)}}><label>Title<input required value={m.title} onChange={e=>set('title',e.target.value)}/></label><label>Photo<input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];try{if(f)set('image',(await readPreviewFile(f)).url)}catch(error){setToast(error.message)}}}/></label>{m.image&&<img className="photo" src={m.image} alt="Memory"/>}<label>Category<input value={m.category} onChange={e=>set('category',e.target.value)}/></label><label>People<select multiple value={m.memberIds} onChange={e=>set('memberIds',[...e.target.selectedOptions].map(x=>x.value))}>{state.members.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Event<input value={m.event} onChange={e=>set('event',e.target.value)}/></label><label>Year<input value={m.year} onChange={e=>set('year',e.target.value)}/></label><label>Milestone<input value={m.milestone} onChange={e=>set('milestone',e.target.value)}/></label><Control className="button" type="submit">Save memory</Control></form>}
