import {useImageEditDraft} from './use-image-edit-draft.jsx';
import {PageObjectTools} from './page-object-tools.jsx';
import {PAGE_ELEMENT_TYPES,MAX_PAGE_ELEMENTS} from './page-elements-model.js';
import {cardSlots,cardLayoutOf,addCardElement,setCardSlotRemoved,updateCardLayout} from './card-content-layout-model.js';
import {CardContentLayout} from './card-content-layout.jsx';
import {LayoutGlyph as ElementLayoutGlyph,ImageLayoutContext} from './image-edit-controls.jsx';
import {PhotoFramingEditor,photoFrameStyle} from './photo-framing.jsx';
import {InlineDisclosure} from './inline-disclosure.jsx';
import {ImageUploadControl} from './image-upload-control.jsx';
import {PageMarkdownEditor,PageMarkdownBody} from './page-markdown.jsx';
import React,{useContext,useEffect,useId,useLayoutEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Button,Control,Glyph,Sheet,useApp} from './ui-core.jsx';
import {usePageContent,PagePanelLockContext,safePageMediaUrl} from './page-content.jsx';
import {readPreviewFile} from './uploads.js';
import {SHARED_IMAGE_TYPES,SHARED_CONTENT_LIMITS,SHARED_PAGE_SCHEMA,validateSharedPageContent} from './shared-content-schema.js';
import {PANEL_PRESETS,PANEL_LIMITS,panelLayoutOf,createSharedPanel,addSharedPanel,changeSharedPanel,removeSharedPanel,restoreSharedPanel,moveSharedPanel,stepSharedPanel,canRelockPanel,sharedPanelTitle,keyboardSharedPanel,activePanelPage,REUNION_PANEL_PAGES,isHeroPanel,setSharedPanelHero,panelLayoutBands} from './shared-panels.js';
import './page-panels.css';
import {ChoiceControl} from './choice-control.jsx';
const title=(panel,page,content,records)=>sharedPanelTitle(page,panel,content,records);
const zoneLabel=zone=>zone==='side'?'Side area':'Main area';
import {useNarrow} from './use-narrow.js';
function OptionalPageMedia({initialOpen,children}){const [open,setOpen]=useState(initialOpen);return <details className="page-optional-media" open={open} onToggle={event=>setOpen(event.currentTarget.open)}>{children}</details>}
function LayoutGlyph({layout}){return <svg viewBox="0 0 48 34" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><rect x="2" y="2" width="44" height="30" rx="3"/>{layout==='text'?<path d="M9 10h22M9 16h30M9 22h25"/>:layout==='columns'?<path d="M9 10h12M9 16h12M9 22h12M27 10h12M27 16h12M27 22h12"/>:layout==='photo'?<><rect x="8" y="7" width="32" height="12" rx="1"/><path d="M8 24h32M8 28h22"/></>:<><rect x="8" y="7" width="14" height="20" rx="1"/><path d="M27 10h13M27 16h13M27 22h10"/></>}</svg>;}
function DragGlyph(){return <svg className="glyph" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M8 5h1m6 0h1M8 12h1m6 0h1M8 19h1m6 0h1" strokeLinecap="round"/></svg>;}
function LockGlyph({locked}){return <svg className="glyph" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><rect x="5" y="10" width="14" height="11" rx="2"/>{locked?<path d="M8 10V7a4 4 0 0 1 8 0v3"/>:<path d="M8 10V7a4 4 0 0 1 8 0"/>}<path d="M12 14v3"/></svg>;}
function useLayoutEditor(page){const editor=usePageContent(page),layout=panelLayoutOf(editor.content,page),busy=editor.pending||editor.record?.status==='saving';const change=(fn,historyLabel)=>{let changed=false;const updated=editor.update(page,content=>{const layout=panelLayoutOf(content,page),next=fn(layout);changed=next!==layout;return {...content,panelLayout:next}},{historyLabel});return updated&&changed;};return {...editor,layout,busy,change};}
// Pointer capture supports tablet touch dragging. Native drag supports mouse;
// all mutations also have ordinary buttons and a labelled location select.
function usePanelDrag({disabled,onMove,onKeyMove}){
 const [dragging,setDragging]=useState(null),[over,setOver]=useState(null),gesture=useRef(null),root=useRef(null);
 const reset=()=>{gesture.current?.node?.style.removeProperty('transform');gesture.current=null;setDragging(null);setOver(null);};
 useEffect(()=>{if(disabled)reset()},[disabled]);
 const targetAt=(x,y)=>{const node=document.elementFromPoint(x,y)?.closest('[data-panel-drop]');if(!node||!root.current?.contains(node))return null;const panel=node.closest('[data-panel-id]');return {zone:node.dataset.panelDrop,beforeId:node.dataset.panelDropBefore||panel?.dataset.panelId||null};};
 const commit=target=>{const id=gesture.current?.id||dragging;if(id&&target)onMove(id,target);reset();};
 const handle=(panel)=>({
  draggable:!disabled&&!panel.locked,
  onDragStart:event=>{if(disabled||panel.locked||event.target.closest('button,input,select,textarea,a,summary')&&!event.currentTarget.matches('button')){event.preventDefault();return;}gesture.current={id:panel.id,native:true};setDragging(panel.id);event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',panel.id);},
  onDragEnd:reset,
  onPointerDown:event=>{if(disabled||panel.locked||event.button!==0||event.target.closest('button,input,select,textarea,a,summary')&&!event.currentTarget.matches('button'))return;gesture.current={id:panel.id,x:event.clientX,y:event.clientY,active:false,pointer:event.pointerId,node:event.currentTarget};try{event.currentTarget.setPointerCapture?.(event.pointerId)}catch{}},
  onPointerMove:event=>{const g=gesture.current;if(!g||g.pointer!==event.pointerId)return;if(!g.active&&Math.hypot(event.clientX-g.x,event.clientY-g.y)<7)return;g.active=true;setDragging(g.id);if(g.node?.classList.contains('page-order-card'))g.node.style.transform=`translate(${event.clientX-g.x}px,${event.clientY-g.y}px)`;const scroller=root.current?.closest('#sheet-body')||root.current?.closest('dialog')||document.scrollingElement;if(scroller){const rect=scroller.getBoundingClientRect();if(event.clientY<rect.top+48)scroller.scrollTop-=18;else if(event.clientY>Math.min(rect.bottom,window.innerHeight)-48)scroller.scrollTop+=18;}setOver(targetAt(event.clientX,event.clientY));},
  onPointerUp:event=>{const g=gesture.current;if(g?.pointer!==event.pointerId)return;if(g.active)commit(targetAt(event.clientX,event.clientY));else reset();},
  onPointerCancel:event=>{if(gesture.current?.pointer===event.pointerId)reset()},
  onLostPointerCapture:event=>{if(gesture.current?.pointer===event.pointerId)reset()},
  onKeyDown:event=>{if(event.key==='Escape'){event.preventDefault();reset();return}if(event.target!==event.currentTarget)return;if(!disabled&&!panel.locked&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();onKeyMove?.(panel.id,event.key)}}
 });
 const drop=(zone,beforeId=null)=>({
  'data-panel-drop':zone,'data-panel-drop-before':beforeId||undefined,
  onDragOver:event=>{if(!dragging||disabled)return;event.preventDefault();event.stopPropagation();event.dataTransfer.dropEffect='move';setOver({zone,beforeId});},
  onDrop:event=>{if(!dragging||disabled)return;event.preventDefault();event.stopPropagation();commit({zone,beforeId});},
  'data-drop-active':!!dragging&&over?.zone===zone&&over?.beforeId===beforeId||undefined
 });
 return {root,handle,drop,dragging,reset};
}
export function PagePanelActions({page}){
 const app=useApp(),target=activePanelPage(page,app.route?.tab),editor=useLayoutEditor(target),[modal,setModal]=useState(null);
 useEffect(()=>setModal(null),[target,editor.editing]);
 if(!editor.editing||!editor.valid||target==='global')return null;
 return <div className="page-panel-actions"><Control type="button" disabled={editor.busy||editor.layout.panels.filter(p=>p.kind==='content').length>=PANEL_LIMITS.maxCustomPanels} onClick={()=>setModal('add')}><Glyph name="plus"/>Add Panel</Control><Control type="button" className="page-mobile-order-entry" disabled={editor.busy||editor.layout.mobileOrder.length<2} onClick={()=>setModal('mobile')}><DragGlyph/>Reorder panels</Control><span className="page-editor-help">{page==='family'?SHARED_PAGE_SCHEMA[target].label+' · ':''}{editor.layout.panels.filter(p=>p.kind==='content').length>=PANEL_LIMITS.maxCustomPanels?'23 custom panels reached. Restore a removed panel to reuse it.':'Only shared page content is editable.'}</span>{modal==='add'&&<AddPanel page={target} onClose={()=>setModal(null)}/>} {modal==='mobile'&&<MobilePanelOrder page={target} onClose={()=>setModal(null)}/>}</div>;
}
function AddPanel({page,onClose}){
 const editor=useLayoutEditor(page),[zone,setZone]=useState('main'),[preset,setPreset]=useState('text'),[error,setError]=useState('');
 const add=()=>{try{const panel=createSharedPanel('panel-'+crypto.randomUUID(),zone,preset);if(editor.change(layout=>addSharedPanel(layout,panel),'Add panel')){onClose();requestAnimationFrame(()=>document.querySelector('[data-panel-id="'+panel.id+'"] [aria-label="Edit Panel heading"]')?.focus());}}catch(error){setError(error.message)}};
 return <Sheet title="Add Panel" kind="filter" onClose={onClose}><div className="page-add-panel"><fieldset><legend>Panel location</legend><div className="page-panel-location-options">{['main','side'].map(value=><label key={value}><input type="radio" name="panel-zone" value={value} checked={zone===value} onChange={()=>setZone(value)}/><span>{zoneLabel(value)}</span></label>)}</div></fieldset><fieldset><legend>Choose a layout</legend><div className="page-layout-presets">{PANEL_PRESETS.map(option=><label key={option.id}><input type="radio" name="panel-preset" value={option.id} checked={preset===option.id} onChange={()=>setPreset(option.id)}/><span><LayoutGlyph layout={option.id}/><strong>{option.label}</strong></span></label>)}</div><p className="page-editor-help">{PANEL_PRESETS.find(p=>p.id===preset).description}</p></fieldset><p className="page-editor-help">Your new panel starts ready to edit. Changes save automatically.</p>{error&&<p role="alert" className="page-editor-error">{error}</p>}<div className="sheet-footer"><Button disabled={editor.busy} onClick={add}>Add {zone==='main'?'main':'side'} panel</Button></div></div></Sheet>;
}
function MobilePanelOrder({page:initialPage,onClose}){
 const narrow=useNarrow(),[page,setPage]=useState(initialPage),[target,setTarget]=useState(()=>narrow?'mobile':'desktop'),editor=useLayoutEditor(page),[notice,setNotice]=useState(''),mobile=target==='mobile',scope=mobile?'Mobile':'Full';
 const moved=(change,id)=>{const ok=editor.change(change,'Move panel');setNotice(ok?title(editor.layout.panels.find(p=>p.id===id),page,editor.content,editor.records)+' moved in '+scope+' layout.':'Unlock protected cards before moving them or moving across them.');};
 const drag=usePanelDrag({disabled:editor.busy,onKeyMove:(id,key)=>moved(layout=>keyboardSharedPanel(layout,id,key,mobile),id),onMove:(id,drop)=>moved(layout=>moveSharedPanel(layout,id,{beforeId:drop.beforeId,zone:mobile?undefined:drop.zone,mobile}),id)}),panels=editor.layout[mobile?'mobileOrder':'desktopOrder'].map(id=>editor.layout.panels.find(p=>p.id===id));
 const bands=panelLayoutBands(panels);
 const card=panel=>{const name=title(panel,page,editor.content,editor.records),hero=isHeroPanel(panel),previous=editor.layout.panels.find(p=>p.id!==panel.id&&isHeroPanel(p));return <article key={panel.id} className="page-order-card" tabIndex={0} role="group" aria-label={name+' layout card'} aria-description="Drag this card to move it. Arrow keys move it; left and right change area in Full layout." data-panel-id={panel.id} data-hero={hero||undefined} data-dragging={drag.dragging===panel.id||undefined} data-locked={panel.locked||undefined} {...drag.handle(panel)} {...drag.drop(mobile?'mobile':panel.fullWidth?'full':panel.zone,panel.id)}>
  <div className="page-order-card-preview" aria-hidden="true">{panel.kind==='hero'?<Glyph name="image"/>:panel.kind==='content'?<LayoutGlyph layout={panel.layout}/>:<Glyph name="layout"/>}</div><strong>{name}</strong><small>{hero?'Hero · ':''}{panel.fullWidth?'Full width':zoneLabel(panel.zone)}{panel.locked?' · Protected':''}</small>
  <div className="page-order-card-actions"><Control type="button" disabled={editor.busy||!canRelockPanel(page,editor.record.base||editor.record.content,editor.content,panel.id)} aria-label={(panel.locked?'Unlock ':'Lock ')+name} aria-pressed={panel.locked} onClick={()=>editor.change(layout=>changeSharedPanel(layout,panel.id,{locked:!panel.locked}),panel.locked?'Unlock panel':'Protect panel')}><LockGlyph locked={panel.locked}/>{panel.locked?'Unlock':'Protect'}</Control>
   {!mobile&&<><Control type="button" disabled={editor.busy||panel.locked} aria-label={'Full width for '+name} aria-pressed={!!panel.fullWidth} onClick={()=>editor.change(layout=>changeSharedPanel(layout,panel.id,{fullWidth:!panel.fullWidth}),'Change panel width')}>Full width</Control><Control type="button" disabled={editor.busy||panel.locked||!hero&&!!previous?.locked} aria-label={'Hero for '+name} aria-pressed={hero} title={!hero&&previous?.locked?'Unlock the current hero to transfer its role':undefined} onClick={()=>editor.change(layout=>setSharedPanelHero(layout,panel.id,!hero),'Change hero')}>Hero</Control></>}
  </div>
 </article>};
 return <Sheet title="Reorder panels" kind="filter" style={{width:'min(960px,var(--sheet-max-width))'}} onClose={onClose}><div ref={drag.root} className="page-layout-reorder">
  <div className="photo-framing-target" role="group" aria-label="Panel order target">{[['desktop','Full'],['mobile','Mobile']].map(([value,label])=><Control key={value} type="button" aria-pressed={target===value} onClick={()=>{drag.reset();setTarget(value);setNotice('')}}>{label}</Control>)}</div>
  {REUNION_PANEL_PAGES.includes(initialPage)&&<label>Reunion tab<select aria-label="Reunion tab to reorder" value={page} disabled={editor.busy} onChange={event=>{drag.reset();setPage(event.target.value);setNotice('')}}>{REUNION_PANEL_PAGES.map(key=><option key={key} value={key}>{key==='reunion'?'Dashboard':key==='reunion-plans'?'Plan':'Schedule'}</option>)}</select></label>}
  <p className="page-editor-help">{mobile?'Drag cards into the order you want on Mobile. Full layout stays unchanged.':'Drag cards between Main, Side and Full width. Mobile order stays unchanged. Full width and Hero are separate options; each page has at most one Hero.'}</p>
  {mobile?<section className="page-order-lane is-mobile" aria-label="Mobile layout" {...drag.drop('mobile')}>{panels.map(card)}<div className="page-order-drop-end" {...drag.drop('mobile')}>Drop at end</div></section>:<div className="page-order-full-map">
   {bands.map((band,index)=>band.full?<div key={band.full.id} className="page-order-full-row">{card(band.full)}</div>:<div key={'band-'+index} className="page-order-columns">{['main','side'].map(zone=><section key={zone} className={'page-order-lane is-'+zone} aria-label={zoneLabel(zone)} {...drag.drop(zone,bands[index+1]?.full?.id||null)}><h3>{zone==='main'?'Main':'Side'}</h3>{band.columns.filter(p=>p.zone===zone).map(card)}<div className="page-order-drop-end" {...drag.drop(zone,bands[index+1]?.full?.id||null)}>Drop in {zone}</div></section>)}</div>)}
   {!panels.some(p=>!p.fullWidth)&&<div className="page-order-columns">{['main','side'].map(zone=><section key={zone} className="page-order-lane" aria-label={zoneLabel(zone)} {...drag.drop(zone)}><h3>{zone==='main'?'Main':'Side'}</h3><div className="page-order-drop-end" {...drag.drop(zone)}>Drop in {zone}</div></section>)}</div>}
   <div className="page-order-drop-end is-full" {...drag.drop('full')}>Drop a full width card here</div>
  </div>}
  <p role="status" className="page-editor-help">{notice}</p><div className="sheet-footer"><Button onClick={onClose}>Done</Button></div>
 </div></Sheet>;
}

export function SharedPagePanels({page,children,mediaOnly=false,stageMedia=false,mainTail=null,sideTail=null,wideHero=false,afterPrimary=null,nativePanels={},closingPanels=[]}){
 const editor=useLayoutEditor(page),viewportNarrow=useNarrow(),presentation=useRef(viewportNarrow);
 const [mediaTools,setMediaTools]=useState(null);
 useLayoutEffect(()=>{setMediaTools(mediaOnly&&editor.editing?document.querySelector('[data-page-media-tools="'+page+'"]'):null)},[page,mediaOnly,editor.editing]);
 // Reparenting a panel tears down its open task and draft. Adapt the floating
 // surface immediately, but defer canvas reparenting until that task closes.
 if(!editor.activeEditor)presentation.current=viewportNarrow;
 const narrow=presentation.current,[addingElement,setAddingElement]=useState(false),[toolPanel,setToolPanel]=useState(null),toolTrigger=useRef(null),toolId=useId(),[removed,setRemoved]=useState(null),[notice,setNotice]=useState(''),drag=usePanelDrag({disabled:editor.busy||!editor.editing||!editor.arrangingPage||narrow,onKeyMove:(id,key)=>{const moved=editor.change(layout=>keyboardSharedPanel(layout,id,key));setNotice(moved?'Panel moved. Changes save automatically.':'That panel cannot move there. Unlock any panel in the way first.');},onMove:(id,target)=>{const moved=editor.change(layout=>moveSharedPanel(layout,id,target));setNotice(moved?'Panel moved. Changes save automatically.':'That move crosses a locked panel. Unlock it first.');}});
 const visible=editor.layout.panels.filter(p=>!p.removed&&(p.kind!=='native'||nativePanels[p.id]!=null&&nativePanels[p.id]!==false)&&!(p.kind==='hero'&&mediaOnly&&!editor.editing&&(stageMedia&&!['video','gallery'].includes(editor.content.hero.mode)||editor.content.hero.mode==='default'))),archived=editor.layout.panels.filter(p=>p.removed&&(p.kind!=='native'||nativePanels[p.id]!=null&&nativePanels[p.id]!==false)),order=narrow?editor.layout.mobileOrder:editor.layout.desktopOrder,ordered=order.map(id=>visible.find(p=>p.id===id)).filter(Boolean);
 if(!editor.valid)return <>{children}{afterPrimary}{Object.values(nativePanels)}{mainTail}{sideTail}</>;
 const remove=panel=>{const placement={desktop:editor.layout.desktopOrder.indexOf(panel.id),mobile:editor.layout.mobileOrder.indexOf(panel.id)};editor.change(layout=>removeSharedPanel(layout,panel.id),'Remove panel');setRemoved({id:panel.id,title:title(panel,page,editor.content,editor.records),placement});setNotice(title(panel,page,editor.content,editor.records)+' removed from this page. Undo is available.');};
 const restore=(id,placement)=>{editor.change(layout=>restoreSharedPanel(layout,id,placement),'Restore panel');setRemoved(null);setNotice('Panel restored.');};
 const selectedPanel=editor.layout.panels.find(panel=>panel.id===toolPanel&&!panel.removed);
 const openPanel=(panel,event)=>{toolTrigger.current=event.currentTarget.matches('section')?event.currentTarget.querySelector('.page-panel-options-entry button'):event.currentTarget;setAddingElement(false);setToolPanel(panel.id);editor.activateSurface(event.currentTarget,toolId);editor.setSelectedObject({page,panelId:panel.id,label:'Panel · '+title(panel,page,editor.content,editor.records)})};
 const selectNativeAction=(panel,event)=>{if(!editor.editing||editor.arrangingPage||event.type==='keydown'&&event.key==='Tab')return;const target=event.target,action=target.closest?.('button,a,input,select,textarea');if(!action||target.closest('[data-card-slot],[data-page-field],.page-panel-options-entry,.page-panel-inline-controls,.page-object-tools,.page-panel-live-copy,.page-panel-photo,.page-optional-media,.browse-controls'))return;event.preventDefault();event.stopPropagation();openPanel(panel,event)};
 const render=panel=><section key={panel.id} onClickCapture={event=>selectNativeAction(panel,event)} onKeyDownCapture={event=>selectNativeAction(panel,event)} className={'page-shared-panel '+(panel.kind==='hero'?'page-primary-hero':panel.kind==='native'?'page-native-panel':'card page-custom-panel')+(isHeroPanel(panel)?' page-featured-panel':'')+(editor.editing?' is-panel-editing':'')} data-panel-id={panel.id} data-panel-title={title(panel,page,editor.content,editor.records)} data-panel-zone={panel.zone} data-panel-locked={panel.locked||undefined} {...(!narrow?drag.drop(panel.zone,panel.id):{})}>
  {editor.editing&&!editor.arrangingPage&&<div className="page-panel-options-entry"><Control type="button" aria-label={"Panel options for "+title(panel,page,editor.content,editor.records)} onClick={event=>openPanel(panel,event)}><Glyph name="settings"/></Control></div>}
  {editor.editing&&editor.arrangingPage&&<div className="page-panel-arrange-bar"><span className="page-panel-name">{title(panel,page,editor.content,editor.records)}</span><div className="page-panel-inline-controls is-arranging" role="group" aria-label={'Arrange '+title(panel,page,editor.content,editor.records)}>
   {!narrow&&<Control type="button" className="page-panel-drag" title="Move panel" aria-label={'Drag '+title(panel,page,editor.content,editor.records)+'. Arrow keys move or change column'} disabled={editor.busy||panel.locked} {...drag.handle(panel)}><DragGlyph/></Control>}
   <Control type="button" title={panel.locked?'Unlock panel':'Protect panel'} disabled={editor.busy||!canRelockPanel(page,editor.record.base||editor.record.content,editor.content,panel.id)} aria-label={(panel.locked?'Unlock ':'Lock ')+title(panel,page,editor.content,editor.records)} aria-pressed={panel.locked} onClick={event=>{editor.activateSurface(event.currentTarget);editor.change(layout=>changeSharedPanel(layout,panel.id,{locked:!panel.locked}),panel.locked?'Unlock panel':'Protect panel')}}><LockGlyph locked={panel.locked}/></Control>
   {[['main','Main','left'],['side','Side','right'],['full','Full width','full']].map(([zone,label,glyph])=><Control key={zone} type="button" title={label} aria-label={label+' for '+title(panel,page,editor.content,editor.records)} aria-pressed={(panel.fullWidth?'full':panel.zone)===zone} disabled={editor.busy||panel.locked} onClick={()=>editor.change(layout=>zone==='full'?changeSharedPanel(layout,panel.id,{fullWidth:true}):moveSharedPanel(layout,panel.id,{zone}),'Change page area')}><ElementLayoutGlyph kind={glyph}/></Control>)}
   <Control type="button" title="Hero" aria-label={'Hero for '+title(panel,page,editor.content,editor.records)} aria-pressed={isHeroPanel(panel)} disabled={editor.busy||panel.locked||!isHeroPanel(panel)&&editor.layout.panels.some(p=>p.id!==panel.id&&isHeroPanel(p)&&p.locked)} onClick={()=>editor.change(layout=>setSharedPanelHero(layout,panel.id,!isHeroPanel(panel)),'Change hero')}><Glyph name="hero"/></Control>
   {[-1,1].map(direction=><Control key={direction} type="button" title={direction<0?'Move earlier':'Move later'} disabled={editor.busy||panel.locked||(narrow?ordered:ordered.filter(p=>p.zone===panel.zone))[direction<0?0:(narrow?ordered:ordered.filter(p=>p.zone===panel.zone)).length-1]?.id===panel.id} aria-label={'Move '+title(panel,page,editor.content,editor.records)+(direction<0?' earlier':' later')} onClick={()=>editor.change(layout=>stepSharedPanel(layout,panel.id,direction,narrow),'Move panel')}><Glyph name="arrow" className={direction<0?'arrange-up':'arrange-down'}/></Control>)}
   <Control type="button" title="Remove panel" disabled={editor.busy||panel.locked} aria-label={'Remove '+title(panel,page,editor.content,editor.records)} onClick={()=>remove(panel)}><Glyph name="close"/></Control>
  </div></div>}

  <PagePanelLockContext.Provider value={panel.locked}>{panel.kind==='hero'?mediaOnly?<CardContentLayout page={page} items={{media:children}}/>:children||<p className="page-editor-help">The primary hero has no media yet. Unlock it to choose a photo.</p>:panel.kind==='native'?<div className="page-arrange-content-preview" inert={editor.arrangingPage?true:undefined}>{nativePanels[panel.id]}</div>:<PanelContent page={page} panel={panel}/>}</PagePanelLockContext.Provider>
 </section>;
 // Keep the media editor in its ordered panel while uploads change hero mode.
 // Moving it from a separate optional slot into the grid mid-upload loses its
 // progress state, focus and in-flight lock after the first completed file.
 const renderInPlace=panel=>{if(!mediaOnly||!editor.editing||panel.kind!=='hero')return render(panel);const empty=editor.content.hero.mode==='default',entry=<OptionalPageMedia key={panel.id} initialOpen={!empty}><summary><Glyph name="image"/>{empty?'Add '+SHARED_PAGE_SCHEMA[page].label+' photo or video':'Page photo or video'}</summary>{render(panel)}</OptionalPageMedia>;return empty&&mediaTools?createPortal(entry,mediaTools,panel.id):entry};
 // On phones the page's own content follows the hero; panels arranged after the hero follow that content.
 const leadCount=mainTail?ordered.findIndex(panel=>panel.kind==='hero')+1:ordered.length;
 // A closing panel still arranged at the end stays last on phones, after page actions.
 let closeAt=ordered.length;while(closeAt>0&&ordered[closeAt-1].kind!=='hero'&&closingPanels.includes(ordered[closeAt-1].id))closeAt--;
 const leadEnd=Math.min(leadCount,closeAt);
 const hasSide=!!sideTail||visible.some(p=>p.zone==='side'),bands=panelLayoutBands(ordered);
 return <div ref={drag.root} className={'page-panel-layout '+(narrow?'is-mobile':'is-wide')+(hasSide?' has-side':'')+(editor.editing?' is-editing':'')} data-panel-page={page} data-empty-media-tools={mediaOnly&&editor.editing&&editor.content.hero.mode==='default'&&!!mediaTools||undefined}>
  {ordered.length>0||mainTail||sideTail? <>{narrow?<div className="page-panel-mobile-stack">{ordered.slice(0,leadEnd).map(panel=><React.Fragment key={panel.id}>{renderInPlace(panel)}{panel.kind==='hero'&&afterPrimary}</React.Fragment>)}{mainTail}{ordered.slice(leadEnd,closeAt).map(panel=><React.Fragment key={panel.id}>{renderInPlace(panel)}{panel.kind==='hero'&&afterPrimary}</React.Fragment>)}{sideTail}{ordered.slice(closeAt).map(panel=><React.Fragment key={panel.id}>{renderInPlace(panel)}</React.Fragment>)}</div>:<>{bands.map((band,index)=>band.full?<div key={band.full.id} className="page-panel-full-width">{renderInPlace(band.full)}{band.full.kind==='hero'&&afterPrimary}</div>:<div key={'band-'+index} className="page-panel-columns">{['main','side'].map(zone=><div key={zone} className={'page-panel-zone page-panel-zone-'+zone} {...drag.drop(zone)}>{ordered.filter(panel=>band.columns.includes(panel)&&panel.zone===zone).map(panel=><React.Fragment key={panel.id}>{renderInPlace(panel)}{panel.kind==='hero'&&afterPrimary}</React.Fragment>)}{index===bands.length-1&&(zone==='main'?mainTail:sideTail)}</div>)}</div>)}{(!bands.length||bands.at(-1).full)&&(mainTail||sideTail)&&<div className="page-panel-columns"><div className="page-panel-zone page-panel-zone-main">{mainTail}</div><div className="page-panel-zone page-panel-zone-side">{sideTail}</div></div>}</>}</>:null}

  {editor.editing&&!editor.arrangingPage&&selectedPanel&&editor.activeEditor===toolId&&<PageObjectTools title={'Panel · '+title(selectedPanel,page,editor.content,editor.records)} returnFocus={toolTrigger.current} onClose={()=>{setToolPanel(null);editor.activateSurface(null)}}>
   <p>{selectedPanel.locked?'Unlock this panel to edit its content and layout.':'Changes save automatically.'}</p>
   <div className="page-editor-platter"><Control type="button" className="page-editor-item" disabled={editor.busy||!canRelockPanel(page,editor.record.base||editor.record.content,editor.content,selectedPanel.id)} aria-label={(selectedPanel.locked?'Unlock ':'Lock ')+title(selectedPanel,page,editor.content,editor.records)} aria-pressed={selectedPanel.locked} onClick={()=>editor.change(layout=>changeSharedPanel(layout,selectedPanel.id,{locked:!selectedPanel.locked}),selectedPanel.locked?'Unlock panel':'Protect panel')}><LockGlyph locked={selectedPanel.locked}/><span>{selectedPanel.locked?'Unlock to edit':'Protect panel'}</span></Control></div>
   {!selectedPanel.locked&&<>
    {cardSlots(page,selectedPanel).length>0&&<div className="page-editor-platter"><div className="page-content-platter-heading"><h3>Content</h3><Control type="button" aria-label="Add element" title="Add element" aria-expanded={addingElement} disabled={editor.busy||(selectedPanel.elements||[]).length>=MAX_PAGE_ELEMENTS} onClick={()=>setAddingElement(value=>!value)}><Glyph name="plus"/></Control></div>{addingElement&&<div className="page-add-element-menu" role="menu" aria-label="Add panel element">{PAGE_ELEMENT_TYPES.map(([kind,label])=><Control key={kind} type="button" role="menuitem" disabled={editor.busy} onClick={()=>{try{const updated=editor.update(page,content=>addCardElement(content,page,selectedPanel.id,kind,'element-'+crypto.randomUUID()),{historyLabel:'Add '+label.toLowerCase()});if(updated)setAddingElement(false)}catch(error){setNotice(error.message)}}}><Glyph name={kind==='media'?'image':kind==='button'?'arrow':'edit'}/><span>{label}</span></Control>)}</div>}{cardSlots(page,selectedPanel).map(slot=>{const removed=cardLayoutOf(editor.content,page,selectedPanel).hidden?.includes(slot.id);return <div key={slot.id} className="page-editor-element-row"><Control type="button" className="page-editor-item" disabled={editor.busy} onClick={()=>removed?editor.update(page,content=>updateCardLayout(content,page,selectedPanel.id,layout=>setCardSlotRemoved(layout,slot.id,false)),{historyLabel:'Restore '+slot.label}):editor.setObjectRequest({page,cardId:selectedPanel.id,slotId:slot.id})}><Glyph name={removed?'history':slot.role==='image'?'image':'edit'}/><span>{slot.label}{removed&&<small>Removed · Restore</small>}</span><Glyph name={removed?'plus':'arrow'}/></Control>{!removed&&<Control type="button" className="page-editor-remove-element" aria-label={'Remove '+slot.label} title={'Remove '+slot.label} disabled={editor.busy} onClick={()=>editor.update(page,content=>updateCardLayout(content,page,selectedPanel.id,layout=>setCardSlotRemoved(layout,slot.id)),{historyLabel:'Remove '+slot.label})}><Glyph name="close"/></Control>}</div>})}</div>}
    <ChoiceControl label="Page area" aria-label={'Location for '+title(selectedPanel,page,editor.content,editor.records)} value={selectedPanel.fullWidth?'full':selectedPanel.zone} disabled={editor.busy} options={[{value:'main',label:'Main'},{value:'side',label:'Side'},{value:'full',label:'Full width'}]} onChange={value=>editor.change(layout=>value==='full'?changeSharedPanel(layout,selectedPanel.id,{fullWidth:true}):moveSharedPanel(layout,selectedPanel.id,{zone:value}),'Change page area')}/>
    <div className="page-editor-platter"><Control type="button" className="page-editor-item" disabled={editor.busy||!isHeroPanel(selectedPanel)&&editor.layout.panels.some(p=>p.id!==selectedPanel.id&&isHeroPanel(p)&&p.locked)} aria-pressed={isHeroPanel(selectedPanel)} onClick={()=>editor.change(layout=>setSharedPanelHero(layout,selectedPanel.id,!isHeroPanel(selectedPanel)),'Change hero')}><Glyph name="layout"/><span>Hero</span><small>{isHeroPanel(selectedPanel)?'On':'Off'}</small></Control></div>
    <div className="page-object-tools-group"><h3>{narrow?'Mobile':'Full'} order</h3><p>{narrow?'Full order stays unchanged.':'Mobile order stays unchanged.'}</p><div className="page-editor-order">{[-1,1].map(direction=><Control key={direction} type="button" aria-label={'Move '+title(selectedPanel,page,editor.content,editor.records)+(direction<0?' earlier':' later')} title={'Move '+title(selectedPanel,page,editor.content,editor.records)+(direction<0?' earlier':' later')} disabled={editor.busy} onClick={()=>{const moved=editor.change(layout=>stepSharedPanel(layout,selectedPanel.id,direction,narrow),'Move panel');setNotice(moved?'Panel moved.':'Unlock protected panels before moving across them.')}}><Glyph name="arrow" className={direction<0?'arrange-up':'arrange-down'}/></Control>)}</div></div>
    <div className="page-editor-platter sheet-footer page-editor-destructive-group"><Control type="button" className="page-editor-item page-editor-remove" disabled={editor.busy} onClick={()=>{remove(selectedPanel);setToolPanel(null);editor.activateSurface(null)}}><Glyph name="close"/><span>Remove panel</span></Control></div>
   </>}
   <p role="status">{notice||'Changes save automatically.'}</p>
  </PageObjectTools>}
  {editor.editing&&<>{removed&&<div className="page-panel-undo" role="status"><span>{removed.title} removed.</span><Control type="button" disabled={editor.busy} onClick={()=>restore(removed.id,removed.placement)}>Undo</Control></div>}{archived.length>0&&<InlineDisclosure className="page-removed-panels" label={'Removed panels · '+archived.length} icon="history"><p className="page-editor-help">Removed panels remain recoverable in this page and its saved history.</p>{archived.map(panel=><div key={panel.id}><span>{title(panel,page,editor.content,editor.records)}</span><Control type="button" disabled={editor.busy} onClick={()=>restore(panel.id)}>Restore panel</Control></div>)}</InlineDisclosure>}<p className="sr-only" role="status">{notice}</p></>}
 </div>;
}
function PanelContent({page,panel}){
 const editor=useLayoutEditor(page),editable=editor.editing&&!editor.arrangingPage&&!panel.locked;
 return <div className={'page-panel-content page-panel-preset-'+panel.layout}><CardContentLayout page={page} cardId={panel.id} hidden={!editable&&!panel.media.length?['media']:[]} items={{
  media:['photo','feature'].includes(panel.layout)&&<PanelPhoto page={page} panel={panel}/>,
  title:<PanelCopy page={page} panel={panel} field="title" label="Panel heading" as="h2" editable={editable}/>,
  body:<PanelCopy page={page} panel={panel} field="body" label={title(panel,page,editor.content,editor.records)+' body text'} editable={editable}/>,
  secondary:panel.layout==='columns'&&<PanelCopy page={page} panel={panel} field="secondary" label={title(panel,page,editor.content,editor.records)+' second column'} editable={editable}/>
 }}/></div>;
}
function PanelCopy({page,panel,field,label,as:Tag='div',editable}){
 const editor=useLayoutEditor(page),id=useId(),trigger=useRef(null),[active,setActive]=useState(false),original=useRef(''),text=panel[field];
 useEffect(()=>{if(!editable||active&&editor.activeEditor!==id)setActive(false)},[editable,active,editor.activeEditor,id]);
 const finish=()=>{setActive(false);requestAnimationFrame(()=>trigger.current?.focus())};
 const change=value=>editor.change(layout=>changeSharedPanel(layout,panel.id,{[field]:value}));
 const Target=field==='title'?'span':'div',shown=field==='title'?text:<PageMarkdownBody source={text} className="page-panel-body"/>;
 if(!editable)return <Tag>{shown}</Tag>;
 const start=event=>{original.current=text;editor.activateSurface(event.currentTarget,id);setActive(true)};
 if(field!=='title')return <Tag className="page-panel-live-copy"><Target ref={trigger} className="page-panel-copy-target" role={!active?'button':undefined} tabIndex={!active?0:undefined} aria-label={!active?'Edit '+label:undefined} onClick={event=>{if(!active)start(event)}} onKeyDown={event=>{if(!active&&(event.key==='Enter'||event.key===' ')){event.preventDefault();start(event)}}}>{text?shown:<span className="page-empty-copy">{field==='secondary'?'Add second-column text':'Add text'}</span>}</Target>{active&&<PageMarkdownEditor floating ariaLabel={label} value={text} maxLength={PANEL_LIMITS.maxBody} onChange={change} onDone={finish} onCancel={()=>{change(original.current);finish()}} autoFocus/>}</Tag>;
 return <Tag className="page-panel-live-copy">{active?<span className="page-panel-text-edit"><input className="page-copy-input page-panel-title-input" aria-label={label} value={text} maxLength={PANEL_LIMITS.maxTitle} autoFocus onChange={event=>change(event.target.value)} onKeyDown={event=>{if(event.nativeEvent.isComposing)return;if(event.key==='Enter'){event.preventDefault();finish()}else if(event.key==='Escape'){event.preventDefault();change(original.current);finish()}}}/><Control type="button" className="page-field-done" aria-label={'Finish editing '+label} onClick={finish}><Glyph name="check"/></Control></span>:<Target ref={trigger} className="page-panel-copy-target" role="button" tabIndex={0} aria-label={'Edit '+label} onClick={start} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();start(event)}}}>{text?shown:<span className="page-empty-copy">{field==='title'?'Add a heading':field==='secondary'?'Add second-column text':'Add text'}</span>}</Target>}</Tag>;
}
function PanelPhoto({page,panel}){
 const editor=useLayoutEditor(page),[uploading,setUploading]=useState(false),[error,setError]=useState(''),lock=useRef(false),alive=useRef(true),file=panel.media[0],editable=editor.editing&&!editor.arrangingPage&&!panel.locked,[editingPhoto,setEditingPhoto]=useState(false),photoToolId=useId(),photoTrigger=useRef(null);
 useEffect(()=>()=>{alive.current=false},[]);
 useEffect(()=>{if(!editable||editingPhoto&&editor.activeEditor!==photoToolId)setEditingPhoto(false)},[editable,editingPhoto,editor.activeEditor,photoToolId]);
 const setMedia=media=>editor.change(layout=>changeSharedPanel(layout,panel.id,{media}),'Change panel photo');
 async function upload(file){if(!file||lock.current)return;lock.current=true;setUploading(true);setError('');const finish=editor.beginWork();try{const limit=editor.preview?2*1024*1024:SHARED_CONTENT_LIMITS.maxMediaBytes;if(!SHARED_IMAGE_TYPES.includes(file.type)||!file.size||file.size>limit)throw Error('Choose a JPEG, PNG, WebP or GIF photo under '+limit/1024/1024+' MB.');const output=await readPreviewFile(file,editor.preview?'preview':'live');setMedia([{...output,id:output.id||'preview-'+crypto.randomUUID(),alt:''}]);}catch(error){if(alive.current)setError(error.message)}finally{lock.current=false;finish();if(alive.current)setUploading(false)}}
 if(!file&&!editable)return null;
 return <div className="page-panel-photo">{editable?<ImageUploadControl label="Panel photo" src={file?safePageMediaUrl(file.url,editor.preview):''} alt={file?.alt||''} accept={SHARED_IMAGE_TYPES.join(',')} disabled={editor.busy&&!uploading} busy={uploading} progress={uploading?'Uploading panel photo…':''} error={error} frame={file?.frame} onFrameChange={frame=>setMedia([{...file,frame}])} onEdit={node=>{photoTrigger.current=node;editor.activateSurface(node,photoToolId);setEditingPhoto(true)}} onFiles={files=>void upload(files[0])}/>:file&&safePageMediaUrl(file.url,editor.preview)?<div className="page-panel-photo-crop"><img src={safePageMediaUrl(file.url,editor.preview)} alt={file.alt||''} style={photoFrameStyle(file.frame)}/></div>:<div className="page-panel-photo-empty">Photo unavailable</div>}{editable&&file&&editingPhoto&&<PanelPhotoTask page={page} panel={panel} file={file} returnFocus={photoTrigger.current} onClose={()=>setEditingPhoto(false)}/>}</div>;
}

function PanelPhotoTask({page,panel,file,returnFocus,onClose}){
 const editor=useLayoutEditor(page),imageLayout=useContext(ImageLayoutContext),baseline=useRef(JSON.stringify(file)),baselineLayout=useRef(JSON.stringify(imageLayout?.value)),recovery=useImageEditDraft({page,object:panel.id,initial:{file:{...file},layout:imageLayout?.value},validate:value=>{try{const next={...editor.content,panelLayout:changeSharedPanel(panelLayoutOf(editor.content,page),panel.id,{media:value.file?[value.file]:[]})};validateSharedPageContent(page,value.layout&&imageLayout?.apply?imageLayout.apply(next,value.layout):next);return true}catch{return false}}}),draft=recovery.value.file,setDraft=change=>recovery.setValue(value=>({...value,file:typeof change==='function'?change(value.file):change})),[uploading,setUploading]=useState(false),[frameReady,setFrameReady]=useState(false),[error,setError]=useState(''),picker=useRef(null),alive=useRef(true),lock=useRef(false);
 useEffect(()=>()=>{alive.current=false},[]);
 const cancel=()=>{recovery.clear();onClose()};
 const apply=(frame,layout)=>{if(JSON.stringify(panel.media[0])!==baseline.current||JSON.stringify(imageLayout?.value)!==baselineLayout.current){setError('This photo changed while you were editing. Close and reopen it to review the latest version.');return}const updated=editor.update(page,content=>{const next={...content,panelLayout:changeSharedPanel(panelLayoutOf(content,page),panel.id,{media:draft?[{...draft,frame}]:[]})};return layout&&imageLayout?.apply?imageLayout.apply(next,layout):next},{historyLabel:'Edit panel photo'});if(updated){recovery.clear();onClose()}};
 async function replace(file){if(!file||lock.current)return;lock.current=true;setUploading(true);setError('');const finish=editor.beginWork();try{const limit=editor.preview?2*1024*1024:SHARED_CONTENT_LIMITS.maxMediaBytes;if(!SHARED_IMAGE_TYPES.includes(file.type)||!file.size||file.size>limit)throw Error('Choose a JPEG, PNG, WebP or GIF photo under '+limit/1024/1024+' MB.');const output=await readPreviewFile(file,editor.preview?'preview':'live');if(alive.current)setDraft({...output,id:output.id||'preview-'+crypto.randomUUID(),alt:''})}catch(error){if(alive.current)setError(error.message)}finally{lock.current=false;finish();if(alive.current)setUploading(false)}}
 return <PageObjectTools title={'Photo · '+title(panel,page,editor.content,editor.records)} fullHeight returnFocus={returnFocus} onClose={()=>{if(!uploading)cancel()}} busy={uploading} doneDisabled={!!draft&&!frameReady} onDone={()=>apply(draft?.frame,recovery.value.layout)}>
  {error&&<p role="alert" className="page-editor-error">{error}</p>}{recovery.storageError&&<p role="alert">{recovery.storageError}</p>}{recovery.recovered&&<p>Recovered image edit from this tab.</p>}{uploading&&<p role="status">Uploading replacement photo… Your original photo is unchanged.</p>}
  <ImageLayoutContext.Provider value={imageLayout?{...imageLayout,value:recovery.value.layout}:null}>{draft?<PhotoFramingEditor onReadyChange={setFrameReady} src={safePageMediaUrl(draft.url,editor.preview)} alt={draft.alt||''} frame={draft.frame} disabled={uploading} atomicLayout onCancel={cancel} onSave={apply} onDraftChange={({frame,layout})=>recovery.setValue(value=>({...value,file:{...value.file,frame},layout}))} onChangeMedia={()=>picker.current?.click()} details={<div className="page-object-tools-group"><label>Photo description<input aria-label="Photo description" maxLength={240} disabled={uploading} value={draft.alt||''} onChange={event=>setDraft({...draft,alt:event.target.value})}/></label><Control type="button" disabled={uploading} onClick={()=>setDraft(null)}>Remove photo</Control></div>}/>:<><p>The photo will be removed when you apply this edit.</p><div className="photo-framing-actions"><Button secondary onClick={cancel}>Cancel</Button><Button onClick={()=>apply()}>Apply removal</Button></div></>}</ImageLayoutContext.Provider>
  <input ref={picker} type="file" className="sr-only" tabIndex={-1} aria-label="Replacement panel photo" accept={SHARED_IMAGE_TYPES.join(',')} disabled={uploading} onChange={event=>{const file=event.target.files?.[0];event.target.value='';void replace(file)}}/>
 </PageObjectTools>;
}
