import {useImageEditDraft} from './use-image-edit-draft.jsx';
import {PageObjectTools} from './page-object-tools.jsx';
import {cardSlots} from './card-content-layout-model.js';
import {CardContentLayout} from './card-content-layout.jsx';
import {ImageLayoutContext} from './image-edit-controls.jsx';
import {PhotoFramingEditor,photoFrameStyle} from './photo-framing.jsx';
import {InlineDisclosure} from './inline-disclosure.jsx';
import {ImageUploadControl} from './image-upload-control.jsx';
import {PageMarkdownEditor,PageMarkdownBody} from './page-markdown.jsx';
import React,{useContext,useEffect,useId,useRef,useState} from 'react';
import {Button,Control,Glyph,Sheet,useApp} from './ui-core.jsx';
import {usePageContent,PagePanelLockContext,safePageMediaUrl} from './page-content.jsx';
import {readPreviewFile} from './uploads.js';
import {SHARED_IMAGE_TYPES,SHARED_CONTENT_LIMITS,SHARED_PAGE_SCHEMA,validateSharedPageContent} from './shared-content-schema.js';
import {PANEL_PRESETS,PANEL_LIMITS,panelLayoutOf,createSharedPanel,addSharedPanel,changeSharedPanel,removeSharedPanel,restoreSharedPanel,moveSharedPanel,stepSharedPanel,canRelockPanel,sharedPanelTitle,keyboardSharedPanel,activePanelPage,REUNION_PANEL_PAGES} from './shared-panels.js';
import './page-panels.css';
const title=(panel,page,content,records)=>sharedPanelTitle(page,panel,content,records);
const zoneLabel=zone=>zone==='side'?'Side area':'Main area';
function useNarrow(){const [narrow,setNarrow]=useState(()=>typeof matchMedia==='function'&&matchMedia('(max-width: 700px)').matches);useEffect(()=>{const query=matchMedia('(max-width: 700px)'),update=()=>setNarrow(query.matches);update();query.addEventListener('change',update);return()=>query.removeEventListener('change',update)},[]);return narrow;}
function OptionalPageMedia({initialOpen,children}){const [open,setOpen]=useState(initialOpen);return <details className="page-optional-media" open={open} onToggle={event=>setOpen(event.currentTarget.open)}>{children}</details>}
function LayoutGlyph({layout}){return <svg viewBox="0 0 48 34" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><rect x="2" y="2" width="44" height="30" rx="3"/>{layout==='text'?<path d="M9 10h22M9 16h30M9 22h25"/>:layout==='columns'?<path d="M9 10h12M9 16h12M9 22h12M27 10h12M27 16h12M27 22h12"/>:layout==='photo'?<><rect x="8" y="7" width="32" height="12" rx="1"/><path d="M8 24h32M8 28h22"/></>:<><rect x="8" y="7" width="14" height="20" rx="1"/><path d="M27 10h13M27 16h13M27 22h10"/></>}</svg>;}
function DragGlyph(){return <svg className="glyph" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M8 5h1m6 0h1M8 12h1m6 0h1M8 19h1m6 0h1" strokeLinecap="round"/></svg>;}
function LockGlyph({locked}){return <svg className="glyph" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><rect x="5" y="10" width="14" height="11" rx="2"/>{locked?<path d="M8 10V7a4 4 0 0 1 8 0v3"/>:<path d="M8 10V7a4 4 0 0 1 8 0"/>}<path d="M12 14v3"/></svg>;}
function useLayoutEditor(page){const editor=usePageContent(page),layout=panelLayoutOf(editor.content,page),busy=editor.pending||editor.record?.status==='saving';const change=(fn,historyLabel)=>{let changed=false;const updated=editor.update(page,content=>{const layout=panelLayoutOf(content,page),next=fn(layout);changed=next!==layout;return {...content,panelLayout:next}},{historyLabel});return updated&&changed;};return {...editor,layout,busy,change};}
// Pointer capture supports tablet touch dragging. Native drag supports mouse;
// all mutations also have ordinary buttons and a labelled location select.
function usePanelDrag({disabled,onMove,onKeyMove}){
 const [dragging,setDragging]=useState(null),[over,setOver]=useState(null),gesture=useRef(null),root=useRef(null);
 const reset=()=>{gesture.current=null;setDragging(null);setOver(null);};
 useEffect(()=>{if(disabled)reset()},[disabled]);
 const targetAt=(x,y)=>{const node=document.elementFromPoint(x,y)?.closest('[data-panel-drop]');if(!node||!root.current?.contains(node))return null;const panel=node.closest('[data-panel-id]');return {zone:node.dataset.panelDrop,beforeId:panel?.dataset.panelId||null};};
 const commit=target=>{const id=gesture.current?.id||dragging;if(id&&target)onMove(id,target);reset();};
 const handle=(panel)=>({
  draggable:!disabled&&!panel.locked,
  onDragStart:event=>{if(disabled||panel.locked){event.preventDefault();return;}gesture.current={id:panel.id,native:true};setDragging(panel.id);event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',panel.id);},
  onDragEnd:reset,
  onPointerDown:event=>{if(disabled||panel.locked||event.button!==0)return;gesture.current={id:panel.id,x:event.clientX,y:event.clientY,active:false,pointer:event.pointerId};try{event.currentTarget.setPointerCapture?.(event.pointerId)}catch{}},
  onPointerMove:event=>{const g=gesture.current;if(!g||g.pointer!==event.pointerId)return;if(!g.active&&Math.hypot(event.clientX-g.x,event.clientY-g.y)<7)return;g.active=true;setDragging(g.id);const scroller=root.current?.closest('dialog')||document.scrollingElement;if(scroller){const rect=scroller.getBoundingClientRect();if(event.clientY<rect.top+48)scroller.scrollTop-=18;else if(event.clientY>Math.min(rect.bottom,window.innerHeight)-48)scroller.scrollTop+=18;}setOver(targetAt(event.clientX,event.clientY));},
  onPointerUp:event=>{const g=gesture.current;if(g?.pointer!==event.pointerId)return;if(g.active)commit(targetAt(event.clientX,event.clientY));else reset();},
  onPointerCancel:event=>{if(gesture.current?.pointer===event.pointerId)reset()},
  onLostPointerCapture:event=>{if(gesture.current?.pointer===event.pointerId)reset()},
  onKeyDown:event=>{if(event.key==='Escape'){event.preventDefault();reset();return}if(!disabled&&!panel.locked&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();onKeyMove?.(panel.id,event.key)}}
 });
 const drop=(zone,beforeId=null)=>({
  'data-panel-drop':zone,
  onDragOver:event=>{if(!dragging||disabled)return;event.preventDefault();event.stopPropagation();event.dataTransfer.dropEffect='move';setOver({zone,beforeId});},
  onDrop:event=>{if(!dragging||disabled)return;event.preventDefault();event.stopPropagation();commit({zone,beforeId});},
  'data-drop-active':!!dragging&&over?.zone===zone&&over?.beforeId===beforeId||undefined
 });
 return {root,handle,drop,dragging,reset};
}
export function PagePanelActions({page}){
 const app=useApp(),target=activePanelPage(page,app.route?.tab),editor=useLayoutEditor(target),[modal,setModal]=useState(null);
 useEffect(()=>setModal(null),[target,editor.editing]);
 if(!editor.editing||!editor.valid||target==='global')return null;
 return <div className="page-panel-actions"><Control type="button" disabled={editor.busy||editor.layout.panels.filter(p=>p.kind==='content').length>=PANEL_LIMITS.maxCustomPanels} onClick={()=>setModal('add')}><Glyph name="plus"/>Add Panel</Control><Control type="button" className="page-mobile-order-entry" disabled={editor.busy||editor.layout.mobileOrder.length<2} onClick={()=>setModal('mobile')}><DragGlyph/>Reorder panels</Control><span className="page-editor-help">{page==='family'?SHARED_PAGE_SCHEMA[target].label+' · ':''}{editor.layout.panels.filter(p=>p.kind==='content').length>=PANEL_LIMITS.maxCustomPanels?'23 custom panels reached. Restore a removed panel to reuse it.':'Only shared page content is editable.'}</span>{modal==='add'&&<AddPanel page={target} onClose={()=>setModal(null)}/>} {modal==='mobile'&&<MobilePanelOrder page={target} onClose={()=>setModal(null)}/>}</div>;
}
function AddPanel({page,onClose}){
 const editor=useLayoutEditor(page),[zone,setZone]=useState('main'),[preset,setPreset]=useState('text'),[error,setError]=useState('');
 const add=()=>{try{const panel=createSharedPanel('panel-'+crypto.randomUUID(),zone,preset);if(editor.change(layout=>addSharedPanel(layout,panel),'Add panel')){onClose();requestAnimationFrame(()=>document.querySelector('[data-panel-id="'+panel.id+'"] [aria-label="Edit Panel heading"]')?.focus());}}catch(error){setError(error.message)}};
 return <Sheet title="Add Panel" kind="filter" onClose={onClose}><div className="page-add-panel"><fieldset><legend>Panel location</legend><div className="page-panel-location-options">{['main','side'].map(value=><label key={value}><input type="radio" name="panel-zone" value={value} checked={zone===value} onChange={()=>setZone(value)}/><span>{zoneLabel(value)}</span></label>)}</div></fieldset><fieldset><legend>Choose a layout</legend><div className="page-layout-presets">{PANEL_PRESETS.map(option=><label key={option.id}><input type="radio" name="panel-preset" value={option.id} checked={preset===option.id} onChange={()=>setPreset(option.id)}/><span><LayoutGlyph layout={option.id}/><strong>{option.label}</strong></span></label>)}</div><p className="page-editor-help">{PANEL_PRESETS.find(p=>p.id===preset).description}</p></fieldset><p className="page-editor-help">Your new panel starts ready to edit. Changes save automatically.</p>{error&&<p role="alert" className="page-editor-error">{error}</p>}<Button disabled={editor.busy} onClick={add}>Add {zone==='main'?'main':'side'} panel</Button></div></Sheet>;
}
function MobilePanelOrder({page:initialPage,onClose}){
 const narrow=useNarrow(),[page,setPage]=useState(initialPage),[target,setTarget]=useState(()=>narrow?'mobile':'desktop'),editor=useLayoutEditor(page),[notice,setNotice]=useState(''),mobile=target==='mobile',scope=mobile?'Phone':'Wide';
 const moved=(change,id)=>{const ok=editor.change(change,'Move panel');setNotice(ok?title(editor.layout.panels.find(p=>p.id===id),page,editor.content,editor.records)+' moved in '+scope+' order. The other order is unchanged.':'This move crosses a protected panel or reaches the end. Protected panels must be unlocked before moving across them.');};
 const drag=usePanelDrag({disabled:editor.busy,onKeyMove:(id,key)=>moved(layout=>keyboardSharedPanel(layout,id,key,mobile),id),onMove:(id,target)=>moved(layout=>moveSharedPanel(layout,id,{beforeId:target.beforeId,zone:mobile?undefined:target.zone,mobile}),id)}),panels=editor.layout[mobile?'mobileOrder':'desktopOrder'].map(id=>editor.layout.panels.find(p=>p.id===id));
 return <Sheet title="Reorder panels" kind="filter" onClose={onClose}><div ref={drag.root} className="page-mobile-reorder">
  <div className="photo-framing-target" role="group" aria-label="Panel order target">{[['mobile','Phone'],['desktop','Wide']].map(([value,label])=><Control key={value} type="button" aria-pressed={target===value} onClick={()=>{drag.reset();setTarget(value);setNotice('')}}>{label}</Control>)}</div>
  {REUNION_PANEL_PAGES.includes(initialPage)&&<label>Reunion tab<select aria-label="Reunion tab to reorder" value={page} disabled={editor.busy} onChange={event=>{drag.reset();setPage(event.target.value);setNotice('')}}>{REUNION_PANEL_PAGES.map(key=><option key={key} value={key}>{key==='reunion'?'Dashboard':key==='reunion-plans'?'Plan':'Calendar'}</option>)}</select></label>}
  <p className="page-editor-help">{scope} order only. {mobile?'Wide positions':'Phone positions'} stay unchanged. Use arrows, choose a destination, or drag a handle. Keyboard arrows on a handle also move panels.</p>
  <ol>{panels.map(panel=>{const name=title(panel,page,editor.content,editor.records),order=panels.filter(p=>mobile||p.zone===panel.zone),index=order.findIndex(p=>p.id===panel.id);return <li key={panel.id} data-panel-id={panel.id} {...drag.drop(mobile?'mobile':panel.zone,panel.id)}>
   <Control type="button" className="page-panel-drag" aria-label={'Drag '+name+' for '+scope} disabled={editor.busy||panel.locked} {...drag.handle(panel)}><DragGlyph/></Control><span className="page-mobile-drag-label"><strong>{name}</strong><small>{panel.fullWidth?'Full width':zoneLabel(panel.zone)}{panel.locked?' · Protected':''}</small></span>
   <div><Control type="button" disabled={editor.busy||panel.locked||index===0} aria-label={'Move '+name+' earlier on '+scope} onClick={()=>moved(layout=>stepSharedPanel(layout,panel.id,-1,mobile),panel.id)}><Glyph name="arrow" className="arrange-up"/></Control><Control type="button" disabled={editor.busy||panel.locked||index===order.length-1} aria-label={'Move '+name+' later on '+scope} onClick={()=>moved(layout=>stepSharedPanel(layout,panel.id,1,mobile),panel.id)}><Glyph name="arrow" className="arrange-down"/></Control></div>
   <details className="page-order-options"><summary>Options for {name}</summary><div><Control type="button" disabled={editor.busy||!canRelockPanel(page,editor.record.base||editor.record.content,editor.content,panel.id)} aria-label={(panel.locked?'Unlock ':'Lock ')+name} onClick={()=>editor.change(layout=>changeSharedPanel(layout,panel.id,{locked:!panel.locked}),panel.locked?'Unlock panel':'Protect panel')}>{panel.locked?'Unlock to move':'Protect panel'}</Control>
    {!mobile&&!panel.locked&&<label>Page area<select aria-label={'Page area for '+name} value={panel.fullWidth?'full':panel.zone} disabled={editor.busy} onChange={event=>moved(layout=>event.target.value==='full'?changeSharedPanel(layout,panel.id,{fullWidth:true}):moveSharedPanel(panel.kind==='hero'?changeSharedPanel(layout,panel.id,{fullWidth:false}):layout,panel.id,{zone:event.target.value}),panel.id)}><option value="main">Main area</option><option value="side">Side area</option>{panel.kind==='hero'&&<option value="full">Full width</option>}</select></label>}
    <label>Move before<select aria-label={'Move '+name+' before'} value="" disabled={editor.busy||panel.locked} onChange={event=>{if(event.target.value)moved(layout=>moveSharedPanel(layout,panel.id,{beforeId:event.target.value==='__end'?null:event.target.value,mobile,zone:mobile?undefined:panel.zone}),panel.id)}}><option value="">Choose a panel</option>{order.filter(p=>p.id!==panel.id).map(p=><option key={p.id} value={p.id}>{title(p,page,editor.content,editor.records)}</option>)}<option value="__end">End of {mobile?'phone order':zoneLabel(panel.zone).toLowerCase()}</option></select></label>
   </div></details>
  </li>})}</ol>
  <p role="status" className="page-editor-help">{notice}</p><Button onClick={onClose}>Done</Button>
 </div></Sheet>;
}
export function SharedPagePanels({page,children,mediaOnly=false,mainTail=null,sideTail=null,wideHero=false,afterPrimary=null,nativePanels={}}){
 const editor=useLayoutEditor(page),narrow=useNarrow(),[toolPanel,setToolPanel]=useState(null),toolTrigger=useRef(null),toolId=useId(),[removed,setRemoved]=useState(null),[notice,setNotice]=useState(''),drag=usePanelDrag({disabled:editor.busy||!editor.editing||!editor.arrangingPage||narrow,onKeyMove:(id,key)=>{const moved=editor.change(layout=>keyboardSharedPanel(layout,id,key));setNotice(moved?'Panel moved. Changes save automatically.':'That panel cannot move there. Unlock any panel in the way first.');},onMove:(id,target)=>{const moved=editor.change(layout=>moveSharedPanel(layout,id,target));setNotice(moved?'Panel moved. Changes save automatically.':'That move crosses a locked panel. Unlock it first.');}});
 const visible=editor.layout.panels.filter(p=>!p.removed&&(p.kind!=='native'||nativePanels[p.id]!=null&&nativePanels[p.id]!==false)&&!(p.kind==='hero'&&mediaOnly&&!editor.editing&&editor.content.hero.mode==='default')),archived=editor.layout.panels.filter(p=>p.removed),order=narrow?editor.layout.mobileOrder:editor.layout.desktopOrder,ordered=order.map(id=>visible.find(p=>p.id===id)).filter(Boolean);
 if(!editor.valid)return <>{children}{afterPrimary}{Object.values(nativePanels)}{mainTail}{sideTail}</>;
 const remove=panel=>{const placement={desktop:editor.layout.desktopOrder.indexOf(panel.id),mobile:editor.layout.mobileOrder.indexOf(panel.id)};editor.change(layout=>removeSharedPanel(layout,panel.id),'Remove panel');setRemoved({id:panel.id,title:title(panel,page,editor.content,editor.records),placement});setNotice(title(panel,page,editor.content,editor.records)+' removed from this page. Undo is available.');};
 const restore=(id,placement)=>{editor.change(layout=>restoreSharedPanel(layout,id,placement),'Restore panel');setRemoved(null);setNotice('Panel restored.');};
 const selectedPanel=editor.layout.panels.find(panel=>panel.id===toolPanel&&!panel.removed);
 const openPanel=(panel,event)=>{toolTrigger.current=event.currentTarget.matches('section')?event.currentTarget.querySelector('.page-panel-options-entry button'):event.currentTarget;setToolPanel(panel.id);editor.activateSurface(event.currentTarget,toolId);editor.setSelectedObject({page,panelId:panel.id,label:'Panel · '+title(panel,page,editor.content,editor.records)})};
 const selectNativeAction=(panel,event)=>{if(!editor.editing||editor.arrangingPage||event.type==='keydown'&&event.key==='Tab')return;const target=event.target,action=target.closest?.('button,a,input,select,textarea');if(!action||target.closest('[data-card-slot],[data-page-field],.page-panel-options-entry,.page-panel-inline-controls,.page-object-tools,.page-panel-live-copy,.page-panel-photo,.page-optional-media'))return;event.preventDefault();event.stopPropagation();openPanel(panel,event)};
 const render=panel=><section key={panel.id} onClickCapture={event=>selectNativeAction(panel,event)} onKeyDownCapture={event=>selectNativeAction(panel,event)} className={'page-shared-panel '+(panel.kind==='hero'?'page-primary-hero':panel.kind==='native'?'page-native-panel':'card page-custom-panel')+(editor.editing?' is-panel-editing':'')} data-panel-id={panel.id} data-panel-title={title(panel,page,editor.content,editor.records)} data-panel-zone={panel.zone} data-panel-locked={panel.locked||undefined} {...(!narrow?drag.drop(panel.zone,panel.id):{})}>
  {editor.editing&&!editor.arrangingPage&&<div className="page-panel-options-entry"><Control type="button" aria-label={"Panel options for "+title(panel,page,editor.content,editor.records)} onClick={event=>openPanel(panel,event)}><Glyph name="settings"/><span>Panel options</span></Control></div>}
  {editor.editing&&editor.arrangingPage&&<div className={"page-panel-inline-controls"+(editor.arrangingPage?" is-arranging":"")}><span className="page-panel-name">{title(panel,page,editor.content,editor.records)}</span>{editor.arrangingPage&&!narrow&&<Control type="button" className="page-panel-drag" aria-label={'Drag '+title(panel,page,editor.content,editor.records)+'. Arrow keys move or change column'} disabled={editor.busy||panel.locked} {...drag.handle(panel)}><DragGlyph/></Control>}<Control type="button" disabled={editor.busy||!canRelockPanel(page,editor.record.base||editor.record.content,editor.content,panel.id)} title={!canRelockPanel(page,editor.record.base||editor.record.content,editor.content,panel.id)?'Wait for these changes to save before protecting the section':undefined} aria-label={(panel.locked?'Unlock ':'Lock ')+title(panel,page,editor.content,editor.records)} aria-pressed={panel.locked} onClick={event=>{editor.activateSurface(event.currentTarget);editor.change(layout=>changeSharedPanel(layout,panel.id,{locked:!panel.locked}),panel.locked?'Unlock panel':'Protect panel');}}><LockGlyph locked={panel.locked}/><span>{panel.locked?'Edit section':canRelockPanel(page,editor.record.base||editor.record.content,editor.content,panel.id)?'Protect section':'Saving section…'}</span></Control>{editor.arrangingPage&&!panel.locked&&<><label className="page-panel-zone-label"><span className="sr-only">Location for {title(panel,page,editor.content,editor.records)}</span><select aria-label={'Location for '+title(panel,page,editor.content,editor.records)} value={panel.fullWidth?'full':panel.zone} disabled={editor.busy} onChange={event=>editor.change(layout=>event.target.value==='full'?changeSharedPanel(layout,panel.id,{fullWidth:true}):moveSharedPanel(panel.kind==='hero'?changeSharedPanel(layout,panel.id,{fullWidth:false}):layout,panel.id,{zone:event.target.value}))}><option value="main">Main area</option><option value="side">Side area</option>{panel.kind==='hero'&&<option value="full">Full width</option>}</select></label>{!narrow&&<><Control type="button" disabled={editor.busy||ordered.filter(p=>p.zone===panel.zone)[0]?.id===panel.id} aria-label={'Move '+title(panel,page,editor.content,editor.records)+' earlier'} onClick={()=>editor.change(layout=>stepSharedPanel(layout,panel.id,-1))}><Glyph name="arrow" className="arrange-up"/></Control><Control type="button" disabled={editor.busy||ordered.filter(p=>p.zone===panel.zone).at(-1)?.id===panel.id} aria-label={'Move '+title(panel,page,editor.content,editor.records)+' later'} onClick={()=>editor.change(layout=>stepSharedPanel(layout,panel.id,1))}><Glyph name="arrow" className="arrange-down"/></Control></>}<Control type="button" disabled={editor.busy} aria-label={'Remove '+title(panel,page,editor.content,editor.records)} onClick={()=>remove(panel)}><Glyph name="close"/><span>Remove</span></Control></>}</div>}
  <PagePanelLockContext.Provider value={panel.locked}>{panel.kind==='hero'?mediaOnly?<CardContentLayout page={page} items={{media:children}}/>:children||<p className="page-editor-help">The primary hero has no media yet. Unlock it to choose a photo.</p>:panel.kind==='native'?nativePanels[panel.id]:<PanelContent page={page} panel={panel}/>}</PagePanelLockContext.Provider>
 </section>;
 // Keep the media editor in its ordered panel while uploads change hero mode.
 // Moving it from a separate optional slot into the grid mid-upload loses its
 // progress state, focus and in-flight lock after the first completed file.
 const renderInPlace=panel=>mediaOnly&&editor.editing&&panel.kind==='hero'?<OptionalPageMedia key={panel.id} initialOpen={editor.content.hero.mode!=='default'}><summary>{editor.content.hero.mode==='default'?'Add page photo or video':'Page photo or video'}</summary>{render(panel)}</OptionalPageMedia>:render(panel);
 const hasSide=!!sideTail||visible.some(p=>p.zone==='side'),topHero=!narrow&&visible.find(panel=>panel.kind==='hero'&&panel.fullWidth);
 return <div ref={drag.root} className={'page-panel-layout '+(narrow?'is-mobile':'is-wide')+(hasSide?' has-side':'')+(editor.editing?' is-editing':'')} data-panel-page={page}>
  {ordered.length>0||mainTail||sideTail? <>{topHero&&<div className="page-panel-full-width">{renderInPlace(topHero)}{afterPrimary}</div>}{narrow?<div className="page-panel-mobile-stack">{ordered.map(panel=><React.Fragment key={panel.id}>{renderInPlace(panel)}{panel.kind==='hero'&&afterPrimary}</React.Fragment>)}{mainTail}{sideTail}</div>:<div className="page-panel-columns">{['main','side'].map(zone=><div key={zone} className={'page-panel-zone page-panel-zone-'+zone} {...drag.drop(zone)}>{editor.editing&&editor.arrangingPage&&<p className="page-panel-zone-heading">{zone==='main'?'Main panels':'Side panels'}</p>}{ordered.filter(panel=>panel.zone===zone&&panel!==topHero).map(panel=><React.Fragment key={panel.id}>{renderInPlace(panel)}{panel.kind==='hero'&&afterPrimary}</React.Fragment>)}{zone==='main'?mainTail:sideTail}{editor.editing&&editor.arrangingPage&&<div className="page-panel-drop-end" {...drag.drop(zone)}>Drop {zone==='main'?'main':'side'} panel here</div>}</div>)}</div>}
  </>:null}
  {editor.editing&&!editor.arrangingPage&&selectedPanel&&editor.activeEditor===toolId&&<PageObjectTools title={'Panel · '+title(selectedPanel,page,editor.content,editor.records)} returnFocus={toolTrigger.current} onClose={()=>{setToolPanel(null);editor.activateSurface(null)}}>
   <p>{selectedPanel.locked?'Protected panel. Unlock it to change its content or location.':'Select text or a photo on the page to edit it directly.'}</p>
   <div className="page-object-tools-actions"><Control type="button" disabled={editor.busy||!canRelockPanel(page,editor.record.base||editor.record.content,editor.content,selectedPanel.id)} aria-label={(selectedPanel.locked?'Unlock ':'Lock ')+title(selectedPanel,page,editor.content,editor.records)} aria-pressed={selectedPanel.locked} onClick={()=>editor.change(layout=>changeSharedPanel(layout,selectedPanel.id,{locked:!selectedPanel.locked}),selectedPanel.locked?'Unlock panel':'Protect panel')}><LockGlyph locked={selectedPanel.locked}/>{selectedPanel.locked?'Unlock to edit':'Protect panel'}</Control></div>
   {!selectedPanel.locked&&<>{cardSlots(page,selectedPanel).length>0&&<div className="page-object-tools-group"><h3>Content in this panel</h3><div className="page-object-tools-actions">{cardSlots(page,selectedPanel).map(slot=><Control key={slot.id} type="button" onClick={()=>editor.setObjectRequest({page,cardId:selectedPanel.id,slotId:slot.id})}>{slot.label}</Control>)}</div></div>}<label>Page area<select aria-label={'Location for '+title(selectedPanel,page,editor.content,editor.records)} value={selectedPanel.fullWidth?'full':selectedPanel.zone} disabled={editor.busy} onChange={event=>editor.change(layout=>event.target.value==='full'?changeSharedPanel(layout,selectedPanel.id,{fullWidth:true}):moveSharedPanel(selectedPanel.kind==='hero'?changeSharedPanel(layout,selectedPanel.id,{fullWidth:false}):layout,selectedPanel.id,{zone:event.target.value}),'Change page area')}><option value="main">Main area</option><option value="side">Side area</option>{selectedPanel.kind==='hero'&&<option value="full">Full width</option>}</select></label><div className="page-object-tools-group"><h3>{narrow?'Phone':'Wide'} order</h3><p>{narrow?'Wide order stays unchanged.':'Phone order stays unchanged.'}</p><div className="page-object-tools-actions">{[-1,1].map(direction=><Control key={direction} type="button" disabled={editor.busy} onClick={()=>{const moved=editor.change(layout=>stepSharedPanel(layout,selectedPanel.id,direction,narrow),'Move panel');setNotice(moved?'Panel moved. Changes save automatically.':'This move reaches the end or crosses a protected panel.')}}>{direction<0?'Move earlier':'Move later'}</Control>)}</div></div><div className="page-object-tools-actions"><Control type="button" disabled={editor.busy} onClick={()=>{remove(selectedPanel);setToolPanel(null);editor.activateSurface(null)}}>Remove panel</Control></div></>}
   <p role="status">{notice||'Changes save automatically.'}</p>
  </PageObjectTools>}
  {editor.editing&&<>{removed&&<div className="page-panel-undo" role="status"><span>{removed.title} removed.</span><Control type="button" disabled={editor.busy} onClick={()=>restore(removed.id,removed.placement)}>Undo</Control></div>}{archived.length>0&&<InlineDisclosure className="page-removed-panels" label={'Removed panels · '+archived.length} icon="history"><p className="page-editor-help">Removed panels remain recoverable in this page and its saved history.</p>{archived.map(panel=><div key={panel.id}><span>{title(panel,page,editor.content,editor.records)}</span><Control type="button" disabled={editor.busy} onClick={()=>restore(panel.id)}>Restore panel</Control></div>)}</InlineDisclosure>}<p className="sr-only" role="status">{notice}</p></>}
 </div>;
}
function PanelContent({page,panel}){
 const editor=useLayoutEditor(page),editable=editor.editing&&!panel.locked;
 return <div className={'page-panel-content page-panel-preset-'+panel.layout}><CardContentLayout page={page} cardId={panel.id} hidden={!editable&&!panel.media.length?['media']:[]} items={{
  media:['photo','feature'].includes(panel.layout)&&<PanelPhoto page={page} panel={panel}/>,
  title:<PanelCopy page={page} panel={panel} field="title" label="Panel heading" as="h2" editable={editable}/>,
  body:<PanelCopy page={page} panel={panel} field="body" label={title(panel,page,editor.content,editor.records)+' body text'} editable={editable}/>,
  secondary:panel.layout==='columns'&&<PanelCopy page={page} panel={panel} field="secondary" label={title(panel,page,editor.content,editor.records)+' second column'} editable={editable}/>
 }}/></div>;
}
function PanelCopy({page,panel,field,label,as:Tag='div',editable}){
 const editor=useLayoutEditor(page),id=useId(),trigger=useRef(null),[active,setActive]=useState(false),original=useRef(''),text=panel[field];
 useEffect(()=>{if(!editable||active&&editor.activeEditor!==id)setActive(false)},[editable,active,editor.activeEditor,id]);
 const finish=()=>{setActive(false);requestAnimationFrame(()=>trigger.current?.focus())};
 const change=value=>editor.change(layout=>changeSharedPanel(layout,panel.id,{[field]:value}));
 const Target=field==='title'?'span':'div',shown=field==='title'?text:<PageMarkdownBody source={text} className="page-panel-body"/>;
 if(!editable)return <Tag>{shown}</Tag>;
 const start=event=>{original.current=text;editor.activateSurface(event.currentTarget,id);setActive(true)};
 return <Tag className="page-panel-live-copy">{active?field==='title'?<span className="page-panel-text-edit"><input className="page-copy-input page-panel-title-input" aria-label={label} value={text} maxLength={PANEL_LIMITS.maxTitle} autoFocus onChange={event=>change(event.target.value)} onKeyDown={event=>{if(event.nativeEvent.isComposing)return;if(event.key==='Enter'){event.preventDefault();finish()}else if(event.key==='Escape'){event.preventDefault();change(original.current);finish()}}}/><Control type="button" className="page-field-done" aria-label={'Finish editing '+label} onClick={finish}><Glyph name="check"/></Control></span>:<PageMarkdownEditor inline ariaLabel={label} value={text} maxLength={PANEL_LIMITS.maxBody} onChange={change} onDone={finish} autoFocus/>:<Target ref={trigger} className="page-panel-copy-target" role="button" tabIndex={0} aria-label={'Edit '+label} onClick={start} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();start(event)}}}>{text?shown:<span className="page-empty-copy">{field==='title'?'Add a heading':field==='secondary'?'Add second-column text':'Add text'}</span>}</Target>}</Tag>;
}
function PanelPhoto({page,panel}){
 const editor=useLayoutEditor(page),[uploading,setUploading]=useState(false),[error,setError]=useState(''),lock=useRef(false),alive=useRef(true),file=panel.media[0],editable=editor.editing&&!panel.locked,[editingPhoto,setEditingPhoto]=useState(false),photoToolId=useId(),photoTrigger=useRef(null);
 useEffect(()=>()=>{alive.current=false},[]);
 useEffect(()=>{if(!editable||editingPhoto&&editor.activeEditor!==photoToolId)setEditingPhoto(false)},[editable,editingPhoto,editor.activeEditor,photoToolId]);
 const setMedia=media=>editor.change(layout=>changeSharedPanel(layout,panel.id,{media}),'Change panel photo');
 async function upload(file){if(!file||lock.current)return;lock.current=true;setUploading(true);setError('');const finish=editor.beginWork();try{const limit=editor.preview?2*1024*1024:SHARED_CONTENT_LIMITS.maxMediaBytes;if(!SHARED_IMAGE_TYPES.includes(file.type)||!file.size||file.size>limit)throw Error('Choose a JPEG, PNG, WebP or GIF photo under '+limit/1024/1024+' MB.');const output=await readPreviewFile(file,editor.preview?'preview':'live');setMedia([{...output,id:output.id||'preview-'+crypto.randomUUID(),alt:''}]);}catch(error){if(alive.current)setError(error.message)}finally{lock.current=false;finish();if(alive.current)setUploading(false)}}
 if(!file&&!editable)return null;
 return <div className="page-panel-photo">{editable?<ImageUploadControl label="Panel photo" src={file?safePageMediaUrl(file.url,editor.preview):''} alt={file?.alt||''} accept={SHARED_IMAGE_TYPES.join(',')} disabled={editor.busy&&!uploading} busy={uploading} progress={uploading?'Uploading panel photo…':''} error={error} frame={file?.frame} onFrameChange={frame=>setMedia([{...file,frame}])} onEdit={node=>{photoTrigger.current=node;editor.activateSurface(node,photoToolId);setEditingPhoto(true)}} onFiles={files=>void upload(files[0])}/>:file&&safePageMediaUrl(file.url,editor.preview)?<div className="page-panel-photo-crop"><img src={safePageMediaUrl(file.url,editor.preview)} alt={file.alt||''} style={photoFrameStyle(file.frame)}/></div>:<div className="page-panel-photo-empty">Photo unavailable</div>}{editable&&file&&editingPhoto&&<PanelPhotoTask page={page} panel={panel} file={file} returnFocus={photoTrigger.current} onClose={()=>setEditingPhoto(false)}/>}</div>;
}

function PanelPhotoTask({page,panel,file,returnFocus,onClose}){
 const editor=useLayoutEditor(page),imageLayout=useContext(ImageLayoutContext),baseline=useRef(JSON.stringify(file)),baselineLayout=useRef(JSON.stringify(imageLayout?.value)),recovery=useImageEditDraft({page,object:panel.id,initial:{file:{...file},layout:imageLayout?.value},validate:value=>{try{const next={...editor.content,panelLayout:changeSharedPanel(panelLayoutOf(editor.content,page),panel.id,{media:value.file?[value.file]:[]})};validateSharedPageContent(page,value.layout&&imageLayout?.apply?imageLayout.apply(next,value.layout):next);return true}catch{return false}}}),draft=recovery.value.file,setDraft=change=>recovery.setValue(value=>({...value,file:typeof change==='function'?change(value.file):change})),[uploading,setUploading]=useState(false),[error,setError]=useState(''),picker=useRef(null),alive=useRef(true),lock=useRef(false);
 useEffect(()=>()=>{alive.current=false},[]);
 const cancel=()=>{recovery.clear();onClose()};
 const apply=(frame,layout)=>{if(JSON.stringify(panel.media[0])!==baseline.current||JSON.stringify(imageLayout?.value)!==baselineLayout.current){setError('This photo changed while you were editing. Close and reopen it to review the latest version.');return}const updated=editor.update(page,content=>{const next={...content,panelLayout:changeSharedPanel(panelLayoutOf(content,page),panel.id,{media:draft?[{...draft,frame}]:[]})};return layout&&imageLayout?.apply?imageLayout.apply(next,layout):next},{historyLabel:'Edit panel photo'});if(updated){recovery.clear();onClose()}};
 async function replace(file){if(!file||lock.current)return;lock.current=true;setUploading(true);setError('');const finish=editor.beginWork();try{const limit=editor.preview?2*1024*1024:SHARED_CONTENT_LIMITS.maxMediaBytes;if(!SHARED_IMAGE_TYPES.includes(file.type)||!file.size||file.size>limit)throw Error('Choose a JPEG, PNG, WebP or GIF photo under '+limit/1024/1024+' MB.');const output=await readPreviewFile(file,editor.preview?'preview':'live');if(alive.current)setDraft({...output,id:output.id||'preview-'+crypto.randomUUID(),alt:''})}catch(error){if(alive.current)setError(error.message)}finally{lock.current=false;finish();if(alive.current)setUploading(false)}}
 return <PageObjectTools title={'Photo · '+title(panel,page,editor.content,editor.records)} fullHeight returnFocus={returnFocus} onClose={()=>{if(!uploading)cancel()}}>
  {error&&<p role="alert" className="page-editor-error">{error}</p>}{recovery.storageError&&<p role="alert">{recovery.storageError}</p>}{recovery.recovered&&<p>Recovered image edit from this tab.</p>}{uploading&&<p role="status">Uploading replacement photo… Your original photo is unchanged.</p>}
  <ImageLayoutContext.Provider value={imageLayout?{...imageLayout,value:recovery.value.layout}:null}>{draft?<PhotoFramingEditor src={safePageMediaUrl(draft.url,editor.preview)} alt={draft.alt||''} frame={draft.frame} disabled={uploading} atomicLayout onCancel={cancel} onSave={apply} onDraftChange={({frame,layout})=>recovery.setValue(value=>({...value,file:{...value.file,frame},layout}))} onChangeMedia={()=>picker.current?.click()} details={<div className="page-object-tools-group"><label>Photo description<input aria-label="Photo description" maxLength={240} disabled={uploading} value={draft.alt||''} onChange={event=>setDraft({...draft,alt:event.target.value})}/></label><Control type="button" disabled={uploading} onClick={()=>setDraft(null)}>Remove photo</Control></div>}/>:<><p>The photo will be removed when you apply this edit.</p><div className="photo-framing-actions"><Button secondary onClick={cancel}>Cancel</Button><Button onClick={()=>apply()}>Apply removal</Button></div></>}</ImageLayoutContext.Provider>
  <input ref={picker} type="file" className="sr-only" tabIndex={-1} aria-label="Replacement panel photo" accept={SHARED_IMAGE_TYPES.join(',')} disabled={uploading} onChange={event=>{const file=event.target.files?.[0];event.target.value='';void replace(file)}}/>
 </PageObjectTools>;
}
