import {CardContentLayout} from './card-content-layout.jsx';
import {photoFrameStyle} from './photo-framing.jsx';
import {InlineDisclosure} from './inline-disclosure.jsx';
import {ImageUploadControl} from './image-upload-control.jsx';
import {PageMarkdownEditor,PageMarkdownBody} from './page-markdown.jsx';
import React,{useEffect,useRef,useState} from 'react';
import {Button,Control,Glyph,Sheet,useApp} from './ui-core.jsx';
import {usePageContent,PagePanelLockContext,safePageMediaUrl} from './page-content.jsx';
import {readPreviewFile} from './uploads.js';
import {SHARED_IMAGE_TYPES,SHARED_CONTENT_LIMITS,SHARED_PAGE_SCHEMA} from './shared-content-schema.js';
import {PANEL_PRESETS,PANEL_LIMITS,panelLayoutOf,createSharedPanel,addSharedPanel,changeSharedPanel,removeSharedPanel,restoreSharedPanel,moveSharedPanel,stepSharedPanel,canRelockPanel,sharedPanelTitle,keyboardSharedPanel} from './shared-panels.js';
import './page-panels.css';
const title=(panel,page)=>sharedPanelTitle(page,panel);
const zoneLabel=zone=>zone==='side'?'Side panel':'Main panel';
function useNarrow(){const [narrow,setNarrow]=useState(()=>typeof matchMedia==='function'&&matchMedia('(max-width: 700px)').matches);useEffect(()=>{const query=matchMedia('(max-width: 700px)'),update=()=>setNarrow(query.matches);update();query.addEventListener('change',update);return()=>query.removeEventListener('change',update)},[]);return narrow;}
function LayoutGlyph({layout}){return <svg viewBox="0 0 48 34" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><rect x="2" y="2" width="44" height="30" rx="3"/>{layout==='text'?<path d="M9 10h22M9 16h30M9 22h25"/>:layout==='columns'?<path d="M9 10h12M9 16h12M9 22h12M27 10h12M27 16h12M27 22h12"/>:layout==='photo'?<><rect x="8" y="7" width="32" height="12" rx="1"/><path d="M8 24h32M8 28h22"/></>:<><rect x="8" y="7" width="14" height="20" rx="1"/><path d="M27 10h13M27 16h13M27 22h10"/></>}</svg>;}
function DragGlyph(){return <svg className="glyph" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M8 5h1m6 0h1M8 12h1m6 0h1M8 19h1m6 0h1" strokeLinecap="round"/></svg>;}
function LockGlyph({locked}){return <svg className="glyph" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><rect x="5" y="10" width="14" height="11" rx="2"/>{locked?<path d="M8 10V7a4 4 0 0 1 8 0v3"/>:<path d="M8 10V7a4 4 0 0 1 8 0"/>}<path d="M12 14v3"/></svg>;}
function useLayoutEditor(page){const editor=usePageContent(page),layout=panelLayoutOf(editor.content,page),busy=editor.pending||editor.record?.status==='saving';const change=fn=>{let changed=false;const updated=editor.update(page,content=>{const layout=panelLayoutOf(content,page),next=fn(layout);changed=next!==layout;return {...content,panelLayout:next}});return updated&&changed;};return {...editor,layout,busy,change};}
// Pointer capture supports tablet touch dragging. Native drag supports mouse;
// all mutations also have ordinary buttons and a labelled location select.
function usePanelDrag({disabled,onMove,onKeyMove}){
 const [dragging,setDragging]=useState(null),[over,setOver]=useState(null),gesture=useRef(null),root=useRef(null);
 const reset=()=>{gesture.current=null;setDragging(null);setOver(null);};
 useEffect(()=>{if(disabled)reset()},[disabled]);
 const targetAt=(x,y)=>{const node=document.elementFromPoint(x,y)?.closest('[data-panel-drop]');if(!node||!root.current?.contains(node))return null;const panel=node.closest('[data-panel-id]');return {zone:node.dataset.panelDrop,beforeId:panel?.dataset.panelId||null};};
 const commit=target=>{const id=gesture.current?.id||dragging;if(id&&target)onMove(id,target);reset();};
 const handle=(panel)=>({
  draggable:!disabled&&!panel.locked,
  onDragStart:event=>{if(disabled||panel.locked){event.preventDefault();return;}gesture.current={id:panel.id,native:true};setDragging(panel.id);event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',panel.id);},
  onDragEnd:reset,
  onPointerDown:event=>{if(disabled||panel.locked||event.button!==0)return;gesture.current={id:panel.id,x:event.clientX,y:event.clientY,active:false,pointer:event.pointerId};try{event.currentTarget.setPointerCapture?.(event.pointerId)}catch{}},
  onPointerMove:event=>{const g=gesture.current;if(!g||g.pointer!==event.pointerId)return;if(!g.active&&Math.hypot(event.clientX-g.x,event.clientY-g.y)<7)return;g.active=true;setDragging(g.id);const scroller=root.current?.closest('dialog')||document.scrollingElement;if(scroller){const rect=scroller.getBoundingClientRect();if(event.clientY<rect.top+48)scroller.scrollTop-=18;else if(event.clientY>Math.min(rect.bottom,window.innerHeight)-48)scroller.scrollTop+=18;}setOver(targetAt(event.clientX,event.clientY));},
  onPointerUp:event=>{const g=gesture.current;if(g?.pointer!==event.pointerId)return;if(g.active)commit(targetAt(event.clientX,event.clientY));else reset();},
  onPointerCancel:event=>{if(gesture.current?.pointer===event.pointerId)reset()},
  onLostPointerCapture:event=>{if(gesture.current?.pointer===event.pointerId)reset()},
  onKeyDown:event=>{if(event.key==='Escape'){event.preventDefault();reset();return}if(!disabled&&!panel.locked&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();onKeyMove?.(panel.id,event.key)}}
 });
 const drop=(zone,beforeId=null)=>({
  'data-panel-drop':zone,
  onDragOver:event=>{if(!dragging||disabled)return;event.preventDefault();event.stopPropagation();event.dataTransfer.dropEffect='move';setOver({zone,beforeId});},
  onDrop:event=>{if(!dragging||disabled)return;event.preventDefault();event.stopPropagation();commit({zone,beforeId});},
  'data-drop-active':!!dragging&&over?.zone===zone&&over?.beforeId===beforeId||undefined
 });
 return {root,handle,drop,dragging};
}
export function PagePanelActions({page}){
 const app=useApp(),target=page==='family'?(app.route?.tab||'people'):page,editor=useLayoutEditor(target),[modal,setModal]=useState(null);
 useEffect(()=>setModal(null),[target,editor.editing]);
 if(!editor.editing||!editor.valid||target==='global')return null;
 return <div className="page-panel-actions"><Control type="button" disabled={editor.busy||editor.layout.panels.filter(p=>p.kind==='content').length>=PANEL_LIMITS.maxCustomPanels} onClick={()=>setModal('add')}><Glyph name="plus"/>Add Panel</Control><Control type="button" className="page-mobile-order-entry" disabled={editor.busy||editor.layout.mobileOrder.length<2} onClick={()=>setModal('mobile')}><DragGlyph/>Reorder for mobile</Control><span className="page-editor-help">{page==='family'?SHARED_PAGE_SCHEMA[target].label+' · ':''}{editor.layout.panels.filter(p=>p.kind==='content').length>=PANEL_LIMITS.maxCustomPanels?'23 custom panels reached. Restore a removed panel to reuse it.':'Only shared page content is editable.'}</span>{modal==='add'&&<AddPanel page={target} onClose={()=>setModal(null)}/>} {modal==='mobile'&&<MobilePanelOrder page={target} onClose={()=>setModal(null)}/>}</div>;
}
function AddPanel({page,onClose}){
 const editor=useLayoutEditor(page),[zone,setZone]=useState('main'),[preset,setPreset]=useState('text'),[error,setError]=useState('');
 const add=()=>{try{const panel=createSharedPanel('panel-'+crypto.randomUUID(),zone,preset);if(editor.change(layout=>addSharedPanel(layout,panel))){onClose();requestAnimationFrame(()=>document.querySelector('[data-panel-id="'+panel.id+'"] .page-panel-title-input')?.focus());}}catch(error){setError(error.message)}};
 return <Sheet title="Add Panel" kind="filter" onClose={onClose}><div className="page-add-panel"><fieldset><legend>Panel location</legend><div className="page-panel-location-options">{['main','side'].map(value=><label key={value}><input type="radio" name="panel-zone" value={value} checked={zone===value} onChange={()=>setZone(value)}/><span>{zoneLabel(value)}</span></label>)}</div></fieldset><fieldset><legend>Choose a layout</legend><div className="page-layout-presets">{PANEL_PRESETS.map(option=><label key={option.id}><input type="radio" name="panel-preset" value={option.id} checked={preset===option.id} onChange={()=>setPreset(option.id)}/><span><LayoutGlyph layout={option.id}/><strong>{option.label}</strong></span></label>)}</div><p className="page-editor-help">{PANEL_PRESETS.find(p=>p.id===preset).description}</p></fieldset><p className="page-editor-help">Your new panel starts unlocked. Changes stay in your draft until you save the page.</p>{error&&<p role="alert" className="page-editor-error">{error}</p>}<Button disabled={editor.busy} onClick={add}>Add {zone==='main'?'main':'side'} panel</Button></div></Sheet>;
}
function MobilePanelOrder({page,onClose}){
 const editor=useLayoutEditor(page),[notice,setNotice]=useState(''),drag=usePanelDrag({disabled:editor.busy,onKeyMove:(id,key)=>{const moved=editor.change(layout=>keyboardSharedPanel(layout,id,key,true));setNotice(moved?'Mobile order updated in your draft.':'That panel cannot move there. Unlock any panel in the way first.');},onMove:(id,target)=>{const moved=editor.change(layout=>moveSharedPanel(layout,id,{beforeId:target.beforeId,mobile:true}));setNotice(moved?'Mobile order updated in your draft.':'That move crosses a locked panel. Unlock it first.');}}),panels=editor.layout.mobileOrder.map(id=>editor.layout.panels.find(p=>p.id===id));
 return <Sheet title="Reorder for mobile" kind="filter" onClose={onClose}><div ref={drag.root} className="page-mobile-reorder"><p className="page-editor-help">Drag the text rows or use Earlier and Later. Desktop and tablet positions stay the same. Use the drag handle’s arrow keys for keyboard moves. Unlock a locked panel inline to move it.</p><ol>{panels.map((panel,index)=><li key={panel.id} data-panel-id={panel.id} {...drag.drop('mobile',panel.id)}><Control type="button" className="page-panel-drag" aria-label={'Drag '+title(panel,page)+' for mobile'} disabled={editor.busy||panel.locked} {...drag.handle(panel)}><DragGlyph/></Control><span className="page-mobile-drag-label" {...drag.handle(panel)}><strong>{title(panel,page)}</strong><small>{zoneLabel(panel.zone)}{panel.locked?' · Locked':''}</small></span><div><Control type="button" disabled={editor.busy||panel.locked||index===0} aria-label={'Move '+title(panel,page)+' earlier on mobile'} onClick={()=>{const moved=editor.change(layout=>stepSharedPanel(layout,panel.id,-1,true));setNotice(moved?'Mobile order updated in your draft.':'Unlock the panel in the way first.')}}>Earlier</Control><Control type="button" disabled={editor.busy||panel.locked||index===panels.length-1} aria-label={'Move '+title(panel,page)+' later on mobile'} onClick={()=>{const moved=editor.change(layout=>stepSharedPanel(layout,panel.id,1,true));setNotice(moved?'Mobile order updated in your draft.':'Unlock the panel in the way first.')}}>Later</Control></div></li>)}</ol><div className="page-panel-drop-end" {...drag.drop('mobile')}>Drop at end</div><p role="status" className="page-editor-help">{notice}</p><Button onClick={onClose}>Done</Button></div></Sheet>;
}
export function SharedPagePanels({page,children,mediaOnly=false,mainTail=null,sideTail=null,wideHero=false,afterPrimary=null,nativePanels={}}){
 const editor=useLayoutEditor(page),narrow=useNarrow(),[removed,setRemoved]=useState(null),[notice,setNotice]=useState(''),drag=usePanelDrag({disabled:editor.busy||!editor.editing||narrow,onKeyMove:(id,key)=>{const moved=editor.change(layout=>keyboardSharedPanel(layout,id,key));setNotice(moved?'Panel moved. Save changes to share the new layout.':'That panel cannot move there. Unlock any panel in the way first.');},onMove:(id,target)=>{const moved=editor.change(layout=>moveSharedPanel(layout,id,target));setNotice(moved?'Panel moved. Save changes to share the new layout.':'That move crosses a locked panel. Unlock it first.');}});
 const visible=editor.layout.panels.filter(p=>!p.removed&&(p.kind!=='native'||nativePanels[p.id]!=null&&nativePanels[p.id]!==false)&&!(p.kind==='hero'&&mediaOnly&&editor.content.hero.mode==='default'&&!editor.editing)),archived=editor.layout.panels.filter(p=>p.removed),order=narrow?editor.layout.mobileOrder:editor.layout.desktopOrder,ordered=order.map(id=>visible.find(p=>p.id===id)).filter(Boolean);
 if(!editor.valid)return <>{children}{afterPrimary}{Object.values(nativePanels)}{mainTail}{sideTail}</>;
 const remove=panel=>{const placement={desktop:editor.layout.desktopOrder.indexOf(panel.id),mobile:editor.layout.mobileOrder.indexOf(panel.id)};editor.change(layout=>removeSharedPanel(layout,panel.id));setRemoved({id:panel.id,title:title(panel,page),placement});setNotice(title(panel,page)+' removed from this page. Undo is available.');};
 const restore=(id,placement)=>{editor.change(layout=>restoreSharedPanel(layout,id,placement));setRemoved(null);setNotice('Panel restored.');};
 const render=panel=><section key={panel.id} className={'page-shared-panel '+(panel.kind==='hero'?'page-primary-hero':panel.kind==='native'?'page-native-panel':'card page-custom-panel')+(editor.editing?' is-panel-editing':'')} data-panel-id={panel.id} data-panel-zone={panel.zone} data-panel-locked={panel.locked||undefined} {...(!narrow?drag.drop(panel.zone,panel.id):{})}>
  {editor.editing&&<div className="page-panel-inline-controls"><span className="page-panel-name">{title(panel,page)}</span>{!narrow&&<Control type="button" className="page-panel-drag" aria-label={'Drag '+title(panel,page)+'. Arrow keys move or change column'} disabled={editor.busy||panel.locked} {...drag.handle(panel)}><DragGlyph/></Control>}<Control type="button" disabled={editor.busy||!canRelockPanel(page,editor.record.base||editor.record.content,editor.content,panel.id)} title={!canRelockPanel(page,editor.record.base||editor.record.content,editor.content,panel.id)?'Save these changes before locking the panel':undefined} aria-label={(panel.locked?'Unlock ':'Lock ')+title(panel,page)} aria-pressed={panel.locked} onClick={event=>{editor.activateSurface(event.currentTarget);editor.change(layout=>changeSharedPanel(layout,panel.id,{locked:!panel.locked}));}}><LockGlyph locked={panel.locked}/><span>{panel.locked?'Unlock':canRelockPanel(page,editor.record.base||editor.record.content,editor.content,panel.id)?'Lock':'Save to lock'}</span></Control>{!panel.locked&&<><label className="page-panel-zone-label"><span className="sr-only">Location for {title(panel,page)}</span><select aria-label={'Location for '+title(panel,page)} value={panel.zone} disabled={editor.busy} onChange={event=>editor.change(layout=>moveSharedPanel(layout,panel.id,{zone:event.target.value}))}><option value="main">Main panel</option><option value="side">Side panel</option></select></label>{!narrow&&<><Control type="button" disabled={editor.busy||ordered.filter(p=>p.zone===panel.zone)[0]?.id===panel.id} aria-label={'Move '+title(panel,page)+' earlier'} onClick={()=>editor.change(layout=>stepSharedPanel(layout,panel.id,-1))}>Earlier</Control><Control type="button" disabled={editor.busy||ordered.filter(p=>p.zone===panel.zone).at(-1)?.id===panel.id} aria-label={'Move '+title(panel,page)+' later'} onClick={()=>editor.change(layout=>stepSharedPanel(layout,panel.id,1))}>Later</Control></>}<Control type="button" disabled={editor.busy} aria-label={'Remove '+title(panel,page)} onClick={()=>remove(panel)}><Glyph name="close"/><span>Remove</span></Control></>}</div>}
  <PagePanelLockContext.Provider value={panel.locked}>{panel.kind==='hero'?mediaOnly?<CardContentLayout page={page} items={{media:children}}/>:children||<p className="page-editor-help">The primary hero has no media yet. Unlock it to choose a photo.</p>:panel.kind==='native'?nativePanels[panel.id]:<PanelContent page={page} panel={panel}/>}</PagePanelLockContext.Provider>
 </section>;
 const hasSide=!!sideTail||visible.some(p=>p.zone==='side'),topHero=null;
 return <div ref={drag.root} className={'page-panel-layout '+(narrow?'is-mobile':'is-wide')+(hasSide?' has-side':'')+(editor.editing?' is-editing':'')} data-panel-page={page}>
  {topHero&&<>{render(topHero)}{afterPrimary}</>}{narrow?<div className="page-panel-mobile-stack">{ordered.map(panel=><React.Fragment key={panel.id}>{render(panel)}{panel.kind==='hero'&&afterPrimary}</React.Fragment>)}{mainTail}{sideTail}</div>:<div className="page-panel-columns">{['main','side'].map(zone=><div key={zone} className={'page-panel-zone page-panel-zone-'+zone} {...drag.drop(zone)}>{editor.editing&&<p className="page-panel-zone-heading">{zone==='main'?'Main panels':'Side panels'}</p>}{ordered.filter(panel=>panel.zone===zone&&panel!==topHero).map(panel=><React.Fragment key={panel.id}>{render(panel)}{panel.kind==='hero'&&afterPrimary}</React.Fragment>)}{zone==='main'?mainTail:sideTail}{editor.editing&&<div className="page-panel-drop-end" {...drag.drop(zone)}>Drop {zone==='main'?'main':'side'} panel here</div>}</div>)}</div>}
  {editor.editing&&<>{removed&&<div className="page-panel-undo" role="status"><span>{removed.title} removed.</span><Control type="button" disabled={editor.busy} onClick={()=>restore(removed.id,removed.placement)}>Undo</Control></div>}{archived.length>0&&<InlineDisclosure className="page-removed-panels" label={'Removed panels · '+archived.length} icon="history"><p className="page-editor-help">Removed panels remain recoverable in this page and its saved history.</p>{archived.map(panel=><div key={panel.id}><span>{title(panel,page)}</span><Control type="button" disabled={editor.busy} onClick={()=>restore(panel.id)}>Restore panel</Control></div>)}</InlineDisclosure>}<p className="sr-only" role="status">{notice}</p></>}
 </div>;
}
function PanelContent({page,panel}){
 const editor=useLayoutEditor(page),editable=editor.editing&&!panel.locked,change=(key,value)=>editor.change(layout=>changeSharedPanel(layout,panel.id,{[key]:value}));
 return <div className={'page-panel-content page-panel-preset-'+panel.layout}><CardContentLayout page={page} cardId={panel.id} hidden={!editable&&!panel.media.length?['media']:[]} items={{
  media:['photo','feature'].includes(panel.layout)&&<PanelPhoto page={page} panel={panel}/>,
  title:editable?<label className="page-panel-field"><span>Panel heading</span><input className="page-panel-title-input" maxLength={PANEL_LIMITS.maxTitle} disabled={editor.busy} value={panel.title} onFocus={event=>editor.activateSurface(event.currentTarget)} onChange={event=>change('title',event.target.value)}/></label>:<h2>{panel.title}</h2>,
  body:editable?<div className="page-panel-field" onFocus={event=>editor.activateSurface(event.currentTarget)}><span>Body text</span><PageMarkdownEditor ariaLabel={title(panel,page)+' body text'} value={panel.body} maxLength={PANEL_LIMITS.maxBody} disabled={editor.busy} onChange={value=>change('body',value)}/></div>:<PageMarkdownBody source={panel.body} className="page-panel-body"/>,
  secondary:panel.layout==='columns'&&(editable?<div className="page-panel-field" onFocus={event=>editor.activateSurface(event.currentTarget)}><span>Second column</span><PageMarkdownEditor ariaLabel={title(panel,page)+' second column'} value={panel.secondary} maxLength={PANEL_LIMITS.maxBody} disabled={editor.busy} onChange={value=>change('secondary',value)}/></div>:<PageMarkdownBody source={panel.secondary} className="page-panel-body"/>)
 }}/></div>;
}
function PanelPhoto({page,panel}){
 const editor=useLayoutEditor(page),[uploading,setUploading]=useState(false),[error,setError]=useState(''),lock=useRef(false),alive=useRef(true),file=panel.media[0],editable=editor.editing&&!panel.locked;
 useEffect(()=>()=>{alive.current=false},[]);
 const setMedia=media=>editor.change(layout=>changeSharedPanel(layout,panel.id,{media}));
 async function upload(file){if(!file||lock.current)return;lock.current=true;setUploading(true);setError('');const finish=editor.beginWork();try{const limit=editor.preview?2*1024*1024:SHARED_CONTENT_LIMITS.maxMediaBytes;if(!SHARED_IMAGE_TYPES.includes(file.type)||!file.size||file.size>limit)throw Error('Choose a JPEG, PNG, WebP or GIF photo under '+limit/1024/1024+' MB.');const output=await readPreviewFile(file,editor.preview?'preview':'live');setMedia([{...output,id:output.id||'preview-'+crypto.randomUUID(),alt:''}]);}catch(error){if(alive.current)setError(error.message)}finally{lock.current=false;finish();if(alive.current)setUploading(false)}}
 if(!file&&!editable)return null;
 return <div className="page-panel-photo">{editable?<ImageUploadControl label="Panel photo" src={file?safePageMediaUrl(file.url,editor.preview):''} alt={file?.alt||''} accept={SHARED_IMAGE_TYPES.join(',')} disabled={editor.busy&&!uploading} busy={uploading} progress={uploading?'Uploading panel photo…':''} error={error} frame={file?.frame} onFrameChange={frame=>setMedia([{...file,frame}])} onFiles={files=>void upload(files[0])}/>:file&&safePageMediaUrl(file.url,editor.preview)?<div className="page-panel-photo-crop"><img src={safePageMediaUrl(file.url,editor.preview)} alt={file.alt||''} style={photoFrameStyle(file.frame)}/></div>:<div className="page-panel-photo-empty">Photo unavailable</div>}{editable&&file&&<div className="page-panel-photo-controls"><Control type="button" disabled={editor.busy} onClick={()=>setMedia([])}>Remove photo</Control><label>Photo description<input maxLength={240} disabled={editor.busy} value={file.alt||''} onChange={event=>setMedia([{...file,alt:event.target.value}])}/></label></div>}</div>;
}
