import React,{useContext,useEffect,useId,useRef,useState} from 'react';
import {Button,Control} from './ui-core.jsx';
import {DEFAULT_PHOTO_FRAME,normalizePhotoFrame,photoFrameStyle,movePhotoFrame,keyboardPhotoFrame,photoFrameAt,updatePhotoFrame,photoPanAxes} from './photo-framing-model.js';
import {ImageLayoutContext,ImageLayoutControls,ImageControlRow,LayoutGlyph} from './image-edit-controls.jsx';
import './photo-framing.css';
export {photoFrameStyle} from './photo-framing-model.js';
// Both framing variants and shared layout are local until one Apply callback.
// The source owner combines them into one validated content operation.
export function PhotoFramingEditor({src,alt='',frame,onSave,onCancel,disabled=false,aspect=1.5,label='Photo framing',onChangeMedia,changeMediaLabel='Replace media',atomicLayout=false,details=null,onDraftChange,onReadyChange}){
 const imageLayout=useContext(ImageLayoutContext),[layoutDraft,setLayoutDraft]=useState(()=>imageLayout?.value),[naturalAspect,setNaturalAspect]=useState(aspect);
 disabled=disabled||!!imageLayout?.disabled;
 const [viewport,setViewport]=useState(()=>typeof matchMedia==='function'&&matchMedia('(max-width: 700px)').matches?'mobile':'desktop'),[frames,setFrames]=useState(()=>normalizePhotoFrame(frame)),[draftSource,setDraftSource]=useState(src),originalDraft=useRef({frame:normalizePhotoFrame(frame),layout:imageLayout?.value}),hasChanged=useRef(false),[loaded,setLoaded]=useState(false),[failed,setFailed]=useState(false),[axes,setAxes]=useState({x:false,y:false}),preview=useRef(null),photo=useRef(null),gesture=useRef(null),id=useId();
 const draft=photoFrameAt(frames,viewport),target=viewport==='mobile'?'Mobile':'Full';
 const setDraft=change=>setFrames(value=>updatePhotoFrame(value,viewport,typeof change==='function'?change(photoFrameAt(value,viewport)):change));
 useEffect(()=>{originalDraft.current={frame:normalizePhotoFrame(frame),layout:layoutDraft};hasChanged.current=false;setDraftSource(src);setFrames(normalizePhotoFrame(frame));setFailed(false);setLoaded(false);gesture.current=null},[src]);
 useEffect(()=>{if(draftSource!==src)return;if(JSON.stringify(frames)!==JSON.stringify(originalDraft.current.frame)||JSON.stringify(layoutDraft)!==JSON.stringify(originalDraft.current.layout))hasChanged.current=true;if(hasChanged.current)onDraftChange?.({frame:frames,layout:layoutDraft})},[frames,layoutDraft,draftSource,src]);
 useEffect(()=>{preview.current?.focus()},[]);
 const previewAspect=layoutDraft?.aspect==='original'?naturalAspect:({landscape:16/9,portrait:3/4,square:1}[layoutDraft?.aspect]||aspect);
 useEffect(()=>{const update=()=>{const rect=preview.current?.getBoundingClientRect();setAxes(photoPanAxes(draft,{width:rect?.width,height:rect?.height,imageWidth:photo.current?.naturalWidth,imageHeight:photo.current?.naturalHeight}))};update();const observer=typeof ResizeObserver==='function'?new ResizeObserver(update):null;if(preview.current)observer?.observe(preview.current);return()=>observer?.disconnect()},[draft.zoom,previewAspect,naturalAspect,layoutDraft?.width]);
 useEffect(()=>{onReadyChange?.(loaded&&!failed&&!disabled)},[loaded,failed,disabled,onReadyChange]);
 const nudge=key=>{if(disabled||failed)return;if((key==='ArrowLeft'||key==='ArrowRight')&&!axes.x||(key==='ArrowUp'||key==='ArrowDown')&&!axes.y)return;const next=keyboardPhotoFrame(draft,key);if(next)setDraft(next)};
 const cancel=()=>{gesture.current=null;onCancel?.()};
 return <section className="photo-framing-editor" aria-label={label} onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();cancel()}}}>
  <div className="photo-framing-target" role="group" aria-label="Framing target">{[['desktop','Full'],['mobile','Mobile']].map(([value,name])=><Control key={value} type="button" aria-pressed={viewport===value} disabled={disabled} onClick={()=>{gesture.current=null;setViewport(value)}}>{name}</Control>)}</div>
  <div className="photo-framing-canvas" data-photo-align={layoutDraft?.align||'stretch'}><div ref={preview} className="photo-framing-preview" style={{aspectRatio:previewAspect,width:(layoutDraft?.width||100)+'%'}} tabIndex={disabled?-1:0} role="group" aria-label="Photo framing preview" aria-describedby={id+'-help'} onKeyDown={event=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home'].includes(event.key)){event.preventDefault();nudge(event.key)}}}
   onPointerDown={event=>{if(disabled||failed||event.button!==0)return;event.preventDefault();preview.current?.focus();const rect=event.currentTarget.getBoundingClientRect();gesture.current={id:event.pointerId,x:event.clientX,y:event.clientY,frame:draft,width:rect.width,height:rect.height,imageWidth:photo.current?.naturalWidth,imageHeight:photo.current?.naturalHeight};try{event.currentTarget.setPointerCapture?.(event.pointerId)}catch{}}}
   onPointerMove={event=>{const g=gesture.current;if(!g||g.id!==event.pointerId||disabled)return;setDraft(movePhotoFrame(g.frame,event.clientX-g.x,event.clientY-g.y,g))}}
   onPointerUp={event=>{if(gesture.current?.id===event.pointerId)gesture.current=null}}
   onPointerCancel={event=>{const g=gesture.current;if(g?.id===event.pointerId){setDraft(g.frame);gesture.current=null}}}>
   {failed?<p role="alert">The photo couldn’t load. Cancel and try again.</p>:<img ref={photo} src={src} alt={alt} draggable={false} style={photoFrameStyle(draft)} onLoad={event=>{const image=event.currentTarget;if(image.naturalWidth&&image.naturalHeight){setLoaded(true);setNaturalAspect(image.naturalWidth/image.naturalHeight);const rect=preview.current?.getBoundingClientRect();setAxes(photoPanAxes(draft,{width:rect?.width,height:rect?.height,imageWidth:image.naturalWidth,imageHeight:image.naturalHeight}))}}} onError={()=>setFailed(true)}/>}<span className="photo-framing-center" aria-hidden="true"/>
  </div></div>
  <div className="photo-framing-secondary"><Control type="button" aria-label="Reset frame" title={"Reset "+target.toLowerCase()+" framing"} disabled={disabled||failed} onClick={()=>setDraft({...DEFAULT_PHOTO_FRAME})}><LayoutGlyph kind="reset"/><span>Reset frame</span></Control>{onChangeMedia&&<Control type="button" disabled={disabled} onClick={()=>onChangeMedia({frame:frames,layout:layoutDraft})}><LayoutGlyph kind="original"/><span>{changeMediaLabel}</span></Control>}</div>
  <div className="photo-framing-tools"><div className="photo-framing-summary"><p id={id+'-help'} className="field-help">Drag or use Position to reframe the photo.</p><span className="photo-framing-layout-note">{target} framing</span></div>
  <ImageControlRow label="Zoom"><div className="photo-framing-zoom card-image-size" role="group" aria-label="Photo zoom"><Control type="button" aria-label="Zoom out" title="Zoom out" disabled={disabled||failed||draft.zoom<=1} onClick={()=>setDraft(value=>normalizePhotoFrame({...value,zoom:Math.max(1,value.zoom-.05)}))}><LayoutGlyph kind="minus"/></Control><output aria-label="Photo zoom percentage">{Math.round(draft.zoom*100)}%</output><Control type="button" aria-label="Zoom in" title="Zoom in" disabled={disabled||failed||draft.zoom>=3} onClick={()=>setDraft(value=>normalizePhotoFrame({...value,zoom:Math.min(3,value.zoom+.05)}))}><LayoutGlyph kind="plus"/></Control></div></ImageControlRow>
  <div className="photo-position"><span className="image-control-label">Position</span><div role="group" aria-label="Photo position">{[['ArrowLeft','Move photo left','nudgeLeft','x'],['ArrowUp','Move photo up','nudgeUp','y'],['ArrowDown','Move photo down','nudgeDown','y'],['ArrowRight','Move photo right','nudgeRight','x']].map(([key,name,glyph,axis])=><Control key={key} type="button" aria-label={name} title={name} disabled={disabled||failed||!axes[axis]} onClick={()=>nudge(key)}><LayoutGlyph kind={glyph}/></Control>)}<Control type="button" disabled={disabled||failed||!axes.x&&!axes.y} onClick={()=>setDraft(value=>({...value,x:50,y:50}))}>Center</Control></div>{!axes.x||!axes.y?<p className="page-editor-help">{!axes.x&&!axes.y?'The photo fills this frame. Zoom in to move it.':!axes.x?'Horizontal position fits exactly. Zoom in to move left or right.':'Vertical position fits exactly. Zoom in to move up or down.'}</p>:null}</div>
  {layoutDraft&&<ImageLayoutControls value={layoutDraft} onChange={setLayoutDraft} disabled={disabled||failed} label={imageLayout.label}/>}
  {details}

  <div className="photo-framing-actions"><Button secondary type="button" disabled={disabled} onClick={cancel}>Cancel</Button><Button type="button" disabled={disabled||failed} onClick={()=>{onSave?.(frames,layoutDraft);if(layoutDraft&&!atomicLayout)imageLayout.commit(layoutDraft)}}>{layoutDraft?'Apply image':'Apply framing'}</Button></div>
 </div></section>;
}
