import React,{useEffect,useRef,useState} from 'react';
import {AppContext,Button,Control,Glyph,useApp} from './ui-core.jsx';
import {api} from './live-adapter.js';
import {CommentsView,ReactionBar,MemberLink} from './conversation.jsx';
import './photo-viewer.css';
async function previewPhoto(state,kind,id,index){
 let url,ownerId,name,canSave=true;
 if(kind==='profile'){const member=state.members.find(item=>item.id===id);url=member?.photo;ownerId=id;name=member?.name+' profile photo';canSave=member?.allowPhotoSave!==false||state.selfId===id;}
 if(kind==='memory'){const memory=state.memories.find(item=>item.id===id);url=memory?.image;ownerId=memory?.authorId;name=memory?.title||'Family memory';}
 if(kind==='post'){const post=state.posts.find(item=>item.id===id),images=[...(post?.image?[{url:post.image,name:'Family photo'}]:[]),...(post?.files||[]).filter(file=>/^image\//.test(file.type||'')),...(post?.backgroundMedia&&/^image\//.test(post.backgroundMedia.type||'')?[post.backgroundMedia]:[])];url=images[index]?.url;ownerId=post?.authorId;name=images[index]?.name||'Family photo';}
 if(!url)throw Error('This photo is unavailable.');const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify([kind,id,url]))),key=[...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,'0')).join('');
 return {photo:{kind,id,index,url,ownerId,name,canSave},threadId:'photo:'+key,comments:[],reactions:[],next:null};
}
export function PhotoViewer({kind,id,index=0,children}){
 const app=useApp(),{state}=app,scope=state.mode+':'+state.selfId+':'+kind+':'+id+':'+index,scopeRef=useRef(scope),sequence=useRef(0),lock=useRef(false),[record,setRecord]=useState(null),recordRef=useRef(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loadingMore,setLoadingMore]=useState(false);scopeRef.current=scope;recordRef.current=record;
 const endpoint='/api/photo-discussions/'+encodeURIComponent(kind)+'/'+encodeURIComponent(id),params=new URLSearchParams({index:String(index)});
 async function load(before=null){const current=++sequence.current,requestedScope=scope;try{const next=state.mode==='preview'?await previewPhoto(state,kind,id,index):await api(endpoint+'?'+params+(before?'&before='+encodeURIComponent(before):''));if(scopeRef.current!==requestedScope||sequence.current!==current)return false;if(!next?.photo||!Array.isArray(next.comments)||!Array.isArray(next.reactions))throw Error('Photo details could not be read.');setRecord(previous=>{const keep=before&&previous?.scope===scope&&previous.threadId===next.threadId?previous.comments:[],byId=new Map([...next.comments,...keep].map(comment=>[comment.id,comment]));return {...next,comments:[...byId.values()].sort((a,b)=>a.createdAt-b.createdAt||a.id.localeCompare(b.id)),scope}});setError('');return true;}catch(error){if(scopeRef.current===requestedScope&&sequence.current===current){if([401,403,404].includes(error.status))setRecord(null);setError(error.message||'Photo details could not be loaded.');}return false;}}
 useEffect(()=>{scopeRef.current=scope;setRecord(null);setError('');load();return()=>{sequence.current++;scopeRef.current=null}},[scope]);
 useEffect(()=>{if(state.mode!=='live')return;const refresh=()=>{if(document.visibilityState==='visible'&&!lock.current&&!app.data.pending)load()};const timer=setInterval(refresh,15000);return()=>clearInterval(timer)},[scope,app.data.pending]);
 const current=record?.scope===scope?record:null;
 async function dispatch(action){if(!['ADD_COMMENT','TOGGLE_REACTION'].includes(action.type))return app.dispatch(action);if(!current||lock.current||app.data.pending)return false;lock.current=true;setBusy(true);setError('');const requestedScope=scope;try{const own=state.mode==='preview'?state.reactions[action.targetId]||[]:current.reactions.filter(item=>item.member_id===state.selfId&&(item.comment_id||current.threadId)===action.targetId).map(item=>item.emoji),payload=state.mode==='preview'?action:{...action,photoTarget:{kind,id,index,photo:current.photo.url},...(action.type==='TOGGLE_REACTION'?{photoSelected:!own.includes(action.emoji)}:{})};const ok=await app.dispatch(payload);if(ok===false&&scopeRef.current===requestedScope)setError('Couldn’t confirm whether or not your change was saved. Your draft is still here.');if(ok!==false&&scopeRef.current===requestedScope&&state.mode==='live'){const loaded=await load();if(!loaded)setError('Your change was saved. Try refreshing the photo conversation.');}return ok;}finally{lock.current=false;if(scopeRef.current===requestedScope)setBusy(false);}}
 async function download(){if(!current||!current.photo.canSave||lock.current)return;lock.current=true;setBusy(true);setError('');try{let response;if(state.mode==='live')response=await fetch(endpoint+'/download?'+params+'&photo='+encodeURIComponent(current.photo.url),{credentials:'same-origin',cache:'no-store'});else{const url=new URL(current.photo.url,location.href);if(url.origin!==location.origin)throw Error('Open the original photo to save this preview image.');response=await fetch(url);}if(!response.ok){let message='The photo could not be downloaded.';try{const data=await response.json();message=typeof data.error==='string'?data.error:message}catch{}throw Error(message);}const blob=await response.blob();if(!/^image\//.test(blob.type))throw Error('The service did not return a photo.');if(scopeRef.current!==scope)return;const url=URL.createObjectURL(blob),anchor=document.createElement('a'),extension={'image/png':'png','image/gif':'gif','image/webp':'webp'}[blob.type]||'jpg';anchor.href=url;anchor.download=(current.photo.name||'Family photo').replace(/[\\/\u0000-\u001f]/g,'_').slice(0,100)+'.'+extension;document.body.append(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);app.setToast('Photo download prepared.');}catch(error){if(scopeRef.current===scope)setError(error.message)}finally{lock.current=false;if(scopeRef.current===scope)setBusy(false);}}
 if(!current)return <div className="stack">{error?<><p role="alert">{error}</p><Button secondary onClick={()=>load()}>Try again</Button></>:<p role="status">Loading photo…</p>}</div>;
 const reactions={},reactionCounts={},reactionMembers={};for(const item of current.reactions){const target=item.comment_id||current.threadId;(reactionMembers[target]??={})[item.emoji]??=[];reactionMembers[target][item.emoji].push(item.member_id);(reactionCounts[target]??={})[item.emoji]=(reactionCounts[target]?.[item.emoji]||0)+1;if(item.member_id===state.selfId)(reactions[target]??=[]).push(item.emoji);}
 const known=new Set(current.comments.map(comment=>comment.id)),comments=current.comments.map(comment=>({...comment,parentId:comment.parentId&&!known.has(comment.parentId)?null:comment.parentId}));
 const viewerState=state.mode==='preview'?state:{...state,comments:{...state.comments,[current.threadId]:comments},reactions:{...state.reactions,...reactions},reactionCounts:{...state.reactionCounts,...reactionCounts},reactionMembers:{...state.reactionMembers,...reactionMembers}};
 return <AppContext.Provider value={{...app,state:viewerState,dispatch,data:{...app.data,pending:app.data.pending||busy}}}><div className="photo-viewer-content"><img className="photo-viewer-image" src={current.photo.url} alt={current.photo.name||'Family photo'}/><div className="photo-viewer-details"><MemberLink id={current.photo.ownerId} compact/>{children}<ReactionBar targetId={current.threadId} countsOnly/><div className="photo-viewer-actions"><ReactionBar targetId={current.threadId} triggerOnly/>{current.photo.canSave?<Button secondary disabled={busy} onClick={download}><Glyph name="image"/>Save photo</Button>:<p className="small muted">Photo saving is turned off for this profile.</p>}</div>{(error||app.data.error)&&<div><p role="alert">{app.data.error||error}</p><Button secondary disabled={busy} onClick={()=>load()}>Refresh conversation</Button></div>}<h3>Comments</h3>{current.next&&<Button secondary disabled={loadingMore||busy} onClick={async()=>{setLoadingMore(true);try{await load(current.next)}finally{setLoadingMore(false)}}}>Load earlier comments</Button>}<CommentsView targetId={current.threadId}/></div></div></AppContext.Provider>;
}
