import {canManageCalendar} from './calendar-model.js';
import {ChoiceControl} from './choice-control.jsx';
import {MemberPicker} from './member-picker.jsx';
import {derivePlanning} from './planning-model.js';
import {PlanningStatus,SavedPlanningHistory} from './planning-checklist.jsx';
import React,{useState} from 'react';
import {Control,Button,Glyph,useApp} from './ui-core.jsx';
export function ReunionFeesPanel(){
 const {state,dispatch,openSheet}=useApp(),[paymentOpen,setPaymentOpen]=useState(false),[editing,setEditing]=useState(false),[payment,setPayment]=useState(state.payment||{paypal:'',cashApp:'',amount:''});
 const plan=derivePlanning(state),feeTask=plan.byId.fees;
 const preview=state.mode==='preview',treasurer=preview?state.members.find(m=>m.id===state.selfId)?.moderator:state.capabilities?.treasurer;

 return <section className={'card stack reunion-fees-panel is-'+feeTask.status}><h2 className="planning-task-label">Reunion fees</h2><p>Status: <PlanningStatus task={feeTask}/></p><p className="small muted">{feeTask.detail}</p><p>{payment.amount?'Contribution: '+payment.amount:'The contribution amount has not been set yet.'}</p>{feeTask.status==='todo'&&<Button secondary onClick={()=>dispatch({type:'SET_FEES',value:'paid'})}>I sent my contribution</Button>}<Control type="button" className="button secondary" aria-expanded={paymentOpen} onClick={()=>setPaymentOpen(v=>!v)}><Glyph name="wallet"/><span>{paymentOpen?'Hide payment destinations':'Payment destinations'}</span></Control>{paymentOpen&&<div className="payment-inline stack">{[['PayPal',payment.paypal],['Cash App',payment.cashApp]].map(([label,url])=><p key={label}>{label}: {url?(preview?<span>{url} · Preview only</span>:<a href={url} target="_blank" rel="noreferrer">Open {label}</a>):'Not configured'}</p>)}{treasurer&&(editing?<form className="stack" onSubmit={async e=>{e.preventDefault();if(await dispatch({type:'SET_PAYMENT',value:payment}))setEditing(false)}}><label>Contribution amount<input value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})} maxLength="80"/></label><label>Verified PayPal.Me link<input type="url" value={payment.paypal} onChange={e=>setPayment({...payment,paypal:e.target.value})}/></label><label>Verified Cash App link<input type="url" value={payment.cashApp} onChange={e=>setPayment({...payment,cashApp:e.target.value})}/></label><Control className="button" type="submit">Save destinations</Control></form>:<Button secondary onClick={()=>setEditing(true)}>Edit verified destinations</Button>)}</div>}<p className="muted small">{preview?'Preview never transfers money. ':''}Payments go directly to the treasurer. Opening a link or reporting payment does not confirm receipt.</p></section>;
}
export function Planner(){return <div className="stack"><ReunionFeesPanel/><SavedPlanningHistory/></div>}
export function DetailsForm({onSaved}){const {state,dispatch,openSheet,go}=useApp(),[d,setD]=useState(state.details),update=(field,value)=>setD(x=>({...x,[field]:value}));return <form className="details-form stack" onSubmit={async e=>{e.preventDefault();const {schedule,...reunionDetails}=d;if(await dispatch({type:'DETAILS',value:reunionDetails})){if(onSaved)onSaved();else openSheet(null)}}}><fieldset><legend>When</legend><div className="field-row"><label>Start date<input type="date" value={d.date||''} onChange={e=>update('date',e.target.value)}/></label><label>Start time<input type="time" value={d.time||''} onChange={e=>update('time',e.target.value)}/></label></div><div className="field-row"><label>End date<input type="date" value={d.endDate||''} onChange={e=>update('endDate',e.target.value)}/></label><label>RSVP deadline<input type="date" value={d.rsvpDeadline||''} onChange={e=>update('rsvpDeadline',e.target.value)}/></label></div></fieldset><fieldset><legend>Where & who</legend><label>Venue<input value={d.location||''} onChange={e=>update('location',e.target.value)} placeholder="Venue name"/></label><label>Address<input value={d.address||''} onChange={e=>update('address',e.target.value)} placeholder="Street, city, state"/></label><MemberPicker label="Organizer contact" value={d.organizerMemberId||''} onChange={id=>setD(x=>({...x,organizerMemberId:id,contact:state.members.find(m=>m.id===id)?.name||''}))}/>{!d.organizerMemberId&&d.contact&&<p className="field-help">Current contact: {d.contact}. Choose their directory profile to link them.</p>}</fieldset>{canManageCalendar(state)&&<section className="stack"><h3>Calendar &amp; Events</h3><p className="field-help">Manage the shared schedule and individual activities together.</p><Button secondary onClick={()=>go({type:'leader-tools',section:'calendar'})}>Manage calendar &amp; events</Button></section>}<Control type="submit" className="button">Save event details</Control></form>}
export function Rsvp(){
 const {state,dispatch,openSheet,route,setToast}=useApp(),[count,setCount]=useState(state.rsvp?.count||1),[status,setStatus]=useState(state.rsvp?.status||'Planning to come'),[saving,setSaving]=useState(false);
 return <form className="stack" aria-busy={saving} onSubmit={async e=>{e.preventDefault();if(saving)return;setSaving(true);try{if(await dispatch({type:'RSVP',value:{count,status}})){if(route?.type==='rsvp'||route?.type==='reunion')setToast('RSVP saved');else openSheet(null)}}finally{setSaving(false)}}}>
  <ChoiceControl label="How many people?" value={count} onChange={value=>setCount(Number(value))} options={Array.from({length:50},(_,i)=>i+1)} searchPlaceholder="Find a number"/>
  <ChoiceControl label="Your plans" required value={status} onChange={setStatus} options={['Planning to come','Still deciding','Can’t make it']}/>
  {status==='Can’t make it'&&<p className="small muted">After saving, attendance tasks will be marked Not needed. Existing orders and payment records stay in place.</p>}
  <Control className="button" type="submit" disabled={saving}>{saving?'Saving RSVP…':'Save RSVP'}</Control>
 </form>
}
