import {PaymentMethodsDisplay} from './payment-methods.jsx';
import {ReunionSelector} from './reunion-years.jsx';
import {reunionArchived,reunionLabel,selectedReunion} from './reunion-model.js';
import {canManageCalendar} from './calendar-model.js';
import {ChoiceControl} from './choice-control.jsx';
import {MemberPicker} from './member-picker.jsx';
import {derivePlanning} from './planning-model.js';
import {PlanningStatus,SavedPlanningHistory} from './planning-checklist.jsx';
import React,{useEffect,useState} from 'react';
import {Control,Button,Glyph,useApp} from './ui-core.jsx';
export function ReunionFeesPanel({heading}){
 const {state,dispatch,go}=useApp(),[paymentOpen,setPaymentOpen]=useState(false),plan=derivePlanning(state),feeTask=plan.byId.fees,archived=reunionArchived(state);
 return <section className={'card stack reunion-fees-panel is-'+feeTask.status}><h2 className="planning-task-label">{heading||'Reunion fees'}</h2><p className="small muted">{reunionLabel(selectedReunion(state))}</p><p>Status: <PlanningStatus task={feeTask}/></p><p>{state.payment?.amount?'Contribution: '+state.payment.amount:'The contribution amount has not been set yet.'}</p><p className="small muted">{feeTask.detail}</p>{feeTask.status==='todo'&&!archived&&<Button secondary onClick={()=>dispatch({type:'SET_FEES',reunionId:state.selectedReunionId,value:'paid'})}>I sent my contribution</Button>}<Control type="button" className="button secondary" aria-expanded={paymentOpen} onClick={()=>setPaymentOpen(v=>!v)}><Glyph name="wallet"/><span>{paymentOpen?'Hide payment methods':'Payment methods & instructions'}</span></Control>{paymentOpen&&<PaymentMethodsDisplay/>}{(state.mode==='preview'||state.capabilities?.treasurer)&&!archived&&<Button secondary onClick={()=>go({type:'leader-tools',section:'fees'})}>Manage payment methods</Button>}{archived&&<p className="small muted">Archived contribution records are kept for reference.</p>}</section>;
}
export function Planner(){return <div className="stack"><ReunionSelector/><ReunionFeesPanel/><SavedPlanningHistory/></div>}
export function DetailsForm({onSaved}){const {state,dispatch,openSheet,go}=useApp(),[d,setD]=useState(state.details),update=(field,value)=>setD(x=>({...x,[field]:value}));useEffect(()=>setD(state.details),[state.selectedReunionId]);return <form className="details-form stack" onSubmit={async e=>{e.preventDefault();const {schedule,...reunionDetails}=d;if(await dispatch({type:'DETAILS',reunionId:state.selectedReunionId,value:reunionDetails})){if(onSaved)onSaved();else openSheet(null)}}}><fieldset disabled={reunionArchived(state)}><legend>When</legend><div className="field-row"><label>Start date<input type="date" value={d.date||''} onChange={e=>update('date',e.target.value)}/></label><label>Start time<input type="time" value={d.time||''} onChange={e=>update('time',e.target.value)}/></label></div><div className="field-row"><label>End date<input type="date" value={d.endDate||''} onChange={e=>update('endDate',e.target.value)}/></label><label>RSVP deadline<input type="date" value={d.rsvpDeadline||''} onChange={e=>update('rsvpDeadline',e.target.value)}/></label></div></fieldset><fieldset disabled={reunionArchived(state)}><legend>Where & who</legend><label>Venue<input value={d.location||''} onChange={e=>update('location',e.target.value)} placeholder="Venue name"/></label><label>Address<input value={d.address||''} onChange={e=>update('address',e.target.value)} placeholder="Street, city, state"/></label><MemberPicker label="Organizer contact" value={d.organizerMemberId||''} onChange={id=>setD(x=>({...x,organizerMemberId:id,contact:state.members.find(m=>m.id===id)?.name||''}))}/>{!d.organizerMemberId&&d.contact&&<p className="field-help">Current contact: {d.contact}. Choose their directory profile to link them.</p>}</fieldset>{canManageCalendar(state)&&<section className="stack"><h3>Calendar &amp; Events</h3><p className="field-help">Manage the shared schedule and individual activities together.</p><Button secondary onClick={()=>go({type:'leader-tools',section:'calendar'})}>Manage calendar &amp; events</Button></section>}<Control type="submit" className="button" disabled={reunionArchived(state)}>Save event details</Control></form>}
export function Rsvp(){
 const {state,dispatch,openSheet,route,setToast}=useApp(),[count,setCount]=useState(state.rsvp?.count||1),[status,setStatus]=useState(state.rsvp?.status||'Planning to come'),[saving,setSaving]=useState(false);
 useEffect(()=>{setCount(state.rsvp?.count||1);setStatus(state.rsvp?.status||'Planning to come')},[state.selectedReunionId]);
 if(reunionArchived(state))return <p>This reunion is archived. Your saved RSVP is {state.rsvp?.status||'not recorded'}.</p>;
 return <form className="stack" aria-busy={saving} onSubmit={async e=>{e.preventDefault();if(saving)return;setSaving(true);try{if(await dispatch({type:'RSVP',reunionId:state.selectedReunionId,value:{count,status}})){if(route?.type==='rsvp'||route?.type==='reunion')setToast('RSVP saved');else openSheet(null)}}finally{setSaving(false)}}}>
  <ChoiceControl label="How many people?" value={count} onChange={value=>setCount(Number(value))} options={Array.from({length:50},(_,i)=>i+1)} searchPlaceholder="Find a number"/>
  <ChoiceControl label="Your plans" required value={status} onChange={setStatus} options={['Planning to come','Still deciding','Can’t make it']}/>
  {status==='Can’t make it'&&<p className="small muted">After saving, attendance tasks will be marked Not needed. Existing orders and payment records stay in place.</p>}
  <Control className="button" type="submit" disabled={saving}>{saving?'Saving RSVP…':'Save RSVP'}</Control>
 </form>
}
