import React,{useEffect,useRef,useState} from 'react';
import {api} from './live-adapter.js';
import {Button,Control,Glyph,Popover,Sheet,useApp} from './ui-core.jsx';
import {contactRows,contactVCard,contactFilename} from './profile-contact-model.js';
import './profile-contact-actions.css';
function ContactGlyph({name}){const custom={phone:'M6 3h4l2 5-3 2c1 3 2 4 5 5l2-3 5 2v4c0 2-2 3-4 2C9 19 5 15 3 7c-1-2 1-4 3-4Z',link:'m10 13 4-4m-6 6-2 2a4 4 0 0 1-6-6l4-4m12 2 2-2a4 4 0 0 0-6-6l-4 4',lock:'M6 10h12v11H6Zm3 0V6a3 3 0 0 1 6 0v4'};return custom[name]?<svg className="glyph" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={custom[name]}/></svg>:<Glyph name={name}/>;}
async function embeddedPhoto(url){
 if(!url)return {};
 const target=new URL(url,location.href);if(target.origin!==location.origin)throw Error('This photo cannot be included in a contact download yet.');
 const response=await fetch(target,{credentials:'same-origin',cache:'no-store'});if(!response.ok)throw Error('The profile photo could not be loaded.');let blob=await response.blob();if(!/^image\/(jpeg|png|gif|webp)$/.test(blob.type)||blob.size>10*1024*1024)throw Error('This photo cannot be included safely.');
 if(blob.type==='image/webp'||blob.size>2*1024*1024){const object=URL.createObjectURL(blob);try{const image=new Image();image.src=object;await image.decode();const scale=Math.min(1,512/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));if(!blob)throw Error('The profile photo could not be prepared.');}finally{URL.revokeObjectURL(object)}}
 const bytes=new Uint8Array(await blob.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return {photoBase64:btoa(binary),photoType:blob.type==='image/png'?'PNG':blob.type==='image/gif'?'GIF':'JPEG'};
}
export function ProfileContactActions({member}){
 const {state,setToast}=useApp(),account=state.mode+':'+state.selfId,scope=account+':'+member.id,own=member.id===state.selfId,apple=/iPhone|iPad|Macintosh/.test(navigator.userAgent),[result,setResult]=useState({scope:'',status:'loading',card:null}),[retry,setRetry]=useState(0),[menu,setMenu]=useState(null),[guide,setGuide]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copyFallback,setCopyFallback]=useState(''),alive=useRef(scope);alive.current=scope;
 useEffect(()=>()=>{alive.current=null},[]);
 const fetchCard=async()=>{if(state.mode!=='live')return own&&state.contact?.name?{...state.contact,memberId:member.id,photo:state.contact.useProfile!==false?member.photo:state.contact.photo,allowPhotoSave:member.allowPhotoSave!==false}:null;const response=await api('/api/directory');if(!Array.isArray(response.cards))throw Error('Contact details could not be checked.');return response.cards.find(card=>card.memberId===member.id)||null;};
 useEffect(()=>{let active=true;setResult({scope,status:'loading',card:null});setMenu(null);setGuide(false);setError('');fetchCard().then(card=>{if(active)setResult({scope,status:'ready',card})}).catch(error=>{if(active)setResult({scope,status:'error',card:null,error:error.message})});return()=>{active=false}},[scope,state.contact,member.photo,member.allowPhotoSave,retry]);
 const current=result.scope===scope?result:{status:'loading',card:null},card=current.card,rows=contactRows(card,{apple,socials:member.socials});
 const copy=async value=>{try{await navigator.clipboard.writeText(value);setToast('Copied');setMenu(null)}catch{setCopyFallback(value)}};
 const download=async(includePhoto=true)=>{if(busy)return;setBusy(true);setError('');const requestScope=scope;try{const fresh=await fetchCard();if(!fresh)throw Error('These contact details are no longer shared with you.');const photo=includePhoto&&fresh.allowPhotoSave!==false?await embeddedPhoto(fresh.photo):{},data=contactVCard(fresh,photo);if(alive.current!==requestScope)return;const url=URL.createObjectURL(new Blob([data],{type:'text/vcard;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=contactFilename(fresh.name);document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);setToast('Contact file prepared. Follow the import steps to save it.');}catch(error){if(alive.current===requestScope)setError(error.message)}finally{if(alive.current===requestScope)setBusy(false)}};
 return <section className="profile-contact-details" aria-label="Contact details" aria-busy={current.status==='loading'}>{current.status==='loading'?<p role="status">Checking shared contact details…</p>:current.status==='error'?<div><p role="alert">{current.error}</p><Button secondary onClick={()=>setRetry(n=>n+1)}>Try again</Button></div>:!card?<p className="profile-contact-private"><ContactGlyph name="lock"/><span>Contact details are private or haven’t been shared.</span></p>:<><div className="profile-contact-grid">{rows.map(row=><div className="profile-contact-row" key={row.key}><a href={row.href} aria-label={row.label+': '+row.value} {...(/^https:/.test(row.href)?{target:'_blank',rel:'noreferrer'}:{})}><ContactGlyph name={row.glyph}/><span><small>{row.label}</small><span>{row.value}</span></span></a><Control className="contact-more" aria-label={row.label+' options'} aria-expanded={menu?.key===row.key} onClick={event=>{setCopyFallback('');setMenu({...row,anchor:event.currentTarget})}}>⋯</Control></div>)}</div>{!rows.length&&<p className="muted">No contact details added yet.</p>}<Button secondary onClick={()=>{setError('');setGuide(true)}}>Add to Contacts</Button></>}
 {current.status==='ready'&&<Popover open={!!menu} onClose={()=>setMenu(null)} anchor={menu?.anchor}><div className="stack"><Control className="button" onClick={()=>copy(menu.value)}>Copy {menu?.label.toLowerCase()}</Control>{copyFallback&&<label>Select and copy<input readOnly value={copyFallback} onFocus={event=>event.currentTarget.select()}/></label>}</div></Popover>}
 {current.status==='ready'&&guide&&<Sheet title="Add to your contacts" busy={busy} onClose={()=>setGuide(false)}><div className="stack"><p>This downloads a contact card for {card?.name}. You choose whether to save it in your Contacts app.</p><ol>{apple?<><li>Download the contact card.</li><li>Open the downloaded .vcf file. If Safari doesn’t offer Contacts, open it from an email or message attachment.</li><li>Choose to create a contact or add it to an existing one, then confirm.</li></>:<><li>Download the contact card.</li><li>Open Contacts, then Organize → Import from file.</li><li>Choose the downloaded .vcf file and the account where you want to save it.</li></>}</ol><p className="small muted">Steps can vary by phone. This saves a copy; later profile changes won’t update your phone automatically.</p>{card?.allowPhotoSave===false&&<p className="small muted">This person’s photo won’t be included because they’ve turned off photo saving.</p>}{error&&<p role="alert">{error}</p>}<Button disabled={busy} onClick={()=>download(true)}>{busy?'Preparing…':'Download contact card'}</Button>{error&&<Button secondary disabled={busy} onClick={()=>download(false)}>Download without photo</Button>}</div></Sheet>}
 </section>;
}
