import React,{useEffect,useId,useRef,useState} from 'react';
import {Control,Button,Glyph} from './ui-core.jsx';
import {themeSongInfo} from './profile-model.js';
import {profileSocialServices,socialHandle,socialUrlFromHandle} from './profile-social-model.js';
import {searchThemeSongs,resolveThemeSongLink,lookupThemeSong} from './music-catalog.js';
import {ServiceLogo} from './profile-brand-icons.jsx';
import './profile-connections.css';

export function SocialLinksEditor({entries,onChange,errors={}}){
 const [adding,setAdding]=useState(false),[focusService,setFocusService]=useState(''),inputRefs=useRef({}),addButton=useRef(null),id=useId();
 const remaining=profileSocialServices.filter(service=>!entries[service.name]);
 useEffect(()=>{if(focusService){inputRefs.current[focusService]?.focus();setFocusService('')}},[focusService]);
 function add(name){onChange({...entries,[name]:{handle:'',initialHandle:'',original:'',legacy:false}});setAdding(false);setFocusService(name)}
 function remove(name){const next={...entries};delete next[name];onChange(next);setAdding(false);requestAnimationFrame(()=>addButton.current?.focus())}
 function update(name,value){const extracted=socialHandle(name,value.trim());onChange({...entries,[name]:{...entries[name],handle:extracted??value,legacy:false}})}
 return <section className="profile-connections profile-social-editor" aria-labelledby={id+'-title'}><div className="connection-heading"><h3 id={id+'-title'}>Social links</h3><span className="field-optional">Optional</span></div><p className="field-help">Choose a service, then add your username.</p>
  <div className="social-handle-list">{profileSocialServices.filter(service=>entries[service.name]).map(service=>{const entry=entries[service.name],inputId=id+'-'+service.icon,url=socialUrlFromHandle(service.name,entry.handle);return <div className="social-handle-row" key={service.name}>
   <div className="social-handle-heading"><label htmlFor={inputId}><ServiceLogo name={service.icon}/>{service.name}</label><Control type="button" className="text-button" aria-label={'Remove '+service.name} onClick={()=>remove(service.name)}>Remove</Control></div>
   {entry.legacy?<div className="social-saved-link"><a href={entry.original} target="_blank" rel="noreferrer">Your saved {service.name} profile <Glyph name="arrow"/></a><Control type="button" className="text-button" onClick={()=>{onChange({...entries,[service.name]:{...entry,legacy:false}});setFocusService(service.name)}}>Change username</Control></div>:<><div className="social-handle-input"><span aria-hidden="true">@</span><input id={inputId} ref={node=>{inputRefs.current[service.name]=node}} type="text" value={entry.handle} placeholder={service.example} autoComplete="off" autoCapitalize="none" autoCorrect="off" spellCheck="false" maxLength={300} aria-invalid={!!errors[service.name]} aria-describedby={inputId+'-help'} onChange={e=>update(service.name,e.target.value)}/></div><p id={inputId+'-help'} className={errors[service.name]?'field-help form-error':'field-help social-link-preview'}>{errors[service.name]||url?.replace('https://','')||service.prefix+service.example}</p></>}
  </div>})}</div>
  {remaining.length>0&&<Control ref={addButton} type="button" className="connection-add" aria-expanded={adding} aria-controls={id+'-services'} onClick={()=>setAdding(value=>!value)}><Glyph name={adding?'close':'plus'}/>{adding?'Cancel':'Add service'}</Control>}
  {adding&&<div className="social-service-chooser" id={id+'-services'} aria-label="Choose a social service">{remaining.map(service=><Control type="button" className="social-service-option" key={service.name} onClick={()=>add(service.name)}><ServiceLogo name={service.icon}/><span>{service.name}</span><Glyph name="plus"/></Control>)}</div>}
 </section>
}

function LinkIcon(){return <svg className="glyph" viewBox="0 0 24 24" aria-hidden="true"><path d="m9 15 6-6m-6-1 2-2a4.2 4.2 0 0 1 6 6l-2 2M9 10l-2 2a4.2 4.2 0 0 0 6 6l2-2"/></svg>}
function SearchIcon(){return <svg className="glyph" viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.75" cy="10.75" r="6.75"/><path d="m16 16 4.5 4.5"/></svg>}
function SongArtwork({song}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[song?.artwork]);return song?.artwork&&!failed?<img className="song-artwork" src={song.artwork} width="56" height="56" alt="" loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>:<span className="song-artwork song-artwork-empty" aria-hidden="true"><ServiceLogo name="applemusic"/></span>}
function SongStoreLink({song}){return <a className="song-store-link" href={song.storeUrl||song.url} target="_blank" rel="noreferrer" aria-label={'Open '+song.title+' on iTunes'}><img src="profile-assets/itunes-store-badge.svg" alt="Get it on iTunes Store" width="110" height="40"/></a>}
export function ThemeSongEditor({value,onChange,error:formError=''}){
 const id=useId(),[service,setService]=useState(()=>themeSongInfo(value)?.service||'Apple Music'),[mode,setMode]=useState('search'),[query,setQuery]=useState(''),[results,setResults]=useState([]),[searched,setSearched]=useState(false),[loading,setLoading]=useState(false),[resolving,setResolving]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState(null),linkInput=useRef(null),request=useRef(null),spotifyLink=useRef(null);
 const current=themeSongInfo(value),selectedSong=selected?.url===current?.url?selected:null;
 useEffect(()=>()=>request.current?.abort(),[]);
 useEffect(()=>{if(!value||themeSongInfo(value)?.service!=='Apple Music')return;const controller=new AbortController();lookupThemeSong(value,{signal:controller.signal}).then(song=>{if(song&&!controller.signal.aborted)setSelected({...song,url:themeSongInfo(value).url})}).catch(()=>{});return()=>controller.abort()},[value]);
 useEffect(()=>{if(formError){setMode('link');requestAnimationFrame(()=>linkInput.current?.focus())}},[formError]);
 function resetRequest(){request.current?.abort();setLoading(false);setResolving(false);setError('')}
 function chooseService(next){resetRequest();setService(next);setMode('search');setResults([]);setSearched(false)}
 function paste(){resetRequest();setMode('link');requestAnimationFrame(()=>linkInput.current?.focus())}
 async function search(){if(query.trim().length<2)return;resetRequest();const controller=new AbortController();request.current=controller;setLoading(true);setSearched(false);setResults([]);try{const songs=await searchThemeSongs(query,{signal:controller.signal});if(!controller.signal.aborted){setResults(songs);setSearched(true)}}catch(e){if(!controller.signal.aborted)setError(e.message)}finally{if(!controller.signal.aborted)setLoading(false)}}
 async function useLink(){resetRequest();const controller=new AbortController();request.current=controller;setResolving(true);try{const song=await resolveThemeSongLink(value,{signal:controller.signal});if(!controller.signal.aborted){onChange(song.url);setSelected(song.title?song:null);setService(themeSongInfo(song.url)?.service||service);setMode('search')}}catch(e){if(!controller.signal.aborted)setError(e.message)}finally{if(!controller.signal.aborted)setResolving(false)}}
 function selectSong(song){resetRequest();onChange(song.url);setSelected(song);setResults([]);setSearched(false);setQuery('')}
 const spotifySearch='https://open.spotify.com/search/'+encodeURIComponent(query.trim());
 return <section className="profile-connections profile-music-editor" aria-labelledby={id+'-title'}><div className="connection-heading"><h3 id={id+'-title'}>Theme song</h3><span className="field-optional">Optional</span></div><p className="field-help">A song that feels like you. It only plays when family chooses to listen.</p>
  {current&&<div className="selected-theme-song"><div className="selected-song-main">{selectedSong?<SongArtwork song={selectedSong}/>:<span className="song-artwork song-artwork-empty"><ServiceLogo name={current.service==='Spotify'?'spotify':'applemusic'}/></span>}<div><strong>{selectedSong?.title||'Your theme song'}</strong><span>{selectedSong?.artist||current.service}</span><a href={current.url} target="_blank" rel="noreferrer">Open in {current.service}<Glyph name="arrow"/></a></div><Control type="button" className="text-button" aria-label="Remove theme song" onClick={()=>{resetRequest();onChange('');setSelected(null)}}>Remove</Control></div>{selectedSong&&<SongStoreLink song={selectedSong}/>}</div>}
  {mode==='search'?<><label htmlFor={id+'-query'} className="sr-only">Song or artist</label><div className="song-search-input"><SearchIcon/><input id={id+'-query'} type="search" value={query} maxLength={120} placeholder="Search a song or artist" autoComplete="off" enterKeyHint="search" onChange={e=>{setQuery(e.target.value);if(loading||searched||error){resetRequest();setResults([]);setSearched(false)}}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();if(service==='Apple Music')search();else spotifyLink.current?.click()}}}/>{service==='Apple Music'?<Control type="button" className="song-search-action" disabled={loading||query.trim().length<2} onClick={search}>{loading?'Searching…':'Search'}</Control>:<a ref={spotifyLink} className="song-search-action" href={spotifySearch} target="_blank" rel="noreferrer">Find song <Glyph name="arrow"/></a>}</div></>:<div className="song-paste-form"><label htmlFor={id+'-link'}>Song link</label><input ref={linkInput} id={id+'-link'} type="url" autoCapitalize="none" autoCorrect="off" spellCheck="false" placeholder={service==='Spotify'?'https://open.spotify.com/track/…':'Spotify or Apple Music song link'} value={value||''} onChange={e=>{resetRequest();onChange(e.target.value);setSelected(null)}} aria-describedby={id+'-status'}/><div className="song-paste-actions"><Button secondary onClick={useLink} disabled={!value?.trim()||resolving}>{resolving?'Checking link…':'Use link'}</Button><Control type="button" className="text-button" onClick={()=>{resetRequest();setMode('search')}}>Back to search</Control></div></div>}
  <div className="song-search-controls"><div className="music-services" role="group" aria-label="Music service">{[['Apple Music','applemusic'],['Spotify','spotify']].map(([name,icon])=><Control type="button" key={name} aria-pressed={service===name} onClick={()=>chooseService(name)}><ServiceLogo name={icon}/><span>{name}</span></Control>)}</div>{mode!=='link'&&<Control type="button" className="text-button song-paste-toggle" onClick={paste}><LinkIcon/>Paste link</Control>}</div>
  {service==='Spotify'&&mode==='search'&&<p className="field-help">Find your song on Spotify, then copy its song link and choose Paste link.</p>}
  <div id={id+'-status'} aria-live="polite" aria-atomic="true">{loading?<p className="field-help">Searching the Apple music catalog…</p>:error||formError?<p role="alert" className="form-error">{error||formError}</p>:searched&&!results.length?<p className="field-help">No songs found. Try the artist’s name, or paste a song link.</p>:results.length>0?<p className="field-help">{results.length} songs found. Choose your theme song.</p>:null}</div>
  {results.length>0&&<ul className="song-search-results" aria-label="Song search results">{results.map(song=><li key={song.id}><Control type="button" className="song-result-choice" onClick={()=>selectSong(song)} aria-label={'Choose '+song.title+' by '+song.artist}><SongArtwork song={song}/><span className="song-result-copy"><strong>{song.title}</strong><span>{song.artist}</span><small>{song.album}</small></span><Glyph name="plus"/></Control><SongStoreLink song={song}/></li>)}</ul>}
  {service==='Apple Music'&&<p className="music-catalog-credit">Search uses Apple’s public iTunes catalog. No sign-in needed.</p>}
 </section>
}
