import {unlinkInterfaceAccent} from './interface-accent.js';
import {ChoiceControl} from './choice-control.jsx';
import {ImageUploadControl} from './image-upload-control.jsx';
import {InlineDisclosure} from './inline-disclosure.jsx';
import './form-layout.css';
import React,{useState,useRef,useEffect} from 'react';
import {Control,Avatar,Button,Glyph,MemberBadges,useApp} from './ui-core.jsx';
import {PostCard} from './conversation.jsx';
import {profilePalette,themeSongInfo,socialInfo,hasPostMedia,safeWebUrl} from './profile-model.js';
import {readPreviewFile} from './uploads.js';
import {SocialLinksEditor,ThemeSongEditor} from './profile-connections.jsx';
import {socialDrafts,serializeSocialDrafts} from './profile-social-model.js';
import {resolveThemeSongLink} from './music-catalog.js';
import {ServiceLogo} from './profile-brand-icons.jsx';
import {MemberPicker} from './member-picker.jsx';
export function ThemeSong({url}){const song=themeSongInfo(url),[opened,setOpened]=useState(false);if(!song)return null;return <div className="theme-song">{opened?<><iframe title={'Theme song on '+song.service} src={song.embed} allow="encrypted-media" sandbox="allow-scripts allow-same-origin allow-popups" referrerPolicy="no-referrer"/><Control className="text-button" onClick={()=>setOpened(false)}>Close player</Control></>:<Button secondary onClick={()=>setOpened(true)}><Glyph name="play"/> Play theme song · {song.service}</Button>}<small className="muted">Tap to open the player, then play. Never starts automatically.</small></div>}
export function ProfileOverview({member:m,personal=false}){const {state,go,openSheet,messaging}=useApp();if(!m)return null;const posts=state.posts.filter(p=>p.authorId===m.id),media=posts.filter(hasPostMedia),memories=state.memories.filter(p=>p.authorId===m.id),socials=Object.values(m.socials||{}).map(socialInfo).filter(Boolean);return <section className="card profile profile-overview"><div className="profile-cover" aria-hidden="true"><img src="tree-artwork.png" alt=""/></div><div className="profile-overview-head"><Avatar member={m} size="large-avatar"/><div><span className="eyebrow">{personal?'Your family profile':'In the family'}</span><h2>{m.name}</h2><MemberBadges member={m} interactive/></div></div><div className="profile-overview-copy">{m.bio?<p>{m.bio}</p>:personal?<p className="muted">Add a little about yourself so your family can get to know you.</p>:null}</div><dl className="profile-counts"><div><dt><Glyph name="chat"/>Posts</dt><dd>{posts.length}</dd></div><div><dt><Glyph name="image"/>Media posts</dt><dd>{media.length}</dd></div><div><dt><Glyph name="heart"/>Memories</dt><dd>{memories.length}</dd></div></dl>{socials.length>0&&<div className="profile-socials">{socials.map(s=><a key={s.name} href={s.url} target="_blank" rel="noreferrer"><ServiceLogo name={s.name.toLowerCase()}/>{s.name}<Glyph name="arrow"/></a>)}</div>}{m.themeSong&&<ThemeSong key={m.themeSong} url={m.themeSong}/>}<div className="profile-overview-actions">{m.id!==state.selfId&&!m.managedBy&&m.origin!=='dependent'&&(state.mode==='preview'||messaging?.eligibleIds?.includes(m.id))&&<Button onClick={()=>go({type:'chat-new',id:m.id})}><Glyph name="chat"/>Message</Button>}{personal&&<Button onClick={()=>go({type:'profile',id:m.id})}>View profile <Glyph name="arrow"/></Button>}{m.id===state.selfId&&<Button secondary onClick={()=>openSheet({type:'edit-profile'})}>Edit profile <Glyph name="arrow"/></Button>}</div></section>}
export function Profile({id}){const {state,openSheet,theme,personalThemes}=useApp(),[tab,setTab]=useState('posts'),m=state.members.find(x=>x.id===id);if(!m)return <p>Profile not found.</p>;const posts=state.posts.filter(p=>p.authorId===id&&(tab==='posts'||hasPostMedia(p)));return <div className="stack profile-page" style={personalThemes?profilePalette(m.profileColor,theme):undefined}><ProfileOverview member={m}/><div className="segmented" role="tablist" aria-label="Profile content">{[['posts','Posts'],['media','Media']].map(([v,l])=><Control key={v} role="tab" aria-selected={tab===v} onClick={()=>setTab(v)}>{l}</Control>)}</div>{posts.length?posts.map(p=><PostCard key={p.id} post={p}/>):<p className="muted">{tab==='media'?'No media posts yet.':'No posts yet.'}</p>}</div>}
export function ProfilePhotoControl({name,photo,photoFrame,onPhotoFrame,onPhoto,onRemove,busy=false,disabled=false,error='',label='Profile photo'}){
 return <div className="form-image-control"><ImageUploadControl label={label} src={photo||''} alt={name?name+' profile photo':'Current profile photo'} shape="profile" accept="image/png,image/jpeg,image/webp,image/gif" busy={busy} disabled={disabled} error={error} frame={photoFrame} onFrameChange={onPhotoFrame} onFiles={files=>onPhoto(files[0])}/>{photo&&<Control className="text-button" type="button" disabled={busy||disabled} onClick={onRemove}>Remove photo</Control>}</div>
}
export function ProfileColorEditor({color='#4f996c',onColor,disabled=false,label='Profile color',legend='Make it feel like home',description='Choose your profile color.',selected=true}){
 const {theme}=useApp();
 const colors=[['Red','#e64f59'],['Orange','#ff7a00'],['Yellow','#ec9d00'],['Green','#387b51'],['Blue','#3985e6'],['Violet','#a267d5'],['Coral pink','#ff6685'],['Stone','#8a8178']];
 return <fieldset className="profile-colors" aria-label={label} disabled={disabled}><legend>{legend}</legend><p className="field-help">{description}</p><div className="profile-color-options" role="group" aria-label={label+' options'}><div className="profile-swatches-scroll">{colors.map(([label,value])=><Control key={value} type="button" aria-label={label} aria-pressed={selected&&color.toLowerCase()===value} className="profile-color-swatch" style={{'--swatch':value,'--swatch-active':profilePalette(value,theme)['--control'],'--swatch-active-text':profilePalette(value,theme)['--control-text']}} onClick={()=>onColor(value)}><span aria-hidden="true">{selected&&color.toLowerCase()===value?<Glyph name="check"/>:null}</span></Control>)}</div><label className="profile-custom-color" title={'Custom '+label.toLowerCase()}><input type="color" aria-label={'Custom '+label.toLowerCase()} value={color} onChange={e=>onColor(e.target.value)}/><span>Custom</span></label></div></fieldset>
}
export function ProfileStyleEditor({name,photo,photoFrame,onPhotoFrame,color='#4f996c',onColor,onPhoto,onRemove,busy=false,disabled=false,error='',children,showColors=true,photoLabel='Profile photo',description='Your family profile'}){
 const {setPreviewColor}=useApp();useEffect(()=>{setPreviewColor?.(color);return()=>setPreviewColor?.(null)},[color,setPreviewColor]);
 return <section className="profile-style-editor form-density-scope" aria-label="Profile appearance"><div className="form-image-intro"><ProfilePhotoControl label={photoLabel} name={name} photo={photo} photoFrame={photoFrame} onPhotoFrame={onPhotoFrame} onPhoto={onPhoto} onRemove={onRemove} busy={busy} disabled={disabled} error={error}/><div className="form-image-fields">{children||<div className="profile-style-copy"><strong>{name||'Your name'}</strong><p>{description}</p></div>}</div></div>{showColors&&<ProfileColorEditor color={color} onColor={onColor} disabled={disabled}/>}</section>
}
export function EditProfile(){
 const {state,dispatch,setToast,replaceRoute,interfaceAccent,setInterfaceAccent}=useApp(),me=state.members.find(m=>m.id===state.selfId),[values,setValues]=useState({...me,socials:{...me.socials}}),[socialEntries,setSocialEntries]=useState(()=>socialDrafts(me.socials)),[socialErrors,setSocialErrors]=useState({}),[songError,setSongError]=useState(''),[error,setError]=useState(''),[photoError,setPhotoError]=useState(''),[photoBusy,setPhotoBusy]=useState(false),[saving,setSaving]=useState(false),photoLock=useRef(false);const set=(key,value)=>setValues(v=>({...v,[key]:value}));
 async function photo(file){if(photoLock.current)return;photoLock.current=true;setPhotoBusy(true);setPhotoError('');try{if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type))throw Error('Choose a JPEG, PNG, WebP or GIF profile photo.');if(file.size>10*1024*1024)throw Error('Choose a profile photo under 10 MB.');const upload=await readPreviewFile(file,state.mode);setValues(v=>({...v,photo:upload.url,photoFrame:undefined}))}catch(e){setPhotoError(e.message)}finally{photoLock.current=false;setPhotoBusy(false)}}
 async function submit(e){e.preventDefault();if(photoLock.current||saving)return;if(!values.name.trim()){setError('Enter your name.');return}const socialResult=serializeSocialDrafts(socialEntries);setSocialErrors(socialResult.errors);if(Object.keys(socialResult.errors).length){setError('Check the highlighted social username.');return}setSaving(true);setError('');setSongError('');try{let themeSong='';if(values.themeSong){try{themeSong=(await resolveThemeSongLink(values.themeSong)).url}catch(error){setSongError(error.message);setError('Check your theme song link.');return}}if(await dispatch({type:'SAVE_MEMBER',member:{...values,socials:socialResult.socials,themeSong}})){setToast('Profile saved.');replaceRoute({type:'profile',id:me.id})}}finally{setSaving(false)}}
 return <form className="gw-form profile-edit-form form-density-scope" onSubmit={submit}>
  <fieldset className="form-section"><legend>About you</legend><ProfileStyleEditor name={values.name} photo={values.photo} photoFrame={values.photoFrame} onPhotoFrame={frame=>set('photoFrame',frame)} color={values.profileColor||'#4f996c'} busy={photoBusy} disabled={saving} error={photoError} showColors={false} onColor={value=>set('profileColor',value)} onRemove={()=>{set('photo',null);setPhotoError('')}} onPhoto={photo}>
   <label>Name<input required value={values.name} maxLength="80" autoComplete="name" disabled={saving} onChange={e=>set('name',e.target.value)}/></label>
   <label>Your birthday<input type="date" max={new Date().toISOString().slice(0,10)} value={values.birthday||''} aria-describedby="profile-birthday-help" disabled={saving} onChange={e=>set('birthday',e.target.value)}/></label><p id="profile-birthday-help" className="field-help">Your full birth date stays private.</p>
  </ProfileStyleEditor><label><span className="form-label">Bio <span className="field-optional">Optional</span></span><textarea rows="3" value={values.bio||''} maxLength="400" placeholder="A little about you" disabled={saving} onChange={e=>set('bio',e.target.value)}/></label></fieldset>
  <ProfileColorEditor color={values.profileColor||'#4f996c'} onColor={value=>set('profileColor',value)} disabled={saving}/>
  <label className="check-row"><input type="checkbox" checked={interfaceAccent?.mode==='profile'} disabled={saving} onChange={event=>setInterfaceAccent(previous=>event.target.checked?{...previous,mode:'profile'}:unlinkInterfaceAccent(previous,values.profileColor))}/>Use my profile color for the interface</label><p className="field-help">Turn this off to keep interface colors separate. Choose them in Appearance. Your profile keeps its color.</p>
  <fieldset className="form-section"><legend>Birthday privacy</legend><label className="check-row"><input type="checkbox" checked={!!values.shareAge} disabled={saving} onChange={e=>set('shareAge',e.target.checked)}/>Show my age on my family profile</label><p className="field-help">Optional for adults. Birthday celebrations have a separate opt-in on the Birthdays page.</p></fieldset>
  <ThemeSongEditor value={values.themeSong||''} onChange={value=>{set('themeSong',value);setSongError('')}} error={songError}/><SocialLinksEditor entries={socialEntries} onChange={entries=>{setSocialEntries(entries);setSocialErrors({})}} errors={socialErrors}/>{error&&<p role="alert" className="form-error">{error}</p>}<div className="form-save"><Control className="button form-primary" type="submit" disabled={saving||photoBusy}>{saving?'Saving…':'Save profile'}</Control></div>
 </form>
}
export function ContactCard(){
 const {state,dispatch,setToast,goBack}=useApp(),me=state.members.find(m=>m.id===state.selfId),[contact,setContact]=useState({name:me.name,email:'',phone:'',address:'',social:'',visibility:'Only me',selectedIds:[],optIn:false,useProfile:true,photo:null,...state.contact}),[error,setError]=useState(''),[photoError,setPhotoError]=useState(''),[saving,setSaving]=useState(false),[photoBusy,setPhotoBusy]=useState(false),photoLock=useRef(false);
 const update=(key,value)=>setContact(c=>({...c,[key]:value}));
 async function photo(file){if(photoLock.current)return;photoLock.current=true;setPhotoBusy(true);setPhotoError('');try{if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type))throw Error('Choose a JPEG, PNG, WebP or GIF contact photo.');if(file.size>2*1024*1024)throw Error('Choose a contact photo under 2 MB.');const upload=await readPreviewFile(file,state.mode);setContact(c=>({...c,photo:upload.url,photoFrame:undefined,useProfile:false}))}catch(e){setPhotoError(e.message)}finally{photoLock.current=false;setPhotoBusy(false)}}
 async function save(e){e.preventDefault();if(photoLock.current||saving)return;setError('');if(contact.social&&!safeWebUrl(contact.social)){setError('Use a valid HTTPS social link.');return}if(contact.optIn&&contact.visibility==='Selected family members'&&!contact.selectedIds.length){setError('Choose at least one family member, or choose Only me.');return}setSaving(true);try{if(await dispatch({type:'SAVE_CONTACT',contact})){setToast('Contact card saved.');goBack()}}finally{setSaving(false)}}
 return <form className="gw-form contact-edit-form form-density-scope" onSubmit={save}><p className="field-help">Private by default. Choose exactly who can see the details on this card.</p><fieldset className="form-section"><legend>Your card</legend><div className="form-image-intro">
  <div className="form-image-control"><ImageUploadControl label="Contact photo" src={(contact.useProfile?me.photo:contact.photo)||''} alt={contact.name+' contact photo'} shape="profile" accept="image/png,image/jpeg,image/webp,image/gif" busy={photoBusy} disabled={saving} error={photoError} frame={contact.useProfile?me.photoFrame:contact.photoFrame} onFrameChange={!contact.useProfile?frame=>update('photoFrame',frame):undefined} onFiles={files=>photo(files[0])}/><label className="check-row"><input type="checkbox" checked={contact.useProfile} disabled={photoBusy||saving} onChange={e=>update('useProfile',e.target.checked)}/><span>Use profile photo</span></label>{!contact.useProfile&&contact.photo&&<Control type="button" className="text-button" disabled={photoBusy||saving} onClick={()=>{update('photo',null);setPhotoError('')}}>Remove photo</Control>}</div>
  <div className="form-image-fields"><label>Name<input required value={contact.name} maxLength="80" autoComplete="name" disabled={saving} onChange={e=>update('name',e.target.value)}/></label><label><span className="form-label">Email <span className="field-optional">Optional</span></span><input type="email" autoComplete="email" value={contact.email} maxLength="160" disabled={saving} onChange={e=>update('email',e.target.value)}/></label><label><span className="form-label">Phone <span className="field-optional">Optional</span></span><input type="tel" autoComplete="tel" value={contact.phone} maxLength="40" disabled={saving} onChange={e=>update('phone',e.target.value)}/></label></div>
 </div></fieldset><InlineDisclosure icon="home" label={contact.address||contact.social?'Edit address and link':'Add address and link'} openLabel="Hide address and link" summary={[contact.address,contact.social].filter(Boolean).join(' · ')} populated={!!(contact.address||contact.social)} invalid={!!contact.social&&!safeWebUrl(contact.social)} disabled={saving}><div className="form-section"><label><span className="form-label">Address <span className="field-optional">Optional</span></span><textarea autoComplete="street-address" value={contact.address} maxLength="300" disabled={saving} onChange={e=>update('address',e.target.value)}/></label><label><span className="form-label">Social link <span className="field-optional">Optional</span></span><input type="url" value={contact.social} placeholder="https://…" aria-invalid={!!contact.social&&!safeWebUrl(contact.social)} disabled={saving} onChange={e=>update('social',e.target.value)}/></label></div></InlineDisclosure><fieldset className="form-section contact-sharing"><legend>Sharing</legend><label className="check-row"><input type="checkbox" checked={contact.optIn} disabled={saving} onChange={e=>update('optIn',e.target.checked)}/>{state.mode==='preview'?'Include my card in the preview address book':'Include my card in the family address book'}</label><p className="field-help">{state.mode==='preview'?'These choices use isolated test data.':'You can turn sharing off at any time.'}</p><ChoiceControl label="Who can see your details?" variant="chips" required value={contact.visibility} disabled={saving} onChange={value=>update('visibility',value)} options={['Only me','Selected family members','Family leaders','All approved family members']}/>{contact.visibility==='Selected family members'&&<MemberPicker label="Family who can see your contact card" multiple value={contact.selectedIds||[]} disabled={saving} filter={m=>m.id!==state.selfId} onChange={ids=>update('selectedIds',ids)}/>}<p className="field-help">{!contact.optIn||contact.visibility==='Only me'?'Only you can see this card.':`After saving, your card is shared with ${contact.visibility.toLowerCase()}.`}</p></fieldset>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-save"><Control className="button form-primary" type="submit" disabled={saving||photoBusy}>{saving?'Saving…':'Save contact card'}</Control></div></form>
}
