import React,{useEffect,useRef,useState} from 'react';
import {Button,useApp} from './ui-core.jsx';
import {deviceCapability,createDevicePushController} from './push-client.js';
async function request(path,method='GET',body){const response=await fetch(path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const value=await response.json();if(!response.ok)throw new Error(value.error||'Device push could not be updated.');return value}
export async function clearBrowserPush(){if(!navigator.serviceWorker)return;const registration=await navigator.serviceWorker.getRegistration();const subscription=await registration?.pushManager?.getSubscription();if(subscription)await subscription.unsubscribe();const displayed=await registration?.getNotifications?.();displayed?.forEach(n=>n.close())}
export function PushDeviceSettings(){
 const {state,notifications}=useApp(),account=state.mode==='live'?state.selfId:null,identity=useRef(account);identity.current=account;
 const [status,setStatus]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),registration=useRef(null),controller=useRef(null);
 useEffect(()=>{let active=true;setStatus(null);setError('');controller.current?.invalidate();controller.current=null;if(!account)return;
  (async()=>{try{const result=await request('/api/me/push');if(!active||identity.current!==account||result.accountId!==account)return;setStatus(result);if(result.ready&&navigator.serviceWorker){registration.current=await navigator.serviceWorker.getRegistration();if(!active)return;if(!registration.current?.active||!registration.current?.pushManager){setError('Device notifications are not ready. Reload GW in a supported full browser, then try again.');return;}controller.current=createDevicePushController({Notification:window.Notification,registration:registration.current,currentAccountId:()=>identity.current,save:body=>request('/api/me/push/devices','POST',body),revoke:body=>request('/api/me/push/devices/'+encodeURIComponent(body.id),'DELETE',{expectedAccountId:body.expectedAccountId})});if(active)setStatus({...result})}}catch(e){if(active)setError(e.message)}})();return()=>{active=false;controller.current?.invalidate()}
 },[account,notifications?.settings?.globalOff]);
 const capability=typeof window!=='undefined'?deviceCapability({window,navigator,Notification:window.Notification}):{available:false};
 const reason=!account?'Preview never subscribes a device.':!status?'Checking device availability…':!status.ready?'Not enabled in this build.':notifications?.settings?.globalOff?'Turn Activity in GW on before enabling this device.':capability.reason==='open-full-browser'?'Open GW in a full browser rather than an in-app browser or embedded frame. Activity in GW is still available.':capability.reason==='secure-context-required'?'Open GW using its secure HTTPS address.':capability.reason==='install-ios-first'?'Add GW to your iPhone or iPad Home Screen, then open its icon to enable push.':capability.reason==='permission-denied'?'Notifications are blocked. Change GW’s notification permission in browser or device settings.':!capability.available?'This browser does not expose the required push APIs. Try a current full browser, or keep using activity in GW.':status.pushEnabled?'Enabled for this signed-in session.':'Off on this device.';
 function enable(){if(!controller.current)return;setBusy(true);setError('');const startedFor=account;controller.current.enable(status,account).then(result=>{if(identity.current===startedFor)setStatus(s=>({...s,pushEnabled:result.enabled}))}).catch(e=>setError(e.message)).finally(()=>setBusy(false))}
 async function disable(){setBusy(true);setError('');try{await request('/api/me/push/revoke-session','POST',{expectedAccountId:account});await clearBrowserPush();controller.current?.invalidate();setStatus(s=>({...s,pushEnabled:false}))}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="notification-settings-section notification-device-status"><h2>Push on this device</h2><p role="status">{reason}</p><p className="small muted">Your activity still works in GW. Opening this page never asks for browser notification permission.</p>{status?.ready&&<><p className="small muted">If you enable push, generic updates may appear in your notification center or on your lock screen. Your browser’s push provider handles delivery. Names and message content are never included. Signing out stops push for this session. Installation is required on iPhone/iPad; supported desktop and Android browsers do not require it. Browser/OS settings, private mode or device policy can block delivery.</p><Button disabled={busy||!capability.available||notifications?.settings?.globalOff||!controller.current} onClick={enable}>Enable push on this device</Button><Button secondary disabled={busy} onClick={disable}>Turn off push on this device</Button></>}{!status?.ready&&status?.devices?.length>0&&<Button secondary disabled={busy} onClick={disable}>Turn off push on this device</Button>}{error&&<p role="alert">{error}</p>}</section>
}
export function PushLifecycle(){
 const pendingNotice=useRef(new URL(location.href).searchParams.get('gwNotice'));
 const {state,notifications,go,navigationVersion,setToast}=useApp(),account=state.mode==='live'?state.selfId:null,previous=useRef(account),current=useRef(account);current.current=account;
 useEffect(()=>{if(previous.current&&previous.current!==account)clearBrowserPush().catch(()=>{});previous.current=account},[account]);
 useEffect(()=>{if(!account||!notifications?.ready)return;const url=new URL(location.href),id=pendingNotice.current||url.searchParams.get('gwNotice');if(!id)return;pendingNotice.current=null;url.searchParams.delete('gwNotice');history.replaceState(history.state,'',url);if(!/^[a-zA-Z0-9_-]{1,100}$/.test(id))return;let active=true;const version=navigationVersion?.();notifications.open(id).then(result=>{if(!active||current.current!==account||navigationVersion?.()!==version)return;if(result?.available&&result.route)go(result.route);else setToast('This update is no longer available.')});return()=>{active=false}},[account,notifications?.ready]);
 return null;
}
