import React,{useState} from 'react';
import {Button,Control,useApp} from './ui-core.jsx';
import {reunionLabel,selectedReunion,reunionArchived} from './reunion-model.js';
import './reunion-years.css';
export function ReunionSelector(){
 const {state,dispatch,data}=useApp(),selected=selectedReunion(state);
 if((state.reunions?.length||0)<2)return null;
 return <div className="reunion-selector"><label>Reunion year<select value={state.selectedReunionId} disabled={data.pending} onChange={e=>dispatch({type:'SELECT_REUNION',id:e.target.value})}>{state.reunions.map(r=><option value={r.id} key={r.id}>{reunionLabel(r)} · {r.status==='active'?'Active':r.status==='archived'?'Archived':'Planning'}</option>)}</select></label><p className="small muted">{selected?.status==='active'?'This is the active family reunion.':selected?.status==='archived'?'Archived records are preserved. Restore this reunion to make changes.':'Planning ahead. This reunion has its own RSVP, orders, fees and calendar.'}</p></div>;
}
export function ReunionYearManager(){
 const {state,dispatch,data}=useApp(),current=selectedReunion(state),[year,setYear]=useState(''),[legacyYear,setLegacyYear]=useState(''),[archivePrevious,setArchivePrevious]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 if(!(state.mode==='preview'||state.capabilities?.manageReunion)||!current)return null;
 async function act(action){if(busy||data.pending)return false;setBusy(true);setError('');try{const saved=await dispatch(action);if(!saved)setError('This change wasn’t saved. Please try again.');return saved}finally{setBusy(false)}}
 return <section className="card stack reunion-year-manager"><h2>Reunion years</h2><p className="muted">Plan multiple years together. Each year keeps its own details and records.</p><label>How often do we gather?<select disabled={busy||data.pending} value={state.reunionCadence||'irregular'} onChange={e=>act({type:'SET_REUNION_CADENCE',value:e.target.value})}><option value="annual">Every year</option><option value="biennial">Every two years</option><option value="irregular">When the family chooses</option></select></label><p className="field-help">Cadence is a planning preference. You choose each reunion year explicitly.</p>{!current.year&&<form className="stack" onSubmit={async e=>{e.preventDefault();await act({type:'UPDATE_REUNION',id:current.id,year:Number(legacyYear)})}}><label>Year for existing records<input required type="number" min={1900} max={2200} value={legacyYear} onChange={e=>setLegacyYear(e.target.value)}/></label><p className="field-help">No date was set for these existing records, so a year hasn’t been guessed. Naming the year keeps every record in place.</p><Control type="submit" className="button secondary" disabled={busy||data.pending||reunionArchived(state)}>Set existing reunion year</Control></form>}<form className="reunion-add-year" onSubmit={async e=>{e.preventDefault();if(await act({type:'CREATE_REUNION',year:Number(year)}))setYear('')}}><label>Plan another year<input required type="number" min={1900} max={2200} value={year} onChange={e=>setYear(e.target.value)} placeholder="2028"/></label><Control className="button secondary" type="submit" disabled={busy||data.pending}>Add year</Control></form><div className="stack reunion-lifecycle"><h3>{reunionLabel(current)} · {current.status==='planned'?'Planning':current.status}</h3>{current.status==='planned'&&<><label className="check-row"><input type="checkbox" checked={archivePrevious} onChange={e=>setArchivePrevious(e.target.checked)}/>Archive the current active reunion when switching</label><Button disabled={busy||data.pending} onClick={()=>act({type:'ACTIVATE_REUNION',id:current.id,archivePrevious})}>Make {current.year} active</Button><Button secondary disabled={busy||data.pending} onClick={()=>act({type:'ARCHIVE_REUNION',id:current.id})}>Archive this reunion</Button></>}{current.status==='archived'&&<Button secondary disabled={busy||data.pending} onClick={()=>act({type:'RESTORE_REUNION',id:current.id})}>Restore for planning</Button>}{current.status==='active'&&<p className="small muted">To archive this reunion, select another planned year and make it active. Existing orders, payments and RSVPs will stay here.</p>}</div>{error&&<p role="alert">{error}</p>}</section>;
}
