import {FamilyInvitationClaim,ProvisionalFamilyView,rememberFamilyInvitation,useFamilyInviteWelcome} from './family-invitations.jsx';
import {EnrollmentForm} from './enrollment-form.jsx';
import {SignOutControl} from './account-actions.jsx';
import React,{useState} from 'react';
import {api} from './live-adapter.js';
import {signInProviders,signInRequest} from './sign-in-providers.mjs';
import {OfficialSignInButton,officialProviderBrandReady} from './official-sign-in-button.jsx';
import {Control,Button,Glyph,useApp} from './ui-core.jsx';
import {readDeviceAccount,rememberDeviceProvider} from './device-remembrance.js';
export function SignIn({returning=false}){
 const {data,refreshEntry}=useApp(),[email,setEmail]=useState(''),[code,setCode]=useState(''),[stage,setStage]=useState('email'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const inviteToken=data.preview?null:rememberFamilyInvitation(),inviteWelcome=useFamilyInviteWelcome(inviteToken);
 const [remembered]=useState(readDeviceAccount),[another,setAnother]=useState(false);
 const returningAccount=!inviteToken&&!another?remembered:null;
 returning=returning||Boolean(returningAccount);
 const providers=signInProviders(data.config).map(provider=>provider.id);
 async function social(provider){if(busy)return;setBusy(true);setError('');try{rememberFamilyInvitation();const request=signInRequest(data.config,provider);const r=await api(request.path,{method:'POST',body:JSON.stringify(request.body)});const url=new URL(r.url);if(url.protocol!=='https:'||url.username||url.password)throw Error('Sign-in could not start. Please try again.');if(request.path!=='/api/auth/sign-in/social'&&url.origin!==data.config.origin)throw Error('Sign-in could not start. Please try again.');rememberDeviceProvider(provider);location.assign(url.href)}catch(e){setError(e.message);setBusy(false)}}
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(stage==='email'){await api('/api/auth/email-otp/send-verification-otp',{method:'POST',body:JSON.stringify({email,type:'sign-in'})});setStage('code')}else{await api('/api/auth/sign-in/email-otp',{method:'POST',body:JSON.stringify({email,otp:code})});rememberDeviceProvider('email');await (refreshEntry||data.refresh)()}}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <form className="gw-form sign-in-form" onSubmit={submit}><div className="form-heading"><h2>{stage==='email'?(inviteWelcome?.inviterName?inviteWelcome.inviterName+' invited you to join the fun.':inviteToken?'You’re invited.':returningAccount?'Welcome back, '+returningAccount.name.split(' ')[0]+'.':'Come on in.'):'Check your email.'}</h2><p>{stage==='email'?(inviteWelcome?.error||(inviteToken?'Create your profile to join your family for stories, plans, and new memories.':'Your family space is private. New members need an organizer’s approval.')):`Enter the six-digit code sent to ${email}. It expires in ten minutes.`}</p></div>{stage==='email'&&returningAccount&&<div className="returning-device-account">{returningAccount.avatar&&<img width="48" height="48" src={returningAccount.avatar} alt=""/>}<p className="small muted">{returningAccount.provider?'Last used '+({google:'Google',microsoft:'Microsoft',yahoo:'Yahoo',email:'email'})[returningAccount.provider]+'. ':''}Sign in to confirm your account.</p><Button secondary disabled={busy} onClick={()=>{setAnother(true);setEmail('');setCode('');setError('')}}>Use another account</Button></div>}{stage==='code'&&<aside className="email-delivery-warning" role="note"><Glyph name="mail"/><div><strong>Check Junk or Spam</strong><p>If your code hasn’t arrived, check those folders. Mark the email as Not Junk to help future codes reach your inbox.</p></div></aside>}{stage==='email'&&providers.length>0&&<div className="provider-buttons">{providers.map(provider=>officialProviderBrandReady(provider)?<OfficialSignInButton key={provider} provider={provider} intent={returning?'signin':'signup'} disabled={busy||!!data.pending} onClick={()=>social(provider)}/>:<Button secondary key={provider} disabled={busy||!!data.pending} onClick={()=>social(provider)}>Continue with {provider[0].toUpperCase()+provider.slice(1)}</Button>)}</div>}{data.config?.email&&<>{stage==='email'?<><p className="apple-signin-note">Apple sign-in coming soon. Use an email code below.</p><label><span className="email-field-label"><Glyph name="mail"/>Email</span><input autoComplete="email" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label></>:<label>Sign-in code<input autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6}" maxLength="6" required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></label>}<Control className="button form-primary" type="submit" disabled={busy}>{busy?'Please wait…':stage==='email'?'Email me a code':'Sign in'}</Control>{stage==='code'&&<Button secondary disabled={busy} onClick={()=>{setStage('email');setCode('');setError('')}}>Use another email or resend</Button>}</>}{error&&<p role="alert" className="form-error">{error}</p>}</form>
}
export function Enrollment(){
 const {data,refreshEntry}=useApp();
 async function saveProfile(values){
  await api('/api/enroll',{method:'POST',body:JSON.stringify({name:values.name,birthday:values.birthday,privacyAccepted:values.privacyAccepted,birthdayCelebration:values.birthdayCelebration,profileColor:values.profileColor})});
  if(values.file){const form=new FormData();form.append('file',values.file);await api('/api/onboarding/photo',{method:'POST',body:form})}
  await (refreshEntry||data.refresh)();
 }
 return <div className="stack enrollment-account"><EnrollmentForm initialName={data.session?.user?.name||''} onSave={saveProfile}/><SignOutControl/></div>;
}
export function WaitingForApproval(){
 const {data}=useApp(),[checking,setChecking]=useState(false),[feedback,setFeedback]=useState(''),unverified=data.session?.status==='unverified'||data.session?.verified===false;
 async function check(){if(checking)return;setChecking(true);setFeedback('');try{const session=await data.refresh();setFeedback(!session?'Couldn’t check right now. Please try again.':session.status==='active'?'Approved. Opening your family space…':session.membershipRemoved?'Your membership is removed. Please contact a family admin about restoration.':session.status==='suspended'?'Your access is still paused. Please contact a family organizer.':session.status==='unverified'||session.verified===false?'Your email is still awaiting verification. Checked just now.':'Still waiting for organizer approval. Checked just now.')}finally{setChecking(false)}}
 return <div className="stack approval-state"><h1>{unverified?'Email verification is pending.':data.session?.membershipRemoved?'Your membership was removed.':data.session?.status==='suspended'?'Access is paused.':'You’re on the list.'}</h1><p className="muted">{unverified?'Your sign-in email needs verification before you can join the family. Once it’s verified, check your status again.':data.session?.membershipRemoved?'Your sign-in account is still available. A family admin can restore your membership for review.':data.session?.status==='suspended'?'Please contact a family organizer about your membership.':data.session?.provisionalAccess?'You can look at family updates while an organizer reviews your membership. Posting and other actions need approval.':'A family organizer needs to approve your membership before you can see private posts and details.'}</p><Button disabled={checking} onClick={check}>{checking?'Checking…':'Check my status'}</Button>{feedback&&<p role="status" className="approval-feedback">{feedback}</p>}<FamilyInvitationClaim/>{data.session?.provisionalAccess&&<ProvisionalFamilyView key={data.session.user.id}/>}<SignOutControl/></div>
}
