import {ProfileStyleEditor} from './profiles.jsx';
import React,{useState,useEffect} from 'react';
import {api} from './live-adapter.js';
import {Control,Button,useApp} from './ui-core.jsx';
export function SignIn(){
 const {data}=useApp(),[email,setEmail]=useState(''),[code,setCode]=useState(''),[stage,setStage]=useState('email'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const providers=data.config?.providers||[];
 async function social(provider){setBusy(true);setError('');try{const bridge=provider==='google'&&data.config.googleMode==='access';const r=await api(bridge?'/api/auth/sign-in/cloudflare-google':'/api/auth/sign-in/social',{method:'POST',body:JSON.stringify(bridge?{}:{provider,callbackURL:data.config.origin})});const url=new URL(r.url);if(url.protocol!=='https:')throw Error('Sign-in could not start. Please try again.');location.assign(url.href)}catch(e){setError(e.message);setBusy(false)}}
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(stage==='email'){await api('/api/auth/email-otp/send-verification-otp',{method:'POST',body:JSON.stringify({email,type:'sign-in'})});setStage('code')}else{await api('/api/auth/sign-in/email-otp',{method:'POST',body:JSON.stringify({email,otp:code,name:email.split('@')[0]})});await data.refresh()}}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <form className="gw-form sign-in-form" onSubmit={submit}><div className="form-heading"><h2>{stage==='email'?'Come on in.':'Check your email.'}</h2><p>{stage==='email'?'Your family space is private. New members need an organizer’s approval.':`Enter the six-digit code sent to ${email}. It expires in ten minutes.`}</p></div>{stage==='email'&&providers.length>0&&<div className="provider-buttons">{providers.map(provider=><Button secondary key={provider} disabled={busy} onClick={()=>social(provider)}>Continue with {provider[0].toUpperCase()+provider.slice(1)}</Button>)}</div>}{data.config?.email&&<>{stage==='email'?<>{providers.length>0&&<p className="sign-in-divider">or use an email code</p>}<label>Email<input autoComplete="email" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label></>:<label>Sign-in code<input autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6}" maxLength="6" required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></label>}<Control className="button form-primary" type="submit" disabled={busy}>{busy?'Please wait…':stage==='email'?'Email me a code':'Sign in'}</Control>{stage==='code'&&<Button secondary disabled={busy} onClick={()=>{setStage('email');setCode('');setError('')}}>Use another email or resend</Button>}</>}{error&&<p role="alert" className="form-error">{error}</p>}</form>
}
export function Enrollment(){
 const {data}=useApp(),[step,setStep]=useState(1),[name,setName]=useState(data.session?.user?.name||''),[birthday,setBirthday]=useState(''),[celebrate,setCelebrate]=useState(false),[accepted,setAccepted]=useState(false),[color,setColor]=useState('#4f996c'),[file,setFile]=useState(null),[photo,setPhoto]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>()=>{if(photo?.startsWith('blob:'))URL.revokeObjectURL(photo)},[photo]);
 async function finish(appearance=true){setBusy(true);setError('');try{await api('/api/enroll',{method:'POST',body:JSON.stringify({name,birthday,privacyAccepted:accepted,birthdayCelebration:celebrate,profileColor:appearance?color:'#4f996c'})});if(appearance&&file){const form=new FormData();form.append('file',file);await api('/api/onboarding/photo',{method:'POST',body:form})}await data.refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <form className="gw-form enrollment-form" onSubmit={e=>{e.preventDefault();if(step===1){setError('');setStep(2)}else void finish()}}><div className="onboarding-progress" aria-label={'Step '+step+' of 2'}><span className={step===1?'current':''}>1 · Your details</span><span className={step===2?'current':''}>2 · Your profile</span></div>{step===1?<><div className="form-heading"><h1>A little about you.</h1><p>Your full birthday stays private.</p></div><label>Your name<input required maxLength="80" autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label><label>Birthday<input type="date" required min="1900-01-01" max={new Date().toISOString().slice(0,10)} value={birthday} onChange={e=>setBirthday(e.target.value)}/></label><label className="check-row"><input type="checkbox" checked={celebrate} onChange={e=>setCelebrate(e.target.checked)}/><span>Let the family celebrate my birthday.<small>Optional. Shares month and day and adds a birthday post for adults.</small></span></label><label className="check-row"><input type="checkbox" required checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I understand this profile is for approved family members. My full birthday and household details stay private.</span></label><Control type="submit" className="button form-primary">Continue</Control></>:<><div className="form-heading"><h1>Make it yours.</h1><p>Add a photo and pick your color. Both are optional.</p></div><ProfileStyleEditor name={name} photo={photo} color={color} onColor={setColor} onRemove={()=>{setFile(null);setPhoto(null)}} busy={busy} onPhoto={async next=>{if(!['image/jpeg','image/png','image/webp','image/gif'].includes(next.type)||next.size>10*1024*1024){setError('Choose a JPEG, PNG, WebP or GIF photo under 10 MB.');return}setError('');setFile(next);setPhoto(URL.createObjectURL(next))}}/><div className="form-save"><Control type="submit" className="button form-primary" disabled={busy}>{busy?'Saving your profile…':'Finish joining'}</Control><div className="onboarding-secondary"><Button secondary disabled={busy} onClick={()=>setStep(1)}>Back</Button><Control className="text-button" type="button" disabled={busy} onClick={()=>finish(false)}>Skip for now</Control></div></div></>}{error&&<p role="alert" className="form-error">{error}</p>}</form>
}
export function WaitingForApproval(){
 const {data}=useApp(),[checking,setChecking]=useState(false),[feedback,setFeedback]=useState('');
 async function check(){if(checking)return;setChecking(true);setFeedback('');try{const session=await data.refresh();setFeedback(!session?'Couldn’t check right now. Please try again.':session.status==='active'?'Approved. Opening your family space…':session.status==='suspended'?'Your access is still paused. Please contact a family organizer.':'Still waiting for organizer approval. Checked just now.')}finally{setChecking(false)}}
 return <div className="stack approval-state"><h1>{data.session?.status==='suspended'?'Access is paused.':'You’re on the list.'}</h1><p className="muted">{data.session?.status==='suspended'?'Please contact a family organizer about your membership.':'A family organizer needs to approve your membership before you can see private posts and details.'}</p><Button disabled={checking} onClick={check}>{checking?'Checking…':'Check my status'}</Button>{feedback&&<p role="status" className="approval-feedback">{feedback}</p>}<Button secondary disabled={checking} onClick={()=>data.signOut()}>Sign out</Button></div>
}
