import {EnrollmentForm} from './enrollment-form.jsx';
import React,{useState} from 'react';
import {api} from './live-adapter.js';
import {Control,Button,useApp} from './ui-core.jsx';
export function SignIn(){
 const {data,refreshEntry}=useApp(),[email,setEmail]=useState(''),[code,setCode]=useState(''),[stage,setStage]=useState('email'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const providers=data.config?.providers||[];
 async function social(provider){setBusy(true);setError('');try{const bridge=provider==='google'&&data.config.googleMode==='access';const r=await api(bridge?'/api/auth/sign-in/cloudflare-google':'/api/auth/sign-in/social',{method:'POST',body:JSON.stringify(bridge?{}:{provider,callbackURL:data.config.origin})});const url=new URL(r.url);if(url.protocol!=='https:')throw Error('Sign-in could not start. Please try again.');location.assign(url.href)}catch(e){setError(e.message);setBusy(false)}}
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(stage==='email'){await api('/api/auth/email-otp/send-verification-otp',{method:'POST',body:JSON.stringify({email,type:'sign-in'})});setStage('code')}else{await api('/api/auth/sign-in/email-otp',{method:'POST',body:JSON.stringify({email,otp:code,name:email.split('@')[0]})});await (refreshEntry||data.refresh)()}}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <form className="gw-form sign-in-form" onSubmit={submit}><div className="form-heading"><h2>{stage==='email'?'Come on in.':'Check your email.'}</h2><p>{stage==='email'?'Your family space is private. New members need an organizer’s approval.':`Enter the six-digit code sent to ${email}. It expires in ten minutes.`}</p></div>{stage==='code'&&<aside className="email-delivery-warning" role="note"><strong>Check Junk or Spam</strong><p>If your code hasn’t arrived, check those folders. Mark the email as Not Junk to help future codes reach your inbox.</p></aside>}{stage==='email'&&providers.length>0&&<div className="provider-buttons">{providers.map(provider=><Button secondary key={provider} disabled={busy} onClick={()=>social(provider)}>Continue with {provider[0].toUpperCase()+provider.slice(1)}</Button>)}</div>}{data.config?.email&&<>{stage==='email'?<>{providers.length>0&&<p className="sign-in-divider">or use an email code</p>}<label>Email<input autoComplete="email" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label></>:<label>Sign-in code<input autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6}" maxLength="6" required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></label>}<Control className="button form-primary" type="submit" disabled={busy}>{busy?'Please wait…':stage==='email'?'Email me a code':'Sign in'}</Control>{stage==='code'&&<Button secondary disabled={busy} onClick={()=>{setStage('email');setCode('');setError('')}}>Use another email or resend</Button>}</>}{error&&<p role="alert" className="form-error">{error}</p>}</form>
}
export function Enrollment(){
 const {data,refreshEntry}=useApp();
 async function saveProfile(values){
  await api('/api/enroll',{method:'POST',body:JSON.stringify({name:values.name,birthday:values.birthday,privacyAccepted:values.privacyAccepted,birthdayCelebration:values.birthdayCelebration,profileColor:values.profileColor})});
  if(values.file){const form=new FormData();form.append('file',values.file);await api('/api/onboarding/photo',{method:'POST',body:form})}
  await (refreshEntry||data.refresh)();
 }
 return <EnrollmentForm initialName={data.session?.user?.name||''} onSave={saveProfile}/>;
}
export function WaitingForApproval(){
 const {data}=useApp(),[checking,setChecking]=useState(false),[feedback,setFeedback]=useState(''),unverified=data.session?.status==='unverified'||data.session?.verified===false;
 async function check(){if(checking)return;setChecking(true);setFeedback('');try{const session=await data.refresh();setFeedback(!session?'Couldn’t check right now. Please try again.':session.status==='active'?'Approved. Opening your family space…':session.status==='suspended'?'Your access is still paused. Please contact a family organizer.':session.status==='unverified'||session.verified===false?'Your email is still awaiting verification. Checked just now.':'Still waiting for organizer approval. Checked just now.')}finally{setChecking(false)}}
 return <div className="stack approval-state"><h1>{unverified?'Email verification is pending.':data.session?.status==='suspended'?'Access is paused.':'You’re on the list.'}</h1><p className="muted">{unverified?'Your sign-in email needs verification before you can join the family. Once it’s verified, check your status again.':data.session?.status==='suspended'?'Please contact a family organizer about your membership.':'A family organizer needs to approve your membership before you can see private posts and details.'}</p><Button disabled={checking} onClick={check}>{checking?'Checking…':'Check my status'}</Button>{feedback&&<p role="status" className="approval-feedback">{feedback}</p>}<Button secondary disabled={checking} onClick={()=>data.signOut()}>Sign out</Button></div>
}
