export const tutorialVersion=1;
export const tutorialTopics=[
 {id:'home',title:'Keep up with family',icon:'home',body:'Home brings family posts together. Open a post to read the conversation, reply, or add a reaction.',tip:'Writing something? The plus button opens a new post. Your draft stays with you until you send it.',action:'Explore Home',route:{type:'home'}},
 {id:'messages',title:'Start a private conversation',icon:'chat',body:'Messages is for direct chats and smaller groups. New conversations may begin with an invitation that the other person can accept or decline.',tip:'Choose who joins before you send. Typing indicators are temporary; your draft is never shared.',action:'Open Messages',route:{type:'inbox'}},
 {id:'notifications',title:'Hear about what matters',icon:'bell',body:'The bell holds your family updates. Open an update to visit its post, conversation, or request, or mark it read for later.',tip:'Following controls general posts. Replies and mentions have their own choices. Off pauses every category.',action:'Choose notifications',sheet:{type:'notification-settings'}},
 {id:'you',title:'Make yourself at home',icon:'user',body:'You keeps your profile, household, RSVP, fees, and merchandise together. Contact details have their own sharing choices.',tip:'You can replay this guide any time from You or your profile menu. Adding the app to your Home Screen is optional.',action:'Go to You',route:{type:'you'}}
];
export function tutorialKey(account='preview'){return `gw-help:v${tutorialVersion}:${encodeURIComponent(account)}`}
export function contextualTopic(route={}){return ['chat','inbox','chat-new','chat-settings'].includes(route.type)?'messages':['you','household','profile','contact','edit-profile'].includes(route.type)?'you':'home'}
export function readTutorial(storage,account){try{const value=JSON.parse(storage.getItem(tutorialKey(account)));if(value?.version===tutorialVersion&&tutorialTopics.some(t=>t.id===value.topic)&&['started','skipped','completed'].includes(value.status))return value}catch{}return {version:tutorialVersion,topic:'home',status:'new'}}
export function saveTutorial(storage,account,value){const next={version:tutorialVersion,topic:tutorialTopics.some(t=>t.id===value.topic)?value.topic:'home',status:['started','skipped','completed'].includes(value.status)?value.status:'started'};try{storage.setItem(tutorialKey(account),JSON.stringify(next));return true}catch{return false}}
